pagopa/io-app

.circleci/config.yml, .gitignore
Enables parallel execution of ios and android pipelines, reuse node workspace (with yarn deps) in ios build, adds cache for ruby gems
=> Circleci iOS build cache

ts/store/reducers/profile.ts
Option can't be used with redux-persist. For now we have to avoid using Option. I'll investigate if is possible to attach a simple Option serializer/deserializer to redux-persist.
=> [#157395938] Remove Option from profile reducer

ts/api/index.ts, ts/components/IdpsGrid.tsx, ts/models/IdentityProvider.ts, ts/screens/authentication/IdpSelectionScreen.tsx, ts/store/actions/session.ts, ts/store/reducers/session.ts, ts/utils/api.ts
There were two identical definitions for `IdentityProvider`, I've refactored the code to have just one.
=> Fixes duplicated IdentityProvider definition

ts/boot/configureStoreAndPersistor.ts
We are moving from blacklist to whitelist in the redux-persist config. We explicitly define sections of the store that must be persisted and rehydrated.
=> [#157653360] Move redux-persist config from blacklist to whitelist

README.md, ts/components/forms/SpidInformationForm.tsx, ts/components/forms/utils.tsx
iOS and Android can propose to the user different keyboard types based on the requested input.
In the *Don't have SPID?* view, there is an email field that if selected presents the user a standard generic keyboard.
This commit addresses the issue:
* The presented keyboard is the email one.
* Auto capitalisation is turned off.
* Auto correction is turned off.
* To use those parameters, the `Form/Field` has been transformed into a `Form/TextInput`.
=> Using the proper system email keyboard on email input fields

.circleci/config.yml
To consume less CI resources, I've made the native tests optional (there's an approval process on the circleci UI):
=> Makes native iOS and Android test steps optional

ts/components/wallet/TransactionsList.tsx, ts/store/actions/wallet/cards.ts, ts/store/reducers/wallet/cards.ts
The `selectedCardId` property of the wallet state (used to update the card preview at the top of the layout) was not being set when accessing the "transaction details" screen directly from a transactions list (and not from the "transactions by card" screen). 
This PR fixes it, by setting the selected card id value directly when selecting a transaction.
=> fixing minor bug in the transaction details screen

ts/components/wallet/PaymentMethodsList.tsx, ts/screens/wallet/AddPaymentMethodScreen.tsx
This PR fixes some open points about previous PRs. 
In particular, it fixes the "payment banner" prepended to the "add payment method" screen. 
In the long term, it is probably worth considering whether a "withPaymentBanner" HOC should be introduced to create screens that (1) display the relevant banner and (2) are aligned with the original screens. 
Additionally, since things are getting crowded in screens/wallet, the files may be organized in subdirectories:
```
screen/
wallet/
payment/
... files for handling payments ...
newMethod/
... files to add a new payment method ...
... files for managing the wallet ...
```
=> reordering components

.circleci/config.yml, android/app/build.gradle, android/fastlane/Appfile, android/fastlane/Fastfile, package.json, scripts/json-key-file-setup.sh, scripts/keystore-setup.sh
To make this works:
**Create/dowload the json key file**
Follow this [guide](https://docs.fastlane.tools/getting-started/android/setup/)
**Create the base64 representation using**
```
cat youfile.json | base64
```
**Create a keystore using:**
```
$ keytool -genkey -v -keystore italiaapp-release.keystore -alias italiaapp-release -keyalg RSA -keysize 2048 -validity 10000
```
this command prompts you for passwords for the keystore and key, and to provide the Distinguished Name fields for your key.
**Create the base64 representation using**
```
cat italiaapp-release.keystore | base64
```
**In CircleCI add the following env valiables**
```
ENCODED_ITALIAAPP_JSON_KEY_FILE=[INSERT THE BASE64 REPRESENTATION OF THE GOOGLE PLAY JSON KEY FILE]
ENCODED_ITALIAAPP_RELEASE_KEYSTORE=[INSERT THE BASE64 …
```
=> [#158451703] Add the Android release build to CircleCI

android/app/build.gradle
To allow the build to work also if CIRCLE_BUILD_NUM is not available (ex. locally)
=> Add default version if CIRCLE_BUILD_NUM is not available

package.json, tsconfig.json, yarn.lock
This makes tslint running inside the editor much faster,
see https://github.com/angelozerr/tslint-language-service/blob/master/README.md
=> Enables tslint-language-service

ts/screens/authentication/IdpLoginScreen.tsx
The authLevel is now fixed to SpidL2. If necessary in another story we can make it dynamic.
=> [#159294221] Set authLevel as parameter in the IDP login url

android/app/src/main/AndroidManifest.xml
Without this the RootContainer is recreated every time the application go in background and than in foreground.
It is also needed when using deep-linking https://facebook.github.io/react-native/docs/linking.html#handling-deep-links.
NOTE: The documentation about singleTask is:
```
The system creates the activity at the root of a new task and routes the intent to it. However, if an instance of the activity already exists, the system routes the intent to existing instance through a call to its onNewIntent() method, rather than creating a new one.
```
=> [#159402967] Sets Android main activity mode to singleTask

package.json
- Extend prettifier execution to `.ts*` files (it includes `.tsx`, instead of only .ts files).
- Replace `'` with `\"` into prettier params, to allow execution on some bash command lines (linux issue) and PowerShell (windows issue)
=> Extend prettifier to tsx and fix it for bash

ts/sagas/authentication.ts, ts/store/reducers/navigation.ts
The error was caused by the IngressScreen (the one with the spinner) not removed from the navigation stack.
=> [#159491654] Fix behaviour on logout

ts/screens/wallet/payment/ManualDataInsertionScreen.tsx, ts/screens/wallet/payment/TransactionSummaryScreen.tsx
PR #341 introduced inline buttons, but in some cases the introduced buttons were "inverted" (i.e. the "main action" button (usually the "continue") could be found on the left-hand side of the footer, while it makes more sense to have it on the right-hand part of it), this PR fixes this problem
=> placing "main" button on the right-hand side of the footer

package.json, yarn.lock
The real code change is in the git://github.com/teamdigitale/react-native-confirmation-code-input.git repository.
=> [#159491535] Speedup CodeInput focus

ts/components/GoBackButton.tsx, ts/components/screens/BaseScreenComponent.tsx, ts/components/wallet/WalletLayout.tsx, ts/screens/authentication/IdpLoginScreen.tsx, ts/screens/authentication/SpidInformationRequestScreen.tsx, ts/screens/authentication/SpidInformationScreen.tsx, ts/screens/onboarding/PinScreen.tsx, ts/screens/wallet/AddCardScreen.tsx, ts/screens/wallet/AddPaymentMethodScreen.tsx, ts/screens/wallet/ConfirmSaveCardScreen.tsx, ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx, ts/screens/wallet/payment/PickPaymentMethodScreen.tsx, ts/screens/wallet/payment/PickPspScreen.tsx, ts/screens/wallet/payment/TransactionSummaryScreen.tsx
Testing the back navigation, I discovered that the `ROUTES.PIN_LOGIN` route is duplicated across `AppNavigator` and `PinNavigator`. Why `PinNavigator` should even exist?
I removed the `PinNavigator` and implemented this behaviour: ater the pin has been validated, the router resets the navigator stack, navigating to `ROUTES.MAIN`, so it's impossible to go back to pin screen.
=> [#159195774] Navigate back with Android back button

ts/components/VersionInfoOverlay.tsx, ts/middlewares/analytics.ts
This also fix a problem in the getCurrentRouteName function that was not returning the deepest route
=> [#160195061] Add current route to overlay info

package.json, yarn.lock
The new version of react-native-push-notification switchs from GCM to Firebase. There is a PR for re-adding the old GCM listener https://github.com/zo0r/react-native-push-notification/pull/835. We need to investigate if the Azure NH fully support Firebase and than upgrade this library.
=> [#160226908] Revert react-native-push-notification version

ts/sagas/startup/__tests__/authenticationSaga.test.ts, ts/sagas/startup/authenticationSaga.ts, ts/screens/authentication/IdpSelectionScreen.tsx, ts/store/reducers/authentication.ts
@matteodesanti With this behaviour, should the IDP selection screen have the _back to home_ button?
=> [#158788201] Navigate to IDP selection screen when session expires.

ts/config.ts, ts/sagas/wallet.ts, ts/utils/fetch.ts
This PR introduces an implementation of `fetch` with long timeout, suitable for calling verifica/attiva
=> Little refactoring of fetch and long timeout fetch

ts/api/backend.ts, ts/sagas/index.ts, ts/sagas/startup.ts, ts/sagas/wallet.ts
Make the wallet saga receive the session token from the startup saga and create the backend client(s) once, instead of having child-sagas create their own clients hand having to check the presence of a valid session token
=> Pass sessiontoken to the wallet saga

ts/components/LabelledItem.tsx
As per [this discussion](https://developersitalia.slack.com/archives/CA70BM37X/p1537277944000100) (video documenting the problem [here](https://developersitalia.slack.com/files/U75H1BEHF/FCWSM7K0X/bug_inserimento_carta_1.0.1_-_0.0.56.mov))
New behavior on Android
=> setting underlineColorAndroid to "transparent"

ts/components/messages/MessageDetailComponent.tsx, ts/components/screens/MarkdownScreenComponent.tsx, ts/components/ui/Markdown/__tests__/index.test.tsx, ts/components/ui/Markdown/index.tsx, ts/components/ui/Markdown/rules/link.ts, ts/screens/preferences/ServiceDetailsScreen.tsx
We can now insert internal link to selected screens using this format in markdown:
```
Go to [Profile](ioit://ROUTE_NAME)
```
I have tested and links of this type are already stripped down from the email version of the message
=> [#159265239] Handle internal link in Markdown component

ts/components/wallet/WalletLayout.tsx, ts/components/wallet/card/index.tsx
iOS requires a perspective to be defined in order to render rotations properly. 
Some shadows were also added to make things look better (and resemble the invision more closely). Unfortunately, on Android, shadows don't work quite as well (they do not rotate with the components), so they would look particularly bad. For now, they have been omitted.
**iOS**
**Android**
=> [#160708519] adding shadows and perspective on iOS

ts/components/styles/wallet.ts, ts/components/wallet/TransactionsList.tsx, ts/components/wallet/WalletLayout.tsx, ts/screens/wallet/TransactionDetailsScreen.tsx, ts/screens/wallet/WalletsScreen.tsx
On iPhone X, the left padding of the Content component goes missing, thus generating the problem reported in the relevant story. 
This PR fixes the problem by adding the padding directly to the components
=> [#160315153] specifying padding for Content components

locales/en/index.yml, locales/it/index.yml, ts/components/styles/wallet.ts, ts/components/wallet/TransactionsList.tsx, ts/components/wallet/WalletLayout.tsx, ts/screens/wallet/TransactionDetailsScreen.tsx, ts/screens/wallet/WalletsScreen.tsx, ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
During the payment process, if no wallets are available, the user is shown a message asking to select among the available methods (though there are none). Now, in that case, the message states that there are no cards stored and that the user should proceed with adding a new one.
=> [#160648909] Show relevant screen when the user has no wallets

ts/components/wallet/PaymentSummaryComponent.tsx, ts/sagas/wallet.ts, ts/screens/wallet/payment/ManualDataInsertionScreen.tsx, ts/screens/wallet/payment/ScanQrCodeScreen.tsx, ts/screens/wallet/payment/TransactionSummaryScreen.tsx, ts/store/reducers/wallet/payment.ts
The navigation now moves to the summary of the payment before the data is fetched from pagoPA. Then, when the verifica response arrives, the screen is populated accordingly.
=> Show loading summary screen

ts/components/helpers/withErrorModal.tsx
The error stored in the store will only contain an "identifier" (e.g. "INVALID_AMOUNT") which cannot be presented "as is" to the user. This PR adds mapping codes->user-friendly message
=> Add translation error-code2human-friendly

ts/theme/components/PreferenceItem.ts
This PR fixes the `<PreferenceItem>`'s theme broken by https://github.com/teamdigitale/italia-app/pull/584.
=> Fix preference item theme.

locales/it/privacy.md
Corretto uso delle maiuscole "questa informativa Le fornisce"
Eliminate una decina di maiuscole inutili
Il brand **io** va riportato non in maiuscola ma in forma minuscola, utilizzando il grassetto per evidenziarlo
Corretti un paio di refusi
Nel testo c'è un riferimento a un documento Agid che è introvabile sul web, aperta GitHub issue a riguardo
@matteodesanti
=> Correzione refusi privacy

ts/api/pagopa.ts, ts/components/messages/MessageCTABar.tsx, ts/components/wallet/PaymentBannerComponent.tsx, ts/sagas/wallet.ts, ts/sagas/wallet/utils.ts, ts/screens/PinLoginScreen.tsx, ts/screens/wallet/ConfirmCardDetailsScreen.tsx, ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx, ts/screens/wallet/payment/ManualDataInsertionScreen.tsx, ts/screens/wallet/payment/PickPaymentMethodScreen.tsx, ts/screens/wallet/payment/ScanQrCodeScreen.tsx, ts/store/actions/constants.ts, ts/store/actions/messages.ts, ts/store/actions/wallet/pagopa.ts, ts/store/actions/wallet/payment.ts, ts/store/actions/wallet/wallets.ts, ts/store/reducers/wallet/pagopa.ts, ts/store/reducers/wallet/payment.ts, ts/store/reducers/wallet/wallets.ts, ts/types/pagopa.ts
we broke the action loop by calling `getType` on a non-typesafe-actions action
=> Refactoring wallet saga and hot fix on wallet action loop

locales/en/markdown_reference.md, locales/it/markdown_reference.md, ts/@types/simple-markdown.d.ts, ts/components/ui/Markdown/MarkdownDemo.tsx, ts/components/ui/Markdown/rules/demo.ts, ts/components/ui/Markdown/rules/index.ts, ts/theme/components/markdown/MarkdownDemo.ts, ts/theme/index.ts
Use
`[demo]My paragraph[/demo]`
to add a style like in the figure.
@matteodesanti The font icon need to be re-exported, the one attached in the pivotal task seem not working.
=> [#160720288] Add markdown demo custom tag

locales/en/index.yml, locales/it/index.yml, ts/api/pagopa.ts, ts/sagas/wallet.ts, ts/types/pagopa.ts, ts/types/utils.ts, ts/utils/showToast.ts
This PR patches the `AddWalletCreditCardUsingPOSTT` type in order to decode the `422` response status, meaning that the card already exists in the wallet.
There is also a new function which invoke `Toast.show()` with some default parameters (mainly duration and button style), should we refactor all the toasts using this helper function?
@matteodesanti The actual toast component we are using doesn't accept a component as a button, meaning that we can use the icon font, so I used the `✕` character.
=> [#161081455] Handle "card already exists" error

ts/screens/wallet/payment/TransactionSummaryScreen.tsx
Some of the fields provided by pagoPA are optional and are currently being presented as "undefined". This PR adds checks for not displaying the missing information
=> [#160953931] adding checks on optional information at payment recap

ts/components/wallet/PaymentBannerComponent.tsx, ts/components/wallet/TransactionsList.tsx, ts/components/wallet/WalletLayout.tsx, ts/components/wallet/card/CardBody.tsx, ts/components/wallet/card/CardComponent.tsx, ts/components/wallet/card/FooterRow.tsx, ts/components/wallet/card/Logo.tsx, ts/sagas/startup.ts, ts/sagas/startup/watchApplicationActivitySaga.ts, ts/sagas/wallet.ts, ts/screens/wallet/AddPaymentMethodScreen.tsx, ts/screens/wallet/Checkout3DsScreen.tsx, ts/screens/wallet/ConfirmCardDetailsScreen.tsx, ts/screens/wallet/TransactionDetailsScreen.tsx, ts/screens/wallet/TransactionsScreen.tsx, ts/screens/wallet/WalletHomeScreen.tsx, ts/screens/wallet/WalletsScreen.tsx, ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx, ts/screens/wallet/payment/PickPaymentMethodScreen.tsx, ts/store/actions/navigation.ts, ts/store/actions/wallet/payment.ts, ts/store/actions/wallet/transactions.ts, ts/store/actions/wallet/wallets.ts, ts/store/helpers/indexer.ts, ts/store/reducers/wallet/transactions.ts, ts/store/reducers/wallet/wallets.ts, ts/types/react.ts
Information about wallet and transaction selected for the details screens is now passed via navigation parameters (in a type safe way using custom navigation actions and navigation param types).
Also adds handling the case where a transaction is linked to a wallet that has been deleted (it seemed to me this case wasn't handled).
=> Refactor data flow for wallet and transaction details screens to avoid the redux store  

ts/sagas/wallet.ts, ts/types/pagopa.ts
@cloudify 
The value of the favourite switch was not passed to the API request but also now that is passed the API return value has still `favourite = false` please investigate API-side.
REQUEST PAYLOAD
```
{
"data": {
"creditCard": {
"expireMonth": "12",
"expireYear": "22",
"holder": "Mario Rossi",
"pan": "XXXXXXXX99996934",
"securityCode": "543"
},
"favourite": true,
"idWallet": null,
"type": "CREDIT_CARD"
}
}
```
RESPONSE PAYLOAD
```
{
"data": {
"creditCard": {
"brandLogo": "...generic.png",
"expireMonth": "12",
"expireYear": "22",
"flag3dsVerified": false,
"holder": "Mario Rossi",
"id": 6026,
"pan": "************6934"
},
"favourite": false,
"idWallet": 7205,
"pspEditable": true,
"type": "CREDIT_CARD"
}
}
```
=> [161198605] Set card as favourite if required on save

ts/components/wallet/WalletLayout.tsx, ts/screens/wallet/TransactionDetailsScreen.tsx, ts/screens/wallet/TransactionsScreen.tsx, ts/screens/wallet/WalletHomeScreen.tsx, ts/screens/wallet/WalletsScreen.tsx
Action is needed only when payment button is enabled (in home only)
=> Refactors logic behind main wallet button

locales/en/index.yml, locales/it/index.yml, ts/components/ui/BoxedRefreshIndicator.tsx, ts/components/wallet/TransactionsList.tsx, ts/screens/wallet/WalletHomeScreen.tsx
Not 100% perfect as payments can still be started from a message, but not yet clear from a UX point of view how we can block that when wallets are not yet loaded. Also in the case of a message, the wallet home screen gets rendered when navigating to the payment flow.
=> [#161484154] Do not start a payment if wallets are not available

ts/theme/components/FooterWithButtons.ts
This PR fixes the style applied to `<FooterWithButtons>` with `inlineOneThird` prop to actually be 1/3 and 2/3.
=> Fix "inlineOneThird" style.

ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
(Don't mind the "?"s and the "NaN"s, I used mocked data to show this screen)
=> [#161447989] Fix buttons style in confirm method screen.

ios/ItaliaApp.xcodeproj/project.pbxproj, ios/ItaliaApp/AppDelegate.m, ios/ItaliaApp/Info.plist, ios/ItaliaAppTests/Info.plist
This was causing a problem with iOS 12, the screen would turn white when opening a push notification
=> [#162014016] Removes secure app blank screen on iOS

ts/sagas/profile.ts
Bug should only manifest in iOS simulator since there is no call to the backend for configuring push notifications.
=> [#163254541] Fixes infinite loop when session is expired on startup.

ts/screens/messages/MessageListScreen.tsx, ts/store/reducers/entities/messages/index.ts
The current implementation:
```
export const orderedMessagesStateSelector = createSelector(
messagesAllIdsSelector, // FIXME: not needed, we can extract the IDs from messageStateById
messagesStateByIdSelector,
(potIds, messageStateById) =>
pot.map(potIds, ids =>
[...ids]
.sort((a: string, b: string) => b.localeCompare(a))
.map(messageId => messageStateById[messageId])
.filter(isDefined)
)
);
```
The problem here is that when messagesStateByIdSelector return a new value (ex: a message is loaded or the read status changed) the ids sorting is applied for no reason (the ids are not changed).
To solve i have splitted the function into 2 selector, the second one is using the first.
```
/**
* Returns array of messages IDs inversely lexically ordered.
*/
export const lexicallyOrderedMessagesIds = …
```
=> [#163824330] Optimize MessageState[] selector

README.md, ts/config.ts, ts/sagas/messages/__tests__/messages.test.ts, ts/sagas/messages/messages.ts, ts/sagas/startup.ts, ts/sagas/startup/__tests__/watchLoadMessages.test.ts, ts/sagas/startup/watchLoadMessageWithRelationsSaga.ts, ts/sagas/startup/watchLoadMessagesSaga.ts, ts/sagas/startup/watchMessageLoadSaga.ts
The PR add a generator that listen for loadMessage.request actions and forward them to a pool of created handlers using a redux-saga channel. This means that we will have at most a number of concurrent fetches (of the message detail) equal to the number of the handlers, avoid the current problem of to many concurrent fetches.
Current version with **UNLIMITED** concurrent fetches (the device hangs and the offline message get rendered)
The new version with **LIMITED** concurrent fetch (no device hang and no offline message)
=> [#162164390,#163825403] Handle loadMessage requests with a pool of workers

ts/theme/components/Button.ts, ts/theme/variables.ts
This PR aims to fix message CTA line height for iOS
Screen from iPhone 6s
=> [#164595292] Fixed message CTA line height for iOS

ts/theme/components/Button.ts, ts/theme/variables.ts
This PR aims to fix line height in messages CTA 
iOS (iPhone X)
=============================================
Android
=> [#164595292] fix line height for small message CTA labels in iOS

patches/@types/react-native-text-input-mask+0.7.2.patch, patches/react-native-text-input-mask+0.8.0.patch, ts/@types/native-base-types.d.ts, ts/components/ui/MaskedInput.tsx, ts/screens/wallet/AddCardScreen.tsx
A bug in `react-native-text-input-mask` prevent to clear the TextInputMask component value using setState so a patch is needed.
https://github.com/react-native-community/react-native-text-input-mask/issues/68
https://github.com/react-native-community/react-native-text-input-mask/pull/61
=> [#164351434] Remove card data on background

ts/boot/configureStoreAndPersistor.ts, ts/sagas/installation.ts, ts/sagas/startup.ts, ts/store/actions/installation.ts, ts/store/actions/types.ts, ts/store/reducers/index.ts, ts/store/reducers/installation.ts, ts/store/reducers/types.ts
This PR aims to clear data at first run of the app on iOS devices. 
This has to be considered as a workaround for devices having iOS 12.3 or below, because keychains is not cleared between two consequent installations of the same app, in those versions.
=> [#164896887] Clear user data at first run after install on iOS devices

ts/components/ui/Markdown/index.tsx, ts/screens/preferences/ServiceDetailsScreen.tsx
This PR aims to fix the case when markdown content is rendered during the ease-out animation of the Activity indicator as shown here
=> [#165008942] service detail screen markdown loading

ts/components/ConnectionBar.tsx
The problem of the truncated label occurs only on some devices that use certain system fonts such as the OnePlus or OPPO phones. Forcing the Text to use the RobotoMono-Regular font (already present in the assets folder) the problem is solved.
=> [#161952466] Fixed truncated offline label

ts/components/wallet/card/CardComponent.tsx
The whole card area is available for selection.
=> [#161417464] Whole card component handle touch event, moved from footer and refactored

ts/components/messages/MessageListItemComponent.tsx
This PR aims to fix checkbox padding in iOS
=> [#165377883] Set checkbox padding when message is selected from list

ts/components/wallet/card/CardComponent.style.ts, ts/components/wallet/card/CardComponent.tsx
This pr should fix a bug on the credic card rendering. It had been tested on s5 device. It affects the fontsize of the hidden numbers only, reducing it from the larger to the smaller font size.
**Before the commit:**
**After the commit:**
**Here the rendering on ios after the commit:**
=> [#165274563] Fix credit card rendering on samsung

ts/components/ui/FooterWithButtons.tsx
This PR aims to fix UI when footer right button has a too long label. This bug shows up in QR code read screen.
=> [#165410496] Add ellipsis to QR code button long label

ts/IdentificationModal.tsx
This PR aims to fix TouchID popup-trigger controls by specifying more compelling conditions.
Expected behaviour:
IC: app up and running on any page of choice.
1. CIT presses home button sending the app to background
2. CIT presses side screen-off button
3. CIT presses button of 2. again setting the screen on and unlocks the device
4. IS shows icons in the background
5. CIT taps the app and opens it
6. IS shows the latest page visited (IS DOES NOT prompt the TouchID alert over IO app page)
END
IC: initial conditions . 
IS: the system (the device) of the user . 
CIT: the user .
=> [#165387562] Fix TouchID popup-trigger controls

ts/components/screens/BaseHeader.tsx
This PR aims to replace application name in headers with IO icon everywhere but in the wallet section
---
=> [#165715583] Replace application name in headers with IO icon

ios/ItaliaApp.xcodeproj/project.pbxproj
Removed all references to RCTGeolocation
=> [#165661178] Removed all references to RCTGeolocation

ts/screens/preferences/ServiceDetailsScreen.tsx
This PR aims to add a link to PEC detail in service screen
=> [#165631660] add a link to PEC detail in service screen

ts/screens/wallet/TransactionDetailsScreen.tsx
This pr use the existing function formatDateAsLocal to present data with a format depending on the selected locale.
Here an example of the effect when it is mocked a transaction with creation date (transaction.create) equal to new Date(2018,10,30,13,12,22,30).
English:
Italian:
=> [#162156637]  Make data format depending from locales on transaction details

ios/Podfile.lock, package.json, yarn.lock
> Warning: ViewPagerAndroid has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native'. See https://github.com/react-native-community/react-native-viewpager
The problem is caused by an old version of the "react-native-gesture-handler" library, updating to version 1.2.1 the Warning no longer appears.
=> [#165407029] Fix ViewPagerAndroid Warning message

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/TransactionsList.tsx, ts/screens/wallet/TransactionsScreen.tsx, ts/screens/wallet/WalletHomeScreen.tsx
The label of the Total amount column in the Wallet Home has been changed to Amount since it doesn't include the commission fees.
=> [#162156628] Changed Total amount column label

ts/components/screens/AnimatedScreenContent.tsx, ts/components/wallet/WalletLayout.tsx
This pr introduces the usage of the onLayout attribute to measure the height of the dynamic sub-header into the AnimatedScreenContent component.
=> [#166639738] Inherit dynamic subheader height form the component itself

ts/screens/wallet/payment/TransactionSummaryScreen.tsx
Increased the opacity for the payment summary screen
Before:
Now:
=> [#166694691] Fix opacity in the loading screen of payment summary

ts/components/screens/ScreenContentHeader.tsx, ts/screens/messages/MessagesHomeScreen.tsx
This PR aims to fix header title and tab bar position for android devices
Android
iPhone 8
iPhone X
=> [#166789157] Fix header title and tab bar position for android devices

.circleci/config.yml, scripts/pagopa_api_check.sh
This PR aims to fix the nightly job that checks if there are differences from pagoPa specs **production**/**test**
Different from previous implementation, to skip the hosts difference, now **_host_** section will be removed from both specs file just before execute **diff** command
=> [#167008321] Fix pagoPa specs check

locales/it/index.yml, ts/components/messages/MessageCTABar.tsx, ts/components/messages/PaymentButton.tsx
This pr implements the designed style for CTA pay button if the transaction paired with the message had been completed.
=> [#167106329] add paid style to cta button

locales/en/index.yml, locales/it/index.yml, ts/screens/wallet/WalletHomeScreen.tsx
This pr introduces a check on the user's wallet. If it includes wallets which are not a CREDIT_CARD type, the user displays an alert advising his wallets are not supported on IO app.
TODO: test it with a no mocked account having not supported wallets
=> [#166761429] Check if user has not supported wallets only

ts/screens/preferences/OldServicesHomeScreen.tsx
The list of services is now correctly ordered.
=> [#166761737] Fixed the services list alphabetical order

android/app/proguard-rules.pro
Fixed the crash on Android 5.1 by adding a new rule in proguard.
=> [#167400108] Fix crash on Android 5.1

locales/en/pin_unlock_help.md
This PR introduces the transaltion of the markdown displayed on the IdentificationScreen
=> [#167591482] Add translation

ts/boot/configureStoreAndPersistor.ts
This pr properly migrates the usage of the persisted state isPagoPATestEnabled. When introduced, this state was not migrated and it resulted in the value undefined when calling the backend for those users using the app before the pagopa test enviroment was re-introduced. 
Now, for these kind of users, the state isPagoPATestEnabled is set as default to **false**.
=> [#167479784] Fix undefined on test attribute value at payment activation 

ts/components/MessagesTabIcon.tsx, ts/store/reducers/entities/messages/index.ts
Now the badge counter is incremented ony if messages are unreaded or unarchived
=> [#167595901] Messages badge counter without archived messages

ts/components/FiscalCodeLandscapeOverlay.tsx
This pr introduces the back hardware management on the overlay used to display the fiscal code fac-simile in the landscape mode.
here the final result:
=> [#167900944] Add hardware back managment on FC landscape fac-simile

android/app/src/main/java/it/teamdigitale/app/italiaapp/MainActivity.java, android/app/src/main/res/values-it/strings.xml, android/app/src/main/res/values/strings.xml, ios/ItaliaApp.xcodeproj/project.pbxproj, ios/ItaliaApp/AppDelegate.m, ios/ItaliaApp/en.lproj/Localizable.strings, ios/ItaliaApp/it.lproj/Localizable.strings
Added missing italian translation for the devices rooted/jailbroken alert on iOS and Android.
**iOS:**
**Android:**
=> [#168195574] Device rooted alert translation

locales/en/index.yml, locales/it/index.yml, ts/components/messages/MessageAgenda.tsx, ts/components/messages/MessageDetailComponent.tsx, ts/components/messages/MessageList.tsx, ts/components/messages/MessageListItem.tsx
This pr solves the bug causing error screen if the content  of a message related service is not available (into `state.entities.service.byId`).
If `service_id` is undefined and/or the servce is none, the message detail des not displayes the logo, the organization name and the service name (the latters being ""unkown sender/service)
Here  an example after the implementation:
=> [#168141240] Fix bug if sender is unknown

android/app/src/main/res/values-it/strings.xml, android/app/src/main/res/values/strings.xml, ios/ItaliaApp/en.lproj/Localizable.strings, ios/ItaliaApp/it.lproj/Localizable.strings
Fixed alert message text.
**iOS:**
**Android:**
=> [#168195574] Fix device rooted alert translation

ts/components/messages/CalendarEventButton.tsx
When a reminder is put in calendar, in the message detail screen, the check mark does not appear in the "reminder" button.
|Before                         |After                         |
|-------------------------------|-----------------------------|
|<img width="151" alt="Before_android" src="https://user-images.githubusercontent.com/17931148/64647015-80664380-d418-11e9-97ac-3a4d79d17b44.png">| <img width="151" alt="After_android" src="https://user-images.githubusercontent.com/17931148/64647014-7fcdad00-d418-11e9-9762-0dea6a6b8f2c.png">|
|<img width="151" alt="Before_ios" src="https://user-images.githubusercontent.com/17931148/64647147-c1f6ee80-d418-11e9-9f77-931ff4d5c594.png">|<img width="151" alt="After_ios" src="https://user-images.githubusercontent.com/17931148/64647149-c1f6ee80-d418 …
=> [#168401222] Solves lost reminder mark

locales/en/index.yml, locales/it/index.yml
This PR changes the message displayed in transaction detail screen when the payment method used to pay the transaction is no longer saved into the wallet
=> [#168462053] Change "removed payment method" in Transaction Detail screen

ts/components/Pinpad/index.tsx, ts/screens/onboarding/PinScreen.tsx
Now once you have entered the correct PIN code for the second time, if you press the "cancel" button, the "continue" button is hidden.
BEFORE:
AFTER:
=> [#168507278] Fix confirm pin

ts/screens/profile/PreferencesScreen.tsx, ts/screens/profile/PrivacyMainScreen.tsx, ts/screens/profile/ProfileMainScreen.tsx
This PR add a smile to the end of list in preferences, privacy and profile (debug mode on/off) screen.
| Preferences  | Privacy |
| Profile (debug mode off)  | Profile (debug mode on) |
=> [#168195930] End list component 2

ts/screens/profile/FiscalCodeScreen.tsx, ts/store/reducers/content.ts
This PR fixes a wrong implementation done here https://github.com/teamdigitale/io-app/pull/1356
Now the municipality metadata will be deleted at startup when (if) the current profile has a cf different from the previous one
=> [#168991871] Clear municipality metadata at startup

ts/components/messages/MessageListItem.tsx
This pr updates the message list item to display, under the name of the organization, the service name  instead of the department name
=> [#169311321] From department to service on message list item

ts/sagas/wallet/pagopaApis.ts
This PR fixes a bug inside deleteWalletRequestHandler where the action **deleteWalletFailure** is called with a wrong parameter (a string instead of the Error object)
=> [#169347578] Fix error forwarding on deleteWalletRequestHandler

ts/store/reducers/index.ts
This pr introduces a small fix on the order the reducers are listed in the `appReducer` item to get:
- not persisted states are listed under the `ephemeral state` comment
- persisted states are listed under the `persisted state` comment
=> [#169017205] Order reducers in store index file

ios/ItaliaApp/Info.plist
The **NSBluetoothAlwaysUsageDescription** permission is mandatory if an app (including dependencies) uses the Bluetooth API*.
In older iOS versions it was called **NSBluetoothPeripheralUsageDescription** and it is already present in the Info.plist but it has been replaced with NSBluetoothAlwaysUsageDescription in iOS 13; since the app targets an earlier iOS version both permissions are required.
<sub>*_the API is used by the library react-native-community/react-native-permissions_</sub>
[Apple documentation reference](https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothperipheralusagedescription)
=> [#169732720] Added missing iOS permission

ts/navigation/OnboardingNavigator.ts, ts/navigation/routes.ts, ts/sagas/startup.ts, ts/screens/LoadingScreen.tsx, ts/store/actions/navigation.ts
This PR adds a loading screen during the saga startup process to display until all the saga are performed
=> [#169424936] added LoadingScreen & new loading route

CODE_OF_CONDUCT.md, ts/utils/__tests__/profile.test.ts, ts/utils/profile.ts
This PR fixes the century extraction from CF:
the year of birth is represented by 2 digit (index 6-7) into the cf
ex: GLIRSS**03**L52H501A
03 could mean 1903 or 2003
The fix consist to check if the computed year is greater than a century. In that case we could assume the year is referring to someone born in the 2000
=> [#170014542] Fix data extraction from cf

ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
This PRs fixes a crash that happens when user navigates on ConfirmPaymentMethodScreen
Removed unsupported nested views
Maybe this bug is related to this https://github.com/teamdigitale/io-app/pull/1259
Try for a payment.
=> [#170402537] Fix crash on ConfirmPaymentMethodScreen

ts/IdentificationModal.tsx, ts/boot/configureStoreAndPersistor.ts, ts/components/Pinpad/index.tsx
This PR fixes a security bug on the identification phase.
- Avoid PIN insertion while biometric is requesting
On Identification screen try to insert some pin digitis before the biometric dialog is displayed. The pin digits should be discarded
=> [#170315020] Fix pin insertion while biometric is requesting

ts/components/IdpSuccessfulAuthentication.tsx, ts/screens/authentication/IdpLoginScreen.tsx
This pr introduces some updates to the screens related to the idp selection
- Add comment to describe the `IdpSuccessfulAuthentication` component
- `IdpLoginScreen`:
- shift comment to the top of the screen
- use an enum instead of strings as values of the component state `requestState`
- [MAIN CHANGE]`loggedOutWithIdpAuth`: this state should be always true, having that the corresponding redux state is updated slightly before the app navigates from `IdpSelectionScreen` to this screen. The redux state update process is an async process, so, in the remote case its update takes a longer time, instead of returning a null object (implying a white screen is displayed), we could display a Loader as the following
=> [#169541951] Minor updates to idp selection code

ts/screens/wallet/WalletHomeScreen.tsx
This PR make the footer button visible only when wallets are successfully loaded
=> [#168138829] fix pay notice button

locales/en/index.yml, locales/it/index.yml
this PR changes the locales 'reminders.loadMoreData':
* it
* before: carica le scadenze del periodo precedente
* now: scadenze precedenti
* en
* before: loads the deadlines of the previous period
* now previous deadlines
=> [#169224694] fix reminders.loadMoreData locales

ts/components/messages/MessageList.tsx
this PR allows you to display, if present, the service previously loaded while it is being refreshed.
=> [#169067698] fix loading potService in messageList

ts/components/messages/MessagesArchive.tsx, ts/components/messages/MessagesDeadlines.tsx, ts/components/messages/MessagesInbox.tsx, ts/screens/messages/MessagesHomeScreen.tsx
With this PR the massive selection of messages is disabled when the user scrolls the tab more than 50% or click in another tab
| BEFORE  | AFTER |
=> [#170679956] reset selection when change tab

ts/screens/onboarding/EmailInsertScreen.tsx
This PR fixes 2 bugs when at login the user hasn't got an email. In the screen where user has to insert a valid email address:
- go back returns to previous screen and the app goes in an invalid navigation state
- continue button returns to previous screen and the app goes in an invalid navigation state
Run a local server when the profile has an undefined email
`email: undefined`
=> [#170920948] Fix email insertion navigation

locales/en/index.yml, locales/it/index.yml, ts/screens/profile/PreferencesScreen.tsx, ts/store/reducers/profile.ts
This PR removes some useless type check.
This PR also adds logic to handle a profile with a valid session but with no email (it should not happen)
If the profile has not an email, it is evaluated as **not validated** and the app shows a screen to insert the email address
=> [#170928928] Add logic to handle a profile with no email

ts/sagas/wallet.ts, ts/screens/profile/ProfileMainScreen.tsx, ts/store/actions/wallet/wallets.ts, ts/utils/SessionManager.ts
This PR invalidate payment manager session if/when user profile has not an email validated.
- At the startup the wallet saga checks if the profile has an email validated
- Each time a profile is loaded or updated the wallet saga is triggered and there the session could be stopped or not
=> [#170014535] Invalidate PM session when email is not validated

ts/components/RemindEmailValidationOverlay.tsx
This PR fixes the condition to render the footer in RemindEmailValidationOverlay Screen.
Previously the footer was rendered when the markdown content has been loaded.
But when the email is already validated the markdown component is not included.
The condition to render the footer is:
the email is validated **OR** the markdown content is loaded
=> [#170899177] Fix footer render condition on RemindEmailValidationOverlay

ts/sagas/startup/watchApplicationActivitySaga.ts
This PR fixes a bug causing biometric authentication loop.
This is due to wrong app state changes management:
```typescript
if (lastState === "inactive" && isSecuredRoute) {
yield put(identificationRequest());
}
```
when biometric authentication is prompted to the user the app state changes as follows:
**active** -> Authentication Screen is displayed
**inactive** -> biometric auth is prompt
**active** -> user biometric auth is successfully
so that condition is always true
=> [#171127074] Fix biometric loop

ts/screens/services/ServicesHomeScreen.tsx, ts/store/reducers/content.ts
This PR fixed pull-refresh in the "National" Services tab, now if a list of services is already displayed, it remains displayed during loading
=> [#170745720] fix refresh national services

ts/boot/configureStoreAndPersistor.ts
The pr is aimed to solve a bug on the migration of the redux store which caused a white screen in the 
The error involves the `servicesByScope` state, which is used to evaluate the badge value on the service tab icon. The bug is solved by manually initializing the state within a migration, the state is no more assumed as undefined.
Shift from version 27 (completing the authentication and onboarding) to master to replicate the error.
=> [#171231382] Fix bug on migration of servicesbyscope

package.json, ts/components/wallet/card/CardComponent.tsx, ts/store/reducers/wallet/wallets.ts
This PR fixes a bug on set wallet as favorite: the bug occur when the user deletes a credit card that was set as favorite. The reducer has a wrong logic: on **fetchWalletsSuccess** if there is not favorite wallet  (this is the case when the user delete one) **favoriteWalletId** is never updated and it has the value setted on previous action **fetchWalletsRequest** (_pot.loading_)<br/>
When the user asks for setting a credit card as favorite, the relative handler does nothing if the state of the **favoriteWalletId** is _pot.loading_<br/>
The fix is to set **favoriteWalletId** to _pot.some_ if there is a favorite wallet or to _pot.none_ if it is not
- add a credit card
- set the previous credit card as favorite
=> [#171303752] Fixed wallet reducer

ts/components/ContextualHelp.tsx, ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
Close help modal on back button
In the payment confirmation screen, the help modal of the 'Why' label is not closed on the back button
=> [#171487775] Add closing help modal on back button

ts/components/screens/BaseHeader.tsx
Fix warning
The goback value in BaseHeader component could also be a boolean instead of a function. This generates a warning
=> [#170818734] Fix warning BaseHeaderComponent

ts/sagas/startup.ts
It could happen profile could be none on app initialization.
This could be due to network errors (e.s timeout) or to decoding failure.
When the profile is none, the app starts requesting profile in loop
Add a delayer before start again the initialization saga
Run the [io-dev-api-server](https://github.com/pagopa/io-dev-api-server) and serve a profile that cant be decoded by the app (removing a required field for example)
=> [#171707334] add a delayer before start again initializeApplicationSaga

ts/screens/services/ServiceDetailsScreen.tsx
In the service tab the contacts label appears when the content is displayed
=> [#171764636] Fix label contacts

ts/screens/services/ServiceDetailsScreen.tsx
Replace the deprecated method componentWillReceiveProps  with componentWillUpdate
the changes do not affect the functionality:
go to service detail -> switch off data transfer/local server -> try to enable/disable switch on notifications
Result: as the answer to the request is received, the switch return to the previous value and an error toast is displayed
=> [#171629235] replace deprecated method 

android/app/src/main/AndroidManifest.xml, android/gradle/wrapper/gradle-wrapper.properties
This PR forces removal of an unwanted permission on Android: **READ_PHONE_STATE**.
IO app doesn't need that permission, indeed it is injected from [react-native-revide-info](https://github.com/react-native-community/react-native-device-info) library after the last upgrade
see https://github.com/react-native-community/react-native-device-info/issues/955
=> [#171812026] Remove READ_PHONE_STATE permission on Android

patches/react-native+0.60.5.patch
Added patch to fix refresh control on ios - This patch was already present for the previous version of react-native
When updating the contents of the services home, the loader must always be displayed during loading
=> [#170821365] Added patch to fix refresh control on ios

ts/screens/wallet/payment/ManualDataInsertionScreen.tsx
Added done button (iOS) on keyboard in insert notice data screen
<table style="width:100%">
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/7993551/77441302-956d5780-6de9-11ea-94a0-a887adde9649.png"/></td>
<td><img src="https://user-images.githubusercontent.com/7993551/77441341-9f8f5600-6de9-11ea-907f-e9322d634a68.png"/></td></tr>
</table>
=> [#171644514] Added done button on keyboard

ts/components/RemindEmailValidationOverlay.tsx, ts/screens/onboarding/EmailInsertScreen.tsx, ts/screens/onboarding/EmailReadScreen.tsx
This PR fixes a bug on onboarding navigation.
It happens when a user wants to change his email address.
**Step to reproduce**
- start **first** onboarding
- login with a profile with a validated email
- change it
- blank screen
=> [#171971692] Fix edit email onboarding navigation

ts/IdentificationModal.tsx
This PR fixes a bug on pin insertion.
If biometric authentication failed the user can't insert the pin.
**Steps to reproduce**
- request face id
- face id failure
- choose "use pin"
- can't type any digits on pin pad
=> [#171981450] Fix pin insertion on biometric authentication failure

ts/store/middlewares/navigationHistory.ts
This PR fixes a bug that occurs when user wants leave the app then he comes back and no identification is requested
On Android:
- back press until exit the app
- re-open the app
- no identification is requested
=> [#171981909] Fix identification request on exit app

.circleci/config.yml
This PR removes, temporary, automatic releases on the alpha Android track.
It is due to leave to Google review program 48h to complete the review of our RC submitted on 30th March 2020
=> [#172075548] Hold alpha android releases on circleci

ts/components/HorizontalScroll.tsx
Landing Screen HorizontalScroll:
- reintroduce a space between the footer and the scroll indicator 
- make indicator being rounded not rectangle (it can be appreciated when scrolling)
=> [#172121293] fix missed space

ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
It affects the loader displayed in CieConsentDataUsageScreen
AFTER:
=> [#172122233] update loader opacity to avoid color overlap

ts/components/FiscalCodeComponent.tsx
This PR improves the readability of the Barcode on the Fiscalcode landscape component.
- FiscalCodeComponent.tsx. Styles values
=> [#168726573] Improve landscape Fiscal code barcode readability

ts/screens/services/ServiceDetailsScreen.tsx
This PR adds the EdgeBorderComponent to Service Detail Screen to fix the cutting of the last element in the view.
- screens/services/ServicesDetailsScreen.tsx
=> [#172147176] Added EdgeBorderComponent to Service Detail screen

ts/components/ItemSeparatorComponent.tsx
This PR fix the wrong rendering of the `ItemSeparatorComponent`.
Change the style `height`to `StyleSheet.hairlineWidth` [hairlineWidth](https://reactnative.dev/docs/stylesheet#hairlinewidth)
=> [#171742890] Fix ItemSeparatorComponent height

ts/screens/services/ServiceDetailsScreen.tsx
Wrong text displayed when opening a ServiceDetailsScreen without email as notification channel.
Moved the `<Text>` block with all the information related to the email inside the method `getEmailSwitchRow` dedicated to the rendering of this component.
Open a ServiceDetailsScreen with a service without email as notification channel.
=> [#172059281] Bug service without mail display wrong text

ts/components/InstabugButtons.tsx
Remove email field as required in Instabug report
This is how it looks like now
=> [#172260732] Remove email field as required in Instabug report

ts/components/ui/Switch.tsx
This PR changes the color of the Switch if it's disabled on Android
- ts/components/ui/Switch.tsx
=> [#172247431] Handle android disabled switch color

ts/components/ContextualHelpModal.tsx, ts/components/screens/BaseScreenComponent.tsx, ts/components/screens/DarkLayout.tsx
This PR adds transparency on Contextual Help Modal and manages the transition beetween white and grey color of the status bar.
Previously on android the status bar appeared shadowed.
- ts/components/screens/BaseScreenComponent.tsx
- ts/components/ContextualHelpModal.tsx
- ts/components/screens/DarkLayout.tsx
Click on the question mark on the top in any screen
=> [#172197576] Fixed Status bar behaviour on modal

ts/screens/profile/ProfileMainScreen.tsx
Adds the missing separator above "About IO Beta" menu item
- ts/screens/profile/ProfileMainScreen.tsx
=> [#172275302] Fixed missing separator on "About IO Beta" menu voice

ts/store/reducers/entities/services/index.ts
**NOTE** this is a workaround not a solution
since a service can change its organization fiscal code we could have obsolete data in the store: **_byOrgFiscalCode_** could have services that don't belong to organization anymore this cleaning its a workaround, this should be fixed on data loading and not when data are loaded see https://www.pivotaltracker.com/story/show/172316333
=> [#172316347] Add workaround to avoid organizations duplication

ts/store/reducers/entities/services/index.ts
**NOTE** this is a workaround not a solution
since a service can change its organization fiscal code we could have obsolete data in the store: **_byOrgFiscalCode_** could have services that don't belong to organization anymore this cleaning its a workaround, this should be fixed on data loading and not when data are loaded see https://www.pivotaltracker.com/story/show/172316333
This is a little improvement of this workaround https://github.com/pagopa/io-app/pull/1680
=> [#172316347] Add workaround to avoid organizations duplication v2

ts/boot/configureInstabug.ts
This PR fixes a strange Instabug behavior: when we turn off network logger, Instabug turn off all network interceptions also for other tools (ex Reactotron)
see https://github.com/Instabug/Instabug-React-Native/blob/f311ece05205be408bce1ec1e052b25b4c967299/modules/NetworkLogger.js#L21
To avoid this, we turn off network logger only when we are in no-dev envirnment
=> [#172355932] disable network logger only when in release mode

ts/components/messages/MessageDetailComponent.tsx, ts/screens/messages/MessageDetailScreen.tsx
This PR fixes the cut message text from EdgeBorderComponent.
- ts/components/messages/MessageDetailComponent.tsx
- ts/screens/messages/MessageDetailScreen.tsx
=> [#172493528] Fixes EdgeBorderComponent on Message Detail

ts/components/ContextualHelpModal.tsx
This pr updates the dimension of the title in the Contextual Help Modal
BEFORE:
AFTER:
=> [#172531916] Reduce contextual help title font size

package.json
This PR add the `attach` command to package.json in order to debug the application with others third party tools (eg: webstorm).
Added `"attach": "react-native attach"` in scripts section.
=> [#172576541] Add attach command

ts/store/reducers/entities/services/__tests__/index.test.ts, ts/store/reducers/entities/services/index.ts
This PR fixes a bug on listing organizations in _**all**_ tab
If an organization is selected by the user it shouldn't be listed in all services.
This bug was introduced by this PR https://github.com/pagopa/io-app/pull/1681 that merges two or more organizations having the same name
=> [#172580555] Fix selected organizations listed in all services tab

ts/components/screens/BaseScreenComponent.tsx
This PRs 
- restores slide animation when the modal of the contextual help is closed (iOS only).
- avoids modal closing when user request a report that doesn't bring a screenshot
=> [#172580983] Avoid close modal if report type isn't a bug

ts/screens/authentication/cie/CiePinScreen.tsx
This PR fixes the device error when user cancel the CIE authorization loading
- ts/screens/authentication/cie/CiePinScreen.tsx
Login with CIE, insert a PIN on loading screen click "Cancel" button or use the hardware back button to cancel the request
=> [#172474643] Fixes CIE cancel on loading screen critical error

ts/sagas/contentLoaders.ts, ts/store/actions/content.ts, ts/store/middlewares/analytics.ts, ts/store/reducers/content.ts
This pr allows to track when a municipality request is not available in `io-services-metadata`.
- Changed the payload of `contentMunicipalityLoad.failure` adding the `codiceCatastale`.
- Send the message to MixPanel when there is an event of `contentMunicipalityLoad.failure`
Using the `dev` server, temporarily remove the handler:
```typescript
app.get(`${staticContentRootPath}/municipalities/:A/:B/:CODE`, (_, res) => {
res.json(municipality);
});
```
and check if the event is correctly registered on mixpanel using the jql:
```javascript
function main() {
return Events({
from_date: "2020-xx-xx",
to_date: "2020-xx-xx"
})
.groupBy(
["properties.codice_catastale"],
mixpanel.reducer.count()
);
}
```
=> [#172577116] Track failure on mixpanel when trying to load a missing municipality

ts/components/cie/CieNfcOverlay.tsx
This PR fixes the blocking transition on CieNfcOverlay screen when trying to go back.
- ts/components/cie/CieNfcOverlay.tsx
Disable NFC on smartphone and Login with CIE after PIN insertion, go back from Enable NFC screen without enabling NFC
=> [#172526234] Fixes the lock on CieNFCOverlay screen

ts/utils/payment.ts
According to internal PDO, IO forwards to instabug only necessary data to detect a payment when user needs support.
=> [#172678394] Forward to Instabug only necessary data

ts/screens/wallet/payment/TransactionSuccessScreen.tsx
this pr introduces a missed space between the footer buttons of the screen displayed at the end of a sucessfull payment:
=> [#172698983] Add missing space in paymentsuccessScreen

ts/screens/wallet/payment/TransactionSummaryScreen.tsx
This pr fixes a bug on navigation on payment 
Steps to reproduce the bug:
1. verify we have at least one added payment method
2. go to message listfind a message linked to payment and press 'pay'
3. from the displayed transaction summary, press next
4. from the displayed 'pay with'  screen select 'change method'
from the change payment method screen, go back until the payment is cancelled:
5.  press back on change method screen
6. press back on the 'pay with' screen
7. press back on the transaction summary screen
8.BEFORE: the focus remains on the transaction summary but the form is empty
8.AFTER: the focus returns to the message list
=> [#171743242] Grant back from transaction summary

ts/components/messages/MessageCTABar.tsx
This pr solve a bug on the message detail: if paid, we don't care anymore if the message is expiring or if it is expired:
NOTE: the bug is only on the current version of the CTA bar which will be overwritten by next pr
=> [#172553600] hide bottom bar if message payment is paid

ts/screens/wallet/payment/TransactionSummaryScreen.tsx
This PR improves the navigation from transaction summary to the payment entrypoint
- ts/screens/wallet/payment/TransactionSummaryScreen.tsx
=> [#171743242] Fixes back from Transaction summary screen to the payment entrypoint

ts/components/wallet/PaymentsHistoryList.tsx, ts/screens/wallet/PaymentHistoryDetailsScreen.tsx, ts/utils/payment.ts
- Add payment outcome inside payment detail screen
- Improve function to get payment details as log
=> [#172794872] Add payment outcome inside payment detail

ts/screens/wallet/payment/TransactionSuccessScreen.tsx
This pr updates the 'Close' button having that, now, we return to the payment entrypoint.
=> [#172818099] update success payment screen button content

ts/screens/services/ServicesHomeScreen.tsx
This pr automatically adds the tag `services-loading-error` when a bug report is sent from the the `ServicesHomeScreen`.
- Added the method `Instabug.appendTags([this.instabugReportTag]);`
Send a bug report from the `ServicesHomeScreen` and verify that the new report on istabug have the tag `services-loading-error`.
=> [#172886190] Automatically add the tag "services-loading-error" on instabug

ts/screens/wallet/PaymentHistoryDetailsScreen.tsx
This pr adds the tag "payment-support" when a new payment assistance request is sent to instabug.
- ` Instabug.appendTags(["payment-support"]);`
Send a Instabug request from the payment assistance section.
=> [#172941125] Add "payment-support" tag to instabug payment assistance requests

ts/sagas/startup/watchAbortOnboardingSaga.ts
This pr fixes a bug that allow to save the pin if the onboarding is aborted.
- call `deletePin` when `abortOnboarding` is dispatched.
Do the onboarding without complete it and abort. Restart again and verify if the pin is asked again.
=> [#172932681] Reset pin if the onboarding is aborted

ts/features/bonusVacanze/api/backendBonusVacanze.ts, ts/features/bonusVacanze/components/AvailableBonusItem.tsx, ts/features/bonusVacanze/components/RequestBonus.tsx, ts/features/bonusVacanze/screens/AvailableBonusScreen.tsx, ts/features/bonusVacanze/screens/BonusInformationScreen.tsx, ts/features/bonusVacanze/store/actions/bonusVacanze.ts, ts/features/bonusVacanze/store/reducers/availableBonuses.ts, ts/features/bonusVacanze/types/bonusesAvailable.ts, ts/screens/wallet/WalletHomeScreen.tsx
This PR aligns the bonus available type with the new remote data:
- added `is_active` required field (boolean)
- added `service_id` optional field (string)
=> [#173146890] Align bonus available type with the remote data

ts/screens/authentication/IdpLoginScreen.tsx
Instead of a translation key should be show the translation value
=> [#173289577] Fix ContextualHelp title translation

ts/RootContainer.tsx, ts/screens/modal/RootModal.tsx
Due to a scheduled update (checking if the min version is still compliant with the backend) the RootContainer inner state changes on each round.
The fix consists in a new component that holds the state of updates and shows a modal if it is needed.
This is what happens on every update: since a re-render is ordered the webview shows a refresh
=> [#173322606] Fix RootContainer re-renders

ts/components/wallet/PaymentSummaryComponent.tsx, ts/utils/__tests__/string.test.ts, ts/utils/strings.ts
This PR fixes a bug on transaction details.
Due to a wrong statement the app try to render an empty text
Buggy code
`stringValue && <SomeComponent>` fails when `stringValue===""`
this is because:
- `undefined && <SomeComponent>` -> `undefined` 
- `"some text" && <SomeComponent>` -> `<SomeComponent>` 
- `"" && <SomeComponent>` -> `""` 
It goes fine only when _stringValue_ is not undefined and with length > 0
| before  | fixed |
=> [#173353526] Fix transaction details crash

ts/features/bonusVacanze/store/sagas/eligibility/getBonusEligibilitySaga.ts
According with the API this PR
**removes**
- considering 404 as a blocking error in get eligibility. It should happen the IO backend returns 404 despite the previous start went fine. So on 404 the polling **should be not stopped**
**adds**
- before start eligibility check try a first get to check if the result is already available. This is because if the app does start a new check is spawned, with possibile delays
=> [#172989345] Improve eligibility check

ts/features/bonusVacanze/screens/activation/ActivateBonusCompletedScreen.tsx, ts/features/bonusVacanze/store/actions/bonusVacanze.ts, ts/features/bonusVacanze/store/sagas/activation/__tests__/handleBonusActivationTests.ts, ts/features/bonusVacanze/store/sagas/activation/__tests__/mockData.ts, ts/features/bonusVacanze/store/sagas/activation/handleBonusActivationSaga.ts
This pr allows to see the details of the bonus after the activation success.
- Dispatch the navigation event `navigateToBonusActiveDetailScreen` after the activation is completed
- Complete the bonus activation flow
- Execute `handleBonusActivationTests`
=> [#173414551] Navigate to BonusDetails after activation success

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/card/CardComponent.style.ts, ts/components/wallet/card/CardComponent.tsx, ts/components/wallet/card/RotatedCards.tsx, ts/components/wallet/card/SectionCardComponent.tsx, ts/features/bonusVacanze/components/BonusCardComponent.tsx, ts/features/bonusVacanze/components/RequestBonus.tsx, ts/screens/wallet/WalletHomeScreen.tsx
This PR adds some UI Fixes on wallet home header
- Card dimensions updated to mockups
- if no payment method or bonus is available the section cards are blue
- corrects some typos and labels
=> [#173353035] UI corrections to wallet header screen

ts/components/wallet/WalletLayout.tsx, ts/features/bonusVacanze/components/RequestBonus.tsx, ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx, ts/screens/wallet/WalletHomeScreen.tsx
This PR adds the handling on wallet home for multiple active bonuses
- ts/features/bonusVacanze/components/RequestBonus.tsx
- ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx
- ts/screens/wallet/WalletHomeScreen.tsx
=> [#173417354] Show all the active bonuses for the user

ts/store/reducers/entities/services/__tests__/index.test.ts, ts/store/reducers/entities/services/index.ts
This PR fixes a bug on services selector  **[visibleServicesDetailLoadStateSelector](https://github.com/pagopa/io-app/blob/f670e37c303101e280cff965f32373723015efea/ts/store/reducers/entities/services/index.ts#L94)**
The bug is on evaluating if there are some services still in loading:
```typescript
const areServicesLoading =
pot.isLoading(visibleServices) ||
visibleServicesById.some(
vs => vs === undefined || pot.isLoading(vs)
);
```
bug: if at least one service is in state **_someLoading_**, **_areServicesLoading_** -> true
Another issue is about: Why does service hold the state _**someLoading**_?
This will be investigated in another PR btw the data returned by the API, for this specific service (azure-deployc49a), could be not synced: **_version_** mismatches …
=> [#172075979] Fix services loading

ts/features/bonusVacanze/store/reducers/allActive.ts, ts/store/reducers/persistedPreferences.ts
This PR adds the store cleaning when requesting all bonus ids.
- ts/features/bonusVacanze/store/reducers/allActive.ts
Load all active bonus from dev-server, change it's payload and reload data from App.
=> [#173443457] Clean the store on loadAllBonusActivation

ts/components/ui/Markdown/index.tsx, ts/features/bonusVacanze/data/availableBonuses.ts, ts/features/bonusVacanze/screens/BonusInformationScreen.tsx
The bonus vacanze content is cutted.
This is because the markdown component compute an height that is not enough to display the whole content
=> [#173469785] Fix display Bonus Vacanze Detail content

locales/en/index.yml, ts/features/bonusVacanze/components/infoScreen/InfoScreenComponent.tsx, ts/features/bonusVacanze/components/infoScreen/imageRendering.tsx
This pr changes the aspect of the InfoScreenComponent, aligning the vertical content to middle.
iPhone 11            |  iPhone 8
Android Nexus 5 (1080x1920)    480 xxhdpi         |  
:-------------------------:|
- Modified the layout of `InfoScreenComponent.tsx`
- Changed `imageRendering.tsx` in order to scale the image size when the screen height is too short.
=> [#173430903] Center the content of the InfoScreenComponent

ts/api/backend.ts, ts/sagas/wallet.ts, ts/sagas/wallet/pagopaApis.ts, ts/utils/fetch.ts
This PR fixes infinite polling on payment id requests
- create a new backend client for every polling request
- each client has its own deferredPromise
- on cancel polling request, backend client will be stopped by using the relative deferredPromise instance
=> [#166572994] Fix payment ID infinite polling

android/app/src/main/java/it/pagopa/io/app/MainActivity.java
This PR removes the check that avoid usage on Android tablets
=> [#173640667] Remove tablet block from Android

ts/components/TosWebviewComponent.tsx, ts/screens/onboarding/TosScreen.tsx
- restore the "Accept" button state as **enabled** by default
- fix a bug that occurs by visiting tos from Profile section: an info box is shown even when the user has already accepted the ToS
=> [#173703926] Restore ToS accept button state

package.json, ts/components/cie/CieRequestAuthenticationOverlay.tsx, ts/screens/authentication/IdpLoginScreen.tsx, ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx, ts/screens/modal/Checkout3DsModal.tsx, ts/utils/login.ts, yarn.lock
Upgrade `@types/react-native` to 0.60.20.
=> [#173729510] upgrade @types/react-native: 0.60.20

locales/en/index.yml, locales/it/index.yml, ts/components/ButtonDefaultOpacity.tsx, ts/components/GoBackButton.tsx, ts/components/InstabugChatsComponent.tsx, ts/components/screens/BaseHeader.tsx, ts/components/search/SearchButton.tsx, ts/components/ui/CustomBadge.tsx
This pr improves the accesibility with a vocal assistant for the top bar.
- The buttons "back", "search", "help" and "instabug chat" are now identified as buttons (ios, android)
- When the voice assistante focus the "instabug chat" icon, announces also the number of unread messages.
- The`headerTitle` is now recognized as "header" (ios only)
=> [#173701927] Improve accessibility for top bar

locales/en/index.yml, locales/it/index.yml, ts/features/bonusVacanze/screens/activation/request/ActivateBonusReminder.tsx, ts/features/bonusVacanze/screens/activation/request/ActivateBonusRequestComponent.tsx
Update copy about household composition.
- Removed link from `ActivateBonusReminder.tsx`
=> [#173733388] update copy about household composition

ts/features/bonusVacanze/screens/BonusInformationScreen.tsx
This pr allows the link "Information on the processing of personal data" inside the screen `BonusInformationScreen` to be recognized as link from a screen reader.
=> [#173768527] Personal data link not recognized as link

ts/components/ui/LightModal.tsx
This PR fixes the half screen visualization on LightModal visualization.
- ts/components/ui/LightModal.tsx
***Before***
***After***
=> [#173794022] Fixes LightModal half screen bug

ts/components/RemindEmailValidationOverlay.tsx, ts/components/screens/TopScreenComponent.tsx, ts/screens/profile/FiscalCodeScreen.tsx
This PR adds accessibility on screen and components using customGoBack which wasn't recognized by screen reader
Adds the `avoidNavigationEventsUsage` prop on `TopScreenComponent` to avoid the crash error when EmailValidationOverlay shows up
=> [#173828514] Fixes customGoBack not accessible

ts/boot/configureStoreAndPersistor.ts
Fix `undefined is not an object`
When the app is running in not-dev environment that object is **undefined**
=> [#173877360] Fix undefined is not an object

ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx
This PR fixes the bonus detail header title color
=> [#173815288] Fixes bonus header title color

ts/types/pagopa.ts, ts/utils/__tests__/pagopa.test.ts
This PR fixes isSuccessTransaction that consider successfully only transactions done with CREDIT_CARD
We need to consider successfully also all other transactions payed with other methods different from CREDIT_CARD
https://docs.google.com/document/d/1zXrVafaJyfYDNH8M7LOvnW3MtTbLkEn6qvueZ4TZnSQ/edit#
=> [#173850410] Fix isSuccessTransaction

.env.production, ts/api/content.ts
This PR change the endpoint for static assets/data from [io-services-metadata](https://github.com/pagopa/io-services-metadata) to IO-CDN
=> [#173707422] Get static assets and data from IO CDN

scripts/changelog/gradle_updater.js, scripts/changelog/version_utility.js
This pr changes the format of the `versionName` value for Android.
Released version | Android previous`versionName` | Android new`versionName` 
:---------:|:---------:|:---------:
1.0.0 | 1.0.0 | 1.0.0  
1.1.0-rc.0 | 1.1.0-rc.0 | 1.1.0.0 
1.1.0-rc.1 | 1.1.0-rc.1 |  1.1.0.1
1.1.0 | 1.1.0 |  1.1.0 
1.1.1-rc.0 | 1.1.1-rc.0 | 1.1.1.0
- Changed `gradle_updater.js ` to support the new syntax
=> [#173984555] Change Android gradle versionName format

.circleci/config.yml
This pr allows to generate a new Android release only when a new version tag is pushed (regardless of the branch).
- Added a `release` workflow, triggered only when a new release tag is pushed.
=> [#173984610] Android alpha build is created at each master commit

ts/components/ui/Markdown/index.tsx, ts/features/bonusVacanze/screens/BonusInformationScreen.tsx
This PR improves the font-size on bonus vacanze information screen and unifies the font-size of markdown component
- ts/components/ui/Markdown/index.tsx
- ts/features/bonusVacanze/screens/BonusInformationScreen.tsx
=> [#173998756] Fixes font-size on Markdown component

ts/api/pagopa.ts, ts/screens/profile/LanguagesPreferencesScreen.tsx, ts/screens/profile/PreferencesScreen.tsx, ts/utils/__tests__/payment.test.ts
This PR fixes mainly a bug about psp list filtering:
if the retrieved psp has a language not compliant with which one used by the device the psp will be discarded.
Now the language used to retrieve and filter the psp is one of these used by the app: italian or english
If the current language is neither italian or english, en is the fallback
Another fix is about the current language representation. The following screen is on device where the device language is polish
=> [#174005728,#174005947] All psp are filtered 

.circleci/config.yml
This pr disables the e2e tests manual trigger (never executed) and restore the `Codecov` comment report for the "build" workflow. 
- Changed `.circleci/config.yml` to disable the manual steps.
=> [#174024289] Disable e2e tests manual trigger for "build" workflow

scripts/check_urls/check_urls.py
Change the checked urls from io-services-metadata to IO-cdn
=> [#174010680] Change checked urls with IO-cdn

ts/screens/profile/ProfileMainScreen.tsx
Remove the arrows in ListComponents if the item leads to an immediate
action (ie. there's no submenu).
| Before  | After |
| ![before](https://user-images.githubusercontent.com/788293/88934688-37fa8300-d281-11ea-8266-e9bd367eeb18.png )  | ![after](https://user-images.githubusercontent.com/788293/88934729-447edb80-d281-11ea-8f16-5d47cb51ba66.png)  |
=> fix(ui): Don't use the arrows if there's no submenu.

ts/screens/wallet/TransactionDetailsScreen.tsx
This PR Fixes the not working go back from transaction details' screen to the transactions list of a card
- ts/screens/wallet/TransactionDetailsScreen.tsx
=> [#174099632] Fix the back handler from transaction detail to cards transactions

ts/utils/__tests__/appVersion.test.ts, ts/utils/appVersion.ts
This PR fixes a wrong representation of app version in Android OS
1.4.0.2 is displayed as 1.4.0.2.3 (3 is the build number)
This fix includes:
- ios family: version within the build number
- andorid family: version without the build number
=> [#174119099] Display app version

ts/sagas/startup/__tests__/watchLoadMessages.test.ts, ts/sagas/startup/watchLoadMessagesSaga.ts, ts/store/reducers/entities/__tests__/messagesStatus.ts, ts/store/reducers/entities/messages/messagesStatus.ts, ts/store/reducers/index.ts
This PR adds a little improvement on messagesStatus store section
By adding the handling of `removeMessages` action, the reducer can clean all entries that are no longer needed: i.e when the messagesStatus store contains a messageId (one or more) that is not present in the loaded messages (different user or message delete)
Starting from the cleaning, the messagesStatus won't be deleted on logout (explicit or implicit (session expired))
=> [#174085364] messagesStatus store section cleaning

locales/en/index.yml, locales/it/index.yml, ts/screens/services/ServiceDetailsScreen.tsx, ts/utils/openMaps.ts, ts/utils/url.ts
**This PR depends on** https://github.com/pagopa/io-services-metadata/pull/134
Now `support_url` service metadata is displayed in _ServiceDetailScreen_
This PR also does some refactoring and bug fixing:
- added a warp function `renderRowWithDefinedValue` to avoid crashes due to empty strings ("")
- fix `openMap` function that tries to open a weburl
=> feat: [#173735284] Display support_url metadata

ts/boot/configureRectotron.ts
`/symbolicate` is POST toward the metro server
We could ignore it from Reactotron API tracing
=> chore: [#174318377] Add symbolicate to urls ignored in Reactotron

ts/screens/profile/PreferencesScreen.tsx
This fixes the display name of the local calendar on some devices like Xiaomi phones.
=> fix: [#174294652] Fix calendar display name on preferences screen

locales/en/index.yml, ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx, ts/screens/wallet/payment/PickPspScreen.tsx
This PR adds a logic to hide the _This card does not belong to the pagoPA payment network._ label on `PickPspScreen` if the user choose to navigate to the screen.
Run the app on pagoPa test environment, start a payment and navigate to change PSP chosen
=> fix: [#174317167] Hide no pagopa network label if user choose to navigate to pick psp screen

ts/screens/services/ServiceDetailsScreen.tsx
This PR fixes the dynamic change for service enable/disable switch label.
=> fix: [#174160259] Switch label to change text on switch value change

ios/fastlane/README.md, locales/en/index.yml, locales/it/index.yml, ts/screens/wallet/TransactionDetailsScreen.tsx, ts/utils/__tests__/payment.test.ts, ts/utils/payment.ts
Displaying second section extracted from transaction description as notice [is an error ](https://docs.italia.it/italia/pagopa/pagopa-codici-docs/it/stabile/_docs/Capitolo3.html)
Now `Identificativo Univoco di Versamento (IUV)` will be shown in replacement
=> fix(Payments): [#174646257] Display notice in place of IUV

ts/components/wallet/PaymentsHistoryList.tsx, ts/sagas/wallet.ts, ts/screens/wallet/PaymentHistoryDetailsScreen.tsx, ts/store/actions/wallet/wallets.ts, ts/store/middlewares/analytics.ts, ts/store/reducers/payments/history.ts, ts/utils/__tests__/payment.test.ts, ts/utils/payment.ts
This PR changes few points about **payments**:
1. fix notice code composition (specifically `aux 3` case)
1. leave all other text following the _causale_ extracted from transaction description
1. add and dispatch a dedicated action when a new credit card is added to the user wallet
=> fix(Payments): [#174552971] Notice number is wrong composed

ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx
If the bonus is not active (redeemed, failed) then the footer won't be shown
=> feat(Bonus Vacanze): [#174693564] Remove footer when bonus is not active

ts/screens/profile/LanguagesPreferencesScreen.tsx, ts/store/actions/profile.ts, ts/utils/locale.ts
This PR update the user's profile when he/she selects the language which he wants use.
this is the flow how looks like now:
- pick a language
- update the profile and show loading
- check when the update finishes
- if update went well show a modal to inform the app should be restarted
- if update went wrong show a toast with an error message
=> feat: [#173190756] Update profile on language selection

scripts/changelog/ts/__mocks__/storyMock.ts, scripts/changelog/ts/__tests__/changelog.test.ts, scripts/changelog/ts/changelog.ts
This pr allows to add changelog scope for the stories that belong to an epic project label (`epic-bpd` and `epic-myportal` at the moment).
- Changed regular expression to identify valid label in `scripts/changelog/ts/changelog.ts`.
- Added display name for `bpd` and `myportal` in `scripts/changelog/ts/changelog.ts`.
Added new test case to `scripts/changelog/ts/__tests__/changelog.test.ts`
=> chore: [#174841069] Add scope for some project epic labels

package.json, ts/utils/keychain.ts, yarn.lock
Downgrade [react-native-keychain](https://github.com/oblador/react-native-keychain) to version 3.1.3 because it seems to cause few issues on the store (persist and ephemeral)
- increase startup load time (+ 3/4 seconds)
- some persisted store sections lose data
It mainly causes the user loses its session and then he must login again
=> fix: [#175009303] downgrade react-native-keychain

ts/components/Pinpad/KeyPad.tsx
This PR fix the warning related to the duplicate keys on the Keypad component on the app authentication and in the app insertion screens.
Use pin label as key.
- ts/components/Pinpad/KeyPad.tsx
=> fix: [#174949682] Fix duplicate keys on Keypad

ts/sagas/startup/watchApplicationActivitySaga.ts
This PR removes `WALLET_ADD_CARD` route from these that trigger identification when app goes in background
=> feat: [#175009115] No identification required on credit card insertion

ts/sagas/startup/watchSessionExpiredSaga.ts
`content.municipality` isn't restored to initial state when session expires (30day elapsed or the user does a login into another device)
This PR dispatches `clearCache` when `sessionExpired` is detected
It also removes the logout step: this is useless since when the session is expired there is no valid token to use for logout
=> fix: [#175030743] Some store sections are not cleaned when session expires

locales/en/index.yml, locales/it/index.yml, ts/screens/wallet/ConfirmCardDetailsScreen.tsx
This PR fixes a wrongly displayed success toast when actually the payment method is not correctly added.
Fixes on some texts.
- Start a payment
- Change payment method and add a new one
- Insert wrong data (such as wrong expiration date)
- Confirm the method via webview and wait the API to refuse the method
=> fix(Payments): [#174837301] Fixes wrong toast shown on add wallet error

ts/features/bonus/bpd/saga/networking/index.ts, ts/features/bonus/bpd/store/actions/details.ts, ts/features/bonus/bpd/store/actions/onboarding.ts
This PR handles status code 404 on response of these API:
- `bpd/io/citizen` GET (load citizen info)
- `bpd/io/citizen` PUT (enroll citizen to BPD)
when the response is 404 the app business logic stores these values
- `enabled = false` and `payoffInstr = undefined`
=> feat(Bonus Pagamenti Digitali): [#174970898] Handle citizen not found as not enrolled to BPD

ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx
This PR fixes the colors of the text inside the status badge of bonus detail screen
=> fix(Bonus Vacanze): [#175058176] Fixes the color of bonus status badge text

ts/screens/authentication/SpidCIEInformationScreen.tsx
This PR substitute the destination link when a user click on the "Request CIE" button.
Substituted the link from "https://www.cartaidentita.interno.gov.it" to "https://www.prenotazionicie.interno.gov.it/cittadino/n/sc/wizardAppuntamentoCittadino/sceltaComune"
=> fix: [#175252651] Susbtitute link on request CIE button

.env.example, .env.local, .env.production, ts/RootContainer.tsx, ts/config.ts, ts/features/bonus/bpd/components/BpdTestOverlay.tsx
This pr adds a Bpd test overlay, in order to avoid ambiguity when test bpd versions are released.
- Enabled with `BPD_TEST_OVERLAY=YES`
- Tap on the text to dismiss the overlay.
- Informs the user if bpd is enabled, the BPD endpoint type (SIT, UAT, PROD) the PM endpoint type (UAT, PROD)
=> chore(Bonus Pagamenti Digitali): [#175329922] Add Bpd Test Overlay

ts/features/bonus/bpd/saga/networking/paymentMethod.ts
This pr handles the `404` response for `GET bpd/io/payment-instruments/{id}`
=> fix(Bonus Pagamenti Digitali): [#175396286] Handle 404 for bpd payment activation status

ts/types/pagopa.ts, ts/utils/wallet.ts
This PR nests `walletV2` value inside a new optional field `v2` inside `Wallet`
- generate models from spec `yarn generate:all`
- set feature flag `bpdEnabled` to true
field `v2` will be undefined if `bpdEnabled === false` -> get wallets from v1 api
=> feat(Bonus Pagamenti Digitali): [#175185419] Nesting WalletV2 inside Wallet

ts/api/pagopa.ts
This PR changes the codec used in add bancomat response.
The right one is `PatchedWalletV2ListResponse`
=> fix(Bonus Pagamenti Digitali): [#175410649] Codec fails on add bancomat response

ts/components/HorizontalScroll.tsx, ts/features/bonus/bpd/screens/details/BpdPeriodSelector.tsx
This PR fixes the single period render and the scrollTo selected period from wallet home screen of BPDCard carousel.
=> fix(Bonus Pagamenti Digitali): [#175647501,#175647625] Fixes render on single period found and automatic scroll

locales/en/index.yml, locales/it/index.yml, ts/components/bottomSheet/BottomSheetHeader.tsx, ts/components/core/typography/Monospace.tsx, ts/components/core/variables/IOStyles.ts, ts/features/bonus/bpd/components/transactionItem/BaseBpdTransactionItem.tsx, ts/features/bonus/bpd/components/transactionItem/BpdTransactionItem.tsx, ts/features/bonus/bpd/saga/networking/transactions.ts, ts/features/bonus/bpd/screens/details/transaction/BpdTransactionsScreen.tsx, ts/features/bonus/bpd/screens/details/transaction/detail/BpdTransactionDetailComponent.tsx, ts/features/bonus/bpd/screens/details/transaction/detail/BpdTransactionWarning.tsx, ts/features/bonus/bpd/store/actions/transactions.ts, ts/features/bonus/bpd/store/reducers/details/combiner.ts
This pr adds the bottomsheet with details for a transaction.
Normal            |  MaxTransactionCashback
MaxPeriodCashback            |  CancelTransaction
- Added `keyId: string;  maxCashbackForTransactionAmount: number | undefined;` to `EnhancedBpdTransaction`.
- Added `BpdTransactionDetailComponent`  to render a transaction detail.
- Added 
=> feat(Bonus Pagamenti Digitali): [#175269179] Transaction details

ts/features/bonus/bpd/components/BpdTestOverlay.tsx
This pr changes the Bpd overlay in order to display the app version instead of the activation of the feature flag ( all the bpd version will have the feature flat activated).
=> feat(Bonus Pagamenti Digitali): [#175731715] Display app version in bpd overlay

ts/components/wallet/card/CardComponent.tsx, ts/components/wallet/card/RotatedCards.tsx, ts/features/wallet/component/CardPreview.tsx, ts/features/wallet/component/WalletV2PreviewCards.tsx, ts/features/wallet/onboarding/bancomat/components/BancomatWalletPreview.tsx, ts/features/wallet/onboarding/store/abi.ts, ts/screens/wallet/WalletHomeScreen.tsx, ts/store/reducers/wallet/wallets.ts
This pr adds the preview item in the wallet for the bancomat.
`bankLogo !== undefined`           |  `bankLogo === undefined && bankName !== undefined` | `bankLogo === undefined && bankName === undefined`
:-------------------------:|:---------------------:|:-----------------:
*on Android*
- Changed the credit card representation format from `●●●● ●●●● ●●●● 1234` to `●●●● 1234`.
- Added `CardPreview`, a generic compontent to represent a card in the wallet (extracted an simplified from `CardComponent (preview mode)`
- Added `WalletV2PreviewCards` that will reders all the preview cards of v2 type (only bancomat atm).
- Added `BancomatWalletPreview` in order to render a preview of a bancomat.
- Added `bancomatSelector` to filter the bancomat from the wallet and add the missing data from the …
=> feat(Bonus Pagamenti Digitali): [#175682399] Bancomat card preview in wallet

ts/features/wallet/bancomat/component/bancomatCard/BancomatCard.tsx
This PR fixes the build of bancomat expiring date.
This bug is present only on Android devices
=> fix(Bonus Vacanze): [#175744639] Bancomat expiration date is build as invalid

ts/components/ContextualHelpModal.tsx, ts/components/FAQComponent.tsx
This PR is based on this one https://github.com/pagopa/io-services-metadata/pull/154
Now the faqs showed in the Contextual Help could be _remote_ or _local_.
Remote ones, if defined, will be always displayed in place of local
- get the last commit from `io-dev-api-server` branch `support-bpd`
- `io-dev-api-server` `yarn generate:all`
- app `yarn generate:all`
=> feat(Bonus Pagamenti Digitali): [#175718879] Show remote faqs 

locales/en/index.yml, locales/it/index.yml, ts/components/CopyButtonComponent.tsx
This PR adds an in-button feedback on copy button component to prevent toast hiding bug.
=> fix(Bonus Pagamenti Digitali): [#175697866] Shows an inline feedback to copy button

ts/features/wallet/onboarding/bancomat/screens/searchBancomat/SearchAvailableUserBancomatScreen.tsx
This pr allows to handle also the ca bancomat return code `CUSTOMER_NOT_FOUND(21)` and `CARDS_NOT_FOUND(23)`.
With this pr the user will receive the right feedback screen when all the ca return without error (success or not found).
=> fix: [#175879918] Add missing ca bancomat success code

scripts/changelog/ts/__tests__/changelog.test.ts, scripts/changelog/ts/changelog.ts, ts/features/wallet/component/WalletV2PreviewCards.tsx, ts/features/wallet/onboarding/bancomat/store/reducers/addedPans.ts, ts/store/reducers/wallet/__tests__/wallets.test.ts, ts/store/reducers/wallet/wallets.ts, ts/types/pagopa.ts, ts/utils/paymentMethod.ts
This pr adds the selector fo BPay and BancomatPay.
- Added `creditCardListSelector`, `satispayListSelector` and `bPayListSelector`.
- Moved `enhanceBancomat` and `enhancePaymentMethod` to utils.
- Added fix for changelog scope generation.
Run `ts/store/reducers/wallet/__tests__/wallets.test.ts`
=> feat(Bonus Pagamenti Digitali): [#175883590] Satispay and Bancomatpay selector

ts/screens/wallet/AddCardScreen.tsx
This PR prefills the credit card holder field with the current profile name and surname
=> feat(Bonus Pagamenti Digitali): [#175876762] Prefill holder credit card form field

ts/features/bonus/bpd/components/BaseDailyTransactionHeader.tsx, ts/features/bonus/bpd/components/transactionItem/BaseBpdTransactionItem.tsx, ts/features/bonus/bpd/screens/details/BpdDetailsScreen.tsx, ts/features/bonus/bpd/screens/details/transaction/BpdTransactionsScreen.tsx, ts/features/bonus/bpd/screens/details/transaction/GoToTransactions.tsx
This PR fixes the cut content by footer on BPD detail screen.
| Before  | After |
| ![image](https://user-images.githubusercontent.com/3959405/100133825-91696c00-2e87-11eb-978c-4297e8b8dd79.png) | ![image](https://user-images.githubusercontent.com/3959405/100133926-b1992b00-2e87-11eb-887e-cc2434bf188a.png) |
This PR includes some minor fixes on transactions list items and header for content padding.
=> fix(Bonus Pagamenti Digitali): [#175717757,#175876304] Empty footer cuts screen content on BPD Detail

locales/en/index.yml, locales/it/index.yml, ts/components/CopyButtonComponent.tsx, ts/features/bonus/bpd/components/paymentMethodActivationToggle/bottomsheet/BpdChangeActivationConfirmationScreen.tsx
This pr adds a disclaimer that informs the user that the cashback can only be activated by a payment method that belongs to him.
- Modified `BpdChangeActivationConfirmationScreen.tsx `
Activate bpd on a payment method from any entrypoint (bpd details, pm details, new bancomat added, new card added)
=> feat(Bonus Pagamenti Digitali): [#175876837] Show disclaimer when activate bpd on a payment method

ts/api/pagopa.ts, ts/features/wallet/onboarding/satispay/saga/networking/index.ts, ts/sagas/wallet.ts
This PR implements the API to add satispay to the user's wallet
- make sure to have the last commit of `io-dev-server` (branch `support-bpd`)
- dispatch a fake action to add satispay to wallet
```typescript
addSatispayToWallet.request({
hasMore: false,
token:
"3c469e9d6c5875d37a43f353d4f88e61fcf812c66eee3457465a40b0da4153e0",
uidSatispay: "uidSatispay",
uidSatispayHash:
"d077188941373349f188e5475faeacd4aadc8e4bd6ce241de8d20f7bd66ef817"
})
```
=> feat(Bonus Pagamenti Digitali): [#175883670] Support adding Satispay to wallet

ts/screens/wallet/AddCardScreen.tsx
This PR fixes this bug: even if the user fills all fields, the primary CTA button is disabled
=> fix(Bonus Pagamenti Digitali): [#175922698] On credit card insertion CTA is disabled

ts/features/bonus/bonusVacanze/screens/BonusInformationScreen.tsx, ts/features/bonus/bpd/screens/onboarding/BpdInformationScreen.tsx, ts/features/bonus/common/components/BonusInformationComponent.tsx
This PR fixes the wrong text shown in bonus vacanze details screen primary CTA
=> fix(Bonus Pagamenti Digitali): [#175922831] CTA text is wrong in bonus vacanze details screen

ts/sagas/wallet.ts, ts/store/actions/wallet/wallets.ts, ts/store/middlewares/analytics.ts
See title.
1. Comment line 124 of `src/routers/wallet.ts` inside the dev server to always trigger a failure case
2. Try to add a card.
=> chore(Payments): [#175845944] Dispatch action to MixPanel on credit card addition failure

ts/screens/wallet/AddCardScreen.tsx
=> fix(Bonus Pagamenti Digitali): [#175938380] Holder name pre-fill forced when field is empty

ts/features/bonus/bpd/store/reducers/details/periods.ts
This pr fixes the wrong behaviour that periods with different ids were not removed from the store following an update.
- With the action `bpdPeriodsLoad.success` the store is cleaned and the new entry are the periods from the action.payload
=> fix(Bonus Pagamenti Digitali): [#175973442] Periods with different ids were not removed from the store following an update

.env.example, .env.local, .env.production, ts/features/bonus/bpd/api/backendBpdClient.ts, ts/features/bonus/bpd/components/paymentMethodActivationToggle/base/PaymentMethodBpdToggle.tsx, ts/sagas/wallet.ts, ts/screens/wallet/WalletHomeScreen.tsx
This PR changes the fetch configuration for all requests to Payment Manager
Furthermore this PR fixes a double render in WalletHomeScreen
- timeout 10sec
- retries 0/3 (for some requests 0, 3 for others)
- timeout 16sec
- retries 0
=> feat(Bonus Pagamenti Digitali): [#175971953] No retries and increased timeout for PM requests

ts/components/ContextualHelpModal.tsx, ts/features/wallet/bancomat/component/bancomatCard/BancomatCard.tsx, ts/features/wallet/bancomat/component/bancomatCard/BaseBancomatCard.tsx, ts/features/wallet/bancomat/component/bancomatCard/PreviewBancomatCard.tsx, ts/features/wallet/onboarding/bancomat/screens/add-pans/AddBancomatComponent.tsx
This pr allows to display the bank name if the bank logo is not available.
- Update the `BaseBancomatCard` behaviour
- Update `loadSupportToken` when the user open a report.
=> feat(Bonus Pagamenti Digitali): [#175777655] Display bank fallback if logo is not available in bancomat card

ts/features/bonus/bpd/saga/networking/index.ts
This pr fixes the wrong failure event sent to mixpanel.
=> fix(Bonus Pagamenti Digitali): [#176023285] Wrong tracking for the event bpdLoadActivationStatus.failure

ts/api/content.ts, ts/features/wallet/onboarding/bancomat/saga/networking/index.ts, ts/features/wallet/onboarding/bancomat/screens/search/SearchBankScreen.tsx, ts/sagas/wallet.ts
=> feat(Bonus Pagamenti Digitali): [#176027175] Adds client for ABI list to static contents

locales/en/index.yml
Fix a typo: aleady -> already
- Replace `aleady` with `already`
=> Fix locales-en typo: aleady -> already

ts/api/backendPublic.ts, ts/components/RemindEmailValidationOverlay.tsx, ts/features/bonus/bpd/screens/details/BpdDetailsScreen.tsx, ts/screens/onboarding/EmailInsertScreen.tsx, ts/screens/onboarding/EmailReadScreen.tsx
This PR supports 2 more sections status and adds the related component to Email Screens and BPD detail screen 
Check the `io-dev-server` repo and set to true `emailValidation` and `cashback` sections `is_visible` attribute
=> feat(Bonus Pagamenti Digitali): [#176059090] Adds SectionStatusComponent to email and bpd details screen

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/bpd/screens/details/components/paymentMethod/WalletPaymentMethodBpdList.tsx, ts/features/bonus/bpd/screens/details/components/summary/BpdSummaryComponent.tsx, ts/features/bonus/bpd/screens/details/components/summary/TextualSummary.tsx, ts/features/bonus/bpd/screens/details/components/summary/__test__/bpdSummaryComponent.test.tsx
This pr changes the representation of different states for the payment method section.
None            |  Error | Some
:-------------------------:|:-----------:|:--------------------:
- Changed representation for `WalletPaymentMethodBpdList.tsx`
- Hide `BpdSummaryComponent.tsx` if period === current and numTransaction === 0
- Test the BpdDetail screen with different potValues
=> feat(Bonus Pagamenti Digitali): [#176053275] BPDDetailScreen

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/card/SectionCardComponent.tsx, ts/features/bonus/bonusVacanze/components/RequestBonus.tsx, ts/features/bonus/bpd/saga/networking/prefetctBpdDetails.ts, ts/screens/wallet/WalletHomeScreen.tsx, ts/utils/SessionManager.ts
Changes proposed
- only one `/start-session` can be executed at the same time. All other requests will be rejected as an Error
**WalletsHome**
- disable pull to refresh
-  remove _wallets_ & _transactions_ automatically load
-  pull to refresh load only bonus (vacanze + bpd, no wallets&transactions)
-  _wallets_ & _transaction_ can be loaded manually
=> feat(Bonus Pagamenti Digitali): [#176050060] Wallets home rework

ts/components/core/typography/Monospace.tsx, ts/features/bonus/bpd/screens/iban/ko/IbanKoBody.tsx
- Comment the `switch` in `MainIbanScreen.tsx` line 30, replace with `return <IbanKOWrong contextualHelp={emptyContextualHelp} />;`, `IbanKONotOwned` uses the same `IbanKoBody` component underneath
- Insert any IBAN code
- IBAN should be bold
- Press on the IBAN code, you should be able to copy it in the clipboard
=> feat(Bonus Pagamenti Digitali): [#175165668,#175165677] IBAN code is now Monospace Bold and selectable on KO screens

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/bpd/components/paymentMethodActivationToggle/list/PaymentMethodGroupedList.tsx, ts/features/bonus/bpd/screens/details/components/bottomsheet/WhyOtherCards.tsx
This pr adds the section "why other cards" in the "methods from other channels"
1          |  2
=> chore(Bonus Pagamenti Digitali): [#176069568] Why other cards?

ts/components/bottomSheet/BlurredBackgroundComponent.tsx, ts/features/wallet/component/NewMethodAddedNotifier.tsx, ts/utils/bottomSheet.ts
This pr increases the height for the `BancomatInformation` bottomsheet, in order to better display the content.
=> fix(Bonus Pagamenti Digitali): [#176091299] Resize bancomat confirmation bottomsheet

locales/en/index.yml, locales/it/index.yml
- The co-badged warning is now more clear
- Changed label "cashback collected" to make it work also during the following periods (when we'll show also super cashback)
=> Copy updates

ts/features/bonus/bpd/screens/details/BpdDetailsScreen.tsx
This PR remove the reference to the local Bonus Vacanze faq in BpdDetailsScreen
- removed the local faqs in the component
=> fix(Bonus Pagamenti Digitali): [#176022289] remove wrong faq category in BpdDetailsScreen

ts/components/SectionStatusComponent.tsx, ts/components/__tests__/SectionStatusComponent.test.tsx, ts/components/ui/IconFont.tsx, ts/store/reducers/backendStatus.ts
=> chore(Bonus Pagamenti Digitali): [#176148630] Add tests on SectionStatusComponent

ts/features/wallet/onboarding/bancomat/screens/search/SearchBankComponent.tsx
This PR solves the behavior of the Flatlist in SearchBankComponent which required 2 clicks to select the bank from the list.
- Set keyboardShouldPersistTaps prop to the Flatlist component
=> fix(Bonus Pagamenti Digitali): [#175990175] fix double click on bancomat search

ts/features/wallet/bancomat/screen/BancomatInformation.tsx, ts/features/wallet/component/NewMethodAddedNotifier.tsx
This PR removes the infobox on top of the bottom sheet notifier that appears when we add a bancomat to wallet, but keeps it visible on bancomat detail screen
=> chore(Bonus Pagamenti Digitali): [#176116658] Hides the infobox on add bancomat bottom sheet

locales/en/index.yml
Try to add a new Bancomat, you should now see the space in place of "theinformation".
=> fix: [#176038688] Fixed en locale typo

ts/mixpanel.ts, ts/store/reducers/wallet/index.ts
This PR fixes a bug that could happen if app persists wallet store while it is loading state
It also fixes a critical bug that happens when try to send PN token to mixpanel (only for internal tests)
=> fix: [#176173361] Wallets store doesn't use persist transform

ts/components/DetailedlistItemComponent.tsx
it removes the border on the paid badge
- the border's now got the same colour as the background (IOColors.aqua)
=> fix: [#176166635] removes border from the paid badge

locales/en/index.yml, locales/it/index.yml, ts/features/wallet/onboarding/DigitalMethodsList.tsx, ts/features/wallet/onboarding/satispay/screens/StartSatispaySearchScreen.tsx, ts/features/wallet/onboarding/satispay/screens/add/AddSatispayScreen.tsx, ts/features/wallet/satispay/screen/SatispayDetailScreen.tsx
This pr changes the Satispay screens with some graphical refinements.
- Add right arrow to `DigitalMethodsList.tsx`
- Remove Satispay logo from `StartSatispaySearchScreen.tsx`
- Center Satispay card in `AddSatispayScreen.tsx`
- Make the "Remove payment method" button not sticky in `SatispayDetailScreen`
=> chore(Bonus Pagamenti Digitali): [#176203167] Satispay screens graphical refinements

ts/screens/onboarding/EmailInsertScreen.tsx
Message covered the input field.
Before:
After:
1. Go to Profile -> Preferences -> Email Address -> Edit email
2. Focus the input field to expand the keyboard
=> fix: [#176068510] Removed status message in edit email screen

locales/en/index.yml, locales/it/index.yml, ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
This PR adds an InfoBox in PickPaymentMethod Screen to warn AMEX users of limits affecting their transactions 
- Added an `InfoBox `in `PickPaymentMethodScreen`
Visual Test: please see the attached images
Before delivery, a test in production with a real card and real payment is needed
- Test 1: No AMEX, Amount > 1000 EUR
- Test 2: No AMEX, Amount < 1000 EUR
- Test 3: Si AMEX, Amount < 1000 EUR
- Test 4: Si AMEX, Amount > 1000 EUR
=> feat: [#176299898] Amex warning (transaction >1000 EUR)

ts/features/bonus/bpd/screens/details/BpdPeriodSelector.tsx
This PR fixes a bug that shows the wrong detail on selecting cashback period
- load the cashback periods (at least 2 periods)
- open both periods from wallet (now it works as expected)
- load bonus from wallet (refresh)
- the bug is on: by selecting the preview always the 0-indexed period will be shown
=> fix(Bonus Pagamenti Digitali): [#176338423] Wrong cashback detail by selecting card preview

ts/sagas/startup.ts
As of now, If profile activation fails, the operation is retried after 3 seconds.
- Delay is increased to 5 seconds
- No need to use `startTimer`, we'd better use `redux-saga`'s `delay` helper
- Run the app, login
- Stop the dev server
- Reload the app from the simulator
- In Reactotron you should see the target actions being dispatched 5 seconds apart, see the two groups:
=> feat: [#176222893] increased delay between user profile activation retries

ts/api/pagopa.ts, ts/sagas/wallet/pagopaApis.ts, ts/screens/wallet/payment/common.ts, ts/store/actions/wallet/payment.ts
This PR introduces the usage of `/v1/psps/selected` API in place of the deprecated one `/v1/psps` when the app asks for the `psp` during a payment flow
The behavior is pretty the same but the new one wants `idWallet` as required param
=> feat(Payments): [#176364017] Use /v1/psps/selected instead of deprecated /v1/psps

locales/en/index.yml, locales/it/index.yml
The text is now more clear about why users need to sign in again every 30 days
=> feat: [#176392563] Copy Update about login expiration

ts/features/bonus/bpd/screens/details/components/summary/textualSummary/ClosedTextualSummary.tsx
This pr fixes the wrong format for the cashback amount.
=> feat(Bonus Pagamenti Digitali): [#176426698] Fix format amount

locales/en/index.yml, locales/it/index.yml
The text now better explains why the leaderboard is not meaningful yet, and it will be shown later on.
=> chore(Bonus Pagamenti Digitali): [#176392584] Ranking unavailable description

ts/screens/authentication/cie/CiePinScreen.tsx
- Removed unnecessary margin from the CTA
- Corrected label
- Corrected height so that content won't scroll
As usual, edit line 187 of `LandingScreen.tsx` making the condition always true
=> fix: [#176445412] Applied corrections on CIE PIN screen bottom sheet modal

locales/en/index.yml, locales/it/index.yml, ts/features/wallet/onboarding/common/screens/bpd/ActivateBpdOnNewPaymentMethodScreen.tsx, ts/features/wallet/onboarding/common/screens/bpd/SuggestBpdActivationScreen.tsx
This pr fixes the wrong title for `SuggestBpdActivationScreen`.
- Moved locales from`wallet.onboarding.bancomat.bpd.suggestActivation` to `bonus.bpd.suggestActivation`
- Moved locales from `wallet.onboarding.bancomat.bpd.activateNew` to `bonus.bpd.activateOnNewMethods`
- Changed the screen title from `wallet.onboarding.bancomat.headerTitle` to `bonus.bpd.title`
=> fix(Bonus Pagamenti Digitali): [#176496182] SuggestBpdActivationScreen displays always a "pagoBANCOMAT" title

ts/features/bonus/bpd/screens/details/components/summary/ranking/SuperCashbackRankingSummary.tsx, ts/store/reducers/__mock__/backendStatus.ts, ts/store/reducers/__tests__/backendStatus.test.ts, ts/types/backendStatus.ts
This PR introduces a new config flag about bdp ranking (super cashback)
- make sure to have last commit of io-dev-api-server (master branch)
=> chore(Bonus Pagamenti Digitali): [#176498731] Add new bpd ranking config flag

ts/features/bonus/bpd/components/BpdTransactionSummaryComponent.tsx
In `BpdTransactionSummaryComponent.tsx`, we need to show the CTA after the bottom sheet's markdown content has finished loading.
1. Go to Wallet -> Cashback -> n. of transactions -> Anything Missing?
2. See the CTA being shown after MD has loaded
=> fix(Bonus Pagamenti Digitali): [#176477833] Hidden CTA until markdown has finished loading

ts/components/DetailedlistItemComponent.tsx, ts/components/messages/MessageListCTABar.tsx, ts/components/messages/MessageListItem.tsx
This PR removes these elements from the message list item
- payment CTA
- expired (expired & not paid payment advice) badge
- due to a bad logic, a spacer was rendered despite the content is empty
=> feat: [#176434157] Remove payment CTA and expired badge

ts/store/reducers/index.ts
This PR keeps stored the hashed fiscal code on logout (hard logout)
=> fix: [#176607041] Hashed CF is reset on logout

locales/en/index.yml, locales/it/index.yml
Changed text from "earned" to "reached", because reaching the €150 milestone doesn't necessarily mean earning the money (users still have to collect at least 50 transactions).
=> chore(Bonus Pagamenti Digitali): [#176737219] milestone copy

ts/api/pagopa.ts
This PR changes the `expiringDate` field forma from `date-time` to `YYYY-MM-DD`
=> fix(Bonus Pagamenti Digitali): [#176720702] Cobadge add-wallet payload has an invalid date format

ts/__mocks__/react-native-keychain.ts, ts/sagas/installation.ts, ts/sagas/profile.ts, ts/sagas/startup/watchSessionExpiredSaga.ts
It is now possible to log-out and log back in without resetting the unlock code, unless the SPID user is different.
- Log-in and set an unlock code
- Log-out
- Log back in, no unlock code reset should be asked
- Log-out
- In `mock-server/src/global.ts` change the fiscal code and restart the mock server
- Log back in, you should be prompted to set a new unlock code
=> feat: [#174034081] Unlock code is persisted across logins if citizen doesn't change (2nd attempt)

CODEOWNERS
This pr adds @thisisjp as `locales` codeowner 🥳
=> chore: Add thisisjp as locales codeowner

ts/components/screens/BaseScreenComponent.tsx
This PR restores the default behavior for which is possibile to share a screenshot within an Instabug support request.
At the moment only `AddCardScreen` specifies `shouldAskForScreenshotWithInitialValue=false`: the app asks to the user she wants to the screenshot
https://user-images.githubusercontent.com/822471/106718000-b9e8b180-6600-11eb-9234-7774388ab425.mp4
=> fix: [#176778241] On bug report can't share the screenshot

ts/screens/wallet/TransactionDetailsScreen.tsx
removes psp and provider s logo
=> fix:[176632919] removes psp and logo from transaction details

ts/features/wallet/component/PagoPaPaymentCapability.tsx, ts/features/wallet/component/__test__/PagoPaPaymentCapability.test.tsx, ts/types/paymentMethodCapabilities.ts, ts/utils/__tests__/paymentMethodCapabilities.test.ts, ts/utils/paymentMethodCapabilities.ts
This PR substitute the in app payment badge with a disabled switch
- Added the `onboardableNotImplemented` case in the `isPaymentMethodSupported` utils
- Added the `onboardableNotImplemented` case in the `PagoPaPaymentCapability` component
=> feat(Bonus Pagamenti Digitali): [#176578587] Update the co-badge in app payment badge

scripts/check_urls/check_urls.py, ts/@types/react-native-pull.d.ts, ts/@types/react-native-vector-icons.d.ts, ts/api/pagopa.ts, ts/components/ui/Markdown/handlers/link.ts, ts/config.ts, ts/features/bonus/bpd/api/backendBpdClient.ts, ts/sagas/services/watchLoadServicesSaga.ts, ts/store/middlewares/analytics.ts, ts/store/reducers/profile.ts, ts/utils/bottomSheet.ts, ts/utils/number.ts, ts/utils/share.ts
This PR extends the url checking to *.ts source files
This to ensure we are always using valid urls
It also adds [backend status](https://raw.githubusercontent.com/pagopa/io-services-metadata/master/status/backend.json) to the remote monitored resources and remove [services.xml](https://assets.cdn.io.italia.it/services.yml) from monitoring since it is not longer used 
This is the current outcome
----
found 7 errors
[ts][status code 404] -> https://reactnavigation.org/docs/guides/screen-tracking#Screen-tracking-with-Redux
[ts][status code 404] -> https://react-native-community.github.io/react-native-share/docs/share-open#supported-options
[ts][status code 404] -> https://github.com/gorhom/react-native-bottom-sheet/blob/master/docs/modal.md#present
[ts][status code 404] -> …
=> chore: [#176900759] Extend urls checking to *.ts source files

ts/sagas/wallet/pagopaApis.ts, ts/store/middlewares/analytics.ts
This pr changes the tracking for the `/v2/wallet` in order to track all the calls.
Atm, only the actions `fetchWalletsFailure`, `fetchWalletsRequest` and `fetchWalletsSuccess` are tracked, but the function `getWalletsV2` can be also called without using `fetchWalletsRequest`; this generates an incorrect and untrue subset of data.
- Removed from analytics `fetchWalletsFailure`, `fetchWalletsRequest` and `fetchWalletsSuccess`.
- Added custom track in `getWalletsV2` in order to track all the function invocation.
=> fix(Bonus Pagamenti Digitali): [#176551362] Not all the getWalletV2 call are tracked

ts/components/ServiceTabIcon.tsx, ts/components/services/NewServiceListItem.tsx
This PR removes:
1. service tab counter badge indicator
2. service item unread badge indicator
=> feat(Services): [#176919053] Remove services tab counter badge and item unread badge indicator

ts/features/wallet/bancomat/screen/BancomatInformation.tsx
This pr changes the BANCOMAT detail icon from (!) to (i)
=> fix(Bonus Pagamenti Digitali): [#176940152] The BANCOMAT detail icons is (!) instead of (i)

locales/en/index.yml, locales/it/index.yml, ts/components/LabelledItem.tsx, ts/components/core/typography/H5.tsx, ts/screens/wallet/AddCardScreen.tsx, ts/screens/wallet/__tests__/AddCardScreen.test.tsx, ts/utils/__tests__/input.test.ts, ts/utils/input.ts
This PR block the add credit card workflow if the user insert in the cardholder a string with accented characters.
- Added the diacritical marks check in the `AddCardScreen`
- Removed pre-filled cardholder
- Fixed error that allow the user to add a card without cardholder
- Added the optional description in the `LabelledItem` component
- Aligned `LabelledItem` label style with invision design
- Added `AddCardScreen` tests
- Added `isValidCardHolder` tests in `input.test.ts`
- Added `getCreditCardFromState` tests in `input.test.ts`
https://user-images.githubusercontent.com/11773070/108376588-6df25b00-7203-11eb-9b50-417bf8ebcfc9.mov
=> feat: [#176980827] Don't allow user to add a credit card when insert a cardholder with accented characters

ts/components/ui/Markdown/index.tsx, ts/features/bonus/bpd/components/superCashbackRanking/SuperCashbackRanking.tsx
This PR fixes an annoying behavior that allows text selection in bottom sheet making a bad UX
=> fix(Bonus Pagamenti Digitali): [#176993827] In SuperCashbackRanking bottom sheet text is selectable

README.md
Added new troubleshooting line to solve "bundle install" error
After executing the command "bundle install" an error similar to this "Can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)" may come out.
=> chore: [#177204492] Update/Correct README

ts/components/services/LocalServicesWebView.tsx
This PR fixes a bug causing the navigation to service details screen instead of message detail screen when a message is tapped
https://user-images.githubusercontent.com/822471/110753472-ea96b900-8246-11eb-9369-ef1c387c1380.mov 
https://user-images.githubusercontent.com/822471/110753524-f71b1180-8246-11eb-93b3-bdff22337c1d.mov
=> fix: [#177298671] On message pressed Service details is shown instead of Message details

ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
This PR Fixes the double tap needed to navigate from list item to merchant detail
Navigate to CGN detail, navigate to merchants list and tap on any item even if the focus is yet on input box
https://user-images.githubusercontent.com/3959405/110931407-82210800-832a-11eb-94f8-e7c5f189acf8.mov
=> fix(Carta Giovani Nazionale): [#177303103] First tap on merchants list item fails

locales/en/index.yml, locales/it/index.yml, ts/features/wallet/onboarding/privative/screens/add/AddPrivativeCardScreen.tsx, ts/features/wallet/onboarding/privative/screens/search/LoadPrivativeSearch.tsx, ts/features/wallet/onboarding/privative/screens/search/SearchPrivativeCardScreen.tsx, ts/features/wallet/onboarding/privative/screens/search/ko/PrivativeKoNotFound.tsx, ts/features/wallet/onboarding/privative/screens/search/ko/PrivativeKoTimeout.tsx
This PR manages the search privative card step.
If the status is loading it shows the `LoadPrivativeSearch` screen, while if the status is ko it shows the `PrivativeKoTimeout` screen or if there isn't any card the `PrivativeKoNotFound`.
Finally if the card is found the `AddPrivativeCardScreen` is shown.
- Manage the search results in `SearchPrivativeCardScreen`
- Fill the `LoadPrivativeSearch` screen
- Fill the `PrivativeKoTimeout` screen 
- Fill the `PrivativeKoNotFound` screen
| LoadPrivativeSearch Loading  | LoadPrivativeSearch Error  |
| PrivativeKoTimeout  | PrivativeKoNotFound  |
=> feat(Bonus Pagamenti Digitali): [#177243713,#177144863,#177144964] Manages privative search loading and ko.

.env.production
This pr changes the configuration in order to use the UAT endpoints (for test purpose).
=> feat(Bonus Pagamenti Digitali): [#177339683] Change configuration to UAT

ts/features/wallet/onboarding/cobadge/saga/networking/addCobadgeToWallet.ts, ts/features/wallet/onboarding/cobadge/saga/networking/index.ts, ts/features/wallet/onboarding/privative/saga/networking/handleAddPrivativeToWallet.ts, ts/features/wallet/onboarding/privative/store/actions/index.ts, ts/features/wallet/onboarding/privative/store/reducers/addedPrivative.ts, ts/features/wallet/onboarding/privative/store/reducers/addingPrivative.ts, ts/features/wallet/onboarding/privative/store/reducers/index.ts, ts/utils/paymentMethod.ts
This pr fixes the wrong decode of the `/cobadge/add-wallets` response when adding a new `PrivativePaymentMethod`.
- Changed `addCobadgeToWallet` in order to return a `RawPaymentMethod` instead of `RawCreditCardPaymentMethod`
- Changed `handleAddCoBadgeToWallet` in order to check the `CreditCardPaymentMethod` type
- Changed `handleAddPrivativeToWallet` in order to check the `RawPrivativePaymentMethod` type
- Changed the type for `addPrivativeToWallet`, `addedPrivativeReducer`, `onboardingPrivativeAddedSelector`, `onboardingPrivativeAddingResultSelector`
=> fix(Bonus Pagamenti Digitali): [#177357472] Wrong decode during the add of a new privative card to the wallet

.env.production, ts/features/bonus/bpd/analytics/index.ts, ts/features/wallet/onboarding/bancomat/analytics/index.ts, ts/features/wallet/onboarding/bancomatPay/analytics/index.ts, ts/features/wallet/onboarding/cobadge/analytics/index.ts, ts/features/wallet/onboarding/privative/analytics/index.ts, ts/features/wallet/onboarding/privative/screens/search/LoadPrivativeSearch.tsx, ts/features/wallet/onboarding/privative/screens/search/SearchPrivativeCardScreen.tsx, ts/features/wallet/onboarding/privative/screens/search/ko/PrivativeKoTimeout.tsx, ts/features/wallet/onboarding/privative/store/actions/index.ts, ts/features/wallet/satispay/analytics/index.ts, ts/store/middlewares/analytics.ts
This pr adds the mixpanel tracking for troubleshooting and alerting purpose.
[List of the new events](https://docs.google.com/spreadsheets/d/1bXNRcTDKU-5l2RqCcwSbT7Y1M9QQTWtS_f-3-AIqSYk/edit#gid=1909779257&range=A108:D108)
- Added tracking for relevant events
- Rename `PRIVATIVE_NO_QUERY_PARAMS_ERROR` to `WALLET_ONBOARDING_PRIVATIVE_NO_QUERY_PARAMS_ERROR` in order to have the same namespace
- Rename `WALLET_ONBOARDING_PRIVATIVE_LOAD_PRIVATIVE_ISSUERS_SUCCESS` to `WALLET_ONBOARDING_PRIVATIVE_LOAD_ISSUERS_SUCCESS`
=> feat(Bonus Pagamenti Digitali): [#177144429] Add mixpanel tracking for privative workflow

ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
This PR fixes a bug where CGN details doesn't load when activation flow is completed
=> fix(Carta Giovani Nazionale): [#177385897] CGN Details doesn't load automatically when activation is completed

ts/features/wallet/onboarding/cobadge/screens/add-account/AddCobadgeComponent.tsx
This pr changes the behaviour of the disclaimer bold text, in order to avoid to always wrap.
=> feat(Bonus Pagamenti Digitali): [#177244740] In the "co-badge add card to wallet" screen, the disclaimer bold text now does not always wrap 

ts/features/wallet/cobadge/component/BaseCoBadgeCard.tsx, ts/features/wallet/privative/component/card/BasePrivativeCard.tsx
This pr fixes the align for the bottom-left text in the privative and cobadge cards.
=> fix(Bonus Pagamenti Digitali): [#177368806] Wrong align for the bottom-left text of the privative & cobadge cards

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/common/components/BonusInformationComponent.tsx, ts/features/wallet/component/card/FeaturedCardCarousel.tsx
This PR fixes the footer text of the CGN information screen with the link to policy and guide
=> fix(Carta Giovani Nazionale): [#177455388] Footer text on CGN information screen shows the wrong text referring to Cashback

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/FavoriteMethodSwitch.tsx, ts/components/wallet/FavouriteMethodSwitch.tsx, ts/components/wallet/card/CardComponent.tsx, ts/screens/wallet/TransactionsScreen.tsx, ts/store/reducers/wallet/wallets.ts, ts/utils/wallet.ts
This PR adds a switch to handle the user request to set that payment method as favorite.
The switch is replaced by a loader when the setting is in progress
https://user-images.githubusercontent.com/822471/112162908-c9da4600-8bec-11eb-9dce-551c180a4cff.mov
=> feat(Payments): [#176176928] Add a switch to set payment method as favorite

ts/screens/services/ServicesHomeScreen.tsx
This PR shows the services status banner, if available, even when the services section is in loading state
| list  | loading |
=> chore: [#177137637] Show services status banner in any rendering state

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/cgn/screens/activation/CgnActivationCompletedScreen.tsx
This PR fixes 2 typos on CGN Eyca Description BottomSheet and changes the pictogram inside CgnActivationCompletedScreen.
=> fix(Carta Giovani Nazionale): [#177490938] Success Screen pictogram results cut on the bottom

ts/features/bonus/bpd/screens/details/transaction/detail/BpdTransactionDetailComponent.tsx
This pr fixes the wrong privative loyalty logo rendering in the cashback transaction detail bottomsheet
=> fix(Bonus Pagamenti Digitali): [#177511360] Wrong rendering of privative loyalty logo in cashback transaction detail bottomsheet

ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
This PR fixes a minor UI Bug where the bottom sheet title overflows the BS close button
=> fix(Carta Giovani Nazionale): [#177490914] Discount bottom sheet title doesn't break line

ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx, ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
This PR Fixes the hardware back button not working on android phones when trying to exit from CGN Detail screen.
In addition, minor styles fixes has been implemented in CGN Card component
=> fix(Carta Giovani Nazionale): [#177485208] Hardware back button doesn't work on CGN Detail screen

ts/components/wallet/PayWebViewModal.tsx, ts/store/reducers/payments/history.ts, ts/store/reducers/wallet/creditCard.ts, ts/utils/payment.ts
This PR adds the reason that causes the webview closing during a credit card on-boarding or a payment:
- `USER_ABORT` -> web view has been closed by the user (back press)
- `EXIT_PATH` -> web view has closed it self automatically by detecting the exit path in an url
This new data will be sent attached to the Instabug ticket
| payment  | credit card |
=> feat(Payments): [#177548187] Add credit card / payment webview closing reason

ts/screens/services/ServiceDetailsScreen.tsx
Removed switch row and edit link useless spacing in service details screen
**Before changes:**
**After changes:**
Move in service details screen and see if there is an useless padding left in the rows with the switch button and an useless space after edit link
=> fix: [#177314796] Starting blank space on link "update your preferences"

.circleci/config.yml
This PR temporary disables the check on iOS button existence - CIE authentication flow - since it seems have stopped working
=> chore: [#177755852] Disable CI CIE iOS button check

ts/components/ButtonDefaultOpacity.tsx, ts/components/bottomSheet/AccessibilityContent.tsx, ts/components/wallet/WalletHomeHeader.tsx
This PR Fixes a bug where any button inside a bottom sheet on android would not be pressable
=> fix: [#177606620] Buttons inside BottomSheets are not pressable on Android

locales/en/index.yml, locales/it/index.yml
this is the correct copy for the Legal Team - thanks guys
=> [#177456804] Footer on bonus information screen has a wrong text

scripts/changelog/add_pivotal_stories.js
This PR introduces another step in the `postchangelog` phase to fix these scenarios
`cleanCloses` detectes the noise pattern and removes it from CHANGELOG
=> fix: [#177960813] Changelog may contains noise suffixes

locales/en/index.yml
Fix grammar error in 'locales/en/index.yml'
- Change 'it usually takes up 3 working days' to 'it usually takes up to 3 working days'.
=> fix: grammar error in locales/en/index.yml

locales/en/index.yml, locales/it/index.yml
This PR changes the error which appears when the authentication fails: "Wrong code" is now a simpler "Try again", to support all use cases.
=> chore: [#178065366] Copy change

ts/utils/__tests__/input.test.ts, ts/utils/input.ts
This PR update the lower limit for the number of digits allowed for the credit card.
This allow the user to insert a Diners credit card.  
- Update the lower limit to 14
- Update the tests case
=> fix: [#178070799] Allow the addition of Diners cards

ios/ItaliaApp.xcodeproj/project.pbxproj
This pr allows the develop build on physical devices.
- Updated `debug` signing settings, using the Development certificates:
- Changed signing settings for different build type (debug / release):
- Fixed test signing:
1. Open XCode
2. Choose as target the physical device
3. Run the application `cmd+r`
=> fix: [#178129966] Cannot deploy a develop build on physical device

.env.example, .env.local, .env.production, ts/api/backendPublic.ts, ts/config.ts, ts/sagas/backendStatus.ts
This PR removes the usage of a legacy backend status endpoint
Now all status assets are hosted in IO CDN https://assets.cdn.io.italia.it/
- **prod**: you are ready!
- **dev**: make sure to get the last commit from [master](https://github.com/pagopa/io-dev-api-server)
=> chore: [#178106274] Remove legacy backend status endpoint

ts/boot/scheduleLocalNotifications.ts
This pr fixes a bug that doesn't clearing scheduled notifications correctly after the SPID / CIE login.
- Removed `PushNotification.cancelLocalNotifications`
- Added `PushNotification.cancelAllLocalNotifications`
It's possible to see the currently scheduled notification with `PushNotification.getScheduledLocalNotifications`
=> fix: [#178155677] Local scheduled notification aren't canceled after login with SPID / CIE

ts/screens/wallet/AddPaymentMethodScreen.tsx
This pr fixes the privative payment method displayed as "Incoming" when the user adds a new payment method, during a payment.
- Changed the state from `incoming` to `notImplemented`.
Add a payment method during a payment.
=> fix(Bonus Pagamenti Digitali): [IAC-57] Privative displayed as incoming when adding a new payment method during a payment

ts/components/wallet/TransactionsList.tsx, ts/screens/wallet/WalletHomeScreen.tsx
At the moment if the first page (transaction API is paginated) has [no valid transactions](https://github.com/pagopa/io-app/blob/ac6e9ef811711a60d8f6cc5733051bb5c2b07788/ts/types/pagopa.ts#L352), the app shows the user she has no transactions. 
This PR also adds the `<EdgeBorderComponent />` to have a better info displaying
https://user-images.githubusercontent.com/822471/118269859-84851700-b4bf-11eb-9643-28d2a782ad00.mp4
this happens when the first page of transactions contains all invalid transactions, even if in the other pages there are valid ones
https://user-images.githubusercontent.com/822471/118270062-bd24f080-b4bf-11eb-92d5-08d79bf71cd5.mp4
- take the last commit of dev-server
- create a set of mixed transactions here 
replace this line …
=> fix: [#178157694] No transactions done even if there are

locales/en/index.yml, locales/it/index.yml, ts/screens/modal/IdentificationLockModal.tsx, ts/screens/modal/IdentificationModal.tsx
Replaced "Identification failed" text that shows if you fail the biometric identification and wrong code error text.
Now you will see a generic "Try again" for both errors.
It seems that "Try again" text of biometric identification fail comes out only when you put the "wrong finger" in the biometric sensor and then open the app from the iPhone
Try to unlock the app, in the identification modal component, if biometry state is in failure state or if you fail to write the unlock code you should see "Try again" text.
If you fail to write the unlock code more than 4-5 times you should see "Try again. Number of remaining attempts" text.
**Before:**
**After:**
=> chore: [#178065380] Replaced failed identification text

ts/components/wallet/card/CardComponent.tsx, ts/features/wallet/bancomat/component/bancomatCard/BaseBancomatCard.tsx, ts/features/wallet/cobadge/component/BaseCoBadgeCard.tsx
Changed "Valid until" label color on credit card
You can see the changes in these points:
- Credit card detail (from wallet)
- During checkout step (when you pay a notice)
- When you add PagoBANCOMAT or Co-badge card
**Before:**
**After:**
=> feat: [#178230437] Changed valid until color

ts/screens/wallet/WalletHomeScreen.tsx, ts/screens/wallet/payment/__tests__/PickPaymentMethodScreen.test.tsx, ts/store/reducers/wallet/wallets.ts
This PR corrects a bug due to the receipt of incomplete data: in fact, the onboardingChannel field was added after the creation of some wallets and for these it has not been evaluated.
This resulted in the user seeing all his payment methods in the wallet section but not when he changed payment method during a payment.
- Added the undefined check to the `isVisibleInWallet` utils
- **Dev mode:** remove the field `onboardingChannel` from the card (_src/payloads/wallet_v2.ts_). 
- **Prod**: if you have an added card without the field `onboardingChannel`
In both the cases you should see the card in the `PAYMENT_PICK_PAYMENT_METHOD` screen.
- Added a test case in `PickPaymentMethodScreen.test.tsx`
=> fix: [#178243533] Fix cards not visible during payment

ts/features/bonus/bpd/store/reducers/details/transactionsv2/__test__/normalization.test.ts, ts/features/bonus/bpd/store/reducers/details/transactionsv2/entities.ts
This pr fixes the wrong normalization when the pivot transaction is in the same page but in a different day.
Before
https://user-images.githubusercontent.com/26501317/119334416-62438400-bc8b-11eb-8bba-b41af6bd5429.mov
After
https://user-images.githubusercontent.com/26501317/119334497-7b4c3500-bc8b-11eb-91ff-1fdbfb4f437e.mov
- changed the use of the initial state instead of the accumulator `foundPivot` in `updateTransactions`
- run `ts/features/bonus/bpd/store/reducers/details/transactionsv2/__test__/normalization.test.ts`
=> fix(Bonus Pagamenti Digitali): [IAC-66] Wrong normalization of cashback amount when the pivot transaction is in a different day but in the same page

scripts/ts/common/ticket/jira/types.ts, scripts/ts/common/ticket/types.ts, ts/store/reducers/__mock__/backendStatus.ts, ts/types/backendStatus.ts
This PR allows to have a dedicated status banner about eu covid certificate
- include this component wherever you want
`<SectionStatusComponent sectionKey={"messages"} />`
- get the last commit from io-dev-server
- edit the `euCovidCert` block in [backend.ts](https://github.com/pagopa/io-dev-api-server/blob/c516e6751d279875d7cd0a410b0fc85e12527ba5/src/payloads/backend.ts#L158)
```json
euCovidCert: {
is_visible: true,
level: "warning",
message: {
"it-IT": "euCovidCert banner test",
"en-EN": "euCovidCert banner test"
}
}
```
- reload the app
=> feat(EU Covid Certificate): [IAGP-36] Add euCovidCert as new section status

locales/en/index.yml, locales/it/index.yml, ts/features/euCovidCert/screens/ko/EuCovidCertGenericErrorKoScreen.tsx, ts/features/euCovidCert/store/reducers/current.ts
This pr adds the generic error screen for the EU Covid certificate.
https://user-images.githubusercontent.com/26501317/120926692-39d17600-c6de-11eb-9fb6-b1975a62f000.mov
- Added graphical implementation for `EuCovidCertGenericErrorKoScreen`
- Picked `euCovidCertCurrentSelector` from https://github.com/pagopa/io-app/pull/3091 
- Open a message with an EU Covid Certificate and return `500` with dev-server or disconnect the dev-server before the request.
=> feat(EU Covid Certificate): [IAGP-23] Added generic error screen in case of networking errors, 500 error or other unmanaged response code 

ts/components/messages/MessageListCTABar.tsx
Protects the message CTA by chacking the Feature Flag.
Disable the Feature flag on `.env` file and check if the CTA is displayed on the message item for covid certificates information.
=> chore(EU Covid Certificate): [IAGP-46] Prevent the Covid CERT CTA if FF is disabled

ts/features/euCovidCert/screens/BaseEuCovidCertificateLayout.tsx
This PR introduces the SectionStatus message on the EuCovidCertificate screen component.
Set to `true` the visibility of the `euCovidCert` section on `io-dev-api-server` and check the visibility of the app
=> feat(EU Covid Certificate): [IAGP-2] Introduces the SectionStatusComponent on BaseEuCovidCertificateLayout component

ts/sagas/profile.ts, ts/screens/onboarding/EmailInsertScreen.tsx
This PR fixes a bug with error management during the email update.
- change the API status response with 500 [on dev-server ](https://github.com/pagopa/io-dev-api-server/blob/efa0d9261bf6b9ce92bf8fe08e845986f2382638/src/routers/profile.ts#L52)
- update the user email (from profile/preferences section or from onboarding phase - first login)
- press continue
- 🐛 
https://user-images.githubusercontent.com/822471/121391187-625fa700-c94e-11eb-8659-5541d87a60ed.mov
https://user-images.githubusercontent.com/822471/121390833-0d239580-c94e-11eb-8304-7caaed0798c2.mov
=> fix: [IA-3] Error swallowing on upsert email API fault code

ts/components/ui/Markdown/index.tsx
This pr adds the overflow wrap for the `Markdown` component.
- Added `overflow-wrap` and `hyphens` to markdown body style.
=> fix(EU Covid Certificate): [IAGP-56] Add overflow wrap for markdown component

android/app/src/main/AndroidManifest.xml, ts/mixpanel.ts
This PR updates the Mixpanel setup on Android.
On iOS it always worked as expected, on Android it needs an extra configuration in Android Manifest file
[more info ](https://help.mixpanel.com/hc/en-us/articles/115004494803-Disable-Geolocation-Collection)
=> Update mixpanel setup

ts/features/euCovidCert/analytics/index.ts, ts/store/middlewares/analytics.ts
This PR removes some obsolete events no longer user by the app (e.g bonus vacanze eligibility & activation)
It also removes some properties that are no useful for stats or troubleshooting assistance
=> Remove obsolete events

ts/store/middlewares/analytics.ts
This PR uses only the Unique Id (the device unique ID) to identify the usage of the app
=> Use Unique ID on identify

ts/components/TosWebviewComponent.tsx, ts/screens/onboarding/TosScreen.tsx
This PR allows to open links, contained in the Terms of Service web page, in the device browser.
It injects a JS into the webview to intercept the clicked links and it command to open them in the system default browser.
This PR also fixes a navigation bug for which if the user opens an internal link he/she can't go back in the previous web page.
- add the `link clicked` handling
- remove the `end of scroll` handling since it is never sent by the webview (no script added)
https://user-images.githubusercontent.com/822471/122024995-3d918680-cdc9-11eb-98d4-e32f2fa414e3.mov
https://user-images.githubusercontent.com/822471/122025040-4aae7580-cdc9-11eb-90a5-28934d52afd8.mov
=> chore: [IA-32] Open ToS links in external browser

ts/components/messages/MessageDetailData.tsx
Based on the multiple requests from the institutions to make the logic of copying the id of a message clearer, I have implemented a step that, in addition to copying the message, also copies the service name.
**The format will then be: service_name - 000000000001**
https://user-images.githubusercontent.com/53444973/122354418-444b0580-cf51-11eb-9647-040062ddb91b.mov
https://user-images.githubusercontent.com/53444973/122354279-21205600-cf51-11eb-80a5-168d33970f13.mov
=> chore: [IA-19] When copy id message is missing service name

ts/screens/profile/components/ShareDataComponent.tsx
This pr fixes the wrong behaviour described in the pr title.
- Change the layout of `MarkdownBody`
=> fix: [IA-40] In "your data" screen, missing bottomsheet content when the screen reader is enabled

ts/screens/profile/ProfileMainScreen.tsx
Expose the unique device ID and let the developer copy it to the clipboard.
Please note that the UUID is longer than the available space and will be cut most of the time using ellipsis. This was discussed on the relevant ticket and is not deemed an issue.
* add a new item in the _Profile_ screen to show the device unique ID and copy it
* separate rendering of developer's items to improve readability
1. open _Profile_ tab
2. activate _debug mode_ (either via 5 taps or using the toggle)
3. the last blue item containst the device UUID
4. tap on the item to copy the UUID to the clipboard
See the recording below for a full walk-through:
https://user-images.githubusercontent.com/2094604/122768194-a7b39b00-d2a3-11eb-98ae-598cc0e16476.mov
=> chore: [IA-41] Expose the unique device ID and let the developer copy it to the clipboard

ts/store/middlewares/analytics.ts, ts/utils/analytics.ts
This PR adds the event `SCREEN_CHANGE_V2` that sends all route changes not included in the defined blacklist.
=> chore: [IA-62] Add SCREEN_CHANGE_V2 event

ts/features/bonus/bpd/screens/details/components/summary/textualSummary/ClosedTextualSummary.tsx
This pr fixes a wrong textual representation when a closed period have `superCashbackAmount === 0`
- Check if the period `props.period.superCashbackAmount > 0`
- Wallet > Open a cashback card with `props.period.superCashbackAmount===0`
=> fix(Bonus Pagamenti Digitali): [IAC-84] Wrong textual representation when superCashbackAmount === 0 for a period

ts/screens/authentication/IdpSelectionScreen.tsx, ts/store/actions/navigation.ts
This PR fix a bug from #3136.
It doesn't allow the user authentication due to a wrong navigation route.
- Modified the route associated to `navigateToSPIDLogin` from `AUTHENTICATION_IDP_SELECTION` to `ROUTES.AUTHENTICATION_IDP_LOGIN`
Try to login both in dev and prod mode.
=> fix: [IA-73] Can't login with spid due to wrong navigation route

ts/components/ui/Accordion.tsx
VoiceOver doesn't work correctly, if you try to read FAQ's accordion content, it will say "Horizontal scroll bar, 1 page, vertical scroll bar ..."
Move into a FAQ, open an accordion and try to listen its content with the VoiceOver
**Before:**
https://user-images.githubusercontent.com/61834253/123981132-62d5e580-d9c2-11eb-9de5-05d237272af0.mp4
**After:**
https://user-images.githubusercontent.com/61834253/123981198-71bc9800-d9c2-11eb-9026-e30fd998a45e.mp4
=> fix: [IA-58] VoiceOver doesn't read the FAQ's content

ts/screens/modal/RootModal.tsx, ts/screens/modal/UpdateAppModal.tsx
This pr add remote placeholder and tracking for the `UpdateAppModal`.
- Added contextual help
- Added `UPDATE_APP_MODAL` event
1. In dev-server, change the payload https://github.com/pagopa/io-dev-api-server/blob/c516e6751d279875d7cd0a410b0fc85e12527ba5/src/payloads/backend.ts#L4 in order to return a app version > of the current (eg: `2.0.0`)
2. Open the app and check the `UpdateAppModal`.
=> feat: [IA-72] Add contextual help and tracking to UpdateAppModal

ts/screens/authentication/cie/CiePinScreen.tsx
With VoiceOver activated, try to log in via CIE, immediately after entering the eight-digit PIN, you can't press the Continue button
1. Enter the CIE login
2. Activate VoiceOver
3. Enter the 8-digit PIN
4. Tap Continue button, then double-tap to press it, you should be able to proceed to the next screen.
NOTE: Unfortunately I can't test it on a IOS physical device, the simulator does not allow me to simulate the double tap to press the Continue button. I need someone to test it for me.
=> fix: [IA-63] CIE login continue button doesn't work with VoiceOver activated

ts/features/wallet/component/__test__/FeaturedCardCarousel.test.tsx, ts/features/wallet/component/card/FeaturedCardCarousel.tsx
This pr removes the cashback item from the `FeaturedCardCarousel` in wallet.
- Removed the cashback item
Navigate to wallet home without being enrolled in cashback  > the `FeaturedCardCarousel` is not displayed (with `CGN_ENABLED` === false)
=> feat(Bonus Pagamenti Digitali): [IAC-96] Remove cashback item from FeaturedCardCarousel in wallet

ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.ts, ts/features/bonus/bpd/saga/orchestration/activateBpdOnNewAddedPaymentMethods.ts, ts/features/bonus/bpd/screens/details/components/summary/__test__/bpdSummaryComponent.test.tsx, ts/features/bonus/bpd/screens/details/components/summary/ranking/SuperCashbackRankingSummary.tsx, ts/features/bonus/cgn/screens/CgnDetailScreen.tsx, ts/features/wallet/privative/component/__tests__/PrivativeWalletPreview.test.tsx, ts/sagas/wallet.ts, ts/store/reducers/__mock__/backendStatus.ts, ts/store/reducers/__tests__/backendStatus.test.ts, ts/store/reducers/backendStatus.ts, ts/store/reducers/wallet/__mocks__/wallets.ts, ts/types/backendStatus.ts
This pr integrates the remote configuration for the cashback enroll suggestion after a payment method has been added.
The current configuration is `enroll_bpd_after_add_payment_method: false` -> the user is not invited to activate the cashback after adding a payment method.
https://user-images.githubusercontent.com/26501317/124494770-7b297400-ddb7-11eb-97ab-a2cd4fdcfa08.mov
- Integrated `enroll_bpd_after_add_payment_method` condition in `activateBpdOnNewPaymentMethods` (used for all payment methods except credit cards )
- Integrated `enroll_bpd_after_add_payment_method` condition in `startOrResumeAddCreditCardSaga`.
- Removed `configSelector` (not all the config should be boolean)
- Added new specific selectors `bpdRankingEnabledSelector`, `bpdRemoteConfigSelector` and …
=> feat(Bonus Pagamenti Digitali): [IAC-97] Remote configuration for cashback enroll after add payment method

ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx, ts/screens/profile/EmailForwardingScreen.tsx, ts/screens/profile/ServicesPreferenceScreen.tsx, ts/store/middlewares/analytics.ts, ts/store/middlewares/serviceAnalytics.ts
This PR introduces the tracking ability for the newly implemented APIs for setting single service contact preferences
=> chore(Redesign Servizi): [IARS-29] Add mixpanel track for newly integrated service preference API

ts/sagas/services/servicePreference/handleUpsertServicePreferenceSaga.ts
This PR fixes an issues that wouldn't reactivate notification channel if user reactivates the service communication
https://user-images.githubusercontent.com/3959405/124942626-174bb900-e00c-11eb-995e-705139b67309.mp4
=> fix(Redesign Servizi): [IARS-37] Fix disabled webhook flag when reactivating service communication

ts/components/ContextualHelpComponent.tsx, ts/components/__tests__/ContextualHelp.test.tsx, ts/components/__tests__/ContextualHelpComponent.test.tsx, ts/components/ui/ActivityIndicator.tsx, ts/utils/emptyContextualHelp.tsx
This was expect to be a short fix but led to a major refactoring due to the component's internal structure.
I decided to (perhaps) overdo the testing side because the lack of it made this task much more difficult than it should have been.
- the major change is that the body of [emptyContextualHelp](https://github.com/pagopa/io-app/compare/IA-9-remove-extra-space-context-help?expand=1#diff-5964beb965ba64ac8c59e200cef71c4ae29d9d759f5193414ec729905ccc3d08R10) now defaults to `null`
- updated the structure of [ContextualHelpComponent](ts/components/ContextualHelpComponent.tsx) to accommodate the new logic and avoid extra spacers be rendered
- add two new test files to ensure that my major change is reasonably safe and that future updates on the same component will be easier
- I've realized …
=> fix: [IA-9] Remove extra space context help

ts/boot/configureStoreAndPersistor.ts
This PR adds a missing migration from version 15 to 16
=> fix: [IA-125] Persisted store doesn't migrate

ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap, ts/boot/__tests__/persistedStore.test.ts
This pr adds the snapshot tests for the persisted store, in order to "freeze" the current layout of the persisted store and fails when a new fields is added. When this happens, it will serve as a reminder to write a migration, if it has not already been done.
- Added snapshot tests for all the persisted store sections.
Run `ts/boot/__tests__/persistedStore.test.ts`
=> chore: [IA-126] Persisted store snapshot test

ts/screens/profile/LanguagesPreferencesScreen.tsx, ts/store/reducers/__mock__/backendStatus.ts
This PR add `SectionStatusComponent` to the favourite language screen
- add the `SectionStatusComponent` to the `LanguagesPreferencesScreen` with key `email_validation`
Checkout this branch: [IA-97-show-banner-language-section](https://github.com/pagopa/io-dev-api-server/tree/IA-97-show-banner-language-section) on the `io-dev-api-server` and set to `true` the field `is_visible` in the [favourite_language](https://github.com/pagopa/io-dev-api-server/blob/d01707890609e3def06bfccec0e9459125ec08cc/src/payloads/backend.ts#L168) section
=> chore: [IA-97] Add SectionStatusComponent to the favourite language screen

ts/components/services/ContactPreferencesToggles/PreferenceToggleRow.tsx, ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx, ts/components/ui/ActivityIndicator.tsx, ts/components/ui/__test__/ActivityIndicator.test.tsx, ts/components/ui/__test__/__snapshots__/ActivityIndicator.test.tsx.snap, ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.ts, ts/store/reducers/__mock__/backendStatus.ts
This PR fixes a bug that doesn't show activity indicator on Android when the user makes some changes on his/her services preferences
https://user-images.githubusercontent.com/822471/125633856-5a2d4340-013c-400d-a0d0-f7655143d11b.mov
https://user-images.githubusercontent.com/822471/125633858-7c344dfc-f120-45a8-9ec3-65b8012e1841.mov
https://user-images.githubusercontent.com/822471/125633838-95732da9-a877-4a77-9cf1-197de759c6e7.mp4
https://user-images.githubusercontent.com/822471/125633847-f76c742e-c6d5-49e3-9e28-1c15c252f0ac.mp4
=> fix(Redesign Servizi): [IARS-36] Android doesn't show activity indicator on service preference switches

ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.ts, ts/features/bonus/bpd/saga/orchestration/activateBpdOnNewAddedPaymentMethods.ts, ts/sagas/wallet.ts
This pr changes the workflow for new payment methods and asks to enable cashback only if the cashback program is active. The information "is the cashback active?" is provided by the remote configuration `https://assets.cdn.io.italia.it/status/backend.json` within the section `config.bpd.program_active`
`program_active:false`
https://user-images.githubusercontent.com/26501317/125951913-73ef7d79-bfcb-4316-a53b-84e969582d5b.mov
`program_active:true`
https://user-images.githubusercontent.com/26501317/125952559-90935b1e-78e5-4259-af16-06ef9c0e78ed.mov
- Added integration with the remote configuration in `activateBpdOnNewAddedPaymentMethods.ts` orchestrator (for all the payment methods onboarding, except for credit cards)
- Addded integration with the remote configuration in …
=> feat(Bonus Pagamenti Digitali): [IAC-100] Ask to enable cashback on a new onboarded payment method only if the cashback program is active

ts/features/bonus/bpd/components/BpdPaymentMethodCapability.tsx, ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx, ts/features/wallet/bancomatpay/screen/BPayDetailScreen.tsx, ts/features/wallet/cobadge/screen/CobadgeDetailScreen.tsx, ts/features/wallet/component/PagoPaPaymentCapability.tsx, ts/features/wallet/component/PaymentMethodCapabilities.tsx, ts/features/wallet/component/__test__/PaymentMethodCapability.test.tsx, ts/features/wallet/privative/screen/PrivativeDetailScreen.tsx, ts/features/wallet/satispay/screen/SatispayDetailScreen.tsx, ts/screens/wallet/PaymentMethodDetailScreen.tsx, ts/store/reducers/backendStatus.ts
This pr changes the payment methods detail screens in order to render the cashback capability only if the the cashback program is active, using the remote configuration `https://assets.cdn.io.italia.it/status/backend.json` `config.bpd.program_active`.
Following all the screen when `program_active: false`
Credit card            |  Bancomat   |  BancomatPAY
:-----------------:|:-------------:|:-------------------------:
Satispay           |  Cobadge   |  Privative
:-----------------:|:-------------:|:-------------------------:
- Refactoring for all the screens, removing `<View spacer={true} />` and including `paddingVertical: 16` for `BpdPaymentMethodCapability` and `PagoPaPaymentCapability`
- Changed `ts/features/wallet/component/PaymentMethodCapabilities.tsx` in order to use the remote …
=> feat(Bonus Pagamenti Digitali): [IAC-101] Display cashback capability for a payment method only if the cashback program is active

locales/en/index.yml, locales/it/index.yml, package.json, ts/screens/authentication/cie/CieCardReaderScreen.tsx, yarn.lock
This PR upgrades `react-native-cie` to the last version
within version 1.0.7 `react-native-cie` includes two main changes proposed on the main [Android sdk repo ](https://github.com/italia/cieid-android-sdk)
1. italia/cieid-android-sdk#17
2. italia/cieid-android-sdk#19
these changes are included in this PR https://github.com/pagopa/io-cie-sdk/pull/34
1. IPZS (the CIE sdk Android mantainer) removed the certificates pinning: a security tech that restricts which certificates are considered valid for the communication client<->server
2. add a new error case: some Android devices (OPPO and Realme vendor) could not support a specific NFC feature required to read the CIE
=> chore: [IA-56] Upgrade react-native-cie

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/bpd/screens/iban/IbanCTAEditScreen.tsx, ts/features/bonus/bpd/screens/onboarding/BpdCTAStartOnboardingScreen.tsx
This pr changes the behaviour of the "Onboard to cashback" and "Edit IBAN" message CTA if the initiative is completed (`program_active: false` in https://assets.cdn.io.italia.it/status/backend.json)
When `program_active: false`:
https://user-images.githubusercontent.com/26501317/126528224-9228a6a9-a50b-47f1-ac17-956ba5d45589.mov
- Changed `ts/features/bonus/bpd/screens/iban/IbanCTAEditScreen.tsx` and `ts/features/bonus/bpd/screens/onboarding/BpdCTAStartOnboardingScreen.tsx` in order to add the new logic related to the remote config.
- Use the messages
provided by the dev-server to test the CTA behaviour, changing the https://github.com/pagopa/io-dev-api-server/blob/a201910e5655f6ce521dfd89be00e10117a60f25/src/payloads/backend.ts#L179 value.
=> feat(Bonus Pagamenti Digitali): [IAC-109] Disable cashback onboarding and edit IBAN from message CTA if the initiative is completed

ts/boot/configureInstabug.ts
This PR updates `InstabugUserAttributeKeys` type definition since one of the element of union type is not used anymore
=> fix: [IA-140] Remove Instubug unused property

ts/screens/services/ServiceDetailsScreen.tsx
This PR fix an error in the `ServiceDetailsScreen` component.
With this error the user was unable to navigate to an internal route using a CTA sended through the `/services/:service_id` API.
- Added the `dispatch` prop
In the dev server simulate a service with a CTA that navigate to an internal route.
Go to the service detail screen and press the CTA.
=> fix: [IA-164] Unable to navigate to an internal route using a CTA in service details 

locales/en/index.yml, locales/it/index.yml, ts/components/core/selection/RadioButtonList.tsx, ts/features/bonus/siciliaVola/saga/orchestration/voucherGeneration.ts, ts/features/bonus/siciliaVola/screens/voucherGeneration/CheckStatusRouterScreen.tsx, ts/features/bonus/siciliaVola/screens/voucherGeneration/SelectBeneficiaryCategoryScreen.tsx, ts/features/bonus/siciliaVola/screens/voucherGeneration/ko/SvCheckIncomeKoScreen.tsx, ts/features/bonus/siciliaVola/screens/voucherGeneration/ko/SvCheckResidenceKoScreen.tsx, ts/features/bonus/siciliaVola/screens/voucherGeneration/ko/SvGeneratedVoucherTimeoutScreen.tsx, ts/features/bonus/siciliaVola/screens/voucherGeneration/ko/SvSelectBeneficiaryCategoryKoScreen.tsx
This PR add the screen that allow the users to choose the category to which they belong.
- Add UI elements to the `SelectBeneficiaryCategoryScreen`
- Complete the `SvSelectBeneficiaryCategoryKoScreen`
- Modify the management of the workunit adding a navigation back if the workunit starts from 
https://user-images.githubusercontent.com/11773070/127887354-cb2f4da7-d5f8-43ca-8ddc-4d204e0556d9.mp4
Starts the flow from the SiciliaVola service detail. Make sure you have the updated version of the master branch on dev-server .
=> feat(Sicilia Vola): [IASV-23] Select beneficiary category screen

ios/ItaliaApp.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock
This pr enables [Hermes](https://reactnative.dev/docs/hermes) on iOS (available with React Native 0.64).
This will ensure better performance also on iOS devices.
- Hermes enabled!
- `cd ios;pod install;cd ..;yarn run-ios`. After running the application, `cmd+d` and the `HermesRuntime` should be visible.
=> chore: [IAI-34] Enable Hermes on iOS

ts/features/wallet/component/__test__/PagoPaPaymentCapability.test.tsx, ts/utils/__tests__/paymentMethodCapabilities.test.ts, ts/utils/paymentMethodCapabilities.ts
This pr changes the custom payment status representation for the cobadge card. Now is just displayed "Not available" instead of a disabled toggle.
- Changed the custom payment status representation
Wallet > A cobadge card > In the payment section should be visible "Not available"
=> feat: [IA-211] Remove cobadge payment status disabled toggle

ts/features/bonus/bpd/components/BpdTransactionSummaryComponent.tsx
Following up from https://github.com/pagopa/io-app/pull/3338 @fabriziofff 
- Use InfoBox component
- Note that we the color changes slightly (from `blueGreyDark` to `blueGrey`) due to the constraints of our typography @thisisjp 
Navigate to Wallet -> Cashback -> Your Transactions
| :----------: | :----------: |
| ![Screenshot 2021-09-01 at 16 50 11](https://user-images.githubusercontent.com/2094604/131693626-2eb2223c-a3a5-4d84-afbe-f5cfd393e71f.png) |  ![Screenshot 2021-09-01 at 16 47 47](https://user-images.githubusercontent.com/2094604/131693648-22d38860-1020-4410-9eab-a5348ec7b7af.png) |
=> fix: [IA-134] Use Infobox for Cashback transactions' info

.github/workflows/stale.yml
Mark stale issues and PR and close them after a grace period.
- Runs every 7 days at 2am UTC
- Issues and PRs without activity in the previous **60 days** are labeled as _stale_
- Issues and PRs with _stale_ label and without activity in the previous **14 days** are closed
- any activity on the issue/PR in the grace period will remove the _stale_ label
=> chore: [IAI-44] Configure actions/stale

ios/Podfile.lock, package.json, yarn.lock
This pr reverts the `react-native-webview` because the upgrade of the library it does not allow you to complete the login via CIE. In the next iteration the library will be upgraded and fixed the wrong CIE behaviour.
- Downgrade `react-native-webview`
=> fix: [IA-223] Revert react-native-webview

ts/components/screens/BaseScreenComponent/index.tsx
This pr fixes an error generated by `React.forwardRef` missing a parameter.
```
ERROR  Warning: forwardRef render functions accept exactly two parameters: props and ref. %s Did you forget to use the ref parameter?
```
=> fix: [IA-233] React.forwardRef is missing a param

android/app/src/debug/java/it/pagopa/io/app/ReactNativeFlipper.java, android/app/src/main/java/it/pagopa/io/app/MainApplication.java
At the moment, every time we add a new native library, we should also manually register the package in `MainApplication.getPackages`, even if the library supports autolink.
This pr restores the autolink on Android for the supported library, from now on it is no longer necessary to add a library manually if it have the support.
This pr also allows to use Flipper again with Android.
- Changed `getPackages()` in order to use the autogenerated list `new PackageList(this).getPackages()`
- Added the missing library that doesn't support the autolinking yet.
- `yarn run-android`
=> chore: [IAI-53] Restore autolink & Flipper on Android

ts/utils/fetch.ts
This pr increases the timeout for `constantPollingFetch` in order to avoid the failure of `/payment-activations` if it takes more than a second.
- Increase `timeout` default value in `constantPollingFetch`
1. In dev server change https://github.com/pagopa/io-dev-api-server/blob/133c4c4164ac6528aa84c3ccb916513859bdbbc6/src/global.ts#L15 to 3000 milliseconds.
1. Try a payment
1. Without this commit the payment remains blocked
=> fix: [IA-237] /payment-activations fails if it takes longer than a second

ts/screens/wallet/payment/common.ts
This pr fixes the bug described in the pr title. If the user chooses to change the psp during the payment, at the end of the payment the value of the default psp is displayed in the thank you page, indicating an incorrect payment total.
- Added `dispatch(paymentFetchPspsForPaymentId.success([psp]))` in `dispatchUpdatePspForWalletAndConfirm`, in order to update also the store state instead of navigation params only (The screen `PaymentOutcomeCodeMessage` uses the store state).
- Messages > Choose a payment message > When request, change the psp > The payment amount should be now updated in the Choose card & psp screen > Continue with the payment > The total is now right in the `PaymentOutcomeCodeMessage`.
**Before:**
https://user-images.githubusercontent.com/26501317/133087591-907dedf8-d010 …
=> fix: [IABT-1253] If the user changes psp during a payment, a wrong payment total is displayed at the end of the operation in the thank you page

ts/components/core/variables/IOStyles.ts, ts/features/bonus/bpd/screens/details/transaction/detail/BpdTransactionDetailComponent.tsx
This PR fixes bad visualization when VO is enabled on the Transaction detail bottom sheet
| Before | After | VO Disabled |
| ------ | ------ | ------ | 
| ![image](https://user-images.githubusercontent.com/3959405/133065090-6dd176b9-e2fd-41e1-98af-b04e06e51bc0.png)| ![image](https://user-images.githubusercontent.com/3959405/133065028-8f03d36b-fce1-49f2-8aef-2ece8785cc53.png)| ![image](https://user-images.githubusercontent.com/3959405/133065239-034e9198-8115-4a8d-a176-1bfa475399e7.png)|
=> fix: [IA-112] Fixes BPD transaction detail bottom sheet hiding elements on VO enabled

ts/components/helpers/withValidatedEmail.tsx, ts/screens/onboarding/EmailInsertScreen.tsx, ts/screens/onboarding/EmailReadScreen.tsx
This pr fixes the crash that occurs when an user insert the email during the first CIE onboarding and others rare edge cases.
https://user-images.githubusercontent.com/26501317/133102372-403fbbcd-f8ed-4c7d-96a5-3c5b56c048cd.mov
- Replace `StackActions.reset` with `StackActions.popToTop`
- On dev server replace https://github.com/pagopa/io-dev-api-server/blob/fe91bdfe8d90f3044f636f0f9610cfda49e5ff61/src/payloads/profile.ts#L84 with `cieProfileFirstOnboarding`
- Logout
- Login
- Insert email
- Now onboarding continues without crashing
=> fix: [IA-235] Crash when inserting email during CIE onboarding

ios/ItaliaApp/Info.plist, ios/ItaliaApp/it.lproj/InfoPlist.strings, locales/de/index.yml, locales/en/index.yml, locales/it/index.yml, patches/patches.md, patches/react-native-qrcode-scanner+1.5.3.patch, ts/screens/wallet/payment/ScanQrCodeScreen.tsx, ts/utils/asyncAlert.ts, ts/utils/permission.ts, ts/utils/share.ts
This pr adds an alert explaining why a permission is required, before asking for that permission.
https://user-images.githubusercontent.com/26501317/133644033-fdf1fe50-0c1d-4275-b96c-fff8d8471875.mov
Gallery:
Rationale            |  Permission
Camera:
Rationale            |  Permission
- Added `AsyncAlert` that allows to work with `Alert.alert` without callbacks.
- Changed `hasAndroidPermission` in `requestIOAndroidPermission`; now before asking for permission display an alert with the rationale
- Changed `ts/screens/wallet/payment/ScanQrCodeScreen.tsx` in order to display an alert with the rationale before the package `react-native-qrcode-scanner` asks for permission.
- Revoke …
=> chore: [IA-249] Add an alert explaining why a permission is required on Android

.circleci/config.yml
This pr changes the time for the `weekly-report` workflow execution.
=> fix: [IAI-59] Wrong time for workflow

ios/ItaliaApp.xcodeproj/project.pbxproj
This PR fix the build error due to the update of Xcode to the version 13.
It exploits the fix find in this PR: https://github.com/facebook/react-native/commit/eb938863063f5535735af2be4e706f70647e5b90
- Included `usr/lib/swift`
- Update XCode to the version 13.
- Try to build the app
=> fix: [IAI-61] Fix Xcode 13 build error

ts/__mocks__/react-native-fingerprint-scanner.ts, ts/components/Pinpad/index.tsx, ts/mixpanel.ts, ts/sagas/startup/checkAcknowledgedFingerprintSaga.ts, ts/screens/modal/IdentificationModal.tsx, ts/screens/onboarding/FingerprintScreen.tsx, ts/screens/profile/SecurityScreen.tsx, ts/utils/__tests__/biometrics.test.ts, ts/utils/biometrics.ts
Please check [this comment](https://pagopa.atlassian.net/browse/IA-217?focusedCommentId=16078) for a summary and access to the dashboard.
- Add property to recognize biometrics type
- Move responsibilites to `utils/biometrics` module, together with the [type definitions](https://github.com/pagopa/io-app/compare/master...IA-217-track-biometric#diff-f1b567fd9a43d3ac2b5ea0042e3fd85db7cf41c709d5c68c26a96f7845973098R12)
- Refactor the usage of `utils/biometrics` and its naming (moving from _*finger*_ to _*biometrics*_)
- Improve significantly the test coverage in `ts/utils/__tests__/biometrics.test.ts`
1. Install the app
2. Log in for the first time
3. Enable biometrics
5. Check the dashboard for the relevant events
Tested on:
* Redmi Note 8 (11)
* iPhone 11 (14.4) 
* iPhone 12 (14.5) …
=> chore: [IA-217] Track biometric capabilities

package.json, yarn.lock
This PR upgrades `react-native-cie` to v`1.1.2`
This version of the library solve two minor issues:
1. https://github.com/pagopa/io-cie-sdk/pull/36
2. https://github.com/pagopa/io-cie-sdk/pull/37
- production endpoint `cp .env.production .env`
- `yarn install`
- plug your real device
- android
- `yarn run-android`
- ios
- `yarn cie-ios:prod`
- press play in XCode
- start CIE authentication flow
=> chore: [IAI-60] Updgrade react-native-cie

ios/Podfile.lock, package.json, ts/components/cie/CieRequestAuthenticationOverlay.tsx, ts/screens/authentication/cie/CieCardReaderScreen.tsx, ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx, ts/screens/authentication/cie/CiePinScreen.tsx, yarn.lock
This pr updates `react-native-webview` and fixes a regression due to a library upgrade. 
The pr https://github.com/react-native-webview/react-native-webview/pull/1590 changed the logic with which the method `shouldOverrideUrlLoading` wait the results from the JavaScript callback `onShouldStartLoadWithRequest`, in order to choose if the loading of the page should be overwritten, waiting for the result with a timeout lock.
In our previous implementation, in `CieRequestAuthenticationOverlay.handleOnShouldStartLoadWithRequest` was called the callback `this.props.onSuccess(event.url)` when the authentication url was found, and the component `CiePinScreen` used this callback to call direcly `onProceedToCardReaderScreen`, triggering a navigation.
Doing all these sequences of operation inside the …
=> fix: [IA-224] Upgrade react-native-webview and fix cie login

ts/store/reducers/notifications/installation.ts
This PR resets the notification token store section when the authentication is not longer valid:
- logout
- session expired
- login from a different device
- successfully tested using the APK that includes these changes https://drive.google.com/file/d/1wOq4fAvsLLwaKjXA2IGUzZRDdYulzwyj/view?usp=sharing
=> chore: [IA-251] Reset notification token state when the authentication is not longer valid

ios/Podfile.lock, package.json, yarn.lock
This pr upgrades `react-native-device-info` in order to support the latest iPhone 13 and correcly calculate the required spacing in the navigation bar.
- Upgrade `react-native-device-info` to the latest version
- Run on iPhone 13
=> fix: [IA-263] Wrong spacing in navigation bar for iPhone 13

.circleci/config.yml, scripts/ts/common/slack/postMessage.ts, scripts/ts/notifyNewAppVersion/notifyNewAppVersion.ts
This pr adds a new step to the `release` workflow, in order to send a slack message after the iOS and Android builds.
- Added new job `notify-new-app-version` executed after `ios-beta-release` and `alpha-release-android`.
- Added a new ts script `scripts/ts/notifyNewAppVersion/notifyNewAppVersion.ts` in order to send the required message.
=> feat: [IAI-5] Automatically notify when a new app version is available

ts/features/wallet/onboarding/paypal/__tests__/PayPalOnboardingCompletedSuccessScreen.test.tsx, ts/features/wallet/onboarding/paypal/screen/PayPalOnboardingCompletedSuccessScreen.tsx, ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalOnboardingCompletedSuccessScreen.test.tsx, ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PayPalOnboardingCompletedSuccessScreen.test.tsx.snap
Since the PayPal onboarding workflow has been change on few details, `close` button is not longer needed
- moved `PayPalOnboardingCompletedSuccessScreen` tests from `paypal/__tests__` to `paypal/screen/__tests__`
=> chore: [IA-408] Remove close button in PayPal onboarding success screen

.circleci/config.yml
This pr upgrades the CircleCI Android image.
> As of Dec 31, 2021, legacy images will no longer be supported on CircleCI.
=> chore: [IAI-82] Upgrade CircleCI Android image

.circleci/config.yml, package.json, ts/components/core/__test__/fontsAndroid.test.ts, yarn.lock
This pr adds the `store_test_results` step in order to have a quick overview when a test fails:
In addition to this, will enable the use of test insights https://circleci.com/docs/2.0/insights-tests/, visible from https://app.circleci.com/insights/github/pagopa/io-app/workflows/build/tests?branch=master
- Changed  test workflow in `.circleci/config.yml`, in order to store the test results.
- Added `jest-junit` to transform the output in the CircleCI required format
- Changed the `test` command in `test:ci` and modified the parameters in order to better support the run on CI.
=> chore: [IAI-83] Store test results on CircleCI

.circleci/config.yml
This pr reverts https://github.com/pagopa/io-app/pull/3466 since the new image need some additional tweaking in order to be used correcly.
=> chore: Revert "Upgrade CircleCI Android image"

locales/en/index.yml, locales/it/index.yml, ts/features/wallet/onboarding/paypal/screen/PayPalPspSelectionScreen.tsx, ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalPpsSelectionScreen.test.tsx
This PR adds the bottom sheet to know more about what a psp is.
https://user-images.githubusercontent.com/822471/140279919-ac37d164-132a-4740-b250-69028a777b51.mov
https://user-images.githubusercontent.com/822471/140279948-9bca18da-91b1-4506-bf09-e9d40ab6b1e4.mov
- Replace the navigation screen in some route
for example in `MessageNavigator` _ts/navigation/MessagesNavigator.ts_
```typescript
[ROUTES.MESSAGE_DETAIL]: {
screen: PayPalPpsSelectionScreen
}
```
=> feat: [IA-304] Add "what is a psp" bottom sheet info

android/app/src/main/AndroidManifest.xml
This pr fixes a bug that doesn't allow to open urls on Android, due to some changes in the new package visibility. 
https://developer.android.com/training/package-visibility/declaring
- Services > Service details > tap "visita il sito"
- Messages > Message details > tap "DESCRIZIONE_LINK"
=> fix: [IA-423] Linking.openURL doesn't open urls on Android

ts/components/SectionStatus/index.tsx
This pr fixes an error that occurs because a wrong color is assigned to the `StatusContent` component
```
ERROR  Warning: Failed prop type: Invalid prop `color` supplied to `Text`: bluegreyDark
Valid color formats are
- '#f0f' (#rgb)
- '#f0fc' (#rgba)
- '#ff00ff' (#rrggbb)
- '#ff00ff00' (#rrggbbaa)
- 'rgb(255, 255, 255)'
- 'rgba(255, 255, 255, 1.0)'
- 'hsl(360, 100%, 100%)'
- 'hsla(360, 100%, 100%, 1.0)'
- 'transparent'
- 'red'
- 0xff00ff00 (0xrrggbbaa)
Bad object: {
"fontSize": 24,
"color": "bluegreyDark",
"alignSelf": "center",
"fontFamily": "io-icon-font",
"fontWeight": "normal",
"fontStyle": "normal"
}
at Text
in Icon (at IconFont.tsx:20)
in IconFont (at connectStyle.js:392)
in Styled(IconFont) (at StatusContent.tsx:56)
in RCTView (at View.js:34)
in View (at StatusContent.tsx:47)
in …
```
=> fix: [IA-440] Wrong color assignment in SectionStatus

ts/components/messages/MessageList.tsx, ts/components/messages/paginated/MessageList/index.tsx
This PR removes the autoscroll on top in the messages list, since [this issue](https://www.pivotaltracker.com/n/projects/2048617/stories/167507729) is no longer present
https://user-images.githubusercontent.com/822471/141496014-2f134f82-2d66-4b27-8012-688791a6abcf.mov
https://user-images.githubusercontent.com/822471/141495838-be6c153b-cb9c-43f9-ba84-f7665d7a0dc1.mov
=> chore: [IA-450] Message list should remember its scroll offset

ts/screens/wallet/payment/TransactionErrorScreen.tsx, ts/store/reducers/__tests__/paymentsHistory.test.ts
When an error occurred during a payment user can ask for assistance. In that moment some payment data are sent attached to the ticket.
This PR fixes a bug that picks wrongly a payment from history considering only the notice number and not also the organization fiscal code. The ID of a payment is the couple `noticeNumber` + `organizationFiscalCode`
- setup the dev-server to [return an error on verifica](https://github.com/pagopa/io-dev-api-server/blob/56c3a36711b93233598ddd602e0ba7b5e0183a9c/src/config.ts#L85)
- make a payment from manual insertion by inserting `000000000000000000` as notice number and `00000000000` as organization fiscal code
- change the error type on dev-server, whatever you want but different from the previous one
- make a payment from manual insertion by inserting …
=> fix: [IABT-1291] Wrong payment history selection

ts/screens/messages/MessageDetailScreen/index.tsx
This pr fixes a bug that doesn't allow to interact with the service link in the MessageDetailsScreen.
**Before**
https://user-images.githubusercontent.com/26501317/141475530-12d534be-dbd2-4c58-8a5b-38619c4e0c86.mov
**After**
https://user-images.githubusercontent.com/26501317/141475690-c2c70fba-4429-404b-848e-e3592a339129.mov
- Restore the navigation to the service detail.
- Messages > Message details > scroll to the end > tap on the message service
=> fix: [IA-447] In MessageDetailsScreen the link to related services doesn't work

ts/screens/authentication/cie/CieWrongCiePinScreen.tsx
This pr fixes the impossibility to cancel the CIE login if a wrong PIN is inserted (a regression introduced in 900d7fb52444d2424b0fbfc1637e91724b73e754)
**Before**
https://user-images.githubusercontent.com/26501317/142186986-86c70edd-7674-4f23-88d8-3a90838b47b9.mov
**After**
https://user-images.githubusercontent.com/26501317/142186916-8ce13c68-3c17-4071-893b-dc1a3cedc14d.mov
- Call the `resetToAuthenticationRoute` when the user tap on `Cancel`
Login with CIE > insert a wrong pin > Press `Cancel`
=> fix: [IA-466] Cannot cancel CIE login if a wrong PIN is inserted

ts/components/ui/Markdown/index.tsx
This pr fixes the unwanted behaviour: All space characters cause the MarkDown component infinite loading.
**Before**
https://user-images.githubusercontent.com/26501317/142013561-19230b7b-1fae-4fef-b9c4-fe5a974d9d1f.mov
**After**
https://user-images.githubusercontent.com/26501317/142012979-aca201bc-3d50-45f6-a90b-3085931524bd.mov
- Changed the `isLoading` condition in `Markdown` component
- In any `Markdown` component -> 
```typescript
<Markdown>
{" "}
</Markdown>
```
=> fix: [IA-420] All space characters text cause infinite loading in the MarkDown component

ios/ItaliaApp/Info.plist, ios/ItaliaApp/it.lproj/InfoPlist.strings, locales/en/index.yml, locales/it/index.yml, ts/components/messages/CalendarEventButton.tsx, ts/screens/profile/PreferencesScreen.tsx
This pr adds an alert explaining why the calendar permissions are required on Android, when the app requires the calendar access.
https://user-images.githubusercontent.com/26501317/142449067-0552e8a5-6453-48e8-93c6-e01b9c38235d.mov
- Added `requestIOAndroidPermission` in `CalendarEventButton.tsx` and `PreferencesScreen.tsx`
- Updated 
With the app without any permission:
Messages > A message with a "reminder" > tap on the reminder
Profile > Preferences > Favourite calendar
=> feat: [IA-467] Add an alert explaining why the calendar permissions are required on Android

ts/components/messages/paginated/MessageList/index.tsx
Add [a return statement](https://github.com/pagopa/io-app/compare/IA-502-edgebordercomponent-not-rendered?expand=1#diff-a0ab177007bd8f5d749d9e7494df01aaddde642f3d379c200e99e9c6048b9b17R231) to the `ListFooterComponent` and extract it to its own function to improve readability.
There was actually a warning in the IDE but I missed it 🤷 
Turn on the pagination flag and access the Messages.
| Before        | After           |
| ------------- |-------------|
| ![Screenshot 2021-11-26 at 10 36 49](https://user-images.githubusercontent.com/2094604/143559856-30ac59e2-15fd-49f9-b566-c8246bac6e31.png) | ![Screenshot 2021-11-26 at 10 37 07](https://user-images.githubusercontent.com/2094604/143559843-0672debc-bbd5-45bc-8e19-39b5f9c959a8.png)
=> fix: [IA-502] Return EdgeBorderComponent in list footer

scripts/check_urls/check_urls.py
This PR updates the setup of check_url script
- use the CDN endpoint in place of the older github raw content
- exclude `paymentPayloads.ts` from monitoring to avoid useless warnings see [here](https://pagopaspa.slack.com/archives/C029VR4LMNK/p1637809479000500)
=> chore: [IA-500] Update check_url script config

android/app/build.gradle, ios/ItaliaApp.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, ts/components/messages/paginated/MessageList/index.tsx, yarn.lock
This PR update the `io-react-native-zendesk` to the **0.3.9**.
[This version](https://github.com/pagopa/io-react-native-zendesk/pull/6) expose 2 new methods: 
- `openTicket`
- `showTickets`
- Updated io-react-native-zendesk to 0.3.9
- Fixed kotlin-reflect version at 1.3.41 as we have 2 package using 2 different version of this package and this leads to compilation error
Try to run both on Android and IOS.
I suggest to remove the `Podfile.lock` before start.
=> chore(Zendesk): [ASZ-124] Update io-react-native-zendesk

scripts/check_urls/check_urls.py, ts/features/common/store/reducers/index.ts, ts/features/euCovidCert/saga/index.ts, ts/features/mvl/saga/index.ts, ts/features/mvl/saga/networking/handleGetMvlDetails.ts, ts/features/mvl/store/actions/index.ts, ts/features/mvl/store/reducers/__test__/byId.test.ts, ts/features/mvl/store/reducers/byId.ts, ts/features/mvl/store/reducers/index.ts, ts/features/mvl/types/MVLData.ts, ts/features/mvl/types/MvlData.ts, ts/features/mvl/types/__mock__/mvlMock.ts, ts/features/mvl/types/mvlData.ts, ts/sagas/startup.ts, ts/store/actions/types.ts, ts/store/reducers/backoffError.ts, ts/types/contentType.ts, ts/types/digitalInformationUnit.ts
This pr adds the types, actions, store, reducers and saga entrypoint required for the legal messages.
- Added `ts/types/digitalInformationUnit.ts` in order to have unambiguous types to measure the digital information
- Added `ts/types/contentType.ts` in order to have a unique enumeration in the app for content-types 
- Defined the datamodel, based on the required data. This could be change in future based also on the API specification. 
`MvlData` represents the MVL with all the information required to render it. It is composed by a body (`MvlBody`), a list of possible attachments (`ReadonlyArray<MvlAttachment>`) and some metadata (`MvlMetadata`). All the `MvlData` have an unique `MvlId`, defined as unique tagged, in order to avoid to mix generic `string` with MVL ids.
- Created a new …
=> chore(Messaggi a valore legale): [IAMVL-8] Add types, actions, store, reducers & saga entrypoint

ts/store/reducers/__mock__/backendStatus.ts
This PR fix a bug introduced with https://github.com/pagopa/io-services-metadata/pull/522 which caused CI tests to fail.
- Update test mocks adding the `zendesk` value in the `backendStatus.ts` file
Run `yarn tsc --noemit`
=> fix: [IA-544] Align mocks to io-services-metadata update

ts/__mocks__/messages.ts, ts/components/messages/paginated/MessageList/Item.tsx, ts/components/messages/paginated/MessageList/__tests__/Item.test.ts.tsx, ts/components/messages/paginated/MessageList/helpers.tsx, ts/store/reducers/entities/messages/transformers.ts, ts/store/reducers/entities/messages/types.ts
Replace temporary definition of `MessageCategory` with the one generated from the API specs.
Build, lint, run tests.
=> [IA-560] Use MessageCategory from definitions

ts/components/MessagesTabIcon.tsx
This PR disabled the messages unread counter badge when pagination is active
| pagination OFF  | pagination ON |
=> chore: [IA-572] Disable messages unread counter badge

package.json, yarn.lock
This PR upgrade the `io-react-native-zendesk` package to the `0.3.11` version.
This version introduce the possibility to send log and custom field and remove the possibility to open a ticket from the ticket list.
=> chore: [IA-576] Upgrade io-react-native-zendesk

ios/Podfile.lock
This PR upgrade the `io-react-native-zendesk` package to the `0.3.11` version in IOS 
For further details check #3585.
=> chore: [IA-576] Upgrade react-native-zendesk IOS 

ts/utils/supportAssistance.ts
This PR update the Zendesk SDK configuration value to those used in production.
- Modify both the anonymous and the authenticated configuration
You can try to open a ticket anonymously both in dev and prod mode.
When you try to open a ticket as authenticated you must be in prode mode and modify this switch https://github.com/pagopa/io-app/blob/d0b98940f74e42591c5fe171de91c6e02451ba5e/ts/components/screens/BaseScreenComponent/index.tsx#L205
in order to execute Zendesk also if the remote FF is setted to instabug.
=> chore: [IA-578] Update Zendesk SDK configuration value

ts/features/zendesk/analytics/index.ts, ts/features/zendesk/saga/orchestration/index.ts, ts/features/zendesk/screens/ZendeskChooseCategory.tsx, ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx, ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx, ts/features/zendesk/store/actions/index.ts, ts/store/middlewares/analytics.ts
This PR adds the track the events that happens in the Zendesk request workflow.
The following events has been tracked:
| Eventi name | Attributes | Description |
| ------------- | ------------- | ------------- |
| ZENDESK_SUPPORT_COMPLETED  |  | the service request workflow has been completed. Either a new ticket has been opened, or the user has entered the list of open tickets, or the user has gone to an internal redirect link, or the user has exited screen panic mode  |
| ZENDESK_SUPPORT_CANCEL  |   | the X button was pressed in the help center screen |
| GET_ZENDESK_CONFIG_REQUEST  |  | remote configuration of Zendesk was required  |
| GET_ZENDESK_CONFIG_SUCCESS  |  | the remote configuration of Zendesk was successfully recovered  |
| ZENDESK_SUPPORT_START  | …
=> chore: [IA-587] Add Zendesk analytics

ts/boot/configureInstabug.ts
This pr disables the Instabug attachments & screen recording.
=> chore: [IA-593] Disable Instabug attachments & screen recording

ts/components/screens/BaseScreenComponent/index.tsx, ts/features/bonus/bpd/screens/details/transaction/__test__/TransactionsUnavailable.test.tsx, ts/screens/wallet/PaymentHistoryDetailsScreen.tsx, ts/screens/wallet/creditCardOnboardingAttempts/CreditCardOnboardingAttemptDetailScreen.tsx, ts/screens/wallet/payment/TransactionErrorScreen.tsx, ts/store/reducers/assistanceTools.ts, ts/utils/supportAssistance.ts
This PR hide the assistance entry points if the assistance tool is Zendesk and the email is not validated.
- Add the `isEmailValidated` condition in `canShowHelp` util
- Modify the entry point passing the `isEmailValidated` param (`BaseScreenComponent`, `CreditCardOnboardingAttemptDetailScreen`, `PaymentHistoryDetailsScreen`, `TransactionErrorScreen`)
https://user-images.githubusercontent.com/11773070/146794373-b0f93b54-ba47-45d8-96ef-01260daa51ee.mp4
Try to set the `is_email_validated` flag to false i[n the dev server](https://github.com/pagopa/io-dev-api-server/blob/88e6dce8a90fd9a445350a62887babfe467155a3/src/payloads/profile.ts#L16)
=> chore: [IA-586] Hide zendesk if email not validated

ios/Podfile.lock, package.json, ts/features/zendesk/components/ZendeskSupportComponent.tsx, ts/features/zendesk/components/__tests__/ZendeskSupportComponent.test.tsx, ts/features/zendesk/saga/index.ts, ts/features/zendesk/saga/networking/handleHasOpenedTickets.ts, ts/features/zendesk/store/actions/index.ts, ts/features/zendesk/store/reducers/index.ts, ts/utils/supportAssistance.ts, yarn.lock
This PR hide the show tickets button if the user has never created a ticket.
- Upgrade io-react-native-zendesk to the version 0.3.13
- Show the show tickets button only if the user has created at least one ticket
https://user-images.githubusercontent.com/11773070/146978297-5eb6bdb5-19ac-4a05-b5ac-bf16f51b40c5.mp4
https://user-images.githubusercontent.com/11773070/146979011-00a4c42d-d7e7-4d02-9eb9-116a45ad4ee9.mov
Try to remove the app, press the assistance button.
Then try to open a ticket.
Finally try to press again the assistance button.
=> chore: [IA-595] Hide show tickets button

locales/en/index.yml, locales/it/index.yml, ts/features/mvl/screens/ko/MvlGenericErrorScreen.tsx
This pr updates the copy for the `MvlGenericErrorScreen`
- Dispatch `NavigationService.dispatchNavigationAction( navigateToMvlDetailsScreen({ id: "id" as UIMessageId }) )` and configure the dev server to fails when request the legal message details
- modify https://github.com/pagopa/io-app/blob/d866cee05be2016382aec4c42577e5d7d26c239a/ts/features/mvl/screens/MvlRouterScreen.tsx#L56 with: `return <MvlGenericErrorScreen id={mvlId} />`
=> chore(Messaggi a valore legale): [IAMVL-33] Update legal message error screen

ts/features/mvl/screens/details/MvlDetailsScreen.tsx
If a service for MVL is not present, try to load it.
There is no retry strategy.
I've assigned the first service in the list to all the messages on the dev-server, then returned the list [1 ... 10] from `/services`. Opening the legal message will trigger a `MVL_DETAILS_REQUEST` as in the picture.
=> chore(Messaggi a valore legale): [IAMVL-36] Fetch service if not present

ts/components/screens/BaseHeader.tsx, ts/components/screens/BaseScreenComponent/index.tsx, ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx, ts/features/wallet/onboarding/paypal/screen/PayPalOnboardingCheckoutScreen.tsx, ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalOnboardingCheckoutScreen.test.tsx
This PR adds the handling of back (hard&soft) while the user is onboarding his/her Paypal account, in the checkout phase
https://user-images.githubusercontent.com/822471/147812941-64c9e463-f30e-4a42-a1ae-4dd2413e8d56.mp4
- add a Paypal account and in the checkout screen press `back`
=> chore: [IA-480] Handle back on Paypal onboarding

ts/components/messages/MessageDetailComponent.tsx
This PR fixes a bug that causes a crash
The previous logic expected a service even when it is not available (it uses an `Option` but it can't never be `none`)
Since the service shape could change is very dangerous to have a dummy/default service and **force a cast** on it
So the fix consists in deal with the service as it can come: `some` or `none`
https://user-images.githubusercontent.com/822471/147917218-940cdf70-3fc2-47de-bf65-1ac961066c7b.mov
https://user-images.githubusercontent.com/822471/147917199-4d9c92c8-b64a-4ee6-af72-4bbd7eabc6c5.mov
the fix should work with `legacy` and `pagination` mode
- use the dev-server [to deny the app gets services details](https://github.com/pagopa/io-dev-api-server/blob/69371e5b4449225b0891b69f33553ac7e6065bb4/src/routers/service.ts#L38) (i.e return …
=> fix: [IA-611] When the MessageDetail can't get the relative sender services, app crashes

ts/RootContainer.tsx, ts/navigation/NavigationService.ts, ts/sagas/mixpanel.ts, ts/sagas/startup.ts
This pr fixes a bug that could cause the execution of the `initializeApplicationSaga` before the `NavigationService` initialization.
- Added logging in `NavigationService` in order to understand if there are call to `NavigationService` before the initialization.
- Changed `initializeApplicationSaga` in order to wait for the `NavigationService` initialization.
=> fix: [IA-616] The initializeApplicationSaga could be executed before the NavigationService initialization

ts/features/zendesk/components/ZendeskSupportComponent.tsx, ts/features/zendesk/screens/ZendeskAskPermissions.tsx, ts/features/zendesk/screens/ZendeskChooseCategory.tsx, ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx
This PR integrates the Zendesk workflow tracked events with the new ones below.
| Event name | Attributes | Description |
| ------------- | ------------- | ------------- |
| ZENDESK_SHOW_TICKETS  |  | the user chooses to see the already opened tickets |
| ZENDESK_DENY_PERMISSIONS  |   | the user denies the permission to send data to the assistance in the `ZendeskAskPermissions` screen |
| ZENDESK_OPEN_TICKET  |  | the user open a ticket from the `ZendeskAskPermissions`, the `ZendeskChooseCategory` or the `ZendeskChooseSubCategory` screen |
=> chore: [IA-627] Integrate Zendesk analytics

.circleci/config.yml
This pr changes the resource class for macOS to `macos.x86.medium.gen2` in order to reduce the build time. For more information see https://discuss.circleci.com/t/coming-soon-gen2-macos-resources/41886 
`run-e2e-test-IOS`:
- Changed resource class for macos to `macos.x86.medium.gen2`
=> chore: [IAI-110] Upgrade macOS resources on CircleCI

scripts/ts/common/ticket/types.ts, scripts/ts/danger/commentPrWithTicketsInfo.ts, scripts/ts/danger/utils/changelog.ts
This PR adds the `epic` case handling.
ATM a task of an epic is reported as follows
With these changes, this is the new report
Note: this task is intentionally child of an epic just for tests purposes
=> chore: [IA-639] Test epic icon

ts/screens/authentication/IdpLoginScreen.tsx
This PR changes the loading layout to avoid it fills the entire screen. With these changes the header is touchable so the user can go back. In Android the back hardware works as usual.
https://user-images.githubusercontent.com/822471/150543308-8bc5d5b0-87d5-4478-8a30-6f0b6fc80301.mov
https://user-images.githubusercontent.com/822471/150543341-b9796a18-9b4f-42b3-9e8a-d24f58d41824.mov
- `IdpLoginScreen.tsx` now the loading layout is not full screen 
- [add some delay](https://github.com/pagopa/io-dev-api-server/blob/35496a6690965872263fff8b23a61a587e7a88d2/src/config.ts#L55) to the dev server to reproduce a certain loading
=> feat: [IA-633] Allow back during SPID webview loading

ts/features/mvl/saga/networking/handleGetMvlDetails.ts
As per [the new specs](https://github.com/pagopa/io-backend/pull/864/files#diff-ac5f41902728c87f4277af9405ffbdf02ba3225a7987805c9b9603119e691e7bR323) we will use the `message.id` value to retrieve an attachment.
Run the app against https://github.com/pagopa/io-dev-api-server/pull/126 and verify that by tapping on a legal message you can still open it.
Task https://pagopa.atlassian.net/browse/IAMVL-63
=> [IAMVL-63] Use message ID to retrieve the attachment

ts/components/DetailedlistItemComponent.tsx, ts/components/messages/paginated/MessageList/Item.tsx, ts/components/messages/paginated/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
This PR will fix the messages' title which at the moment is using a fixed amount of space instead of being flex.
- The message title is now flexible.
| Without label  | With label |
|  ![Simulator Screen Shot - iPhone 12 - 2022-01-25 at 17 10 41](https://user-images.githubusercontent.com/5963683/151017713-b45ff1bd-4b80-4b26-89c3-5bdaa933d6b6.png)  | ![Simulator Screen Shot - iPhone 12 - 2022-01-25 at 17 11 08](https://user-images.githubusercontent.com/5963683/151017742-46b5443c-0111-4f75-922b-e807886dcb4e.png) |
| Without label  | With label |
| <img width="340" alt="Screenshot 2022-01-25 at 17 23 37" src="https://user-images.githubusercontent.com/5963683/151018030-32a60da9-5b46-490a-a7ad-3e57d197542a.png"> | <img …
=> fix: [IA-644] Fixed messages title not flexible

locales/en/index.yml, locales/it/index.yml, ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap, ts/boot/__tests__/persistedStore.test.ts, ts/boot/configureStoreAndPersistor.ts, ts/features/common/store/reducers/index.ts, ts/features/mvl/index.ts, ts/features/mvl/screens/details/components/attachment/DownloadAttachmentConfirmationBottomSheet.tsx, ts/features/mvl/screens/details/components/attachment/MvlAttachments.tsx, ts/features/mvl/screens/details/components/attachment/__test__/MvlAttachments.test.tsx, ts/features/mvl/store/actions/index.ts, ts/features/mvl/store/reducers/__test__/preferences.test.ts, ts/features/mvl/store/reducers/index.ts, ts/features/mvl/store/reducers/preferences.ts, ts/screens/profile/ProfileMainScreen.tsx, ts/store/reducers/entities/index.ts, ts/store/reducers/index.ts, ts/store/reducers/types.ts
Persist on the device the user's preferences for MVL. The only preference available to date is whether to show a warning for attachments or not.
- Update [DownloadAttachmentConfirmationBottomSheet](https://github.com/pagopa/io-app/pull/3681/files#diff-04d9d7c779eec6038ab9af0b57e77a474cfeda11a4052b29b668461fcecb04f3R35) to save the preference **once the user is done** and initialize them
- Update [MvlAttachments](https://github.com/pagopa/io-app/pull/3681/files#diff-2de5ec1ba6bf2598f6aa698a983c5aff6bc00042d3fba19c30ca411622beaffeR93) to sidestep the alert based on the preference
- Add tests for [MvlAttachments](https://github.com/pagopa/io-app/pull/3681/files#diff-4c3f5a56c849be98fa85cd976e88f1c5f275d8fe83d71bada54f4fd635abedc5R80) to ensure it honours the preferences
- Add [new …
=> chore(Messaggi a valore legale): [IAMVL-26] Persist attachments preferences for MVL

ts/utils/__tests__/dates.test.ts, ts/utils/dates.ts
This PR fixes a wrong logic that checks if a date is expired or not
The error is about the comparison, this is how this logic actually works
- current year is less than the given one -> expired ✅ 
or
- current month is less than the given one -> expired 🐞 
So assuming you are checking `isExpired(2023,1)` today (2022-02-01) it will return true (expired 😨 )
| before  | fixed |
- try to execute `isExpired` with one of these inputs (assuming now is today -> 2022-02-01)
- `isExpired(2023,1)`
- `isExpired(2024,1)`
=> fix: [IA-654] The logic to check if a data is expired is wrong

.env.local, .env.production, README.md, ts/RootContainer.tsx, ts/config.ts
This PR will enable the `VersionInfoOverlay` directly in the debug mode, without using a specific feature flag.
- The `VersionInfoOverlay` is now automatically turned on in the debug mode.
- Removed the `shouldDisplayVersionInfoOverlay` flag.
https://user-images.githubusercontent.com/5963683/152001113-f02836b4-a342-437d-a817-ee504180e3f5.mov
Entering debug mode (from the preferences, pressing 5 times on the app version) should activate an overlay on top with the route name
=> feat: [IA-640] The `VersionInfoOverlay` component is now enabled in the debug mode

ts/utils/messages.ts
This PR removes reason field from tracking `CTA_FRONT_MATTER_DECODING_ERROR` event
=> fix: [IA-244] Remove `reason` field from tracking `CTA_FRONT_MATTER_DECODING_ERROR` event

ts/features/wallet/onboarding/__e2e__/creditCardOnboarding.e2e.ts, ts/screens/wallet/ConfirmCardDetailsScreen.tsx
This PR fixes the bug in the e2e test introduced with https://github.com/pagopa/io-app/pull/3691 .
It use the `testId` instead of the text to identify the continue button.
- Added the `testId` to the continue button in the `ConfirmCardDetailsScreen`
- Use the `testId` instead of the text to identify the button
Run the `ts/features/wallet/onboarding/__e2e__/creditCardOnboarding.e2e.ts` test
=> fix: [IA-656] Fix e2e test

ts/features/bonus/bpd/api/patchedTypes.ts, ts/features/bonus/bpd/saga/networking/index.ts, ts/sagas/wallet/pagopaApis.ts
This PR sync the spec with production where `optInStatus` is not returned yet within the citizen payload
It also fixes a logic where the network saga dispatches a failure when `notDeletedMethod` are `!== 0`
=> fix(Bonus Pagamenti Digitali): optInStatus should be optional

ts/utils/payment.ts
This PR adds the `PAA_SYSTEM_ERROR` error code to the "ente" cases.
In this way when the error occurs the relative code will be shown
- use the dev-server and set [here](https://github.com/pagopa/io-dev-api-server/blob/7e2e597c210f0f5cb40a50b8046c7ebb46ee94c2/src/config.ts#L90) this
-  ![Schermata 2022-02-11 alle 17 48 09](https://user-images.githubusercontent.com/822471/153633276-003e1bf6-674e-4f13-817d-9bba50db0ccc.png)
=> feat: [IA-663] Show PAA_SYSTEM_ERROR payment code error

locales/en/index.yml, locales/it/index.yml, ts/components/services/ServiceMetadata/index.tsx
This PR will make the VO read the `C.F.` text as `Codice fiscale`.
- Created an accessibility i18n to describe how `C.F.` will be read by the VO
In the service details screen, the description `C.F. Ente` should be read as `Codice fiscale Ente`. The accessibility label should match in the Accessibility Inspector.
=> feat: [IA-400] The `C.F.` text will be read as `Codice fiscale` by the Voice Over

ts/screens/wallet/payment/TransactionErrorScreen.tsx
This PR is going to fix an alignment error in `TransactionErrorScreen`, centering the label text.
| ------ | ------|
|  <img width="410" alt="Screenshot 2022-02-22 at 12 19 57" src="https://user-images.githubusercontent.com/5963683/155122315-8063046c-ee42-4030-965e-33ea6920c35c.png"> |  <img width="410" alt="Screenshot 2022-02-22 at 12 19 17" src="https://user-images.githubusercontent.com/5963683/155122339-717a8864-da01-4389-a8d9-d07f25a4a469.png"> |
- Centered the text in `TransactionErrorScreen`
Setting `wallet.verificaError` as `Detail_v2Enum.PPT_STAZIONE_INT_PA_SCONOSCIUTA` in the dev server configuration, and executing a payment, the resulting error screen should be centered correctly.
=> fix: [IABT-1300] Centered label text in `TransactionErrorScreen`

ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsChoiceScreen.tsx
This PR fixes the wrong translation in the `OptInPaymentMethodsChoiceScreen`
- Used a function instead of a const to translate labels ( `radioButtonListItems` ) 
Navigate to the `OptInPaymentMethodsChoiceScreen` dispatching the `navigateToOptInPaymentMethodsChoiceScreen` setting different languages.
=> fix(Bonus Pagamenti Digitali): [IAC-142] Fix wrong translation in OptInPaymentMethodsChoiceScreen

ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx, ts/screens/profile/CgnLandingPlayground.tsx
This PR fixes the problem that prevents to send the http Referer on Android system webview.
https://user-images.githubusercontent.com/3959405/155972785-dfac3ff1-afdc-475c-be54-d469292d174f.mov
https://user-images.githubusercontent.com/3959405/155972981-8f4c7d1d-831f-420a-9a67-6cfb33379c12.mov
=> fix(Carta Giovani Nazionale): [IOACGN-61] Fixes the bug that prevents to send Referer header for CGN landing page Discount

ts/screens/messages/MessagesHomeScreen.tsx, ts/screens/messages/paginated/MessagesHomeScreen.tsx
The status banner in messages home screen should be shown on top when the screen reader is ON, but on bottom when the SR is OFF. At the moment it is always shown on top. This PR fixes it (both paginated messages and not).
- Add `isScreenReaderEnabled` state (`false` by default) in `MessagesHomeScreen` (updated in `componentDidMount` with `isScreenReaderEnabled()`)
- In `paginated/MessagesHomeScreen` the `useScreenReaderEnabled()` function is used instead
Enable a status message in the dev server and run the app both with the screen reader enabled and disabled. Beware that the status is just read once when the component is mounted, so when you switch the settings, please re-launch the app from scratch.
| SR disabled | SR enabled |
| - | - |
| …
=> fix: [IA-308] Status banner position in messages when the screen reader is OFF

ts/components/SectionStatus/StatusContent.tsx, ts/components/SectionStatus/index.tsx
The screen reader on Android doesn't recognize the accessibility role in status banners that contain a link. This is caused by a child component that overrides accessibility settings where the link is declared. This PR disables accessibility on the child component.
- Add an (optional) `accessible` prop to the `StatusContent` component
- Disable accessibility for the `StatusComponent` in `SectionStatus` when it's wrapped in a `Tappable` that already has accessibility properties
https://user-images.githubusercontent.com/467098/156402800-ac772391-dbb4-4d4f-b9f9-dc4f1c1f4a5c.mp4
=> feat: [IA-366] Link recognition by the screen reader on Android

ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
#3718 introduced a regression on a fix that was previously made with #3728. In particular a wrapping view for the footer has been removed. This PR re-introduces it, restoring the right behavior.
- Wrap the actual footer in  `<View style={styles.footerContainer}>...</View>`
| - | - |
| ![Simulator Screen Shot - iPhone 12 - 2022-03-07 at 11 24 08](https://user-images.githubusercontent.com/467098/157014469-b6aad57b-1ad3-40fd-af66-4ad1f31aea8d.png) | ![Simulator Screen Shot - iPhone 12 - 2022-03-07 at 11 08 30](https://user-images.githubusercontent.com/467098/157014495-d89d5a27-2252-42fd-9fc7-da17736a6f0e.png) |
Start a payment and navigate to `PAYMENT_CONFIRM_PAYMENT_METHOD` screen with an iPhone X-like simulator. You shouldn't see any "hole" in the bottom safe area.
=> fix: [IA-703] Regression in the layout of the footer with a safe area

ts/components/wallet/PaymentBannerComponent.tsx, ts/components/wallet/__test__/PaymentBannerComponent.test.tsx
When a payment doesn't have a transaction fee, the confirmation screen shows `-` instead of the total amount. This PR fixes it, showing `0` (formatted) as fee, and the right amount as total.
Setup the dev server to return a fee of `0` for the transaction, then perform a payment.
| - | - |
| ![Simulator Screen Shot - iPhone 12 - 2022-03-07 at 15 30 02](https://user-images.githubusercontent.com/467098/157053590-d638c8f5-5ec8-440b-a806-e31ddf82ec27.png) | ![Simulator Screen Shot - iPhone 12 - 2022-03-07 at 15 29 49](https://user-images.githubusercontent.com/467098/157053631-f0e3bf30-4132-439d-a68a-fdae25ac0600.png) |
=> fix: [IA-705] Payment banner shows incorrect total when transaction has no fee

ts/features/uaDonations/screens/UAWebViewScreen.tsx
This pr adds the missing `SafeAreaView` in `UAWebViewScreen`.
=> fix: [IA-716] UAWebViewScreen doesn't have SafeAreaView

ios/Podfile.lock
This pr sync the `RNSVG`version in `Podfile.lock` following https://github.com/pagopa/io-app/pull/3800
=> chore: Sync Podfile.lock for RNSVG

ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
This PR fix a regression added here #3718
This is a **🔥 critical bug 🔥**   since it doesn't allow to make a payment: the payment data are never forwarded in the payment webview
The dev server output 
real payment
https://user-images.githubusercontent.com/822471/157711097-1020a1bb-8385-47ce-b03c-f21e9f759c6a.mp4
=> fix: [IA-721] Payment data are not forwarded in the payment webview

ts/features/zendesk/screens/ZendeskAskPermissions.tsx
This PR fixes the bug that didn't allow to open the email client when the user denied consent to share information during the Zendesk ticket opening.
https://user-images.githubusercontent.com/11773070/158214885-f988f27b-0bea-46c6-9412-0d7c3c618a91.mp4
Try to open a ticket and deny the consent to share information.
If you are running the app in the simulator, or if you don't have the email client installed on your phone, you should see the information toast.
=> fix: [IA-733] The email client is not open when the user denies consent to share information

package.json, yarn.lock
This pr upgrades `react-native-flag-secure-android` to the latest version and remove the custom target.
- Disable dev mode
- Wallet > Add Payment Method > Take a snapshot > The snapshot cannot be taken
=> chore: [IAI-142] Update `react-native-flag-secure-android` and remove custom target

ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx, ts/features/bonus/cgn/store/actions/bucket.ts, ts/features/bonus/cgn/store/reducers/bucket.ts
This PR refactors CGN Bucket code component to avoid automatic bucket code request (and consuption).
Now the Code is requested only when users tap on the related Eye icon.
Check for an available CGN merchant with bucketCode discount type, then open a discount and ask for a bucket code.
https://user-images.githubusercontent.com/3959405/159334291-313497b3-3cea-4e61-9ca0-461cf4e57b8b.mp4
=> chore(Carta Giovani Nazionale): [IOACGN-68] Refactors bucket code request component to avoid huge bucket consuption

ts/api/backend.ts, ts/boot/__tests__/migrateToPagination.test.ts, ts/boot/migrateToPagination.ts, ts/components/messages/paginated/MessageList/helpers.tsx, ts/components/messages/paginated/MessageList/index.tsx, ts/features/euCovidCert/screens/EuCovidCertificateRouterScreen.tsx, ts/features/mvl/screens/MvlRouterScreen.tsx, ts/features/mvl/screens/__test__/MvlRouterScreen.test.tsx, ts/sagas/messages/__tests__/watchUpsertMessageStatusAttributes.test.ts, ts/sagas/messages/watchUpsertMessageStatusAttribues.ts, ts/sagas/startup.ts, ts/screens/messages/MessageDetailScreen/index.tsx, ts/screens/messages/MessagesHomeScreen.tsx, ts/screens/messages/paginated/MessageDetailScreen.tsx, ts/screens/messages/paginated/MessageRouterScreen.tsx, ts/store/actions/messages.ts, ts/store/middlewares/analytics.ts, ts/store/reducers/entities/__tests__/messagesStatus.test.ts, ts/store/reducers/entities/messages/allPaginated.ts, ts/store/reducers/entities/messages/messagesStatus.ts
We implement the networking and logic for upserting message attributes _read_ and _archived_. I've connected the _read_ status to test it, while the _archived_ action is more complex due to sorting edge cases and will be handled in a separate task.
- new backend [endpoint](https://github.com/pagopa/io-app/pull/3848/files#diff-ac04d289df4b924fd0e2cee9ddaa414ad33332daf86424260ab533c21a284193R460)
- new [saga](ts/sagas/messages/watchUpsertMessageStatusAttribues.ts), [action](https://github.com/pagopa/io-app/pull/3848/files#diff-5b727d84caebb631cf6843fbd8f3595a97801341cee749b8d9535aabdbc12460R128), and [tests](ts/sagas/messages/__tests__/watchUpsertMessageStatusAttributes.test.ts)
- former [read](https://github.com/pagopa/io-app/pull/3848/files#diff-5b727d84caebb631cf6843fbd8f3595a97801341cee7 …
=> feat: [IA-728] Saga and networking for upserting message attributes

ts/components/wallet/FavoriteMethodSwitch.tsx
This PR is going to fix the switch loader alignment showed while setting a favourite payment method on Android.
❓ This fix takes for granted that on iOS the switch must be aligned to the top while on Android it's centered.
https://user-images.githubusercontent.com/5963683/159962249-40cddb58-5236-418c-a6d1-5e9249e3f2a2.mov
https://user-images.githubusercontent.com/5963683/159962265-082d98da-67e2-4de0-8532-78fb558c6ef8.mov
- Fixed the loader alignment on Android
Go into the wallet and set a payment method as favourite, the loader should be aligned correctly both on iOS and Android.
=> fix: [IA-735] Fix payment method switch loader alignment on Android

ts/components/messages/paginated/MessageList/index.tsx, ts/components/messages/paginated/MessagesInbox.tsx
Donation banner should only be presented in messages inbox.
- Remove `UaDonationsBanner` from `MessageList` and add a `ListHeaderComponent` prop
- Inject `UaDonationsBanner` as `ListHeaderComponent` from `MessagesInbox`
Make sure you have `uaDonationsEnabled` config set to true and navigate Inbox, Archive and Search.
| - | - |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-04-01 at 16 00 09](https://user-images.githubusercontent.com/467098/161279353-6f937856-0db6-49d2-ba29-8f704fbff7f9.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-04-01 at 15 59 43](https://user-images.githubusercontent.com/467098/161279337-7c182bd0-a9cb-40e7-a5ce-22511e2f0c7e.png) |
|  ![Simulator Screen Shot - iPhone 13 Pro - 2022-04-01 at 16 00 …
=> chore: [IA-801] Remove donation banner from archive and search

ts/sagas/messages/watchUpsertMessageStatusAttribues.ts
Although you can select multiple messages to archive/unarchive, each of them sends a single request to the backend. In some conditions it might happen that some requests get cancelled without neither succeeding nor failing.
This PR addresses the issue.
- Replace `takeLatest` with `takeEvery` in the saga watcher
Select all the messages in the Inbox, put the device in Flight Mode (or shutdown the dev server) and tap on Archive. Messages should be moved to the Archive at first, but when the requests fail they should all be moved back to the Inbox.
=> fix: [IABT-1366,IABT-1367] Requests might be silently cancelled when archiving multiple messages at once

ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx, ts/screens/wallet/payment/__tests__/ConfirmPaymentMethodScreen.test.tsx
This PR adds some changes in order to display BancomatPay in the payment checkout screen.
- use dev-server by pointing this branch `IA-786-bpay-can-pay`
- turn on **[this FF](https://github.com/pagopa/io-dev-api-server/blob/c6c6a71c5c893832546f2a37c228d2d39092c87a/src/payloads/backend.ts#L237)** 
- do a payment and pick BPay as payment method
=> chore: [IA-806] Show BPay in checkout payment screen

ts/screens/authentication/IdpLoginScreen.tsx
This PR fixes a bug that causes to display a void content when an error with SPID login is detected
- simulate an error in the SPID login webview
=> fix: [IA-814] An empty screen is shown when an error occurred in SPID login 

ts/screens/wallet/payment/__tests__/ConfirmPaymentMethodScreen.test.tsx
This PR is going to strengthen the unit tests in the payment checkout section. Now the data sent to the relative WebView are tested in order to prevent issues like: https://github.com/pagopa/io-app/pull/3828.
- Added unit tests to check for the data sent to the WebView during the checkout
Setting the `formData` variable to `{}` (or removing values from it) inside `ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx` should not allow the tests to pass correctly.
=> chore: [IA-724] Add unit tests for the payment checkout WebView data
