- ts/screens/wallet/payment/TransactionSummaryScreen.tsx
Fix the navigation error by matching against the MESSAGE_DETAIL_PAGINATED route. 
Crash scenario is now not reproducible as well.
https://user-images.githubusercontent.com/2094604/162914313-47690618-e2dd-4e2f-9658-04f0b542e02e.mov
> [IABT-1370] Match against message detail route

- ts/__e2e__/payment.e2e.ts
- ts/screens/messages/paginated/MessageDetailScreen.tsx
This PR introduces an E2E test as a guard for preventing future regressions on #3904.
https://user-images.githubusercontent.com/467098/162976186-d8545842-4887-4ae3-be13-b9acbb10c78d.mov
> chore: [IA-821] Add an E2E test to the payment flow that starts from a message

- ts/boot/configurePushNotification.ts
This pr enables the push notifications on iOS when we are in dev mode.
Now is possible to simulate a push notification without commenting any part of the code, just using the command `xcrun simctl push B72B45FE-6DFF-4945-A53B-74918ED7A07A it.pagopa.app.io test.apns` or drag and drop the `apns` file to the emulator.
> chore: [IAI-182] Enable iOS push notification in dev mode

- ts/components/messages/paginated/MessageList/index.tsx
On Android, when the user reaches the end of the message list, the scrolling stops like hitting a wall. Then the next page gets fetched, but the loading indicator remains hidden below the visible area. This PR aims to improve this UX.
- Add a space at the end of the message list so that scrolling stops a bit over the latest message (this leaves some space that will be filled by the loading indicator);
- Increase the `onEndReachedThreshold` so that page loading begins a bit earlier. 
Configure the dev server to return several pages of messages (optionally with some delay). Then start scrolling and verify the the loading indicator is always visible at the end of the list.
https://user-images.githubusercontent.com/467098/163397428-d8d7aeb7-97b8-4b45-a7d1-e9ac7a4342f9.mp4 …
> fix: [IABT-1371] Make the loading indicator more visible while scrolling the message list

- ts/screens/messages/paginated/MessageRouterScreen.tsx
- ts/screens/messages/paginated/__tests__/MessageRouterScreen.test.tsx
Is a service is not available in the message details view, fetch it.
- check against the service in the Router screen
- fetch the service if needed
Cannot share a screencast because I've tested it against my personal account in production.
Instructions:
1. open a message from a local service (in my case: _Anagrafe_)
2. tap on the service's link in the bottom of the message
3. services' card will open (_this_ is the fix)
> fix: [IABT-1369] Check against service when entering the message detail view

- ts/features/zendesk/components/ZendeskSupportComponent.tsx
- ts/features/zendesk/components/__tests__/ZendeskSupportComponent.test.tsx
- ts/features/zendesk/screens/ZendeskAskPermissions.tsx
- ts/features/zendesk/screens/__tests__/ZendeskAskPermissions.test.tsx
This PR fixes the bug that makes the app crash on press the support button on Android.
To fix the bug the commit `d9b4bed: "chore: [IA-778] Move zendesk user identify after ask permission (#3899)"` is been reverted.
- Reverted the commit `d9b4bed`
https://user-images.githubusercontent.com/11773070/163956882-aff14414-f5b7-4555-9b6e-fd5e754e652e.mp4
Try to press the support button (`?`) on an Android physical device both as an anonymous user and as authenticated one.
[IA-778]: https://pagopa.atlassian.net/browse/IA-778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [IA-829] Fix crash on press the support button on Android

- ts/components/messages/paginated/MessageList/Item.tsx
- ts/components/messages/paginated/MessageList/helpers.tsx
- ts/components/messages/paginated/MessagesArchive.tsx
- ts/components/messages/paginated/MessagesInbox.tsx
There's an issue in the current implementation that causes a rendering of the entire message list even if not needed (caused by the callback used for selecting messages). This PR fixes it.
- Wrap `onPressItem` with `useCallback` in order to avoid re-rendering of message list items.
> fix: [IA-830] Fix performance issue when rendering new message pages

- ts/sagas/startup/completeOnboardingSaga.ts
- ts/screens/onboarding/__tests__/OnboardingCompletedScreen.test.tsx
The new navigation library needs the full navigation path for a given screen, unless you're in the same navigator of the destination. This branch fixes this for the "thank you" screen at the end of the onboarding.
- Use `CommonActions.navigate` instead of `NavigationActions.navigate`;
Logout, then login again and verify that the "thank you" screen is shown and dismissed when tapping on the CTA.
> fix: [IA-856] Onboarding cannot be completed after a logout

- ts/features/bonus/cdc/components/CdcServiceCTA.tsx
This PR adds the navigation to the first screen of the bonus request flow when the CTA button is pressed.
- Added the navigation action when the activate bonus button is pressed
https://user-images.githubusercontent.com/11773070/168294599-4ac932da-46a3-4e91-ab9c-cb9b16ee9838.mp4
After enabling the local and the remote feature flag, enter the `Carta della Cultura` service details and press the `Activate card` button.
> chore(Carta della cultura): [AP-26] Update cdc service CTA action

- assets/CdcSwagger.yml
- ts/features/bonus/cdc/components/CdcServiceCTA.tsx
- ts/features/bonus/cdc/components/__test__/CdcServiceCTA.test.ts
- ts/features/bonus/cdc/screens/CdcBonusRequestSelectYear.tsx
- ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectYear.test.ts
- ts/features/bonus/cdc/store/reducers/__test__/cdcBonusRequest.test.ts
- ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
This PR updates the swagger of the `Carta della cultura`
- Fix typo in `StatoBeneficiario` -> `ATTIVABILE`
- Remove `annoRiferimento` from `RichiestaCartaErrata`
Generate the type and check that all works fine
> chore(Carta della cultura): [AP-33] Update cdc swagger

- .circleci/config.yml
This PR is going to enable the dev-server output stream in the CI logs during the end-to-end tests.
- Used `&>` instead of `>`
🦄
> chore: [IAI-202] Save the dev-server output stream in the CI logs

- android/app/build.gradle
This pr fixes the crash on Android due to different `okhttp3` versions, triggered by the update of `react-native`. This is just a temporary fix, the final solution should be implemented in https://pagopa.atlassian.net/browse/IAI-200 or the next time that we are going to upgrade react-native we will have the same problem.
- Updated `android/app/build.gradle`, forcing the same `okhttp3` version required by `react-native`.
- Build the app on Android in production mode -> access & run
> fix: [IAI-199] Crash `Java.lang.NoSuchMethodError` for `okhttp3`

- ts/components/PinCreationForm.tsx
This PR is going to improve the accessibility of the Pin Creation screen (in both the onboarding and the profile).
https://user-images.githubusercontent.com/5963683/171025501-cbe9ab4d-d2ad-4355-9790-82eb187c1f9b.mov
- Added accessibility label for the two fields
- Managed the errors inside the accessibility labels instead of using different text elements
- Added the `done` return key in the keyboard
- **Bonus:** Disabled the paste behaviour on the fields
Using the Voice Over in the pin creation screen during the onboarding or in the profile it should be possible to correctly navigate the various fields.
> chore: [IA-873] Improve the new Pin Screen's a11y

- ts/components/core/IOBadge.tsx
- ts/components/core/typography/LabelSmall.tsx
- ts/screens/showroom/core/TypographyShowRoom.tsx
This pr adds some missing styles to `IOBadge`, in order to facilitate its use in place of `native-base Badge`.
- Add missing colors to `IOBadge`
- Change left & right padding to `8`
- Add border (when required)
- Added the `IOBadge` section in the Showroom
👀
> chore: [IAI-206] Add missing styles to `IOBadge`

- ts/components/WebviewComponent.tsx
- ts/components/__tests__/__snapshots__/WebviewComponent.test.tsx.snap
This PR aims to fix the issue for CGN landing page webview that automatically opens the full-screen media player on iOS devices.
Go to CGN Landing Page Playground under profile/debug section and open https://www.sportesalute.eu/ as a test
> chore(Carta Giovani Nazionale): [IOACGN-78] Fixes landing page to open automatically media playback

- scripts/check_urls/check_urls.py
These changes aim to improve the exclusion of those files where is not interesting to check if they contain URLs and eventually test them
> chore: Improve `check_urls` files exclusion

- ts/features/uaDonations/screens/UAWebViewScreen.tsx
- ts/urls.ts
This pr changes the way to donate on iOS. Now, when tapping on the UABanner or a message CTA a new Safari browser pointing to `https://checkout.pagopa.it/dona` will be opened.
Tap on banner:
https://user-images.githubusercontent.com/26501317/173864481-72229674-ce30-4ff1-8b60-4eff850e2f51.mov
Tap on CTA:
https://user-images.githubusercontent.com/26501317/173864561-ee1ece47-413f-42ed-8a16-0921f87af436.mov
- Added `checkoutUADonationsUrl`
- Changed the mount logic for `iOS`
- On iOS: Tap on the Donation banner or add a CTA with `ioit://UADONATION_ROUTES_WEBVIEW?urlToLoad=https://assets.cdn.io.italia.it/html/donate.html`. Tapping on these two items should open Safari.
- On Android should works as always
> chore: [IA-886] Change UADonations on iOS

- .circleci/config.yml
- scripts/pagopa_api_check.sh
This pr changes the behaviour of the `pagopa_specs_diff`, in order to send only a slack message if the UAT and PROD specs are different, avoiding the failure of the job.
> chore: [IAI-209] The `pagopa_specs_diff` job must not fail if the UAT and PROD specs are different

- ts/features/bonus/cdc/screens/CdcBonusRequestSelectResidence.tsx
- ts/features/bonus/cdc/screens/CdcBonusRequestSelectYear.tsx
- ts/features/bonus/cdc/utils/__tests__/bonusRequest.test.ts
- ts/features/bonus/cdc/utils/bonusRequest.ts
This PR fixes the bug that let the `CdcBonusRequestSelectResidence` screen shows the selection of residence items not sorted by year.
- Added the `compareSelectedBonusByYear` function.
- Sorted the elements shown both in `CdcBonusRequestSelectResidence` and in `CdcBonusRequestSelectYear` screens.
**Before**
https://user-images.githubusercontent.com/11773070/174306399-e3c0b946-4d68-4f5d-8c65-d776b87c31b3.mp4
**After**
https://user-images.githubusercontent.com/11773070/174306252-def09b57-83d5-46bc-8643-76de772196b8.mp4
The test suite is provided.
Request the Carta della cultura and try to select in the `CdcBonusRequestSelectYear` screens the years in a random order. Checks in the `CdcBonusRequestSelectResidence` that the items are sorted ascending by year
> [AP-39] Fix wrong order of the bonus in the select residence screen

- .circleci/config.yml
- scripts/ts/checkOutdatedDependencies/checkOutdatedDependencies.ts
This pr fixes the execution of the `checkOutdatedDependencies` script, removing the `convertUnknownToError` import. Since the script is executed with `ts-node` in isolation mode, we don't have access to the app code.
> fix: [IAI-212] Outdated libraries script doesn't run

- locales/en/index.yml
- locales/it/index.yml
A couple of strings were made clearer for users to understand better requirements and errors while inserting the card holder name of a card they're onboarding in their IO wallet.
> chore: [IA-909] Copy changes to the card holder base + error

- ts/config.ts
This PR is going to update the `tosVersion` config to `4.0` in order to forcefully show the ToS screen to the user.
- Bumped `tosVersion` to `4.0`
The ToS screen should be visible after opening the app.
> chore: [IA-906] Update `tosVersion` to `4.0`

- ts/features/pn/components/PnMessageDetailsContent.tsx
This PR fixes a bug in the PN message details screen. When some strings are empty, the rendering fails with this error:
- Use `isStringNullyOrEmpty` for checking string value
> fix(Piattaforma Notifiche): [IAMVL-92] PN message details is blank if abstract is empty

- android/gradle.properties
- ios/ItaliaApp.xcodeproj/project.pbxproj
- ios/Podfile
- ios/Podfile.lock
- package.json
- yarn.lock
This PR makes the app build correctly on Mac with Apple silicon. Especially on iOS, the app for the simulator needs to be built using `x86_64` architecture.
- Update Flipper to 0.154 to fix a build error
- Remove `arm64` from supported architectures used for building the app for the simulator (this is needed because `vision-camera` doesn't support Apple silicon)
Make sure you have Rosetta installed, then build the app on both iOS and Android. This shouldn't change anything on Macs with Intel.
> chore: [IA-916] Fix build errors on Apple silicon

- ts/components/messages/paginated/MessageList/index.tsx
- ts/screens/messages/paginated/__tests__/MessagesHomeScreen.test.tsx
Right now the message list is fetched automatically with an app cold start. Then messages are only fetched manually by the user with the pull-to-refresh gesture. With this PR I want to add an automatic check for new messages when the list becomes focused (with a minimum interval of 1 minute to prevent pressure to the backend).
As a bonus, now the refresh gesture always causes a reload of the message list (either Inbox or Archive). Before, if there were messages, it asked just for new ones. In this way the manual refresh can be used to recover messages state in case the client goes out of sync with the backend. 
- Use `useActionOnFocus` to load new messages automatically (no more than once per minute)
- Always reload the messages list when manually refreshing
Run the app with a tool that …
> fix: [IA-838] Automatically check for new messages on focus

- ts/screens/messages/paginated/MessageRouterScreen.tsx
This PR fixes a glitch caused by dispatching multiple navigations from an `useEffect` hook (maybe introduced as a regression by #4080).
https://user-images.githubusercontent.com/467098/181591695-d527714a-68e3-4dc8-a168-3d6e3c0cdaf7.mp4
> fix: [IA-922] Prevent multiple navigations when opening a message

- ts/features/bonus/cdc/navigation/CdcStackNavigator.tsx
- ts/features/bonus/cgn/navigation/navigator.tsx
- ts/features/bonus/siciliaVola/navigation/navigator.tsx
- ts/features/euCovidCert/navigation/navigator.tsx
- ts/features/mvl/navigation/navigator.tsx
- ts/features/pn/navigation/navigator.tsx
- ts/features/zendesk/navigation/navigator.tsx
- ts/navigation/MessagesNavigator.tsx
- ts/navigation/ProfileNavigator.tsx
- ts/navigation/ServicesNavigator.tsx
- ts/utils/navigation.ts
This PR is going to disable the navigation gestures on Android due to a bug present on Android 9 and below causing various `ScrollView` around the app to not work properly.
<details>
<summary>Before</summary>
https://user-images.githubusercontent.com/5963683/182397049-572c0001-31a1-402a-8607-c3a8a01b95c5.mov 
</details>
<details>
<summary>After</summary>
https://user-images.githubusercontent.com/5963683/182397347-7863c685-0d1e-471b-8698-b004e7d5ff0c.mov 
</details>
- Created an `isGestureEnabled` flag
- Replaced all the `gestureEnabled: true` with the new `isGestureEnabled` flag
Using an emulator with Android 9 and below all the `ScrollView` should work properly (for example the Green Pass details or the CGN category list).
> fix: [IA-921] Disable navigation gestures on Android

- ts/screens/wallet/payment/components/TransactionSummary.tsx
This small PR modifies the payment notice number clipboard copy to prevent spaces.
> fix: [IABT-1381] Copy payment notice number to the clipboard without spaces

- ts/features/pn/components/PnMessageDetails.tsx
- ts/screens/wallet/payment/NewTransactionSummaryScreen.tsx
- ts/screens/wallet/payment/components/TransactionSummaryErrorDetails.tsx
- ts/utils/payment.ts
This PR fixes a bug for which payments with the `PPT_PAGAMENTO_DUPLICATO` status are not correctly reported as paid.
| Bug | Fix |
| - | - |
| ![Simulator Screen Shot - iPhone 13 - 2022-08-03 at 17 46 15](https://user-images.githubusercontent.com/467098/182652220-5583374c-6b9c-4e1e-8dfb-30e248e4457f.png) | ![Simulator Screen Shot - iPhone 13 - 2022-08-03 at 17 46 30](https://user-images.githubusercontent.com/467098/182652264-92472f05-b749-41c5-ac2d-a72334d5ac32.png) |
| ![Simulator Screen Shot - iPhone 13 - 2022-08-03 at 16 31 28](https://user-images.githubusercontent.com/467098/182652305-7ee3c63e-1c12-45be-b7a3-4b9786069e67.png) | ![Simulator Screen Shot - iPhone 13 - 2022-08-03 at 16 45 38](https://user-images.githubusercontent.com/467098/182652395-282230c3-6b45-45e8-a205-7ae45eb91ae8.pn …
> fix: [IABT-1382] Do not consider PPT_PAGAMENTO_DUPLICATO as error 

- ts/store/reducers/entities/messages/__tests__/allPaginated.test.ts
- ts/store/reducers/entities/messages/allPaginated.ts
There's a buggy implementation when upserting the message read state after opening it. One failing scenario is opening a message from a push notification that leaves the message in an unread state. This PR aims to fix it.
https://user-images.githubusercontent.com/467098/182607569-f41c5325-58e7-4b8a-b902-96a7a5335ff5.mp4
https://user-images.githubusercontent.com/467098/182608293-c6c8bd1e-1c9d-43a4-8f54-814d80ff5db9.mp4
- Added a failing test to reproduce the bug
- Fixed the bug 😊
Simulate a push notification with an unread message ID and tap on it. Go back to the inbox. The message should be marked as read.
> fix: [IA-827] Message is still shown as unread after opening it

- locales/en/index.yml
- locales/it/index.yml
- ts/features/messages/components/MessageAttachmentPreview.tsx
This PR updates the copy of the error message when attachment preview fails.
| Old | New |
| - | - |
| ![Simulator Screen Shot - iPhone 13 - 2022-08-22 at 17 08 23](https://user-images.githubusercontent.com/467098/185955439-a235dd73-f7c5-4683-a2ca-9bc00295f442.png) | ![Simulator Screen Shot - iPhone 13 - 2022-08-22 at 17 07 10](https://user-images.githubusercontent.com/467098/185955477-8a69af78-efab-4845-bf43-9eb443cf33c4.png) |
> feat: [IIP-63] Change PDF preview error copy

- locales/en/index.yml
- locales/it/index.yml
This PR updates the error message when an attachment download fails.
| Old | New |
| - | - |
| ![Simulator Screen Shot - iPhone 13 - 2022-09-12 at 15 03 19](https://user-images.githubusercontent.com/467098/189661175-900fadc4-0944-4aa6-9d89-2c7181699797.png) | ![Simulator Screen Shot - iPhone 13 - 2022-09-12 at 15 01 02](https://user-images.githubusercontent.com/467098/189661217-23c5daee-a9a6-453f-9cc1-760852fc29fb.png) |
> feat: [IIP-103] Fix error message when attachment download fails

- ts/features/messages/components/MessageAttachmentPreview.tsx
- ts/features/mvl/index.ts
- ts/features/mvl/saga/networking/downloadMvlAttachment.ts
- ts/features/mvl/saga/networking/handleGetMvlDetails.ts
- ts/features/mvl/screens/details/MvlDetailsScreen.tsx
- ts/features/mvl/screens/details/components/attachment/MvlAttachmentDownload.tsx
- ts/features/mvl/screens/details/components/attachment/MvlAttachmentPreview.tsx
- ts/features/mvl/screens/details/components/attachment/__test__/MvlAttachments.test.tsx
- ts/features/mvl/store/actions/downloads.ts
- ts/features/mvl/store/reducers/__test__/downloads.test.ts
- ts/features/mvl/store/reducers/downloads.ts
- ts/features/mvl/types/__mock__/mvlMock.ts
- ts/features/mvl/types/mvlData.ts
- ts/features/pn/components/PnMessageDetails.tsx
- ts/features/pn/screens/PnAttachmentPreview.tsx
- ts/features/pn/store/types/transformers.ts
Attachment IDs are not guaranteed to be unique per user. Instead they are unique per message. Until now attachments were cached in the app using their ID. This could cause a collision if two attachments use the same ID, even if they are contained in different messages.
With this PR we're changing how an attachment is indexed in app (using the both the message and the attachment ID).
- Added `messageId` property to the `MvlAttachment` type
- Changed the `MvlDownloads` type in order to use `messageId` as a key to group attachments
- Updated the `mvlDownloadsReducer` and the selector
- Added a migration to clear old stored downloads (if any)
- Updated screens in order to use the new selector
- Updated tests
Use the [IIP-18-add-pn-endpoints](https://github.com/pagopa/io-dev-api-server/tree/IIP …
> fix(Piattaforma Notifiche): [IAMVL-99] Attachment ID might not be unique per user

- ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
#3803 introduced a regression that made the service configuration not working as expected during the first onboarding. In particular tapping on the "manual configuration" has no effect. This PR fixes this behavior.
https://user-images.githubusercontent.com/467098/193542974-1cc3c628-7ad7-4f7b-af32-b17187b8dd13.mov
https://user-images.githubusercontent.com/467098/193543035-ed9dd29f-caca-4234-b6f2-4c82dffdf3d1.mov
- Added missing `manualConfigBottomSheet` to the view hierarchy of the screen
- Perform a logout
- Set `firstOnboarding` to `true` in the [dev server config](https://github.com/pagopa/io-dev-api-server/blob/02ea784cdf244759c9dd90cac42b60ad03491b58/src/config.ts#L63)
- Perform a login
- You should see the first onboarding flow
- Make sure you can select the manual service …
> fix: [IA-947] Manual configuration not selectable during first onboarding

- ts/screens/authentication/LandingScreen.tsx
This PR adds a specific event to analyze when the rooted devices dedicated modal has been shown.
> chore: [IOAPPCIT-6] Add event to track the Rooted device information modal

- ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts
Add test for initiative steps of the IDPay Onboarding machine
Just tests
yarn jest
> chore(IDPay): [IODPAY-37] Add tests for initiative steps

- android/build.gradle
Fix problem described [here](https://github.com/software-mansion/react-native-reanimated/issues/3743) with the solution proposed [here](https://github.com/facebook/react-native/issues/35210).
> fix(Platform): [IOAPPFD0-12] Fix Android bundling

- ts/features/idpay/onboarding/xstate/provider.tsx
- ts/hooks/useXStateMachine.tsx
To avoid the recreation os the xstate machine we use a custom hook that maintains the machine as Ref
- A generic useXStateMachine hook
- Change the provider to use the new hook
The warning message stating that the machine has been changed do not occurs anymore
> chore(IDPay): [IODPAY-51] Avoid XState machine recreation on provider rerendering

- ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
This PR changes how to determine if an IDPay initiative needs configuration based on its status.
- Changed `UNSUBSCRIBED` to `NOT_REFUNDABLE` 
Open the details screen of an initiative and check if it requires a configuration whit `NOT_REFUNDABLE` status
> fix(IDPay): Change IDPay initiative configuration status check

- ts/components/wallet/PaymentMethodsList.tsx
This PR fixes the missing separator between the second-last and last element in the list.
| - | - |
| <img src="https://user-images.githubusercontent.com/1255491/204485319-656327da-3fa6-4e5d-804a-a2cfbdc10b8e.png" width=350 /> | <img src="https://user-images.githubusercontent.com/1255491/204485372-76806fad-38a5-44ac-9b06-c0343f0656b5.png" width=350 />
1. Go to _Wallet_
2. Tap on _**Aggiungi**_ (or **_Add_**) in the top right area of the screen
3. Tap on **_Metodo di pagamento_** (or **_Payment method_**)
The bug has been reported by @fabriziofff
> fix: [IABT-1338] Fix missing separator in the `Add Payment Method` screen

- ts/features/bonus/bpd/components/optInPaymentMethods/BpdOptInPaymentMethodsContainer.tsx
This PR fixes the logic that caused a retry loop on loading the optin status for BPD
> fix: [IOAPPPEB-12] Avoid reload loop on Optin failure

- ts/components/messages/paginated/hooks/useMessageOpening.tsx
- ts/screens/messages/paginated/MessagesArchiveScreen.tsx
- ts/screens/messages/paginated/MessagesHomeScreen.tsx
- ts/screens/messages/paginated/MessagesInboxScreen.tsx
This PR fixes the bottom sheet that does not open when selecting a PN message
- Added the bottom Sheet component reference to both `MessagesArchiveScreen.tsx` and `MessagesInboxScreen.tsx`
- Removed a redundant `map` call on the `bottomSheets` instance in `MessagesHomeScreen.tsx`
Enable `includePn` in the [dev server config](https://github.com/pagopa/io-dev-api-server/blob/master/src/config.ts#L122) and increment `pnCount` in the [dev server config](https://github.com/pagopa/io-dev-api-server/blob/master/src/config.ts#L78). 
Start the application and select a PN message. A bottom sheet should open (try to close it and to also navigate to the message).
Repeat the same test for a normal message (in this case, the bottom sheet should not open)
> fix: [IOAPPCOM-35] Fix bottom sheets not opening (on a PN message)

- ts/components/screens/LogoutScreen.tsx
- ts/features/messages/saga/attachments.ts
- ts/sagas/__tests__/notifications.test.ts
- ts/sagas/startup/__tests__/watchLogoutSaga.test.ts
- ts/sagas/startup/watchLogoutSaga.ts
- ts/screens/profile/RemoveAccountSuccessScreen.tsx
- ts/store/actions/authentication.ts
- ts/store/reducers/__tests__/persistedPreferences.test.ts
- ts/store/reducers/identification.ts
- ts/store/reducers/index.ts
- ts/store/reducers/wallet/wallets.ts
This PR fixes the in-memory state not being persisted after logout/login with the same user (with respect to the linked issue, the "Paid" badge not showing up if the app is killed after logout and restarted, logging in with the same user).
It also removes the `keepUserData` parameter in the logout actions.
Detailed explanation of the issue [here](https://pagopa.atlassian.net/wiki/spaces/IOAPP/pages/605454598/IOAPPCOM-40+Out-of-synch+between+in-memory+and+persisted+state).
- Edited main reducer (`ts/store/reducers/index.ts`) in order to include the added `_persist` property (from redux-persist) when the state is recreated after a logout (for any reducer that includes a persisting configuration);
- Parameter `keepUserData` has been removed from Success and Failure logout actions.
In order …
> feat: [IOAPPCOM-40] Fix synchronization between in-memory state and stored one (after logout and login)

- ts/components/IdpsGrid.tsx
- ts/screens/authentication/IdpSelectionScreen.tsx
This PR removes a nesting between a ScrollView and a FlatList on the Idp selection screen (which caused a silent error)
- `Content` component (native base) has been replaced with a `View` (react native) in `ts/screens/authentication/IdpSelectionScreen.tsc` and all the scrolling has been delegated to the `FlatList` component.
- To preserve the same UI and UX, all previous views below the `IdpsGrid` have been grouped in a Flat List Footer (and Header) given (with styles) to the `IdpsGrid` component
Start the application from scratch and check that the UI and UX of the Idp selection view is the same as before on different devices (see attached screenshots): check on different display size like 3.6", 4.0", 5.0"+ and/or on different OSs (_e.g._, iPhone 6s and iPhone 13/14, Nexus 5, ...). 
Make …
> chore: [IOAPPFD0-21] Remove nesting between ScrollView and FlatList on Idp selection screen

- ts/components/services/ServiceMetadata/InformationRow.tsx
- ts/components/services/ServiceMetadata/__tests__/__snapshots__/InformationRow.test.tsx.snap
- ts/components/services/ServiceMetadata/index.tsx
- ts/screens/services/ServiceDetailsScreen.tsx
This PR improves the text behaviour in the ServiceDetail's metadata section, removing the width limit set to 50%, applied to the keys/values. It doesn't change the default single line behaviour.
| - | - |
| <img src="https://user-images.githubusercontent.com/1255491/211326019-799fd4b8-513a-4910-a0ff-9e9243ff84f7.png" width="350" /> | <img src="https://user-images.githubusercontent.com/1255491/211326072-1196454a-9ad7-4aac-94d3-9cffeaee8e28.png" width="350" />
- Remove flex properties that introduced that width limit
- Decrease the vertical margin because it was huge
> chore: [IAI-259] Remove width limit applied to the text in the Services' metadata

- ts/features/idpay/initiative/configuration/components/InstrumentEnrollmentSwitch.tsx
- ts/features/idpay/initiative/configuration/screens/InstrumentsEnrollmentScreen.tsx
- ts/features/idpay/initiative/configuration/xstate/events.ts
- ts/features/idpay/initiative/configuration/xstate/machine.ts
- ts/features/idpay/initiative/configuration/xstate/selectors.ts
- ts/features/idpay/initiative/configuration/xstate/services.ts
This PR adds the ability to remove enrolled payment instruments from an initiative.
https://user-images.githubusercontent.com/6160324/211323521-eb52abc3-ee89-49f9-9bb4-48ca579f95ca.mp4
- Added events and handlers to the XState machine
- Refactoring of `InstrumentEnrollmentSwitch` in order to support the cancel method
Open the details of an initiative and go to the payment instrument configuration screen. Try to add and remove instruments using the switches in the list.
> feat(IDPay): [IODPAY-74] Add ability to remove payment instruments from an IDPay initiative

- ts/utils/hooks/bottomSheet.tsx
This PR adds the ability to catch dismiss event on an bottom sheet presented by the `useIOBottomSheetModal` hook.
- Added optional `onDismiss` parameter to `useIOBottomSheetModal`
Pass an handler to a bottom sheet and check if it is triggered when the bottom sheet closes
> chore: [IAI-262] Add `onDismiss` handler parameter to `useIOBottomSheetModal`

- ts/features/fci/components/__tests__/SuccessComponent.test.tsx
- ts/features/fci/utils/dates.ts
This PR adds `Math.round` to `daysBetweenDate` to avoid fails during test in ci related to rounding-off machine precision.
- Update `daysBetweenDate`
Run related test
> fix(Firma con IO): [SFEQS-1354] Add rounding to daysBetweenDate

- ts/screens/authentication/LandingScreen.tsx
Added the right role to the buttons
- ts/screens/authentication/LandingScreen.tsx: added the right role and label to the buttons.
iOS:
Run app, VoiceOver, disable CIE support and verify if the login buttons are read properly;
Run app, VoiceOver, enable CIE support and verify if the login buttons are read properly;
Android:
Run app, TalkBack, disable CIE support and verify if the login buttons are read properly;
Run app, TalkBack, enable CIE support and verify if the login buttons are read properly;
> feat: [IA-362,IA-367] -- Accessibility doesn't recognise CIE/SPID login button

- ts/components/Pinpad/index.tsx
Added accessibility info to the component to fix the problem.
- ts/components/Pinpad/index.tsx: added accessibility info to the component 
Run app, enable VoiceOver (or TalkBack) and verify if the button is properly read.
> feat: [IA-362,IA-369] Accessibility: unlock code forgotten not recognised as button

- ts/components/core/selection/RemoteSwitch.tsx
- ts/components/core/selection/__test__/__snapshots__/RemoteSwitch.test.tsx.snap
- ts/components/services/ContactPreferencesToggles/PreferenceToggleRow.tsx
- ts/components/services/ContactPreferencesToggles/__test__/__snapshots__/PreferenceToggleRow.test.tsx.snap
- ts/screens/profile/NotificationsPreferencesScreen.tsx
Added accessibility support to switch elements.
- ts/components/core/selection/RemoteSwitch.tsx: added accessibility support to the component.
- ts/screens/profile/NotificationsPreferencesScreen.tsx: added accessibility label to RemoteSwitch(s).
- ts/components/services/ContactPreferencesToggles/PreferenceToggleRow.tsx: added accessibility support to Switch component.
Run app, enable VoiceOver (or TalkBack) and verify wether, by highlighting a switch in profile settings or a switch in a specific service settings, the accessibilityLabel is read.
> feat: [IA-362,IA-389,IA-344] Added accessibility support to switch components.

- ts/components/IdpsGrid.tsx
This PR fixes the issue present on Android about IdP logo caching. 
When an IdP logo is changed — its URI remains the same and on Android — the image never changes but remains the first ever downloaded.
This is a known [RN issue](https://github.com/facebook/react-native/issues/12606).
- ts/components/IdpsGrid.tsx: Add a timestamp query param on Android on IdP URI to simulate a TTL of 24h.
Run the app without this fix against the dev server, and after the first IdPs Selection Screen render, change an IdP logo and restart the server. Load the IdP Selection Screen again and see that the logo remains the same. Apply this fix, run the app, and check that the logo has changed.
> fix: [IABT-1389] On Android IdP logo never refresh when it's changed

- ts/components/core/variables/IOColors.ts
- ts/features/design-system/core/DSColors.tsx
This PR adds the new color palette, the foundation of the new visual language that will be gradually introduced over the next few months.
https://user-images.githubusercontent.com/1255491/218756279-3ea4ef6e-d07e-444e-9589-8ad77214f3e0.mp4
- Add the new color values to the existing `IOColors` object to avoid disruption on the current components
- Separate the different color values into different groups: `IOColorsLegacy`, `IOColorsNeutral`, `IOColorsTints`, `IOColorsStatus`, `IOColorsExtra` (the mentioned names might change over the time)
- Change `DSColors` grid from two columns to single one.
Go to the `Profile → Design System → Colors`
> chore: [IOAPPFD0-33] Add the new color palette

- locales/en/index.yml
- locales/it/index.yml
This PR changes the italian and english translations of the message that is displayed when the download of a message attachment fails.
- locales/it/index.yml has the new italian translation
- locales/en/index.yml has the new english translations
Simulate the download failure using the dev-server (return any http status code in range [400-599] but 415) and check that the message is correctly displayed in both italian and english languages
> [IGB-87] New feedback message displayed on a message attachment download failure

- ts/screens/authentication/IdpLoginScreen.tsx
This PR fixes the missing PosteID rapid access missing choice on IdP credential screen
| ❌ | ✅ | 
| - | - |
| <img src="https://user-images.githubusercontent.com/16268789/219661773-dff9d091-f05d-4cd4-b763-c38a9d2c2069.PNG" width="150" /> | <img src="https://user-images.githubusercontent.com/16268789/219661780-a566307a-e9fe-4423-9d46-efcb3b3ff9b4.PNG" width="150" /> |
> fix: [IOAPPCIT-46] Fixes the missing PosteID rapid access missing choice on IdP credential screen

- ts/features/idpay/onboarding/screens/BoolValuePrerequisitesScreen.tsx
- ts/features/idpay/onboarding/xstate/machine.ts
- ts/features/idpay/onboarding/xstate/selectors.ts
This PR adds the ability to toggle (switch on and switch off) the self declarations in the IDPay onboarding flow.
https://user-images.githubusercontent.com/6160324/219682847-fbf07304-18e2-4812-893b-44a3171533a9.mp4
- Added `TOGGLE_BOOL_CRITERIA` event to the onboarding machine to mutate self declarations in the context
- Added selector to know if all the bool self declaration were set to true and the "continue" button should be enabled.
- Start the onboarding for an IDPay initiative. The initiative should have a list of bool self declarations
- In the self declaration screen, try to switch on and off the self declaration toggles.
- Verify that the continue button is disabled if any of the toggles is off.
> fix(IDPay): [IODPAY-104,IODPAY-105] Fix IDPay onboarding self declaration toggles

- ts/features/lollipop/hooks/useLollipopLoginSource.tsx
- ts/features/lollipop/utils/login.ts
- ts/sagas/startup/generateCryptoKeyPair.ts
- ts/screens/authentication/IdpLoginScreen.tsx
- ts/utils/analytics.ts
- ts/utils/crypto.ts
This PR adds Lollipop failure mixpanel events (described [here](https://docs.google.com/spreadsheets/d/1bXNRcTDKU-5l2RqCcwSbT7Y1M9QQTWtS_f-3-AIqSYk/edit#gid=1624395933))
Approved by the Privacy - [ticket](https://pagopa.atlassian.net/browse/LLK-47)
Following trackings have been added
* `LOLLIPOP_IDP_LOGIN_FAILURE { reason: string }` - Sent when there is a failure in the lollipop spid login.
Reason is one of the following:
- "Missing key tag while trying to login with lollipop"
- "Missing ID parameter in samlp:AuthnRequest"
- "Mismatch between local and remote ID parameter content"
- "Unable to convert saml request from xml to json"
refactored `taskRegenerateKey` to use fp-ts instead of promises
Check that the events are received by mixpanel
> chore: [LLK-35] Add mixpanel events for Lollipop failure

- locales/en/index.yml
- locales/it/index.yml
- ts/features/idpay/initiative/details/components/InitiativeCardComponent.tsx
- ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
This PR fixes display issues in the initiative details card.
- Refactoring of the InitiativeCardComponent:
- Changed props to only one prop  `initiative: InitiativeDTO`
- I18n refactoring with params
- The amount to be repaid now displays correct amount in the initiative details card
- Navigate to the initiative details screen.
- Check if the amount to be repaid in the card displays the correct value. The correct value should be `accrued - refunded` where `accrued` is the total amount accumulated since the start of the initiative and `refunded` is the amount already refunded to the enrolled IBAN.
> fix(IDPay): [IODPAY-157] Add correct amount to initiative card

- ts/features/idpay/initiative/configuration/xstate/machine.ts
Set a proper pot state when the request is in progress
- Set a proper pot state when the request is in progress
Try to enable an instrument for an initiative and check if the spinner appears
> fix(IDPay): [IODPAY-159] Show loader when enrollment request in progress

- ts/features/zendesk/components/ZendeskSupportComponent.tsx
- ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
This PR fixes the text displayed inside the box and adds space under the buttons. 
| Before  | After  | 
| ------------- | ------------- | 
| ![android-before](https://user-images.githubusercontent.com/29163287/221159900-134e6c0c-6672-4345-aec7-b7ee447edcd0.png)  | ![android-after](https://user-images.githubusercontent.com/29163287/221159929-72e80813-a9ef-47ed-a3fa-fdf3f4b97411.png)  |
- updated `ZendeskSupportComponent.tsx`
- updated `ZendeskSupportHelpCenter.tsx`
- Start dev server
- Perform a login
- Browse to message list
- Open contextual help
> fix: [IABT-1435] Fix unwrap text info box

- ts/features/idpay/common/navigation/linking.ts
- ts/features/idpay/onboarding/navigation/navigator.tsx
- ts/navigation/AppStackNavigator.tsx
This PR enables navigation to an IDPay initiative details screen from message CTAs.
https://user-images.githubusercontent.com/6160324/221604205-9986acd9-d1b6-40a1-ad74-8a5309f08f7e.mp4
- Added linking options for `ioit://idpay/initiative/:initiativeId`
- Open a message with a CTA with the implemented route 
- Click on the CTA and see if the app navigates to the initiative details screen.
> [IODPAY-161] Navigate to initiative details from message CTA 

- package.json
- ts/features/design-system/core/DSListItems.tsx
- ts/features/idpay/initiative/details/components/TimelineOperationListItem.tsx
- ts/features/idpay/initiative/details/store/__test__/store.test.ts
Updated ListItem to follow design
- the number in `ListItem`'s right now shows `accrued` instead of `amount`
- updated definitions to correctly serialize data
navigate to an initiative's detail page, possibly also to the timeline page and make sure the `ListItem`s correctly display the accrued amount only in the right section
> fix(IDPay): [IODPAY-160] Update ListItem import to follow design

- ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
This PR adds an item separator component to the bottom of the qtsp tos screen.
- Update `FciQtspClausesScreen`
Using `io-dev-server-api` try a signing flow, the qtsp clauses screen should have an item separator for all items
> fix(Firma con IO): [SFEQS-1317] Add item separator to tos screen

- ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
This PR fixes an issue in displaying the correct information in the PDND screen.
|--------|-------|
|   <img src="https://user-images.githubusercontent.com/6160324/221874877-30e64f4c-c0cc-4028-b3ab-30da4c443544.png" width="200" />     |    <img src="https://user-images.githubusercontent.com/6160324/221874882-fdf5a08c-622d-4a3c-8c4b-1ffaf5e7f14a.png" width="200" />   |
- `ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx`
- Start an initiative onboarding
- Check if the data is correctly displayed (label and value) in the PDND prerequisites step,
> fix(IDPay): [IODPAY-133] Fix PDND prerequisites screen list item UI

- ts/sagas/startup/__tests__/checkProfileEmailSaga.test.tsx
- ts/screens/authentication/IdpLoginScreen.tsx
🤚 This PR depends on [137](https://github.com/pagopa/io-spid-commons/pull/137) 🤚
This PR removes the user-agent that was sent during Spid login and fixes an unrelated typo in tests
- `ts/screens/authentication/IdpLoginScreen.tsx`: removed the code that was generating and setting the user agent
- `ts/sagas/startup/__tests__/checkProfileEmailSaga.test.tsx`: fixed a typo in the parameter of the `describe` method invocation
- Test that both LolliPoP Spid login and non-LolliPop Spid login work (using the LOLLIPOP property in the `.env` file). If you're using the dev-server, make sure that you are on the branch with no user-agent checking
> chore: [LLK-55] Removed user-agent during Spid login

- package.json
- ts/features/idpay/initiative/details/components/TimelineOperationListItem.tsx
In the operations timeline use the amount on operation of PAID_REFUND type.
Use the amount instead of the accrued value on operation of type PAID_REFUND
Check the timeline with an operation of PAID_REFUND type.
> chore(IDPay): [IODPAY-167] Show amount on PAID_REFUND operation

- .env.local
- .env.production
Change the timeout from 30s to 120s.
Update the backgroundActivityTimeout from 30s to 120s. 
Put the app in background for less than 120s and check that you are not required to insert the pin/biometric.
> fix: [IABT-1436] Change the background activity timeout

- ts/features/fci/components/DocumentViewer.tsx
This PR fix the copy of the footer in `DocumentPreview` component. So the copy is the same of the message with attachments.
| iOS  |Android |
| <img width="150" alt="Screenshot 2023-03-07 at 10 44 20" src="https://user-images.githubusercontent.com/49342144/223436270-38a50e2f-ec12-4836-953e-18a50a3c9456.png"> | <img width="150" alt="Screenshot 2023-03-07 at 10 44 20" src="https://user-images.githubusercontent.com/49342144/223436341-ba083725-6d99-4968-8a2b-495faa89bc5e.png"> |
- Update `DocumentPreview`
Start a signing flow using io-dev-server or if not merged this [branch](https://github.com/pagopa/io-dev-api-server/pull/190) and on the provider page try to open a linked document.
> fix(Firma con IO): [SFEQS-1489] Update footer on document preview component with right label

- ts/features/fci/utils/signature.ts
This PR fixes custom signature creation by checking attribute string for empty state.
- Update `getCustomSignature`
> fix(Firma con IO): [SFEQS-1437] Fix empty attributes when document to sign not has signature fields or coordinates

- ts/components/core/variables/IOStyles.ts
- ts/components/ui/ButtonOutline.tsx
- ts/components/ui/ButtonSolid.tsx
- ts/features/design-system/core/DSButtons.tsx
This PR removes the `dimensionsFullWidth` class with relative style properties, as they are redundant. There's no need to specify the `flex: 1` property because React Native makes the button fill the entire horizontal space by default.
When developing specific layouts, these additional properties caused some annoyance.
- Remove `dimensionsFullWidth` from `ButtonSolid` and `ButtonOutline` components
Go to the `Profile → Design System → Buttons`
> fix: [IOAPPFD0-47] Remove extra properties from new buttons

- scripts/api-config.json
This pull request updates the `api-config.js` file utilized in the E2E tests by assigning a value of `0` to `archivedMessageCount`. This is to prevent possible conflicts between the E2E tests and the selected message.
To perform the test, run the development server using this configuration, and verify that no message in the inbox is moved to the archived section.
> chore: [IOAPPFD0-48] Remove shuffled archived message from E2E tests

- ts/components/services/LocalServicesWebView.tsx
This PR implements a workaround for a potential crash that could occur when navigating out of a screen with a WebView on Android. It doesn't happen on iOS devices.
This is an [issue](https://github.com/react-native-webview/react-native-webview/issues/811#issuecomment-570813204) of possibly some versions of WebView as it doesn't always occur. 
- ts/components/services/LocalServicesWebView.tsx: Replaced the inline styling with a StyleSheet containing a conditional styling which applies an opacity of 0.99 for Android and the default one for iOS. 
1. Select "services" in the bottom tab navigator and then "Local" in the tab navigator;
2. Select "National" in the tab navigator and then select any available service.
> fix: [IOAPPFD0-50] Crash when navigating out of a WebView on Android

- ts/components/IdpsGrid.tsx
- ts/components/ui/MultiImage.tsx
- ts/utils/dates.ts
This PR implements a workaround for the aggressive ```Image``` component caching on Android which prevents the services logos from refreshing when changed.
The implemented workaround is the same as [this PR](https://github.com/pagopa/io-app/pull/4360). 
- ```ts/utils/dates.ts```: added the ```toAndroidCacheTimestamp``` function to return the locale formatted timestamp;
- ```ts/components/ui/MultiImage.tsx```: added a timestamp to the URI on Android by using ```toAndroidCacheTimestamp```. This component is used to render services logos;
- ```ts/components/IdpsGrid.tsx```: added a timestamp to the URI on Android by using ```toAndroidCacheTimestamp```.
Using the dev server: 
1. Open any national service detail screen in the app;
2. Replace the service logo at …
> fix: [IABT-1447] Services logos not updating on Android devices

- ts/components/IdpsGrid.tsx
- ts/components/ui/MultiImage.tsx
- ts/utils/dates.ts
This PR  reverts pagopa/io-app#4458 because we have found we didn't manage `undefined` values the right way.
> fix: [IABT-1447] Revert: services logos not updating on Android devices

- locales/en/index.yml
- locales/it/index.yml
- ts/features/idpay/initiative/details/components/InitiativeSettingsComponent.tsx
added missing i18n and rendering logic
see description
opening up an initiative's details while having a single method connected should now render "1 method" instead of "1 methods"
> fix(IDPay): [IODPAY-183] Singular for payment methods i18n in initiative details page 

- ts/features/lollipop/__tests__/login.test.ts
- ts/features/lollipop/saga/index.ts
- ts/store/reducers/authentication.ts
This PR fixes the test login. After the addition of the `assertionRef`, it's now impossible to successfully login with a test account.
- ts/store/reducers/authentication.ts: adds type guards and selectors to check the logged-out state.
- ts/features/lollipop/saga/index.ts: disables `assertionRef` check if we are logged-in with a test account.
You should succeed while logging in with a test login.
> fix: [LLK-71] Fix test login

- locales/en/index.yml
- locales/it/index.yml
- ts/features/fci/hooks/useFciCheckService.tsx
- ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
- ts/features/fci/store/reducers/fciMetadata.ts
This PR adds a BS and a check on the inbox status of the service preference giving the serviceId of FCI.
https://user-images.githubusercontent.com/49342144/229453496-9757b75c-b873-4ce6-966b-724c3f199a64.mp4
- Add check service bs
- Update `FciQtspClausesScreen`
1.  start `io-dev-api-server`
2. go to the service panel -> Firma con IO and disable "Contattarti in app"
3. tap on a `WAIT_FOR_SIGNATURE` message and start a signing flow
4. on the QTSP clauses screen try to tap to continue and should appear a BS
NOTE: tapping on "Attiva ora" or "Non ora" are a non blocking CTA. The signing flow should continue in any case. The BS gives to the user the availability to activate "Contattarti in app" without go in the service preference screen.
> feat(Firma con IO): [SFEQS-1044] Add bottom sheet to check/activate service preferences

- ts/__e2e__/payment.e2e.ts
After merging #4480, e2e tests fail for the manual payment test. 
- Updates the testID for the `EntityCode` mask.
- Run the payments E2E tests locally by following [these](https://github.com/pagopa/io-app/blob/master/TESTING_E2E.md) instructions. Tests should succeded.
> chore: [IOAPPFD0-79] update e2e test for manual payments

- ts/utils/analytics.ts
This PR fixes an issue which makes the app track a `KEY_CHAIN_GET_GENERIC_PASSWORD_FAILURE`, introduced in [this PR](https://github.com/pagopa/io-app/pull/4494), even when there's no error at all. 
We couldn't reproduce the error so we weren't sure wether or not the stack trace was being capture. Given that we know for sure that the tracking event is indeed working and the stack track is properly captured, we can now narrow the tracking function only when the `reason` parameter is defined.
- ts/utils/analytics.ts: Checks if the `reason` parameter is defined before sending the event to Mixpanel.
- Start the app and the error shouldn't be tracked when you're logging in or reopening the app;
- In order to "force" an error, you can refer to [this …
> fix: [IOAPPFD0-88] Keychain error event tracked without reason parameter

- ts/components/messages/MessageDetail/Content.tsx
- ts/components/messages/MessageDetail/__tests__/__snapshots__/Content.test.tsx.snap
This PR adds text wrapping to the sender of a message in the details screen. Closes #4563.
- ts/components/messages/MessageDetail/Content.tsx: Adds text wrapping to the sender details. Also moves the trailing space to the `Body` content to avoid issues with the `Label` wrapping.
<details>
<summary>PROD</summary>
| ![IMG_0003 2](https://user-images.githubusercontent.com/12371664/234527155-4a5082c4-6084-441d-b989-cb93e482b4dc.PNG) | ![IMG_0002](https://user-images.githubusercontent.com/12371664/234527260-19fb5fae-c8e3-4b7c-b348-283b815f547c.PNG)  | 
</details>
<details>
<summary>DEV</summary>
| ![Simulator Screen Shot - iPhone 13 - 2023-04-26 at 10 59 44](https://user-images.githubusercontent.com/12371664/234526283 …
> fix: [IOAPPFD0-91] Message sender details not wrapping

- locales/en/index.yml
- locales/it/index.yml
- ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
added separate I18n keys for an initiative's details' lastUpdated field
- new i18n keys
- updated initiative details to follow
navigate to an initiative's details page and check that the small text under the card displays the correct text
> fix(IDPay): [IODPAY-192] Wrong copy in initiativeDetails' "lastUpdated"

- ts/navigation/NotAuthenticatedStackNavigator.tsx
This PR updates `NotAuthenticatedStackNavigator` adding `ZendeskStackNavigator`. It should possibile to open contextual help when user is not authenticated tap on question mark.
- Update `NotAuthenticatedStackNavigator`
Using io-dev-api-server in the `AUTHENTICATION_LANDING ` screen after tap on question mark a contextual help should appear.
> fix: [IABT-1473] Fix contextual help when user is not authenticated

- ts/components/messages/MessageDetail/__tests__/__snapshots__/MedicalPrescriptionDueDateBar.test.tsx.snap
- ts/components/messages/MessageDetail/common/CalendarEventButton.tsx
- ts/components/messages/MessageList/Item.tsx
- ts/components/messages/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
This PR fixes the UI regression of the `Paid` badge in the message list, caused by the introduction of the new `IOBadge` component (see https://github.com/pagopa/io-app/pull/4337 for reference)
- Fix the UI regression
- [EXTRA] Add space between icon and text in the bottom CTA (Message Detail screen)
| - | - |
| <img src="https://github.com/pagopa/io-app/assets/1255491/57eedfdc-80d6-423d-b2f5-cbd4e67bdd15" width="350" /> | <img src="https://github.com/pagopa/io-app/assets/1255491/bfbee193-0d06-4881-993f-720cec4cf3bc" width="350" />
N/A
> fix: [IOAPPFD0-109] Fix UI regression of the `Paid` badge in the message list

- ts/screens/modal/RootModal.tsx
This PR disables the minimum app version check if the IT-WALLET feature flag is enabled.
- `ts/screens/modal/RootModal.tsx`: Checks if the IT-WALLET FF is enabled to bypass the minimum app version check.
Login should be successful while targeting the dev server.
> feat(IT Wallet): [SIW-242] Disable min app version check if FF is enabled

- ts/screens/wallet/AddPaymentMethodScreen.tsx
This PR removes the entry point of PagoBANCOMAT flow from "Add new payment methods" screen;
|Before|After|
|-|-|
| <img src="https://github.com/pagopa/io-app/assets/34343582/b619ffb9-978b-47af-9692-97c689acb2b3"  width="250"/>| <img src="https://github.com/pagopa/io-app/assets/34343582/41b91a83-056e-4abe-911a-c536310b980e" width="250" />
- Removed from screen list the data source of PagoBANCOMAT
- Go into wallet tab;
- Press on top-right button "+ Aggiungi"
- Press on "New payment method"
- Inside the list there must not be visible PagoBANCOMAT item
> chore: [IOBP-77] Remove entry point of PagoBANCOMAT flow

- ts/components/cie/CieNotSupported.tsx
- ts/components/cie/CieRequestAuthenticationOverlay.tsx
- ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
This PR fixes the CIE Login flow.
* [ts/components/cie/CieNotSupported.tsx](https://github.com/pagopa/io-app/blob/0944df5cbab1a63eaa8d9e385a85b372dbd5b01b/ts%2Fcomponents%2Fcie%2FCieNotSupported.tsx): Fixes UI to avoid crash.
* [ts/components/cie/CieRequestAuthenticationOverlay.tsx](https://github.com/pagopa/io-app/blob/0944df5cbab1a63eaa8d9e385a85b372dbd5b01b/ts%2Fcomponents%2Fcie%2FCieRequestAuthenticationOverlay.tsx): Removes replace.
* [ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx](https://github.com/pagopa/io-app/blob/0944df5cbab1a63eaa8d9e385a85b372dbd5b01b/ts%2Fscreens%2Fauthentication%2Fcie%2FCieConsentDataUsageScreen.tsx): Uses `decodeURIComponent` to allow the `WebView` to navigate to the obtain auth url.
- Run `yarn cie-ios:prod` and run the app on a physical …
> fix: [IOPID-377] iOS crash while reading CIE with NFC

- ts/features/fims/components/WebviewErrorComponent.tsx
- ts/features/fims/screens/FimsWebviewScreen.tsx
This PR updates the header of the `FimsWebviewScreen`
- removed the Back Button
- added the Close Button 
- added padding only for `WebviewErrorComponent`
Using the `io-dev-api-server`, change the `withCTA` configuration to generate a message with FIMS CTA and enable the [FIMS dev feature flag](https://github.com/pagopa/io-dev-api-server/blob/e3ac6784acecbb5ad80a44dfc7777f80946dcab5/src/payloads/backend.ts#L45) in `src/payloads/backend.ts`.
Select such message and tap the FIMS CTA at the bottom.
Verify that the header of the screen is updated.
> feat: [IOCOM-345] Updated header for FIMS screen

- android/app/proguard-rules.pro
- android/app/src/debug/java/it/pagopa/io/app/poc/itwallet/ReactNativeFlipper.java
- android/app/src/main/java/it/pagopa/io/app/poc/itwallet/MainApplication.java
- android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/MainApplicationReactNativeHost.java
- android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/components/MainComponentsRegistry.java
- android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
- android/fastlane/Appfile
This PR updates the Android `applicationId` in order to, hopefully, fix the Android deployment via FastLane.
In particular, `android/fastlane/Appfile` still had the old `applicationId`. 
Delete `android/build` or run `cd android && ./gradlew clean`.
Delete any IO app instance from the simulator/device.
Run `yarn generate` then start building with `yarn run-android`.
> feat(IT Wallet): [SIW-268] Update applicationId to fix Android deployment

- ts/screens/modal/RootModal.tsx
- ts/utils/appVersion.ts
This PR force `isVersionSuported` to return true if itWalletEnabled FF is enabled
- Update `isVersionSuported`
Start the app with prod env and try a SPID login
> chore(IT Wallet): [SIW-270] Bypass version supported

- ts/features/idpay/initiative/details/components/TimelineOperationListItem.tsx
- ts/features/idpay/initiative/timeline/components/TimelineDiscountTransactionDetailsComponent.tsx
This PR removes the “in progress" badge and Alert info from an authorized transaction into IDPay timeline;
- Edited into `TimelineOperationListItem.tsx` the switch-case of an `AUTHORIZED` transaction doing the same behavior of a `REWARDED` transaction (showing amount instead badge); 
- Removed into `TimelineDiscountTransactionDetailsComponent.tsx` the case about the `AUTHORIZED` state;
Go into a IDPay discount initiative details and check if there is not present the `in corso` badge if the transaction state is `AUTHORIZED`;
> fix: [IOBP-117] Remove "in progress" state handling for AUTHORIZED transactions

- locales/en/index.yml
- locales/it/index.yml
- ts/components/ui/ListItemTransaction.tsx
- ts/features/design-system/core/DSListItems.tsx
In this PR:
- The icon behavior into `ListItemTransaction` component has been changed in order to add also a custom icon different from the `IOLogoPaymentType` and image uri.
- Has been done a design refinement following the [Redesign Portafoglio Figma](https://www.figma.com/file/nXyEtYEzfW4cnollwkgiXg/Redesign-Portafoglio?type=design&node-id=4-6089&mode=design&t=uB6svwBrSA52rREF-4) adding two more transaction statuses unhandled (_cancelled_, _refunded_)
- Changed the behavior into `ListItemTransaction`-> `LeftComponent`: Now it can show also a `React.ReactNode` (ideally an `Icon` component);
- Two more transaction statuses has been added into `ListItemTransaction` component: 
- _cancelled_: It shows a right badge with a "Cancelled" text inside;
- _refunded_: It sets the …
> chore: [IOBP-125] `ListItemTransaction` refinements

- ts/features/idpay/payment/navigation/navigator.tsx
This PR adds the gesture navigation in the transaction code manual input screen.
- [ts/features/idpay/payment/navigation/navigator.tsx](https://github.com/pagopa/io-app/pull/4787/files#diff-db3bd7a286b3c1c1c1d256147d82387d23b714bafaba4d9ceba25a685bd2c27e): enabled gesture navigation
Navigate to the transazione code input screen and try to navigate back with a swipe gesture.
> fix: [IOBP-127] Add swipe back gesture navigation in transaction code input screen

- locales/en/index.yml
- locales/it/index.yml
- ts/features/it-wallet/hooks/useItwResetFlow.tsx
- ts/features/it-wallet/screens/ItwHomeScreen.tsx
- ts/features/it-wallet/store/actions/index.ts
- ts/features/it-wallet/store/reducers/itwCredentials.ts
This PR adds a reset button in the wallet home screen.
- `locales/en/index.yml` & `locales/it/index.yml`: Adds necessary locales;
- `ts/features/it-wallet/hooks/useItwResetFlow.tsx`: Adds an hook to display the bottom sheet to reset the wallet;
- `ts/features/it-wallet/screens/ItwHomeScreen.tsx`: Adds a reset button when the wallet is active;
- `ts/features/it-wallet/store/actions/index.ts`: Adds the reset action;
- `ts/features/it-wallet/store/reducers/itwCredentials.ts`: Adds the new action to the reducer which resets the state to the initial one.
Active the IT Wallet, then open the wallet section and try to reset it.
> chore(IT Wallet): [SIW-300] Add wallet reset

- ts/components/screens/DarkLayout.tsx
- ts/components/wallet/WalletLayout.tsx
- ts/screens/services/ServicesHomeScreen.tsx
- ts/screens/wallet/WalletHomeScreen.tsx
This pull request introduces the profile button to main screens, including payments and services.
- `ts/components/screens/DarkLayout.tsx`: Prop drilling;
- `ts/components/wallet/WalletLayout.tsx`: Prop drilling;
- `ts/screens/services/ServicesHomeScreen.tsx`: Adds the profile button to the services screen;
- `ts/screens/wallet/WalletHomeScreen.tsx`: Adds the profile button to the payments screen;
Run the application.
Check if the profile button is displayed in the top bar on each main screen, including payments and services.
> feat(IT Wallet): [SIW-319] Add profile button to main screens

- ts/features/it-wallet/screens/discovery/ItwActivationDetailsScreen.tsx
- ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
This PR adds a vertical spacer in discovery screens. 
- `ts/features/it-wallet/screens/discovery/ItwActivationDetailsScreen.tsx`: Add vertical spacer;
- `ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx`: Add vertical spacer.
| Before  | After |
| <img src="https://github.com/pagopa/io-app/assets/12371664/acffebc8-f2b1-4c00-8da2-8d7686f0967c" height="400">  |  <img src="https://github.com/pagopa/io-app/assets/12371664/26dc9f41-4c2d-43ba-8880-2531c4531a81" height="400">|
> fix(IT Wallet): [SIW-322] Add vertical spacer in discovery screens

- ts/features/idpay/payment/xstate/actions.ts
This PR fixes the navigation behavior after an IDPay transaction authorization. 
- Added navigation reset on authorization exit
With the `io-dev-server`, authorize an IDPay transaction and check that after the authorization you navigate back to the initiative screen.
> fix: [IOBP-145] Fix navigation after IDPay transaction authorization

- ts/components/wallet/TransactionsList.tsx
after a discussion with @thisisjp , it was decided it's best to remove the municipality logo from wallet transactions for now, to then add them later in future evolutives
- removed municipality logos from wallet transactions
navigate to the wallet screen, click on the "show transactions" button and make sure listItems render correctly and with no icons.
> fix: [IOBP-158] Removal of municipality icons in wallet transactions

- package.json
- ts/features/it-wallet/components/ClaimsList.tsx
- ts/features/it-wallet/screens/ItwCredentialDetails.tsx
- ts/features/it-wallet/screens/ItwHomeScreen.tsx
- ts/features/it-wallet/store/actions/credentials.ts
- ts/features/it-wallet/store/reducers/itwPid.ts
- yarn.lock
This PR updates `io-react-native-wallet` dependency to the `0.2.2` version and also replaces the `VerifyResult` type with `PidWithToken` which wasn't exposed in the `0.2.1` version. 
- `package.json && yarn.lock`: Updates the dependency; 
- `ts/features/it-wallet/components/ClaimsList.tsx`: Replaces the `VerifyResult` type with `PidWithToken`;
- `ts/features/it-wallet/screens/ItwCredentialDetails.tsx`: As above;
- `ts/features/it-wallet/screens/ItwCredentialDetails.tsx`: As above;
- `ts/features/it-wallet/screens/ItwHomeScreen.tsx`: As above;
- `ts/features/it-wallet/store/actions/credentials.ts`: As above;
- `ts/features/it-wallet/store/reducers/itwPid.ts`: As above;
The PID issuing flow should still work as expected.
> chore(IT Wallet): [SIW-347] Update io-react-native-wallet

- ts/features/it-wallet/saga/wia.ts
- ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
- ts/features/it-wallet/utils/mocks.ts
- ts/store/reducers/profile.ts
- ts/utils/dates.ts
This PR introduces feature which allows users to bypass the CIE login process during the ITW activation. It completely disables the flow on iOS devices. The data required for issuing the PID is retrieved directly from the user profile or from a mock if not available. The bypass can be activated by long-pressing the image on this screen: 
- `ts/features/it-wallet/saga/wia.ts`: Checks if the platform is iOS in order to disable the CIE login flow on iOS but keep it enabled during tests;
- `ts/features/it-wallet/saga/wia.ts`: Checks the `isEmulator` flag to disabled the NFC process and enable the iOS simulator to skip the CIE login flow;
- `ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx`: Adds the bypass pressable component and logic. Also disables the `Continue` button …
> feat(IT Wallet): [SIW-355] Bypass CIE login during activation

- ios/Podfile.lock
This PR cleans up the `Podfile.lock` removing the reference to `react-native-cie`.  This specific pod is added at built time with the script `cie-ios:prod`.
> chore: Clean-up Podfile.lock

- ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
This PR re-enables the CIE login CTA on iOS which now automatically bypasses the whole process, using the profile data to get the PID.
- In the [ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx](https://github.com/pagopa/io-app/pull/4882/files#diff-9a825d7b18edf875ff691f385e0500af4b0b127f7389586e0a5c8f9b52174ad6) remove the disabled flag when on iOS and call `bypassCieLogin` on press instead.
Test the flow on both iOS and Android. Android should show the CIE login process, iOS should display the PID preview after pressing the CTA button.
> chore(IT Wallet): [SIW-366] Bypass with CTA on iOS

- android/app/src/main/AndroidManifest.xml
This PR adds the `host` attribute into the queries intent filter in order for the canOpenUrl method to work with http/https url (which is used to check and open third-party apps).
- added `host` parameter to `queries` `intent` `data` in the Android manifest (for both `http` and `https` `data` `scheme`s)
From a message with markdown, open an url that points to another installed application
> fix: [IOCOM-472] Fix canOpenUrl on Android which was not taking the host parameter into account

- ts/components/ui/ListItemTransaction.tsx
This PR fixes the visualization of the ListItemTransaction when the experimental flag is enabled
> fix: [IOPLT-127] Fixes list item transaction on sperimental visualization enabled

- locales/en/index.yml
- locales/it/index.yml
- ts/features/it-wallet/screens/issuing/ItwPidAuthInfoScreen.tsx
This PR removes hardcoded strings from the `ItwPidAuthInfoScreen.tsx` and moves them to the translations files.
Test an activation flow and the replaced strings should be displayed properly.
> chore(IT Wallet): [SIW-365] Remove hardcoded strings from info screen 

- locales/en/index.yml
This PR introduces the English translation for the messages section banner.
Set the application language to English. If the wallet has a reset option, perform a reset. Verify that the banner in the messages section is translated into English.
> chore(IT Wallet): [SIW-363] Add main banner translation

- ios/ItaliaApp/Info.plist
- ios/ItaliaApp/it.lproj/InfoPlist.strings
This PR adds proper description for the NSPhotoLibraryAddUsageDescription's permission (iOS only)
- Edited english translation in `ios/ItaliaApp/Info.plist`
- Added italian translation in `ios/ItaliaApp/it.lproj/InfoPlist.strings`
Launch the app on an iOS device/simulator, navigate to a section where you can save an image to the device gallery (like the green pass) and check that the proper text is displayed (both italian and english translations)
> fix: [IOCOM-479] Strings for NSPhotoLibraryAddUsageDescription permission

- ts/utils/notification.ts
This PR fixes a crash on devices running Android 6 Marshmallow, when checking for notifications' permission.
- notifications' checking methods for Android have been modified in order not to check but to return a given permission on devices running Android API level 23 (Android 6 Marshmallow). 
- This is needed since on such Android version, if a permission is requested that was not declared at the time of the Android release (such as the POST_NOTIFICATIONS permission string), the system throws an exception. This behaviour has been changed since Android 7 Nougat (API level 24) in order not to throw anything but return a default value.
- Also note that on any Android versions lower than 13 (API level 33), the notifications' permission is always given (there is no need to ask the user for …
> fix: [IABT-1488] Fix crash on Android 6 when checking for notifications' permission

- ts/features/it-wallet/saga/itwRpSaga.ts
This PR proses a change to the RP initialization saga in order to directly decode the PID during the process. 
This is needed since we don't know if the PID has been already decoded and is present in the state when an user scan a QR code to start the RP flow. 
A better error handling is being tracked by another issue.
- Add the PID decode saga call to the RP initialization saga.
> chore(IT Wallet): [SIW-407] Add PID decode to RP initialization saga

- ios/Podfile.lock
- package.json
- yarn.lock
This PR fixes a startup crash of the app due to the io-react-native-jwt library by updating it to the 0.6.1 version.
The app should now run without crashing at startup.
> fix(IT Wallet): [SIW-405] Fix JWT library crash

- ts/features/idpay/wallet/screens/AvailableInitiativesListScreen.tsx
addition of said component to said screen, both for cleanliness and because some methods sent the whole screen in an error state because their brand does not appear in the payment methods' logo list.
see short description
navigate to a payment method's details screen, then to its connected initiatives (if there are none, check another method, `io-dev-api-server` is your friend here 😉 ) , and then once more to the "view all" page, in order to show the full initiatives list, then make sure nothing breaks.
> chore: [IOBP-218] Add LogoPaymentWithFallback to AvailableInitiativesListScreen

- ts/features/it-wallet/components/ItwLoadingSpinner.tsx
This PR moves the loading animation on the `ItwLoadingSpinner.tsx` component to the native thread. 
This change improves the framerate of the animation and doesn't block it when the JS thread is busy. 
- Sets the `useNativeDriver` to true as explained in the official [React Native documentation](https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated).
Test a PID issuing flow and a presentation flow from a pyshical device to value the difference.
> fix(IT Wallet): [SIW-471] Move loading animation to native thread

- package.json
- ts/components/Banner/index.tsx
- ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
- ts/features/design-system/components/DSAssetViewerBox.tsx
- ts/features/design-system/core/DSAdvice.tsx
- ts/features/design-system/core/DSPictograms.tsx
- ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
- ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
- ts/features/wallet/cobadge/screen/CobadgeDetailScreen.tsx
- yarn.lock
This PR adds the new `PictogramBleed` component. It also replaces some keys used in some `Pictogram` components that no longer exist.
To learn more, please refer to:
* https://github.com/pagopa/io-app-design-system/pull/63
- Update `io-app-design-system` to the `1.7.0` version
- Update `Banner` component to use the new `PictogramBleed` component
- Replaces some `Pictogram` keys that no longer exist
- Add the new **Bleed pictograms** section to the **Pictograms** page
> [!WARNING]
> This update breaks the `OperationResultScreenContent` because the snapshot was generated with the new variant of `ButtonSolid`. The new version of `io-app-design-system` restores the legacy variant when the DS toggle is set to off.
https://github.com/pagopa/io-app/assets/1255491/0ecb8615-ab16-4a7c-a35d-c0de8003d …
> chore: [IOAPPFD0-145] Add the new `PictogramBleed` component

- ts/features/idpay/payment/screens/IDPayPaymentCodeScanScreen.tsx
This PR increases the max length of decoded barcodes in the barcode scan screen, which was causing a bug that would not allow IDPay barcodes to be scanned.
- ts/features/idpay/payment/screens/IDPayPaymentCodeScanScreen.tsx: incresed size of max scanned barcodes lenght
Try to scan an IDPay transaction code from the barcode scan screen.
> fix: [IOBP-248] Fix IDPay decoded barcodes max length in barcode scan screen

- ts/features/design-system/core/DSListItems.tsx
- ts/features/it-wallet/components/ItwListItem.tsx
- ts/features/it-wallet/components/ListItemItw.tsx
This PR adds the `ListItemItw` component used in a few screens like the [credentials catalog ](https://www.figma.com/file/c80PUA6BYANkGPyaqsRBNA/IT-Wallet---Esperienza-in-IO?type=design&node-id=2035-41538&mode=design&t=SiPuRdgQeVDbj4iZ-0)and the[ accepted login methods](https://www.figma.com/file/c80PUA6BYANkGPyaqsRBNA/IT-Wallet---Esperienza-in-IO?type=design&node-id=2851-52986&mode=design&t=SiPuRdgQeVDbj4iZ-0).
It supports an optional left icon, a title, an optional subtitle, an optional right node and a disabled state which greys out the component and disables the onPress callback.
- Adds the `ListItemItw` component;
- Updates the `ListItem` section of the in-app Design System showroom.
Open the Design System showroom, navigate to `ListItem` and scroll to the bottom to see the new …
> feat(IT Wallet): [SIW-497] Add ListItemItw component

- ts/features/it-wallet/screens/discovery/ItwDiscoveryProviderInfoScreen.tsx
This PR adds incoming badge to the SPID item in `ItwDiscoveryProviderInfoScreen`.
- Update `ItwDiscoveryProviderInfoScreen`
Start activation flow. In the Provider Info screen the SPID item should have incoming badge.
> chore(IT Wallet): [SIW-486] Add incoming badge to spid item into info provider screen

- package.json
- yarn.lock
This PR removes `@react-navigation/drawer` dependency, not referenced anymore.
N/A
> chore: [IOAPPFD0-153] Remove `@react-navigation/drawer` dependency

- ts/components/ui/cards/payment/PaymentCardBig.tsx
- ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
- ts/features/wallet/cobadge/screen/CobadgeDetailScreen.tsx
- ts/features/wallet/creditCard/screen/CreditCardDetailScreen.tsx
fixed a mismatch in the payment methods' displayed expire date .
this should fix the problem for Credit/debit cards, bancomat, cobadge
- updated date generation from backend data to follow the correct format
navigate to the details screen of a payment method that has an expiration date, and make sure the displayed expiration date matches the one that is passed from BE
> fix: [IABT-1489] Mismatch in expireDate field on Payment Method details page

- ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
This PR adds the identification request before IdPay transaction authorization
https://github.com/pagopa/io-app/assets/6160324/dbd0f861-c984-442a-8faf-afb0217584bc
- `ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx`: add `identificationRequest` dispatch before authorization action.
Try to authorize an IdPay transaction, the identification request screen should appear.
> chore: [IOBP-150] Add identification request in IdPay transaction authorization

- ts/components/messages/MessagesInbox.tsx
- ts/features/it-wallet/components/ItwActionBanner.tsx
- ts/features/it-wallet/screens/ItwHomeScreen.tsx
This PR introduces a change to the `ItwActionBanner` component, making it non-dismissible. 
- Updates `ItwActionBanner` component props to accept an optional `onClose` prop and a required `labelClose` prop only if `onClose` is provided by using a discriminated union. When both props are not provided the banner is non-dimissable.
- Updates the usage in both `ItwHomeScreen` and `MessagesInbox` by removing the `labelClose` prop to make the banner non dismissable.
Start the app, reset the wallet (if necessary) and check the banner in both screen. It shouldn't be dismissible while retaining its functionality.
> chore(IT Wallet): [SIW-510] Make ItwActionBanner component non dismissible

- ts/features/it-wallet/screens/issuing/cie/ItwCiePinScreen.tsx
This PR removes the `AdviceComponent` from the ITW CIE pin screen which contained wrong copy information.
| <img src="https://github.com/pagopa/io-app/assets/12371664/fb524e46-178f-4ea1-a69c-c4d5fb878f72" height="300"> | <img src="https://github.com/pagopa/io-app/assets/12371664/85a80ab7-a55e-44f5-8213-f17e66ab6bbd" height="300"> | 
Test a PID issuing flow and check if the `AdviceComponent` has been removed.
> chore(IT Wallet): [SIW-519] Remove AdviceComponent from ITW CIE pin screen

- locales/en/index.yml
- locales/it/index.yml
This PR changes the screen title for the payments home screen, namely WALLET_HOME.
| <img src="https://github.com/pagopa/io-app/assets/12371664/4d4bf862-78b0-4a33-b3d1-41c1498766d7" height="300"> | <img src="https://github.com/pagopa/io-app/assets/12371664/a0c808b2-3ee4-4fd5-b95c-e111d09fddfa" height="300"> | 
- Updates the locale used to show the title.
Start the app and open the payments section, the title should be "Pagamenti" or "Payments".
> chore(IT Wallet): [SIW-511] Change payments screen title

- package.json
- ts/components/messages/__tests__/__snapshots__/EmptyListComponent.test.tsx.snap
- ts/features/bonus/cgn/components/detail/eyca/EycaStatusDetailsComponent.tsx
- ts/features/design-system/core/DSPictograms.tsx
- ts/features/idpay/configuration/screens/IbanConfigurationLandingScreen.tsx
- ts/features/idpay/wallet/components/IDPayInitiativesListComponents.tsx
- ts/features/wallet/common/BasePaymentMethodScreen.tsx
- ts/features/wallet/component/features/PaymentMethodSettings.tsx
- ts/screens/onboarding/components/NotificationPreviewSample.tsx
- yarn.lock
This PR adds the color mode support to the pictograms. To learn more, please refer to:
* https://github.com/pagopa/io-app-design-system/pull/82
- Update `io-app-design-system` to `1.10.0`
- Refactor styles that incorrectly used the `IOSpacingScale` array for spacing values
- Update **Pictograms** page to show latest pictogram capabilities
https://github.com/pagopa/io-app/assets/1255491/db3e8d7a-e955-46a0-ac39-e920ab1536a1
Go to the **Design System → Pictograms**
> chore: [IOAPPFD0-155] Add color mode support to the pictograms

- ts/features/it-wallet/screens/ItwHomeScreen.tsx
This PR removes the right horizontal padding of the tab navigator component in the ITW home screen. 
The content should clip in the view on the right side.
Before: 
https://github.com/pagopa/io-app/assets/12371664/60f9588a-2c71-46fe-ba3f-9bbdf7dd11ea 
After: 
https://github.com/pagopa/io-app/assets/12371664/5e7a75a9-f3d6-4ae0-a171-1f5696be9a2d
- Replace the horizontal padding with a left only padding.
Obtain a PID then open the ITW home screen and check the lateral scrolling of the tab navigator. The content should clip on the right.
> chore(IT Wallet): [SIW-529] Remove tab navigator right horizontal padding in ITW home screen

- ts/features/design-system/core/DSIcons.tsx
This PR adds an example of `IconContained` to the `Icons` page
- Add the default (and currently unique) variant of `IconContained`
Go to the **Design System → Icons (Foundation)**
> chore: [IOAPPFD0-144] Add `IconContained` example to DS

- ts/features/idpay/configuration/xstate/services.ts
This PR adds a filter into `loadWalletInstruments` method to filter all the instruments of type `CREDIT_CARD`
- Added a filter into pipe that filters only wallets instruments of type `CREDIT_CARD`
Navigate into an initiative and check inside the instruments list that there is only available instruments of type credit card.
> chore: [IOBP-266] IDPay configuration wallet instruments filter

- .env.production
- ts/features/pn/components/PnMessageDetails.tsx
This PR enables the FF flag for using the new PN screens (that handles the cancelled notification).
It also fixes the PN message details UI, when there are no attachments by not showing the related section's title.
- env.production has the flag turned on
- PnMessageDetails checks for at least one attachment before displaying the related section's title
Using the various io-dev-api-server PN's configurations, check that all data are properly handled and displayed
> feat: [IOCOM-559] Enable the PN flag for cancelled notification's handling

- ts/features/it-wallet/components/ItwLoadingSpinner.tsx
- ts/features/it-wallet/components/ItwLoadingSpinnerOverlay.tsx
- ts/features/it-wallet/components/__tests__/ItwLoadingSpinner.test.tsx
This PR proposes a generalization of the `ItwLoadingSpinner`. 
- Adds an optional `size` prop which defaults to `24` to render the spinner component in different sizes. `76` is kept for backward compatibility with the existing screens and will be removed after we migrate completely to the new design system.
- Makes the `color` prop optional which defaults to `IOColors["blueIO-500"]` for the new design system;
- Removes `captionTitle` and `captionSubtitle` from the loading spinner component and moves it to `ItwLoadingSpinnerOverlay.tsx` which is also updated with the new design system.
Test an issuing flow and check for any regression. Please note that the "legacy" spinner might be a little thinner than before. Also, this is still not updated with the new gradient style.
> feat(IT Wallet): [SIW-560] Generalize loading component

- ts/components/BarcodeCamera.tsx
- ts/features/barcode/hooks/useIOBarcodeCameraScanner.tsx
This PR replaces ultra wide angle camera with wide angle camera in barcode screen
- `ts/features/barcode/hooks/useIOBarcodeCameraScanner.tsx`: explicited the use of `wide-angle-camera` in `useCameraDevices` hook
- `ts/components/BarcodeCamera.tsx`: explicited the use of `wide-angle-camera` in `useCameraDevices` hook
With a device, navigate to the barcode scan screen and check that the camera used is the wide angle camera.
> fix: [IOBP-95] Fix ultra wide angle camera being used in barcode scan screen

- ts/features/it-wallet/screens/ItwHomeScreen.tsx
- ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
- ts/sagas/startup.ts
This PR proposes a refactor to the PID decode process which is now decoded at startup after the user inserts its PIN. 
- Adds the PID decode action dispatch in the startup saga. This allows us to not worry about decoding the PID in each screen it needs to be decoded; 
- Removes the decoding from the `ItwHomeScreen.tsx` screen but keeps it in the `itwPidPreviewScreen.tsx`. That's necessary because the issuing happens after the startup saga if the wallet operational. 
We might rethink the PID state to be incorporated into the credentials state down the road.
There a are few things that should be tested: 
1. Obtain a PID;
2. Authenticate on the RP demo website;
3. Close the app and open it again. You should still see the decoded PID in the wallet section;
4. Close the app and open it again. …
> fix(IT Wallet): [SIW-568,SIW-565] Decode PID at startup after PIN

- ts/features/idpay/code/screens/IdPayCodeDisplayScreen.tsx
This PR fixes an issue when navigating to the failure screen of the ID Pay CIE code flow.
- [ts/features/idpay/code/screens/IdPayCodeDisplayScreen.tsx](https://github.com/pagopa/io-app/pull/5067/files#diff-d707cf1d996ad8193c4fb386857e18e3f1defbfe49e1820b361fd7cd9b357403): changed `navigate` to `replace` in navigation function.
With the `io-dev-server`, navigate to **Profile -> ID Pay Code Playground**
> fix: [IOBP-285] Fix navigation on IdPay CIE code failure

- ts/features/messages/hooks/useMessageOpening.tsx
This PR replaces the new pictograms with the old ones in the `PreconditionBottomSheet`.
See commit list
After increasing the `min_app_version` for PN on the `io-dev-api-server`, open a PN message and verify that the old pictograms are visible.
> chore: [IOCOM-579] Replace the new pictograms with the old ones in the `PreconditionBottomSheet`

- ts/features/idpay/configuration/screens/InstrumentsEnrollmentScreen.tsx
- ts/features/idpay/unsubscription/screens/UnsubscriptionConfirmationScreen.tsx
This PR fixes the bottom sheets inside the ID Pay instruments configuration and unsubscription screens.
- [ts/features/idpay/configuration/screens/InstrumentsEnrollmentScreen.tsx](https://github.com/pagopa/io-app/compare/IOBP-286-fix-idpay-bottom-sheets?expand=1#diff-7bcfebf445dd9574f6d78c786ca8832a4559e3ce28dbb5d9d540de80a64ba8aa): incremented to 175 the bottom sheets bottom padding
- [ts/features/idpay/unsubscription/screens/UnsubscriptionConfirmationScreen.tsx](https://github.com/pagopa/io-app/compare/IOBP-286-fix-idpay-bottom-sheets?expand=1#diff-7a2a5467f073e83a63b580443c564027a011c278100741fc17914d098862f0f3): incremented to 175 the bottom sheets bottom padding
Navigate to the instruments configuration screen and/or the initiative unsubscription screen and check that the bottom …
> fix: [IOBP-286] Fix ID Pay instruments and unsubscription bottom sheets

- ts/features/it-wallet/saga/itwCredentialsSaga.ts
- ts/features/it-wallet/store/actions/itwCredentialsActions.ts
- ts/features/it-wallet/store/reducers/itwCredentialsChecksReducer.ts
This PR adds a `CredentialCatalogItem` mock to the state and a selector to make it available during the issuing flow.
Static checks.
> feat(IT Wallet): [SIW-587] Add credential to the check store

- ts/features/it-wallet/components/ItwCredentialCard.tsx
- ts/features/it-wallet/screens/ItwHomeScreen.tsx
- ts/features/it-wallet/screens/credentials/ItwPidDetails.tsx
- ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
This PR adds customizable credential title to the `ItwCredentialCard.tsx` component which was left out by mistake in #5086, hence why the same ticket number.
- Adds `title` props in `ItwCredentialCards.tsx` component;
- Updates usage accordingly.
Check for any regression in the issuing flow which uses a PID card and also in the wallet section after obtaining a PID.
> chore(IT Wallet): [SIW-535] Refactor title card component

- ts/components/BarcodeCamera.tsx
- ts/features/barcode/hooks/useIOBarcodeCameraScanner.tsx
- ts/features/barcode/hooks/useWindeAngleCameraDevice.tsx
This PR fixes an issue where `wide-angle-camera` is not available on some Android devices, which causes the camera to not work properly.
- Added custom hook `useWideAngleCameraDevice` which handles the logic to select the best matching camera
This PR should be tested on a physical device. Check that the camera is working and it's not an Ultra Wide Angle camera on both Android and iOS devices. 
A list of devices where the issue has been identified is:
- Samsung S22-S23
- Xiaomi 12 Lite, Xiaomi Redmi 10
- Huawei P30 Lite
> fix: [IABT-1494] Fix camera not working on Android devices

- package.json
- ts/components/ui/LoadingIndicator.tsx
- ts/features/design-system/core/DSLoaders.tsx
- yarn.lock
This PR adds the new `LoadingIndicator` component, a component that contains a predefined set of values that are applied to the `LoadingSpinner` component. This component is intended to be an alternative to the current `ActivityIndicator` component.
- Update `io-app-design-system` to `1.13.1`
- Add the new `LoadingIndicator` component
- Add different colors based on the experimental DS value
- Add the predefined a11y related props
https://github.com/pagopa/io-app/assets/1255491/60c106a3-9385-46d1-9e7f-314c8dff1ff2
- https://github.com/pagopa/io-app-design-system/pull/103
Go to the **Profile → Design System → Loaders**
> chore: [IOAPPFD0-174] Add the new `LoadingIndicator` component

- ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
This PR removed the torch icon from the Barcode Scan screen when camera permission is not granted.
- [ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx](https://github.com/pagopa/io-app/compare/IOBP-331-nella-pagina-di-richiesta-consnso-fotocamera-e-presente-licona-torcia?expand=1#diff-1e4e400edd0a8debdd16a6c728d260d849b977083ea5aa108a5ba43ce25ac4c2): added checks to display torch icon
Navigate to the barcode scan screen, check that the torch icon is not displayed when camera permission is not granted.
> fix: [IOBP-331] Remove torch button in Barcode Scan screen if camera permission is not granted

- locales/en/index.yml
- locales/it/index.yml
- ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
fixed a couple of wrong a11y voiceover hints in said screen
- bottom tab navitgation now reads "x of 3"
- flashlight icon now reads "tap to turn the flashlight on/off"
With voiceover active, navigate to a discount-type initiative, then tap the bottom button and make sure that what is listed in the "proposed changes" section actually happens.
> fix: [IOBP-290 , IOBP-289] Voiceover fixes in BarcodeScanScreen

- ts/features/barcode/screens/BarcodeScanScreen.tsx
This PR fixes an issue with the modal dialog in the Barcode Scan screen, which causes ID Pay manual input to appear even if it is not enabled by the FF.
- [ts/features/barcode/screens/BarcodeScanScreen.tsx](https://github.com/pagopa/io-app/compare/IOBP-330-tap-su-autorizza-una-transazione-senza-una-azione-collegata?expand=1#diff-12570b34029e534a64b24f1cb81383d99557273c4b2f34ad4ced82685fa017f6): added IDPay FF check
With the Experimental Design System enabled, navigate to the scan screen and check that the manual input modal is not displayed if IDPay is not enabled.
> fix: [IOBP-330] Fix manual input modal in Barcode Scan screen

- ts/features/pn/components/MessageDetails.tsx
- ts/features/pn/components/PnMessageDetails.tsx
This PR fixes the padding around the `StatusContent` component in PnMessageDetailsScreen.
| --- | --- |
| <img src="https://github.com/pagopa/io-app/assets/29163287/a2e7d0a0-2084-42ad-bf89-dc4ec1ec8702" width="300" /> | <img src="https://github.com/pagopa/io-app/assets/29163287/6e2669bd-f912-41f1-a445-0caef3072b0f" width="300" /> | 
- Moved padding to the scroll view content container
Generate a **cancelled** PN notification using `io-dev-api-server`. Check that the banner is displayed correctly on android and ios.
> fix: [IOCOM-622] Fix padding around the `StatusContent` component on Android

- locales/en/index.yml
- locales/it/index.yml
fixed voiceover reading `POS` as "position"
width=200
/>
- updated I18n to avoid the problem
This is a change that should in my opinion occur in the `FeatureInfo` component, but is being fixed here for now.
With the idpay flag active, navigate to idpay code's onboarding test page in the profile section and make sure that the bottom sheet is correctly read by voiceover
> fix: [IOBP-296] A11y reading acronyms in idpay code onboarding screen

- ts/components/wallet/TransactionsList.tsx
This PR fixes an accessibility issue in `TransactionList` elements, which caused iOS VoiceOver to read the time and amount as a single string.
- added `accessibilityLabel` to `ListItemTransaction` items
With VoiceOver turned on, go to the transaction list on the wallet screen and check that the amount is read correctly.
> fix: [IOBP-243] Fix `TransactionList` a11y

- ts/features/idpay/onboarding/navigation/navigator.tsx
This PR fixes the navigation in the ID Pay Onboarding completed screen, disabling the back navigation gesture if the flow is completed.
| --- | --- |
|  <video src="https://github.com/pagopa/io-app/assets/6160324/c997b92c-0e04-4524-ade8-b26173877b6f" /> |  <video src="https://github.com/pagopa/io-app/assets/6160324/e7653c8d-d1c7-49a0-835b-116251cf66f1" />  |
- [ts/features/idpay/onboarding/navigation/navigator.tsx](https://github.com/pagopa/io-app/compare/IOBP-364-fix-idpay-onboarding-navigation?expand=1#diff-01b5ae5ce43bd13eb4995f7b94f39e84f2b77491d85513f111a2582d06e06115): added `gestureEnabled: false` to `IDPayOnboardingRoutes.IDPAY_ONBOARDING_COMPLETION` route
- Feature B
Try to complete an ID Pay onboarding flow, in the final step, try to navigate back with a …
> fix: [IOBP-364] Disable gesture in ID Pay onboarding completed screen

- locales/en/index.yml
- locales/it/index.yml
- ts/features/it-wallet/components/ItwKoView.tsx
- ts/features/it-wallet/screens/credentials/ItwAddCredentialsCheckScreen.tsx
- ts/features/it-wallet/screens/credentials/ItwCredentialIssuingInfoScreen.tsx
- ts/features/it-wallet/screens/credentials/ItwCredentialPreviewScreen.tsx
- ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationChecksScreen.tsx
- ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationDataScreen.tsx
- ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationResultScreen.tsx
- ts/features/it-wallet/utils/errors/itwErrors.ts
- ts/features/it-wallet/utils/errors/itwErrorsMapping.ts
This PR updates the design system in error screens related to credential issuing and presentation flows. 
It also moves the credential mapping from a monolitic util function to the related screen. 
- Adds horizontal padding in `ItwKoView.tsx`;
- Defines a `ItwErrorMapping` function interface type which can be used in screens to implement a dedicated error mapping function; 
- Defines a new `getItwGenerciMappedError` function to get a generic error view;
- Replaces legacy error view to the new `ItwKoView.tsx` in credential issuing and presentation screens; 
- Sets old error mapping functions helpers to deprecated.
Note: this could be improved by strictly type-checking each possible error in a view but that's up for another PR.
Test the credential issuing and presentation flow. Errors can …
> chore(IT Wallet): [SIW-614] Update error screens DS in credential issuing and presentation

- ts/features/it-wallet/hooks/useItwInfoBottomSheet.tsx
This PR set title prop of `useItwInfoBottomSheet` as optional to re-use it in others screen without H6 title.
- Update `useItwInfoBottomSheet`
Try all flowd where this hook is used.
> chore(IT Wallet): [SIW-643] Update `useItwInfoBottomSheet` hook with optional title

- ts/features/messages/components/MessageAttachmentPreview.tsx
- ts/features/messages/hooks/useAttachmentDownload.tsx
- ts/features/pn/analytics/index.ts
- ts/features/pn/components/MessageDetails.tsx
- ts/features/pn/components/MessageF24.tsx
- ts/features/pn/screens/AttachmentPreviewScreen.tsx
- ts/features/pn/screens/MessageDetailsScreen.tsx
- ts/features/pn/screens/PnAttachmentPreview.tsx
- ts/features/pn/utils/index.ts
This PR adds F24 Mixpanel events
- added the `category` property to the events:
- `PN_ATTACHMENT_OPENING`
- `PN_ATTACHMENT_OPENING_SUCCESS`
- `PN_ATTACHMENT_SHARE`
- `PN_ATTACHMENT_SAVE`
- `PN_ATTACHMENT_OPEN`
- `PN_ATTACHMENT_SAVE_SHARE`
- `PN_ATTACHMENT_DOWNLOAD_FAILURE`
- added event: `PN_SHOW_F24`
- added `contains_f24` property to `PN_UX_SUCCESS`
- renamed `skipDownloadAttachment` to `enableDownloadAttachment`
Using `io-dev-api-server`, check that events are generated with the correct properties
> feat: [IOCOM-461] Add F24 Mixpanel events

- locales/en/index.yml
- locales/it/index.yml
- ts/screens/authentication/NewOptInScreen.tsx
Add contextual help content 
https://github.com/pagopa/io-app/assets/83651704/e7edc293-a09d-4d8d-ae59-b998a1256429
- Add texts 
- Integrate texts
In **.env file**  `FAST_LOGIN_ENABLED=YES` and `FAST_LOGIN_OPTIN=YES`
in io-dev-server-api in backend.ts file:
```ts
fastLogin: {
min_app_version: {
ios: "1.2.1",
android: "0.0.0"
},
opt_in: {
min_app_version: {
ios: "1.2.1", 
android: "0.0.0"
}
}
}
```
NB: if fastLogin is disabled (`0.0.0`) the opt-in is disabled too, but not the reverse. 
Run the application
> feat: [IOPID-987] Add contextual help content

- ts/features/messages/analytics/index.ts
- ts/features/messages/utils/index.ts
- ts/sagas/messages/watchLoadMessageById.ts
- ts/sagas/messages/watchLoadMessageDetails.ts
- ts/sagas/messages/watchLoadNextPageMessages.ts
- ts/sagas/messages/watchLoadPreviousPageMessages.ts
- ts/sagas/messages/watchReloadAllMessages.ts
- ts/sagas/messages/watchUpsertMessageStatusAttribues.ts
This PR adds some error logging to messages sagas.
Following sagas generate an analytics event when failing:
- watchLoadMessageById
- watchLoadMessageDetails
- watchLoadNextPageMessages
- watchLoadPreviousPageMessages
- watchReloadAllMessages
- watchUpsertMessageStatusAttribues
Using the io-dev-api-server, check that failure events are reported with proper `reason` status.
> feat: [IOCOM-667] Failure logging for messages' sagas

- ts/features/idpay/details/components/BeneficiaryDetailsContent.tsx
- ts/features/idpay/details/components/InitiativeRulesInfoBox.tsx
- ts/features/idpay/details/screens/BeneficiaryDetailsScreen.tsx
This PR fixes the ID Pay initiative rules info bottom sheet height for shorter contents.
https://github.com/pagopa/io-app/assets/6160324/7ffc63cf-82d8-4349-a55a-651157537887
- [ts/features/idpay/details/components/InitiativeRulesInfoBox.tsx](https://github.com/pagopa/io-app/compare/IOBP-361-fix-idpay-rules-bottom-sheet?expand=1#diff-aec7df12aad70c4276336c3813019b4655fac37dc09eb456b93208f7c6b8b302): increased bottom padding to `170` for the rules bottom sheet
- [ts/features/idpay/details/components/BeneficiaryDetailsContent.tsx](https://github.com/pagopa/io-app/compare/IOBP-361-fix-idpay-rules-bottom-sheet?expand=1#diff-763f13f0b9f72e4763aa758664939937121a62cc637c86ff29bfe6f41ab7d56c): component props refactoring
Navigate to the ID Pay initiative details screen and check that the rules …
> fix: [IOBP-361] Fix ID Pay rules info bottom sheet in initiative details screen

- ts/features/bonus/cgn/screens/activation/CgnAlreadyActiveScreen.tsx
This PR fixes some CGN e2e test regression after the massive refactor adding a missing test id to a button.
- Added a missing test id to a button
> fix: [PE-494] CGN test ids for e2e tests

- ts/features/it-wallet/screens/ItwHomeScreen.tsx
- ts/features/it-wallet/screens/credential/ItwPidDetails.tsx
- ts/features/it-wallet/screens/credential/issuing/ItwCredentialsCatalogScreen.tsx
- ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
- ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationChecksScreen.tsx
- ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationDataScreen.tsx
- ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationResultScreen.tsx
- ts/features/it-wallet/utils/mocks.ts
This PR addresses an issue where mock data fails to be translated on certain devices. Although I was unable to replicate the issue, the proposed fix revolves around the idea that `I18n` uses the default locale (en) when declaring mock data, as it is not initialized. To resolve this, the proposed solution transforms the constant data into a function that must be called at runtime.
Static tests should be enough.
> fix(IT Wallet): [SIW-674] Untranslated mock data

- ts/features/it-wallet/screens/credential/ItwCredentialDetailsScreen.tsx
- ts/features/it-wallet/screens/credential/ItwPidDetails.tsx
- ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
This PR adds a navigation to the missing feature screen where a feature is not implemented yet.
- Adds the navigation in [ItwCredentialDetailsScreen.tsx](https://github.com/pagopa/io-app/pull/5228/files#diff-94e935f2d7d760954fd0c0647b59f32cd163d70dac988b5588a985aadef0689b) when pressing the `Show QR Code` button and the banner;
- Adds the navigation in [ItwPidDetails.tsx](https://github.com/pagopa/io-app/pull/5228/files#diff-94e935f2d7d760954fd0c0647b59f32cd163d70dac988b5588a985aadef0689b) on the `Show QR Code` button and when tapping on the security level;
- Adds the navigation in [ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx](https://github.com/pagopa/io-app/pull/5228/files#diff-1efa65eedbb4bea4a8d61f1d909912fa8a94af60a4df438f01730c624c2c9fca) when tapping on the …
> chore(IT Wallet): [SIW-624] Add navigation to missing feature screen

- ts/features/it-wallet/screens/credential/issuing/ItwCredentialsCatalogScreen.tsx
This PR proposes a fix for the credential catalog screen not navigating to the checks result screen on error.
The issue comes from the condition on the navigation `pot.isNone` which evaluates to true when the pot is in `NoneError` state, thus preventing the navigation to the result screen. 
- Removes the `pot.isNone` condition leaving only `pot.isLoading`. This is sufficient because we only want to navigate when the pot is not in a loading state and the loading index is not `-1`. 
If the pot is `none`, when the user opens the catalog, the condition will still fail due to the loading index being none. 
If the pot is `noneError` after the user selects a credential, then the navigation happens due to the loading index being different from none. However, if the pot is `noneError` because an …
> fix(IT Wallet): [SIW-695] Fix credentials issuing checks error navigation

- ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
- ts/features/it-wallet/screens/issuing/credential/ItwCredentialPreviewScreen.tsx
This PR introduces the bottom sheet for the `issued by` and `released by` claims in the preview and details screen of a credential. It also removes it from the `assistance` banner which now navigates to the not available screen.
- Adds two bottom sheets for each claim;
- Removes the bottom sheet from the `assistance` banner and adds a navigation the not available screen.
Try to obtain a new credential and test the bottom sheets for the two claims in the preview screen. Also test the navigation when pressing on the assistance banner. Then test them in the credential preview screen by single pressing it in the wallet home screen.
> chore(IT Wallet): [SIW-693,SIW-691] Add released by and issued by claims bottom sheet

- ts/features/it-wallet/screens/issuing/credential/ItwCredentialAuthScreen.tsx
This PR updates the credential issuer label in the auth screen of the credential issuing flow.
- Replaces mocked issuer name with the actual one.
Obtain a PID and then test a credential issuing flow. In the auth screen where the requested claims are shown, the issuer name label should be updated with the actual value.
> fix(IT Wallet): [SIW-697] Update credential issuer in issuing auth screen

- ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
- ts/features/walletV3/payment/screens/WalletPaymentBarcodeChoiceScreen.tsx
This PR resolves an issue with some Mixpanel events that are being sent repeatedly in the `BarcodeScanScreen` component
- Added `useCallback` inside `useFocusEffect` hooks
Navigating to the Barcode Scan screen, the corresponding screen view event `QRCODE_SCAN_SCREEN` should be sent only once, whenever the screen is focused.
> fix: [IOBP-425] Fix Mixpanel events in `BarcodeScanScreen`

- ts/features/it-wallet/components/ItwClaimsWrapper.tsx
- ts/features/it-wallet/components/ItwCredentialCard.tsx
- ts/features/it-wallet/screens/ItwHomeScreen.tsx
- ts/features/it-wallet/screens/issuing/credential/ItwCredentialPreviewScreen.tsx
- ts/features/it-wallet/screens/issuing/pid/cie/ItwPidPreviewScreen.tsx
- ts/features/it-wallet/screens/presentation/ItwPrCredentialDetails.tsx
- ts/features/it-wallet/screens/presentation/ItwPrPidDetails.tsx
- ts/features/it-wallet/utils/mocks.ts
This PR resolves a bug which causes the disappearance of the credential image between usage sessions. The issue is caused by the persistence of mock display data, in particular by the `require` result for the asset which is not constant between usage session. This inconsistency leads to the disappearance of the credential image when restarting the app.
- Instead of including the required assets in the display data which is then persisted, use the credential type to get the assets at runtime with the `getImageFromCredentialType` helper function.
Note that the `CredentialType` enum serves the purpose of avoiding the use of arbitrary strings to represent the credential type. Despite this, the credential type is still represented as a string to align with the library's typing requirements and …
> fix(IT Wallet): [SIW-699] Credential image disappearing from wallet

- ts/features/bonus/cgn/components/merchants/discount/OtpCodeComponent.tsx
This PR fixes OTP code timer issue for a CGN discount
- Added a check `finished` into Animated.timing function callback in order to check if the animation has reached the end
Open a CGN discount with an OTP and try to generate it, you should be able to show the code for some minutes
|Before|After|
|-|-|
| <video src="https://github.com/pagopa/io-app/assets/34343582/2a29e8a7-0e42-45c3-b205-80dab2ab2037" /> | <video src="https://github.com/pagopa/io-app/assets/34343582/3fc4ef33-b0a5-46e4-a260-201d18be86af" />
> fix: [PE-498] CGN OTP code timer issue

- ts/features/it-wallet/saga/new/itwIssuanceSaga.ts
This PR fixes an error which prevents the UI to show an error view while issuing a credential.
The issue is cased by a wrong dispatched action.
- Replaces the wrong action with the right one.
Static checks.
> fix(IT Wallet): [SIW-730] Fix credential issuance error not shown

- ts/features/it-wallet/components/ItwContinueView.tsx
- ts/features/it-wallet/screens/issuing/pid/ItwIssuingPidAuthInfoScreen.tsx
This PR reintroduces the CIE login bypass. It can be used by long pressing the pictogram in the following screen: 
It still remains enabled by default on iOS when pressing the confirmation button.
- Add the `onPictogramPress` optional prop for `ItwContinueView.tsx`;
- Add the bypass in the relative screen.
Test a PID issuing flow and try a long press on the pictogram in the aformentioned screen. It should bypass the CIE authentication.
> chore(IT Wallet): [SIW-722] Reintroduce CIE login bypass

- ios/Podfile.lock
- package.json
- yarn.lock
This PR updates `io-react-native-jwt` to the `1.1.0` version which fixes an issue during the credential issuing on Android. 
More on the issue in [this PR](https://github.com/pagopa/io-react-native-jwt/pull/22).
- Updates the dependency.
Test the credential issuing flow on Android and it should work as expected.
> chore(IT Wallet): [SIW-737] Update io-react-native-jwt library to 1.1.0

- locales/en/index.yml
- locales/it/index.yml
- package.json
- ts/components/screens/GenericErrorComponent.tsx
- ts/sagas/messages/watchThirdPartyMessageSaga.ts
- ts/screens/messages/MessageRouterScreen.tsx
- ts/screens/messages/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
- ts/store/reducers/entities/messages/messageGetStatus.ts
This PR updates the error message in the `MessageRouterScreen` if `getThirdPartyMessage` fails.
- updated error message in the `MessageRouterScreen`
- updated locales
Using `io-dev-api-server` generate a message with remote content that fails. Open the message detail, check that the error message is correctly displayed
> feat: [IOCOM-717] Update error message in the `MessageRouterScreen`

- ts/store/reducers/index.ts
This PR aims to prevent unintentional clear of the contextual help
- change rootReducer initialization
1. Open the app 
2. login 
3. check the contextual help from messages home
4. logout
5. login without closing the app
6. check again the contextual help, data should not be missing.
> fix: [IABT-1474] Avoid clearing contextual help data on logout

- ts/features/idpay/timeline/components/TimelineDetailsBottomSheet.tsx
This PR fixes an issue with the visualization of the correct details component in ID Pay timeline item.
- [ts/features/idpay/timeline/components/TimelineDetailsBottomSheet.tsx](https://github.com/pagopa/io-app/compare/IOBP-467-3-sp-nel-dettaglio-del-pagamento-visualizziamo-un-messaggio-non-corretto?expand=1#diff-290dfda62f62d0a913eb406f4e342bfd3b05c46736f47193e32eed53fae9a073): added correct check in conditional rendering
With the `io-dev-api-server`, navigate to the details screen of an initiative, check that `RTD` channel transactions are displayed correctly.
> fix: [IOBP-467] Add correct details component in ID Pay timeline transaction item

- ts/navigation/TabNavigator.tsx
- ts/navigation/components/HeaderFirstLevelHandler.tsx
This PR fixes an issue that showed the wrong header while navigating to any home section 
- Change the logic of `HeaderFirstLevelHandler` to check the current route stored on redux
- removes listeners on tab navigator
Check flows like payment starting from a message, once completed reach the wallet home screen, the header should be correct
> fix: [IOPLT-304] HeaderFirstLevelHandler logic on current route selector instead of local status

- ts/config.ts
This PR is going to update the `tosVersion` config to 4.7 in order to forcefully show the ToS screen to the user.
- Bumped `tosVersion` to `4.7`
The ToS screen should be visible after opening the app
> feat: [IOCOM-740] Update `tosVersion` to 4.7

- ts/screens/profile/CduEmailInsertScreen.tsx
This PR fixes the missing error toast inside `CduEmailInsertScreen`.
<p>
<video src="https://github.com/pagopa/io-app/assets/16268789/961b10ab-0694-4bfe-9fee-a6d283a6c2ca" />
</p>
</details> 
Modify your profile email simulating an HTTP error (with proxyman or io-dev-api-server) and check that an error snackbar is shown.
> fix: [IOPID-1267] Chore: fix toast

- android/app/src/main/AndroidManifest.xml
- ios/ItaliaApp/Info.plist
- ios/ItaliaApp/it.lproj/InfoPlist.strings
This PR updates `Info.plist` and `AndroidManifest.xml` adding BLE permission as describe on [react-native-ble-manager](https://github.com/innoveit/react-native-ble-manager) repo.
- https://github.com/innoveit/react-native-ble-manager?tab=readme-ov-file#android---update-manifest
- https://github.com/innoveit/react-native-ble-manager?tab=readme-ov-file#ios---update-infoplist
- Update AndroidManifest.xml
- Update Info.plist
Static checks should be enough
> chore(IT Wallet): [SIW-772] Add `BLE` permissions for `iOS` and `Android`

- patches/cipher-base+1.0.4.patch
This PR adds a patch to `cipher-base` package to solve an "issue" during proximity verification flow. It could be related on how `io-app` do the bundle of sub-dependencies (like import/export issue). The patch is also related to these issues on other repositories:
- https://stackoverflow.com/questions/74413490/uncaught-typeerror-cannot-read-properties-of-undefined-reading-call-at-hash
- https://github.com/browserify/cipher-base/issues/10
- Add patch file using patch-package
Static checks should be enough.
> chore(IT Wallet): [SIW-773] Add patch to `cipher-base` package

- ts/features/it-wallet/store/actions/index.ts
- ts/features/it-wallet/store/actions/itwProximityActions.ts
- ts/features/it-wallet/store/reducers/index.ts
- ts/features/it-wallet/store/reducers/itwProximityReducer.ts
This PR adds actions and reducers for proximity flow.
NOTE: this is an experimental proposal to get proximity flow using redux-saga and could change in the future
- Add actions
- Add reducers
Static checks should be enough
> chore(IT Wallet): [SIW-778] Add actions and reducer for proximity flow

- ts/components/messages/MessageDetail/index.tsx
This PR avoids displaying the section title if there are no attachments.
<p>
| before | after |
| - | - |
| <img src="https://github.com/pagopa/io-app/assets/29163287/4ef8ba82-5b04-44c6-8809-bbe6b543e109" width="300" /> | <img src="https://github.com/pagopa/io-app/assets/29163287/25ced45a-a47a-4257-a98c-de9f23508d3f" width="300" /> | 
</p>
</details> 
- updated `hasThirdPartyDataAttachments` in order to not display the section title
Using io-dev-api-server, generate a message without attachments. Open the message detail and check that the section title is not displayed.
> fix: [IOCOM-759] Remove the section title if there are no attachments

- ts/features/messages/components/PreconditionBottomSheet/PreconditionHeader.tsx
This PR adjusts the right margin of the title text of the precondition bottom sheet.
- Styles for the H3 element where the text is displayed
Using the io-dev-api-server, check that the text wraps around the title assigned space
> fix: [IOCOM-761] Text wrapping for precondition's title text

- patches/react-native+0.69.9.patch
This PR fixes a previously applied patch on react-native which caused a build failure
- react-native+0.69.9 patched to add the Android READ_MEDIA_IMAGES permission
Check that all static checks succeed and run android
> Fix: failing Android build

- ts/config.ts
This PR bumps the ToS version from `4.7` to `4.8`
Run the app against the dev server. Either on first onboarding/onboarding or after a successful identification, you should see the ToS screen to accept the new ToS.
> chore: [IOPID-1301] Bump ToS version from 4.7 to 4.8

- ts/features/walletV3/payment/components/WalletPaymentConfirmContent.tsx
This PR removes the cardholder information into `WalletPaymentConfirmScreen` if the user chooses a payment with cards.
- Into `WalletPaymentConfirmContent` the user holder as payment subtitle has been removed.
- Start a payment flow through the `New wallet Playground`;
- Select a credit card as payment method;
- When you reach the end of the payment, you should be able to see only the expiration date of the card
|Before|After|
|-|-|
|<img src="https://github.com/pagopa/io-app/assets/34343582/1270f0c3-b485-42c2-8bd1-952ad602de78)" width="300" /> | <img src="https://github.com/pagopa/io-app/assets/34343582/fd1fb805-d8a8-45f4-8543-8183cf91197f)" width="300" />
> feat: [IOBP-480] Remove holder name from wallet payment confirm screen

- locales/en/index.yml
- locales/it/index.yml
- ts/features/walletV3/payment/components/WalletPaymentMissingMethodsError.tsx
- ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
- ts/features/walletV3/payment/store/selectors/index.ts
This PR adds the (temporary) missing methods error in methods selection screen
- Refactored `WalletPaymentPickMethodScreen` to allow the error to be displayed
- Added `WalletPaymentMissingMethodsError` component
- Added required locale keys
With the `io-dev-api-server`, simulate an empty user wallet. Start a new payment from **Profile > New Wallet > Payment** and check if the error is displayed correctly and with working buttons.
https://github.com/pagopa/io-app/assets/6160324/65f4d64f-6980-4d36-a82d-873ccf505b5e
> chore: [IOBP-479] Add temporary missing methods error in method selection screen

- ts/features/barcode/screens/BarcodeScanScreen.tsx
This PR enables the back navigation using hardware buttons on Android
- `ts/features/barcode/screens/BarcodeScanScreen.tsx`: added `useHardwareBackButton`
Within the Barcode scan screen, try to navigate back using Android hardware back button.
> chore: [IOBP-486] Add hardware button back navigation in Barcode scan screen for Android devices

- locales/en/index.yml
- locales/it/index.yml
- ts/screens/onboarding/UnlockAccessScreen.tsx
Make some styles/copy fix 
- Modify icons name
- modify texts ([figma here](https://www.figma.com/file/2BZhyc0qxN31sF6npvbeTh/IO-Esco?node-id=5159%3A15614&mode=dev))
Log in with CIE or SPID and select the error "Utente con identità bloccata da ioapp.it"
> chore: [IOPID-1227] Fix bottomsheet error 1002

- locales/en/index.yml
- locales/it/index.yml
- ts/features/walletV3/transaction/components/WalletTransactionHeadingSection.tsx
- ts/features/walletV3/transaction/screens/WalletTransactionDetailsScreen.tsx
- ts/features/walletV3/transaction/store/index.ts
fix of a small bug which didn't make a part of the screen render
- removed dead code
- small logic fix
- addition of I18n keys for when there is no PSP name
- small refactors
with the `dev-server` active, navigate to wallet, then down to the transaction history.
done that, open up a transaction's details and make sure that
a. the screen is correctly rendered
b. there is a "fee" info in the top part as in the screenshot (in case it does not render, try opening another op's details, since it is expected to be *possibly* missing sometimes
c. the screen correctly displays in a loading state when loading
> fix: [IOBP-462] Missing transaction details data

- ts/features/walletV3/common/saga/index.ts
- ts/sagas/startup.ts
This PR fixes and sets the correct wallet token for the new wallet flows.
- Edited the previous `bpdToken` to `walletToken` to the wallet v3 sagas
Start the app in UAT env enabling the pagoPA test toggle, you should be able to successfully call any wallet v3 API
> fix: [IOBP-501] Wallet token into new wallet flows

- ts/navigation/AuthenticationNavigator.tsx
- ts/screens/authentication/LandingScreen.tsx
This PR fixes the continuously displaying of the Tablet compatibility alert during the login flow. It took the chance to refactor the `LandingScreen` from `PureComponent` to `FunctionComponent`. 
<p>
| ❌ | ✅ |
| - | - |
| <video src="https://github.com/pagopa/io-app/assets/16268789/68836f13-88f9-41a5-98a6-eceea56de750" />  | <video src="https://github.com/pagopa/io-app/assets/16268789/0e6e24ff-31a2-4aef-958e-0402564629e6" /> |
</p>
</details> 
Launch the app on an Android Tablet and check that the Alert is shown only at every first render of `LandingScreen`.
> feat: [IOPID-1391] Fix tablet compatibility alert displaying

- ts/navigation/AppStackNavigator.tsx
- ts/navigation/NavigationService.ts
- ts/sagas/startup.ts
This PR tries to synchronize the Main stack navigator with the startup saga business logic.
It uses the `waitForMainNavigator` generator function that acts like `waitForNavigatorServiceInitialization`.
- Run the app and during a first onboarding, before reaching the pin creation screen, re-launch the app. You'd navigate to the last screen where you was before re-launching the app. 
- Try different login flows, you'd be reach the messages home all the times.
> chore: [IOPID-1298,IOPID-1396] `Main` stack navigator - `startup` saga synch

- locales/en/index.yml
- locales/it/index.yml
- ts/features/walletV3/details/screens/WalletDetailsScreen.tsx
This PR implements the new generic error screen using the `OperationResultScreenContent` component.
- Removed from `WalletDetailsScreen` the old and deprecated `WorkunitGenericFailure` with the new one
Start and complete an onboarding flow with a new card and when you are in the method details screen, try to force an error on that page.
|Before|After|
|-|-|
| <img src="https://github.com/pagopa/io-app/assets/34343582/4804c505-b4df-4334-b33d-d2b786b18871" width="300" /> | <img src="https://github.com/pagopa/io-app/assets/34343582/1290f81c-6e18-468b-884c-31605a162f60" width="300" /> |
> fix: [IOBP-512] Wallet details with new generic error screen

- ts/screens/profile/CduEmailInsertScreen.tsx
During tests, we realised that in the firs onboarding scenario, the CIT who logs in using SPID and has a valid email, does not see his pre-filled email and if he tries to enter it, an error is displayed that does not allow him to continue. 
So, in this PR we are going to fix this bug. 
<p>
| ❌ | ✅ |
| - | - |
| <video src="https://github.com/pagopa/io-app/assets/83651704/9eb94d8a-a9c8-49d2-add8-4c516c49cc37" /> | <video src="https://github.com/pagopa/io-app/assets/83651704/827f6cf8-ed63-45c1-bce8-8a4b77cf8478" /> |
</p>
Run the application as first onboarding and test all cases
> fix: [IOPID-1408] Fix cdu email insert screen logic 

- ts/utils/permission.ts
This PR removes an unnecessary gallery permission request on iOS.
- Removed iOS case in `requestMediaPermission` function
From the QR Code scan screen, choose the upload photo option and check that on iOS no prompt is displayed.
<video src="https://github.com/pagopa/io-app/assets/6160324/d6bfab14-2a8b-41dd-b77b-2f6d343ed974" />
> chore: [IOBP-517] Removes unnecessary gallery permission on iOS 

- ts/features/bonus/cgn/__e2e__/cgn.e2e.ts
This PR fixes a problem on the E2E CGN test, where the card view is reported as not scrollable.
- the scroll method has been try-catched, since the error appears when the view has already reached its bottom
Run the E2E tests.
> chore: fix CGN e2e test scroll

- ios/Podfile.lock
This PR updates the `Podfile.lock` after the `io-react-native-login-utils` update of [this](https://github.com/pagopa/io-app/pull/5474) PR.
Run `yarn` and `cd ios && bundler exec pod install && cd ..`. Finally, run `git status` and ensure that there are no changes.
> chore(Cross): [IOAPPX-246] Update `Podfile.lock` for `io-react-native-login-utils`

- locales/en/index.yml
- locales/it/index.yml
- package.json
- ts/components/__tests__/__snapshots__/LoadingSpinnerOverlay.test.tsx.snap
- ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
- ts/features/messages/screens/MessageAttachment.tsx
- ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
- yarn.lock
This PR removes the OPEN CTA on an attachment's preview, on Android devices.
- Open CTA removed
- Proper accessibility labels for remaining CTAs
- New DS version that improves accessibility readings on CTA buttons for Android
- Updated snapshots
Using the io-dev-api-server, check that on an Android devices the two remaining CTA still work as expected (accessibility included)
> feat: [IOCOM-1059] Remove 'Open' CTA on Android attachment preview (new DS)

- ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetUserWallets.ts
This PR handles the 404 response from the user wallet list as an empty list instead of showing a generic error screen.
- Added a result status check to verify if the status is 404, it will be treated as an empty wallet list
- Edit the response of the e-commerce wallet list from the `io-dev-app-server` to return a 404 status response
- Start a payment flow from the playground section
- As soon as you get the user wallet list, you should be able to see a screen that invites the user to onboard a new payment method instead of showing a generic error screen
|Before|After|
|-|-|
|<video src="https://github.com/pagopa/io-app/assets/34343582/82148601-6bf1-48b5-a418-859f7cae6660" /> | <video src="https://github.com/pagopa/io-app/assets/34343582/dcda0224-54a2-47a1-8b85-f14f4e88fb97" />
> chore: [IOBP-557] Handled 404 response status with empty list from user wallet list

- ts/features/messages/components/MessageAttachment/MessageAttachment.tsx
- ts/features/messages/components/MessageDetail/index.tsx
- ts/features/messages/hooks/useAttachmentDownload.tsx
- ts/features/messages/navigation/MessagesNavigator.tsx
- ts/features/messages/navigation/params.ts
- ts/features/messages/screens/MessageAttachmentScreen.tsx
- ts/features/messages/screens/MessageCalendarScreen.tsx
- ts/features/messages/screens/MessageDetailsScreen.tsx
- ts/features/messages/screens/MessageRouterScreen.tsx
- ts/features/messages/screens/__tests__/MessageAttachment.test.tsx
- ts/features/messages/store/actions/navigation.ts
- ts/features/pn/components/LegacyMessageDetails.tsx
- ts/features/pn/navigation/navigator.tsx
- ts/features/pn/navigation/params.ts
- ts/features/pn/screens/LegacyAttachmentPreviewScreen.tsx
- ts/features/pn/screens/MessageAttachmentScreen.tsx
- ts/features/pn/screens/MessageDetailsScreen.tsx
- ts/features/pn/screens/PaidPaymentScreen.tsx
- ts/features/pn/screens/__test__/PaidPaymentScreen.test.tsx
- ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
This PR updates message attachment preview. The preview has been updated by sharing the `MessageAttachment` component between standard messages and SEND messages.
- converted the `MessageAttachment` screen into a component
- created the screen `messages/screens/MessageAttachmentScreen.tsx`
- created the screen `pn/screens/MessageAttachmentScreen.tsx`
- updated the params naming convention
Using `io-dev-api-server`, generate messages with attachments. Navigate to the message attachment preview and check that everything is displayed correctly.
> feat: [IOCOM-881] Update message attachment preview

- ts/features/walletV3/payment/screens/WalletPaymentDetailScreen.tsx
- ts/screens/wallet/payment/components/TransactionSummary.tsx
This PR moves the currency symbol to the right of the amount text
- Added the "right" value to the utility function for both TransactionSummary (the old one) and TransactionSummaryScreen (the new one)
- Start a payment process, inside the page you should be able to see the "Amount" label with the currency symbol at the end
> chore: [IOBP-572] Move currency symbol to the right of the amount

- ts/features/messages/navigation/MessagesNavigator.tsx
This PR fixes the double header shown on the message details screen.
- output of isDesignSystemEnabledSelector is checked against undefined values
Check that the message details screen does not have a double navigation header.
> fix: [IOCOM-1154] Fix for double navigation bar on message details

- ts/features/messages/navigation/MessagesNavigator.tsx
- ts/store/reducers/persistedPreferences.ts
This PR fixes the double navigation bar by addressing an `undefined` value in the redux store.
- `isDesignSystemEnabled` may have the `undefined` value in some cases. Comments have been added to explain the anomaly and the related selector has been changed to make sure that no `undefined` value is returned
Check that no double navigation bar is displayed on a message details.
> fix: [IOCOM-1154] Fix for `undefined` value on `isDesignSystemEnabled` (and double navigation bar)

- package.json
- ts/features/fci/components/SignatureFieldItem.tsx
- ts/features/fci/components/__tests__/__snapshots__/SignatureFieldItem.test.tsx.snap
- yarn.lock
This PR upgrade `io-app-design-system` to `v.1.25.1` that solves some accessibility issues
- Start the app and try to use the `ListItemCheckbox` component.
- Using the Accessibility inspector check whether the accessibility label and checkbox state are read correctly.
> chore(Cross): [IOAPPX-259] Upgrade `io-app-design-system` to `v.1.25.1`

- ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
- ts/features/messages/saga/handlePaymentUpdateRequests.ts
- ts/features/messages/saga/index.ts
- ts/features/messages/saga/watchPaymentUpdateRequests.ts
- ts/features/messages/store/actions/index.ts
- ts/features/messages/store/reducers/__tests__/payments.test.ts
- ts/features/messages/store/reducers/index.ts
- ts/features/messages/store/reducers/payments.ts
- ts/features/pn/components/MessageFooter.tsx
- ts/features/pn/components/MessagePaymentBottomSheet.tsx
- ts/features/pn/components/MessagePaymentItem.tsx
- ts/features/pn/components/MessagePayments.tsx
- ts/features/pn/components/__test__/MessagePaymentItem.test.tsx
- ts/features/pn/components/__test__/MessagePayments.test.tsx
- ts/features/pn/screens/LegacyMessageDetailsScreen.tsx
- ts/features/pn/screens/MessageDetailsScreen.tsx
- ts/features/pn/store/actions/index.ts
- ts/features/pn/store/reducers/index.ts
- ts/features/pn/store/sagas/watchPaymentStatusSaga.ts
- ts/features/pn/store/sagas/watchPnSaga.ts
- ts/features/pn/utils/index.ts
- ts/sagas/startup.ts
This PR moves actions, reducer and saga to handle a message payment update from PN to general messages.
- Related files have been moved and renamed
- Redux `payments` entity has been moved from `pn` to `messages` (since it is not persisted, it does not need a migration)
Using the io-dev-api-server, check that, on a PN message, payments are still updated properly.
> feat: [IOCOM-858] Generic payment update for messages

- ts/features/payments/payment/components/WalletPaymentConfirmContent.tsx
- ts/features/payments/payment/components/WalletPaymentHeader.tsx
- ts/features/payments/payment/screens/WalletPaymentPickMethodScreen.tsx
- ts/features/payments/payment/screens/WalletPaymentPickPspScreen.tsx
- ts/features/payments/payment/store/__tests__/store.test.ts
- ts/features/payments/payment/store/actions/orchestration.ts
- ts/features/payments/payment/store/reducers/index.ts
- ts/features/payments/payment/types/index.ts
This PR fixes the behavior when the user goes back from the confirmation screen with a payment method that has only one PSP. 
- Added a check inside the wallet payment header go back handler, if the user is at the third step and the current method has only one PSP, it must be redirected to the first step (selecting the payment method), otherwise go back selecting the PSP from the PSP list screen
- Start a payment inside the new payment playground and choose a payment method with only one PSP
- When you reach the confirmation page, try to go back: You should be redirected to the pick payment method screen
|Before|After|
|-|-|
|<video src="https://github.com/pagopa/io-app/assets/34343582/2f0b81be-25d8-4420-a86a-9c6e63e736ff" />|<video …
> fix: [IOBP-582] Behavior of the new payment go back with only one PSP

- locales/en/index.yml
- locales/it/index.yml
- ts/features/payments/payment/screens/WalletPaymentOutcomeScreen.tsx
This PR adds the user email to the payment outcome 17 description if available, otherwise shows a generic description.
- Edited the description text from the locales;
- Added the email selector to get the user email from the `WalletPaymentOutcomeScreen`
- Start a new payment flow from the playground
- Reach the webview and select from the dropdown outcome list the outcome number `17`
> chore: [IOBP-568] Add email to payment outcome 17 description

- .env.local
- .env.production
- ts/config.ts
- ts/mixpanel.ts
This PR moves the Mixpanel URL into our env file.
- Adds the URL in `.env.local` and `.env.production`;
- Adds the constant in `config.ts`; 
- Remove the hardcoded URL from `mixpanel.ts`.
Test if Mixpanel events are tracked properly.
> chore(Cross): [IOAPPX-282] Move Mixpanel URL into env file

- ts/screens/modal/SystemOffModal.tsx
- ts/store/reducers/backendStatus.ts
This PR removes the use of `reselect` introduced in `backendStatus` selector, because it's redundant.
It uses `lodash` to do a deep equality comparison in the `SystemOffModal`, to avoid unnecessary re-rendering.
@Vangaorth
> fix: restore `backendStatus` previous selector

- ts/features/services/details/components/ServiceDetailsMetadata.tsx
- ts/features/services/details/components/ServiceDetailsPreferences.tsx
- ts/features/services/details/components/ServiceDetailsTosAndPrivacy.tsx
- ts/features/services/details/screens/ServiceDetailsScreen.tsx
This PR fixes the wrong margins in `ServiceDetailsScreen`
<p>
| preferences  |
| - |
| <video src="https://github.com/pagopa/io-app/assets/29163287/9a6c1acb-10dc-443b-a59d-3bc56017c174" width="300"/> |
</p>
</details> 
- removed the `ContentWrapper` component from `ServiceDetailsScreen`
- added padding to Flatlists in `ServiceDetailsScreen`
Using `io-dev-api-server`, navigate to the services tab and tap a service. Tap on the list items to check that the margin is displayed correctly.
> fix: [IOPAE-1125] Wrong margins in `ServiceDetailsScreen`

- ts/features/payments/transaction/screens/PaymentsTransactionOperationDetails.tsx
This PR fixes the a11y values into the new transaction operation details screen in order to spell correctly the value of each list item
- Removed the `accessibilityLabel` override for the list items
Enable the DS feature flag and navigate to the transactions list, then inside of it you should be able to use the voice-over to listen to the values in the correct way
https://github.com/pagopa/io-app/assets/34343582/b914a74a-33f8-4c54-8e3b-b608079cc314
> fix: [IOBP-554] Removed A11y override into transaction operation details

- ts/screens/authentication/LandingScreen.tsx
This PR fixes the `Carousel`'s translations in `LandingScreen` that didn't follow the citizen's locale.
<p>
| ❌ wrong | ✅ 🤖 | ✅ 🍏 | 
| - | - | - | 
| <video src="https://github.com/pagopa/io-app/assets/16268789/5a2ab9ed-cb55-409e-9844-70c303959b74" /> | <video src="https://github.com/pagopa/io-app/assets/16268789/eec186fc-2f3c-47b7-9199-25187eb1fe26" /> | <video src="https://github.com/pagopa/io-app/assets/16268789/cc8d800f-789a-46e3-94c2-6b83191a8931" />
</p>
</details> 
Login with the dev-server with a citizen that has chosen an `EN` locale, then logout and check that the carousel is translated in english as the all page.
> fix: `LandingScreen`'s `Carousel` translations

- locales/en/index.yml
- locales/it/index.yml
- ts/features/services/home/hooks/useInstitutionsFetcher.tsx
- ts/features/services/home/screens/ServicesHomeScreen.tsx
This PR adds button in services tab to navigate the search screen
<p>
| services |
| - | 
| <video src="https://github.com/pagopa/io-app/assets/29163287/7edd0401-009e-4a8c-b459-ce690ddec96e" width="300"/> |
</p>
</details> 
- added button in services tab
- updated locales
Using `io-dev-api-server`, navigate to the services tab. Check that the button is present at the end of the institution list.
> chore: [IOPAE-1212] Added button to navigate the search screen

- locales/en/index.yml
- locales/it/index.yml
- ts/components/services/ServiceMetadata/__tests__/__snapshots__/InformationRow.test.tsx.snap
- ts/features/services/common/components/EmptyState.tsx
Update Services Search `EmptyState` component copy and font size.
- Update copy
- Update font from H3 to H6
Navigate to services search screen to better appreciate changes.
> chore: [IOPAE-1213] Update Services Search EmptyState copy and font size

- ts/screens/wallet/WalletHomeScreen.tsx
This PR removes the feature flag on the new transaction details screen with the current interface
- Removed check on the design system feature flag to navigate to the new transaction details screen
Disable the new design system feature flag and navigate to a transaction details with the old transaction list
https://github.com/pagopa/io-app/assets/34343582/ec4e4228-960e-472e-8f55-dd7e014e596e
> chore: [IOBP-635] Removed FF from the new transaction details screen

- ts/features/services/home/screens/ServicesHomeScreen.tsx
This PR restores the scroll to top action in the `ServicesHomeScreen`.
<p>
| services |
| - | 
| <video src="https://github.com/pagopa/io-app/assets/29163287/baffc4b4-82da-4cf6-965b-7275118f63bd" width="300"/> |
</p>
</details> 
see commit list
Navigate to the services tab, scroll down and then tap on the services tab. Check that the screen scrolls to top when tapping on the active tab
> chore: [IOPAE-1240] Restore scroll to top in the `ServicesHomeScreen`

- ts/features/services/home/hooks/useInstitutionsFetcher.tsx
- ts/features/services/home/screens/ServicesHomeScreen.tsx
- ts/features/services/institution/screens/InstitutionServicesScreen.tsx
This PR solves an infinite loop of the `onEndReached` function. This bug occurs when list height is incremented during data load and reduced when data load fails (a common practice to display a loading skeleton).
<p>
| endless loop |
| - | 
| <video src="https://github.com/pagopa/io-app/assets/29163287/bf706906-3a31-4183-8060-45a41b4dbf99" /> |
</p>
| fix endless loop |
| - | 
| <video src="https://github.com/pagopa/io-app/assets/29163287/8afc3639-547c-4b3f-bac0-bd101fdff3a5"/> |
</p>
</details> 
- Added a guard to prevent endless loop
Try to reproduce the same actions shown in the video.
> chore: [IOPAE-1249] Fix the endless loop of FlatList's `onEndReached`

- locales/en/index.yml
- locales/it/index.yml
- package.json
- ts/features/services/common/navigation/navigator.tsx
- ts/features/services/common/navigation/params.ts
- ts/features/services/home/components/FeaturedInstitutionList.tsx
- ts/features/services/home/components/FeaturedServiceList.tsx
- ts/features/services/home/screens/ServicesHomeScreen.tsx
- ts/features/services/search/hooks/useInstitutionsFetcher.tsx
- ts/features/services/search/screens/SearchScreen.tsx
- ts/navigation/AuthenticatedStackNavigator.tsx
- ts/navigation/components/HeaderFirstLevelHandler.tsx
- ts/navigation/params/AppParamsList.ts
- yarn.lock
The main purpose of this PR is to improve the usability and overall experience of the services search section.
<p>
| services |
| - | 
| <video src="https://github.com/pagopa/io-app/assets/29163287/e7c6b067-255e-472c-8831-7826d71447e1" /> |
</p>
</details> 
- enabled gesture on all services sub-routes (except on SearchScreen)
- removed transition on `SearchScreen` component
- removed `useHeaderSecondLevel` on `SearchScreen` component
- added `handleCancel` callback to navigate back
- update locales
- bump `@pagopa/io-app-design-system` to `1.38.5`
- minor layout fixes
Using `io-dev-api-server`, navigate to the services tab. Check that the search works as expected.
> chore: [IOPAE-1235] Search screen enhancements

- package.json
- ts/features/services/search/screens/SearchScreen.tsx
- ts/navigation/AuthenticatedStackNavigator.tsx
- yarn.lock
This PR depends on https://github.com/pagopa/io-app-design-system/pull/289
This PR sets `keepCancelVisible` prop to true on SearchInput component.
<p>
| SearchInput |
| - | 
| <video src="https://github.com/pagopa/io-app/assets/29163287/20838c71-f3b2-485a-b50f-205bfb7dd58d" width="300"/> |
</p>
</details> 
- bump `@pagopa/io-app-design-system` to 1.39.1
- set `keepCancelVisible` prop to true on SearchInput
- set `keyboardDismissMode` prop to `interactive` for ios and `on-drag` as default
using `io-dev-api-server`, navigate to services search screen and check that the cancel button is always visible when input loses focus
> fix: [IOPAE-1253] Set `keepCancelVisible` prop to true on SearchInput

- ts/screens/profile/DeveloperModeSection.tsx
This PR makes the Push Notification token available in the profile section when the developer mode is enabled.
- Removed the guard that prevented the token to be shown when in production
Run the application and check that the token is visibile when the dev mode is enabled.
> chore: [IOCOM-1541] Show push notification token in the profile section (dev mode on)

- ios/ItaliaApp/Info.plist
- ios/ItaliaApp/ItaliaApp.entitlements
This PR removes `NDEF` as `NFC` format for iOS. We discovered an issue after setting the deployment version to `14.0` while sending the app for approval: 
`18:02:19]: ERROR: [ContentDelivery.Uploader] Asset validation failed (90778) Invalid entitlement for core nfc framework. The sdk version '17.2' and min OS version '14.0' are not compatible for the entitlement 'com.apple.developer.nfc.readersession.formats' because 'NDEF is disallowed'. (ID: 8d8d0695-b5a8-4108-8b07-74211c7ae133)`
The removal of `NDEF` should be safe as our CIE SDK uses [NFCTagReaderSession](https://github.com/pagopa/io-cie-ios-sdk/blob/b7c63653d85eb28ff81841b89f99dceb9c64026d/ciesdk/iociesdkios/CIEIDSdk.swift#L133) with [iso14443](https://developer.apple.com/documentation/corenfc/nfctagreadersession/pollingoption/3043850 …
> chore(Cross): [IOAPPX-327] Remove NDEF as NFC format for iOS

- ts/features/messages/components/Home/DS/DoubleAvatar.tsx
This PR fixes a regression in `getImageState` on `DoubleAvatar`.
- Proper handling of input when it is of type `number` or `ImageURISource`
Check the code against the one in `Avatar` (DS) and verify that, given an input, the output is the same.
> [IOCOm-1553] Proper logic for `getImageState` on `DoubleAvatar`

- ts/components/ui/LoadingIndicator.e2e.ts
- ts/components/ui/RefreshIndicator.tsx
This PR fixes the issue where E2E tests hang after displaying a `LoadingIndicator`.
> [!tip]
> [![Run e2e tests](https://github.com/pagopa/io-app/actions/workflows/test-e2e.yml/badge.svg?branch=cross-fix-e2e-tests)](https://github.com/pagopa/io-app/actions/workflows/test-e2e.yml)
- Replaced `LoadingIndicator` with `RefreshIndicator` for E2E tests.
Run E2E tests locally.
> fix(Cross): [IOAPPX-335] E2e tests hanging forever

- ts/screens/profile/SecurityScreen.tsx
When the pin change flow is triggered, the `IdentificationModal` used for validating certain in-app operations will be shown instead of the one used for app login. This variant is closable, unlike the previously implemented one.
- Changed `IdentificationModal` variant.
Navigate to `Profile -> Security -> Change the unlock code` to trigger the pin change flow.
> chore: [IOPID-1999] - Change IdentificationModal behavior displayed on PIN change operation 

- ios/Podfile.lock
- package.json
- ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
- ts/features/fims/singleSignOn/types/index.ts
- yarn.lock
This PR updates the FIMS consents types and the native HTTP client version
- Updated FIMS consents type
- HTTP Client version to 1.0.5 (support for empty body serialisation on iOS and support for serialisation error on both platforms)
Using the io-dev-api-server, check that the FIMS flow succeeds.
> chore: [IOCOM-1578] Updated types for FIMS consents, latest Http Client version

- scripts/ts/common/slack/postMessage.ts
Minor fix to restore message on release completed to slack channel
[Latest message](https://pagopaspa.slack.com/archives/CQVJ1JES2/p1720616295842229) was sent from local env
> fix: import URL on postMessage script to send slack message on release completed

- .eslintrc.js
- ts/components/AppVersion.tsx
- ts/components/ContextualInfo.tsx
- ts/components/__tests__/TosWebviewComponent.test.tsx
- ts/components/screens/IdpCustomContextualHelpContent.tsx
- ts/components/ui/LoadingIndicator.tsx
- ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
- ts/features/fastLogin/screens/FastLoginModals.tsx
- ts/features/fci/components/__tests__/__snapshots__/LoadingComponent.test.tsx.snap
- ts/features/lollipop/screens/UnsupportedDeviceScreen.tsx
- ts/features/payments/common/utils/index.ts
- ts/features/pn/components/LegacyMessagePayments.tsx
- ts/features/pn/components/MessagePayments.tsx
- ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx
- ts/screens/profile/playgrounds/MarkdownPlayground.tsx
This PR fixes all the wrong `I18n` imports (`import I18n from "i18n-js"`), replacing them with the right ones (`ts/i18n.ts`) and adds a **lint** rule for it (`import I18n from "i18n-js"`)
It also takes the chance to add a **lint** rule for this wrong import too: `import { pot } from "@pagopa/ts-commons";`.
> fix(Cross): I18n imports

- ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
- ts/navigation/AuthenticatedStackNavigator.tsx
This PR fixes an issue with the wallet onboarding screen
- Removed FF for ITW screen
- Added FF for ITW credential catalog in wallet onboarding screen
You should be able to navigate to the wallet onboarding screen by tapping on the "Add to wallet" CTA. Make sure that credentials catalog are visible only if the **IT Wallet** FF is enabled.
> fix(IT Wallet): [SIW-1361] Fix wallet onboarding screen

- ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
- ts/features/messages/components/MessageDetail/OrganizationHeader.tsx
- ts/features/messages/components/MessageDetail/__tests__/MessageDetailsHeader.test.tsx
- ts/features/messages/components/MessageDetail/__tests__/OrganizationHeader.test.tsx
- ts/features/messages/screens/MessageDetailsScreen.tsx
- ts/features/pn/components/MessageDetails.tsx
This PR adds the double avatar on standard message details, when the message contains a payment.
- Double avatar instead of Avatar if the message has payment data
Using the io-dev-api-server, check that a message with payment shows the double avatar. Also check that standard messages and SEND ones do not.
> chore: [IOCOM-1549] Double avatar standard message detail

- ts/features/messages/components/Home/DS/CustomPressableListItemBase.tsx
- ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
This PR fixes the single row items on the message list, so that the background selection fills the whole cell.
- Internal view of pressable set to expand and justify its content
Using the io-dev-api-server, check that the selection feedback fill the entire cell.
> [IOCOM-1611] Proper selection feedback for single row message items

- ts/features/services/details/components/ServiceDetailsMetadata.tsx
This PR fix the _"copy to clipboard"_ value of `organizationFiscalCode` list item in **ServiceDetailsScreen**.
Before the fix, the `serviceId` value was mistakenly copied instead of `organizationFiscalCode`.
In any service detail, scroll through the service details and tap on the _OrganizationFiscalCode_ item.
Paste the copied value outside the app _(for example on a notepad)_ and you'll be able to verify that it is exactly the `OrganizationFiscalCode` shown in the tapped info list item.
> fix: [IOPAE-1315] Fix organizationFiscalCode copy to clipboard value in service details screen

- ts/features/fims/singleSignOn/saga/handleFimsAbortOrCancel.ts
- ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
- ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
- ts/features/fims/singleSignOn/saga/handleFimsResourcesDeallocation.ts
- ts/features/fims/singleSignOn/saga/sagaUtils.ts
- ts/features/fims/singleSignOn/store/reducers/index.ts
Fixed a cookie related problem that caused a decode error when running the FIMS flow for the second time in the same session, when on an iOS device
- added cookie clearing for the RP domain at the end of a FIMS auth flow (any exit/end case)
using an iOS device, with the PROD env, run a fims flow, and then re-run it without exiting the app.
do so a couple of times in succession, and make sure that no decode error ever appears.
> fix: [IOCOM-1612] BUGFIX: FIMS decode error in iOS

- ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
- ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
- ts/features/fims/singleSignOn/saga/sagaUtils.ts
addition of validity checks for the FIMS flow starting CTA
- moved some utility functions to a shared file
- added valid redirect check for the cta response
- added baseUrl check for the CTA response
using the dev-server, while checked out in the FIMS branch, run the fims flow and make sure nothing breaks.
Furthermore, you can update the relyingPartyRouter in the dev-server to return a wrong url, so that the wrong redirect error will be triggered.
> fix: [IOCOM-1620] FIMS validity checks on flow starting CTA

- ts/features/itwallet/common/components/ItwCredentialClaim.tsx
- ts/features/itwallet/common/utils/itwClaimsUtils.ts
- ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
This PR removes the `TINIT` prefix from the fiscal code claim during the visualisation.
- Adds a `FiscalCodeClaim` decoder which uses a regex to parse a fiscal code with the `TINIT` prefix; 
- Adds the aforementioned decoder in both `ItwRequiredClaimsList` and `ItwCredentialClaim` which render the claim during the preview, details and presentation screen. If the decoded claim is of type `FiscalCodeClaim` then it extracts the fiscal code without the prefix.
Test a eID issuance flow and check the preview screen. Then check the details screen and try to obtain a MDL to check the presentation screen. The fiscal code shouldn't have the `TINIT` prefix;
> chore(IT Wallet): [SIW-1382] Remove TINIT prefix from fiscal code claim visualisation

- ts/features/itwallet/common/saga/index.ts
- ts/features/itwallet/identification/saga/handleCieSupportedSaga.ts
- ts/features/itwallet/identification/saga/index.ts
- ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
- ts/features/itwallet/identification/store/actions/index.ts
- ts/features/itwallet/identification/store/reducers/index.ts
- ts/features/itwallet/identification/store/selectors/index.ts
This PR fixes a bug that occurs when the user is already authenticated (has a session token): in that scenario the app does not check whether CIE is supported, so in IT Wallet identification mode selection screen the button CIE+pin does not appear.
- Store the CIE supported status in the `identification` reducer
- Call the CIE SDK manager independently of user authentication
Launch the app with an active session, and activate the wallet: the button CIE+pin should be visible.
> fix(IT Wallet): [SIW-1403] Check CIE support independently of user authentication

- ts/features/itwallet/common/components/ItwCredentialClaim.tsx
- ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
This PR adds the WI reset button in IT Wallet playgrounds
- Removed __DEV__ flag from WI reset button
- Fixed visualization problems in credential detail screen
Static check should pass.
Go to **Profile > Playgrounds > IT Wallet**, make sure the reset button is visible.
> chore(IT Wallet): [SIW-1405] Add WI reset button in IT Wallet playgrounds

- ts/features/itwallet/common/hooks/useItwDisbleGestureNavigation.ts
- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
This PR removes gesture navigation in IT Wallet credential issuance screens, which was causing desync between xstate machine and navigation state
- Added `useItwDisbleGestureNavigation`
- Disabled gesture navigation in `ItwIssuanceCredentialPreviewScreen` and `ItwIssuanceCredentialTrustIssuerScreen` components
Start the mDL issuance, check that you can't navigate back by using gestures
> chore(IT Wallet): [SIW-1406] Remove gesture navigation in IT Wallet credential issuance screens

- ts/features/itwallet/common/components/ItwCredentialClaim.tsx
- ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
- ts/features/itwallet/common/utils/itwClaimsUtils.ts
- ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
This PR removes the workaround for decoding image claims that lack a proper URL schema. It also adds support for multiple types of images according to the mapped [Image](https://reactnative.dev/docs/image#source) component. 
`gif`, `webp`, `psd` are not included because they are either platform specific (`psd`) or require additional setup (`gif` and `webp` on Android).
- Remove the `ImageClaimNoUrl` decoder and its usage; 
- Add supports for multiple image formats (`png`, `jpg`, `jpeg`, `bmp`);
- Add tests for the `ImageClaim` decoder.
Static tests and check if the image claim is rendered properly after the issuer adds the URL schema.
> chore(IT Wallet): [SIW-1378] Remove image claim decoding without URL schema

- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
This PR adds more info about failure in credential issuance failure screen when debug mode is enabled
- Added `Alert` with failure reason in `ItwIssuanceCredentialFailureScreen`
Start the **mDL** issuance flow with debug mode active, if a failure happens you should be able to see an Alert with the reason of the failure.
> chore(IT Wallet): [SIW-1408] Add more info about failure in credential issuance failure screen

- ts/features/itwallet/common/components/ItwCredentialClaim.tsx
This PR removes the calendar icon in claim list according to the new [FIGMA](https://www.figma.com/design/pVD9XCba7crkg5yOIdJCXl/%5BIT-Wallet%5D---%E2%9C%85-Approved-only-%E2%9C%85?node-id=1-28774&t=bymjoIgjAJJeOqnU-0).
| <img src="https://github.com/user-attachments/assets/3b50ac8e-898c-45f5-8299-c6da99a4726c" height="400"> | <img src="https://github.com/user-attachments/assets/47f2cf9c-212a-4db1-b4d0-a3e4151fcb00" height="400"> |
Check the details of a credential, the icon shouldn't be visibile if the claim is recognised as a date.
> chore(IT Wallet): [SIW-1416] Remove calendar icon in claim list

- ios/Podfile.lock
- package.json
- yarn.lock
This PR fixes a runtime crash that occurs on Android devices lacking a browser that supports custom tabs when using `io-react-native-login-utils`. Refer to the details of this [PR](https://github.com/pagopa/io-react-native-login-utils/pull/15) for more information.
- Update `io-react-native-login-utils` to v1.0.4.
- Disable any browser on the Android device;
- Add a payment method or test a payment flow. An error should be shown but the app shouldn't crash.
> fix(Cross): [IOAPPX-361] Runtime crash on Android devices without custom tabs support 

- android/app/src/main/java/it/pagopa/io/app/MainActivity.java
> On Android the View state is not persisted consistently across Activity restarts, which can lead to crashes in those cases. It is recommended to override the native Android method called on Activity restarts in your main Activity, to avoid these crashes. 
[Source](https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#android)
- Replace `savedInstanceState` with `null` in `MainActivity.java` to discard any persisted Activity state during the restart process. This should resolve the crashes we are observing in production.
```
> cd android && ./gradlew clean && cd .. 
> yarn react-native run-android
```
Test that the build works and that there's no regression in the app when restarting it or when swapping between recent apps.
> fix(Cross): [IOAPPX-363] Discard activity state persistence in Android

- ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
- ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
- ts/features/fims/singleSignOn/store/actions/index.ts
- ts/features/fims/singleSignOn/store/reducers/index.ts
- ts/features/fims/singleSignOn/store/selectors/index.ts
Addition of debug-only verbose FIMS error logging, in order to ease development by third parties
- updated saga to return the debug message as well as the standard one
- updated fims errorState selector to return the correct message depending on the state of the debug mode
using the dev-server, set ` consentsEndpointFailureStatusCode` to  any error status code, and check that with both the debug mode enabled and not, the screen behaves as expected
> FIMS verbose debug errorScreen

- publiccode.yml
This PR changes `codiceIPA` from `PCM` to `5n2tr557` that is [the correct one for PagoPA S.p.A.](https://www.indicepa.gov.it/ipa-portale/consultazione/domicilio-digitale/ricerca-domicili-digitali-ente/scheda-area-organizzativa-omogenea/A4UC3BM).
The regression comes from https://github.com/italia/publiccode-issueopener/commit/9db322e077c037de8e7fe24859d8295b00c65da4.
> chore(Cross): update `codiceIPA` from `PCM` to `5N2TR557`

- locales/de/index.yml
- locales/en/index.yml
- locales/it/index.yml
- ts/sagas/startup.ts
In this PR, we modified the last copies referring to the profile (referring to the settings). 
This PR was created in collaboration with @mariateresaventura 
- We have updated some remaining copies
- We put under Feature flags the copies that appear during profile deletion and that refer to the profile section (as you can see in the demo videos)
>[!Note]
> This video demo is only intended to demonstrate correct navigation and the text changing correctly under feature flags. All other changed text is not shown
<p> 
| Old - click on "Go to profile" | Old - click on "Ignore" | New - click on "Go to Settings" | New - click on "Ignore" | 
| - | - | - | - |
| <video src="https://github.com/user-attachments/assets/bf29c39b-5708-4f01-a3a1-37053687c8b1"/> | <video …
> chore: [IOPID-2007] Edit latest copy referred to profile

- ts/features/payments/checkout/screens/WalletPaymentInputFiscalCodeScreen.tsx
- ts/features/payments/checkout/screens/WalletPaymentInputNoticeNumberScreen.tsx
updated the payment flow's manual input screens to follow a11y best practices, in order to avoid crashes on android
- set view wrappers to accessible
- included usage of utility functions
- small refactors
with both android and iOS, make sure that the manual input payment flow (both fiscal code and notice number)  work as intended. (see https://github.com/pagopa/io-app/pull/5556 for reference) 
especially, make sure that the `continue` button correctly moves a11y focus when the textInput has not been completely filled or does not dontain correct data.
> fix: [IOBP-811] Payment manual input a11y focus crash on android

- ts/features/itwallet/machine/eid/__tests__/machine.ts
- ts/features/itwallet/machine/eid/events.ts
- ts/features/itwallet/machine/eid/machine.ts
This PR adds unit tests for the eID issuance machine logic
- Added unit tests
- Removed unnecessary `RequestAssistance` event
Static checks should pass
> chore(IT Wallet): [SIW-1341] Add eID issuance machine unit tests

- ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
- ts/features/messages/__mocks__/messages.ts
- ts/features/messages/analytics/index.ts
- ts/features/messages/components/Home/EmptyList.tsx
- ts/features/messages/components/Home/MessageList.tsx
- ts/features/messages/components/Home/PagerViewContainer.tsx
- ts/features/messages/components/Home/WrappedMessageListItem.tsx
- ts/features/messages/components/Home/__tests__/EmptyList.test.tsx
- ts/features/messages/components/Home/__tests__/MessageList.test.tsx
- ts/features/messages/components/Home/__tests__/PagerViewContainer.test.tsx
- ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
- ts/features/messages/components/Home/__tests__/homeUtils.test.ts
- ts/features/messages/components/Home/homeUtils.ts
- ts/features/messages/saga/handleLoadNextPageMessages.ts
- ts/features/messages/saga/handleLoadPreviousPageMessages.ts
- ts/features/messages/saga/handleReloadAllMessages.ts
- ts/features/messages/saga/handleUpsertMessageStatusAttributes.ts
- ts/features/messages/screens/MessagesSearchScreen.tsx
- ts/features/messages/screens/searchUtils.ts
- ts/features/messages/store/actions/index.ts
- ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
- ts/features/messages/store/reducers/__tests__/messageGetStatus.test.ts
- ts/features/messages/store/reducers/__tests__/payments.test.ts
- ts/features/messages/store/reducers/allPaginated.ts
- ts/features/pushNotifications/utils/configurePushNotification.ts
- ts/store/middlewares/analytics.ts
This PR add the Analytics event for the new messages home and search.
- For the event list, refer to the document linked on IOCOM-1110
Using the io-dev-api-server, generate some messages and check that all analytics events are triggered with proper parameters.
> feat: [IOCOM-1110] Home messages analytics events

- ts/features/messages/components/Home/__tests__/homeUtils.test.ts
- ts/features/messages/components/Home/homeUtils.ts
- ts/features/messages/store/reducers/archiving.ts
This PR fixes a race condition that prevented loading message details
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/08598397-2bd6-4e61-8d82-6e6b981792e0" />|<video src="https://github.com/user-attachments/assets/13360807-8925-4f67-bddd-25ddfa320b20" />|
- Prevents initial loading of (archived) messages if the system is busy doing an asynchronous home messages operation
- The race condition happened if the first archived message retrieval request was fired during an inbox messages asynchronous operation. In such case, the latter was cancelled by the former (since the saga is handled using a `takeLatest`) and the (former's) pot state was not being updated from the loading state.
Using the io-dev-api-server, set some delay on the messages list retrieval. Load …
> fix: [IOCOM-1687] Fix a race condition on message details loading

- ts/features/payments/checkout/analytics/index.ts
This PR maps the outcome unhandled from the event tracking mixpanel.
- Handled outcome 17 with the label `PAYMENT_WAITING_CONFIRMATION_EMAIL_ERROR`
> fix: [IOBP-810] Map event tracking payment outcome unhandled

- package.json
- patches/patches.md
- patches/react-native-fingerprint-scanner+6.0.0.patch
- yarn.lock
This PR fixes an unresolvable dependency during Android release.
- See https://github.com/hieuvp/react-native-fingerprint-scanner/issues/192
Run the release workflow
> chore: Fix for failing Android build on react-native-fingerprint-scanner dependency

- locales/en/index.yml
- locales/it/index.yml
- ts/features/fims/history/components/FimsHistoryListItem.tsx
addition of said error state when the service details' fetch fails.
- required I18n entries
- addition of said component and its rendering logic
update the dev server's code to return the following line in `src/routers/service.ts, line 58/59`
```ts
res.status(Math.random() > 0.3 ? 200 : 404).json(service)
```
this way, as long as you have a big enough FIMS history list (dev-server, config.ts, I recommend something around 50),
you should be able to see some failed fetches.
make sure everything works as intended and follows the given design.
> chore: [IOCOM-1678] FIMS history single listItem error state

- ts/features/barcode/screens/BarcodeScanScreen.tsx
- ts/features/payments/barcode/screens/PaymentsBarcodeChoiceScreen.tsx
This PR fixes a bug related to the new 'scan' feature in the tab bar, ensuring that when a QR code is scanned, the user is redirected to the new payment flow, fully removing the old flow
- Replaced the old and deprecated `navigateToPaymentTransactionSummaryScreen` with the new `startPaymentFlowWithRptId` 
- With the app deployed in a production environment, try starting a payment flow from the "scan" tab section by scanning or uploading a QRCode. You should be able to see the new payment flow instead of the previous one.
- If you need a valid qr-code in production, please feel free to contact me in DM, I will provide you a ready to use qr-code notice.
> fix: [IOBP-847] Navigate to the new payment flow from scan notice qr-code

- ts/features/itwallet/common/utils/itwClaimsUtils.ts
This PR fixes the duplicate fiscal code attribute in the trust issuer screen when presenting a eID for obtaining a new credential.
- Change the well known claims object `unique_id` attribute to match the one contained in the eID claims list.
Obtain a PID and then try to obtain any other credential. The trust issuer screen should shown the fiscal code as required attribute only once.
> fix(IT Wallet): [SIW-1537] Duplicate fiscal code in trust issuer screen

- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
- ts/features/itwallet/machine/credential/__tests__/machine.test.ts
- ts/features/itwallet/machine/credential/events.ts
- ts/features/itwallet/machine/credential/machine.ts
- ts/features/itwallet/machine/credential/selectors.ts
- ts/features/itwallet/machine/tags.ts
- ts/features/itwallet/navigation/ItwStackNavigator.tsx
- ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
- ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
- ts/features/itwallet/presentation/components/ItwPresentationAlertsSection.tsx
This PR adds a navigation action for the credential renewal started from the credential details screen. The navigation allows to visualize the loading state correctly
- Added `skipNavigation` flag to `selected-credential` event
- Added navigation to the trust issuer screen if `skipNavigation` is set to false
- Added loading component in `ItwIssuanceCredentialTrustIssuerScreen`
- Added tests
From the details screen of an expired credential, tap on "Update" button in the expired alert.
https://github.com/user-attachments/assets/b0293e6b-f5df-427e-98ca-11225131e92b
> chore(IT Wallet): [SIW-1538] Add navigation on credential renewal

- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
This PR fixes an error which causes an error screen to be displayed instead of a loading one when the issuing of a credential takes more than 4 seconds.
- Replace `selectIsLoading` with `selectIsIssuing` selector; 
Test a credential issuing, you should be able to see a loading screen instead of an error one when the credential issuing takes more than 4 seconds.
> fix(IT Wallet): [SIW-1548] Error screen instead of loading screen while issuing credential

- ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
- ts/boot/configureStoreAndPersistor.ts
- ts/screens/profile/DeveloperModeSection.tsx
- ts/store/actions/persistedPreferences.ts
- ts/store/reducers/backendStatus.ts
- ts/store/reducers/persistedPreferences.ts
This PR is a revert of PR #6145
https://github.com/user-attachments/assets/fb46f2ce-eba2-43b1-b7f0-84ce3130a254
Run the application and use a switch in profile section to activate/deactivate the feature
> chore: [IOPID-2196] Revert old PR to delete local FF to activate new scan and settings sections

- ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
- ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
- ts/features/itwallet/credentials/saga/handleItwCredentialsRemoveSaga.ts
- ts/features/itwallet/credentials/saga/handleItwCredentialsStoreSaga.ts
- ts/features/itwallet/credentials/saga/handleWalletCredentialsRehydration.ts
- ts/features/itwallet/credentials/store/actions/index.ts
- ts/features/itwallet/credentials/store/reducers/__tests__/index.test.ts
- ts/features/itwallet/credentials/store/reducers/index.ts
- ts/features/itwallet/lifecycle/store/selectors/__tests__/index.test.ts
- ts/features/itwallet/machine/credential/actions.ts
- ts/features/itwallet/machine/eid/actions.ts
This PR fixes a bug that happens when there is a credential in the wallet and that same credential is renewed. The bug is caused by:
- Always appending new credentials to `features.itWallet.credentials.credentials` array
- Using the unique key tag as the key for wallet cards
- Overwrite credentials of the same type when dispatching `ITW_CREDENTIALS_STORE`
- `ITW_{credential_type}` is used as key for wallet cards to avoid duplicates
- Removed `ITW_CREDENTIALS_MULTIPLE_UPDATE` action: now it is safe to dispatch `ITW_CREDENTIALS_STORE` to store a credential or an array of credentials and overwrite previous instances
Currently one way to test this is to renew the driving license after it's been revoked, and then navigate to the wallet screen. Without the fix two driving license cards will …
> fix(IT Wallet): [SIW-1535] Credential duplication after renewal

- ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
This PR removes the credential filter when requesting a status attestation.
- Remove the `canGetStatusAttestation` function;
- Setup a proxy to intercept calls made by the app;
- Obtain two or more credentials;
- Close the app and reopen it; 
- Check if the `/status` endpoint has been called for each obtained credential.
> chore(IT Wallet): [SIW-1541] Add status attestation for any credential

- locales/en/index.yml
- locales/it/index.yml
- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
This PR updates the copy for a generic error message in the credential issuance flow.
- Change locale by dividing a generic eID and credential error;
- Update usage.
With a proxy map the `/credential` call to `500` and check if the error message is rendered properly for both eID and credential.
> fix(IT Wallet): [SIW-1549] Update copy for credential issuance generic error message 

- ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsPreviewScreen.tsx
This PR fixes the save & share feature allowing the user to share correctly the PDF receipt from the payment details screen.
Thanks to @mastro993 for the hint!
- Replaced `activityItemSources` with the property `filename`
- Try to share any PDF receipt from the payment detail screen and you should be able to do it.
> fix: [IOBP-853] Receipt Share & Save button feature

- ts/features/itwallet/common/utils/itwClaimsUtils.ts
- ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
This PR fixes a small regression causing the ITW credential card to determine the "expire" status without checking the status attestation (only the expiration date in the credential).
When a credential is revoked, the card is not displayed with the red border and the expired badge.
- Switched `getCredentialExpireStatus` with `getCredentialStatus`
Open the detail of a non-skeumorfic credential that has been revoked.
> fix(IT Wallet): [SIW-1587] Use the status attestation info to get the status in `ItwPresentationCredentialCard`

- locales/en/index.yml
- locales/it/index.yml
updated localization to follow design
- updated I18n
navitgate to said screen and make sure the text displayed is correct
> chore: [IOCOM-1691] Update I18n in Fims auth screen

- locales/en/index.yml
- locales/it/index.yml
CGN categories list uncapitalize labels.
Note: German translation left capitalized due to grammar
- update translation files
- Login into app
- go to can card trough wallet (add it if necessary)
- click on "discover opportunities"
- check the labels
> fix: [PE-679] CGN categories list uncapitalize labels

- ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
- ts/features/payments/checkout/saga/networking/handleWalletPaymentGetDetails.ts
This PR fixes a regression bug in the payment notice detail screen (formerly called "verify" screen) that instead showing the correct error page, it shows a generic error screen.
- Edited error status handling passing the error value in the failure action instead a generic one.
- With the `pagoPA test env` feature flag enabled, open the Payments section
- Start a payment with the following notice code and CF:
- 302000000000000000
- 77777777777
- Then you should be able to see the "notice code already paid" error instead a generic one.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/67976d05-311e-46d0-b368-a2c6f3f9b2b7" />|<video src="https://github.com/user-attachments/assets/eb218455-ee76-4ea0-9ee2-3cd64d97d6f2" />|
> fix: [IOBP-867] Regression of generic error page into verify payment screen

- ts/features/bonus/cgn/components/merchants/CgnModuleDiscount.tsx
If the discount amount is set to 0% by the operator, do not show the badge
- change conditional rendering
- start api dev server setting this value to 0 https://github.com/pagopa/io-dev-api-server/blob/f368eb22c588c2c7cfe8c7c995f447e167a59a51/src/payloads/features/cgn/merchants.ts#L165
- login into app
- go to can card trough wallet (add it if necessary)
- go to discover opportunities
- go to detail of any provider
> fix: [PE-681] CGN hide discount badge if 0 

- locales/en/index.yml
This PR adds the English locales to the "Rimuovi" confirm button modal into the deletion of a payment method.
> fix: [IABT-1527,IOBP-877] Translated "Rimuovi" into delete payment method button in english

- ios/Podfile.lock
- package.json
- yarn.lock
bump of said dep's version
- version upgrade
with both an iOS and an Android physical device, start a flow that uses the inAppBrowser (FIMS flow was used for this purpose) -- and make sure nothing breaks.
> fix: [IOCOM-1808] Update io-react-native-login-utils

- ts/navigation/AuthenticatedStackNavigator.tsx
CGN detail screen fix missing swipe back gesture
- login into the app on iOS
- go to cgn card detail screen trough wallet (add it if necessary)
- swipe back to check if it goes back to wallet page
> fix: [PE-700] CGN detail fix missing swipe back gesture

- .github/workflows/test-e2e.yml
This PR comments the workflow part which sends a Slack message on E2E failure. Currently E2E test are broken, thus our monitor channel gets spammed with these message. 
It can be reintroduced when we fix the E2E tests.
- Comment `notify-test-failure` in `test-e2e.yml` workflow.
N/A
> chore(Cross): [IOAPPX-388] Remove Slack message on E2E failure

- android/app/src/main/AndroidManifest.xml
This PR adds the `largeHeap` attribute to the Android Manifest, in order to request more memory for the application.
This should improve the Android Custom Tabs performances on some devices.
- `largeHeap=true` on the `application` tag in the Android manifest file
Check that the application is properly built
> chore(Cross): [IOAPPX-392] Set `largeHeap=true`

- patches/react-native-device-info+10.8.0.patch
This PR upgrades the patch file for the react-native-device-info, in order to hide the mismatch warning during package installation.
- react-native-device-info@10.8.0.patch upgraded to match the 10.8.0 version
Run a `yarn` command from scratch and check that there are no warnings about react-native-device-info patch mismatch
> chore(Cross): [IOAPPX-390] Device-info patch version upgrade

- .github/workflows/release.yml
This PR updates the JDK version in the release workflow which is supposed to fix an issue we currently have while publishing on Android via GitHub Actions.
- Bump JDK version in `setup-jdk` to version 17;
- Bump `setup-android` to version `3.2.1`;
N/A
> chore(Cross): [IOAPPX-401] Update JDK version in release workflow

- ts/features/pushNotifications/store/reducers/userBehaviour.ts
- ts/features/pushNotifications/utils/index.ts
This PR changes the method used to check push notification permissions, in order to properly read the status on devices running Android 12 or lower.
- Android utility function code switched from `PermissionAndroid.check` to `PushNotification.checkPermission`
- Check for Android 24 or lower has been removed (since min supported version is 25)
- Improved iOS permission check by checking when notification are disabled instead of enabled
- Refactored utility function to improve readability
Using the io-dev-api-server, check that Android devices (all versions) correctly report the push notification permission status.
> fix: [IOCOM-1881] Push notification status on Android 12 or less

- ts/features/itwallet/common/utils/itwAttestationUtils.ts
- ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
- ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
- ts/features/itwallet/machine/eid/actors.ts
This PR refactors the usage of `ensureIntegrityServiceIsReady` from `io-react-native-integrity`. 
This functions checks wether or not the integrity service is available on the device and on Android it warms up the integrity service as detailed in the [design review](https://pagopa.atlassian.net/wiki/spaces/SIW/pages/921436266/IO-WALLET-DR-0007+Play+Integrity+API), based on the Google documentation.
Currently the function gets called multiple times when needed, however this is totally unnecessary and also adds up more time to the wallet instance issuance flow.
> [!NOTE]
> A refactor is needed in order to leverage the returned value from this function. It will be handled in another PR.
- Remove any usage of `ensureIntegrityServiceIsReady` and move the call at the startup when checking for …
> chore(IT Wallet): [SIW-1756] Prepare integrity service at startup

- ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
This PR fixes a crash which happens when the integrity service is not available. 
- Catch the error when calling `ensureIntegrityServiceIsReady` on a device which doesn't support it.
Start the app on the simulator, you shouldn't see any error after the startup saga.
> fix(IT Wallet): [SIW-1761] Crash when integrity service is not available 

- ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
This PR removes the secondary CTA on integrity error temporary, until we have an actual URL with FAQ for the citizien. 
Remap the answer of the `/api/v1/wallet/token` endpoint to `409 Conflict` and try to active a wallet from scratch. It is important that you don't have an active wallet instance before testing it and this can be ensured by resetting the wallet from the developer options, documenti su IO and reset wallet instance.
> chore(IT Wallet): [SIW-1765] Remove secondary CTA on integrity error

- ts/features/newWallet/components/WalletCardsContainer.tsx
This PR adds the activation/coming soon banners when the wallet is empty.
- Wrap the banners in a single component;
- Add the wrapper inside the empty wallet return case and replace it everywhere else.
Test that the banner are correctly shown based on the trial system status both when the wallet is empty and when it's not.
> fix(IT Wallet): [SIW-1766] Enable banners with empty wallet

- ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
- ts/features/payments/bizEventsTransaction/utils/index.ts
This pull request includes changes to the `getPayerInfoLabel` function and its corresponding tests to improve the formatting of the payer's tax code. The main change is the removal of parentheses around the tax code in the output.
- Remove parenthesis from `getPayerInfoLabel` function 
- Update `getPayerInfoLabel` test
- Go into `Pagamenti`
- Tap on a payment from the list
- Check the tax code under the  payer name
> fix: [IOBP-900] Remove parenthesis from tax code in payment screen 

- ts/features/payments/details/screens/PaymentsMethodDetailsScreen.tsx
This pull request includes a change to the `PaymentsMethodDetailsScreen` component to enhance the `getCardHeaderTitle` function. The update adds specific handling for BPAY and PayPal payment methods.
- Update `getCardHeaderTitle` function to handle missing edge cases
To test all card cases, update the `generateWalletData` function by adding this line: `generateUserWallet(3)`
- Tap in _Portafoglio_
- BPAY or PayPal card
- Verify the correct card header title is displayed
> fix: [IOBP-901] Missing header in payment methods

- locales/en/index.yml
- locales/it/index.yml
This PR fixes a typo in the identification mode selection screen.
- Update IT/EN locales;
Static check should be enough but this can be tested by running `yarn generate:locales` and by opening the identification mode screen by trying to activate the wallet:
> chore(IT Wallet): [SIW-1784] Typo in identification mode selection screen

- ts/features/bonus/common/components/BonusInformationComponent.tsx
This pull request includes several changes to the `BonusInformationComponent.tsx` file to improve the user interface and ensure better compatibility with the `IOScrollViewWithLargeHeader` component.
- Add images dimension
- Replace deprecated component with `IOScrollViewWithLargeHeader`
Try activating the CGN card and verify if the images are displayed correctly
> fix: [PE-688] CGN activation images

- .env.local
- .env.production
- ts/config.ts
- ts/features/itwallet/common/components/ItwUpcomingWalletBanner.tsx
This PR add action to `ItwUpcomingWalletBanner`. Clicking the banner the user will be redirected to the following page: https://io.italia.it/documenti-su-io
- Add `action` to `ItwUpcomingWalletBanner` component with the correct link 
- The `ITW_DOCUMENTS_ON_IO_URL` variable has been added to both `.env.local` and `.env.production` 
Using the `io-dev-api-server`, simulate a state other than SubscriptionStateEnum.ACTIVE and verify that clicking on the banner redirects to the correct page (https://io.italia.it/documenti-su-io)
https://github.com/user-attachments/assets/aef47420-7751-414d-963f-4e5e08904315
> chore(IT Wallet): [SIW-1716] Add action to ITWallet upcoming banner

- package.json
Change version of io-services-metadata ref in package.json in order to delete the reference to sessionRefresh. 
> [!Note] 
> This PR depends on https://github.com/pagopa/io-services-metadata/pull/847 and is related to https://github.com/pagopa/io-app/pull/6255
> chore: [IOPID-2359] Delete sessionRefresh FF reference

- ts/features/payments/details/components/PaymentsMethodDetailsBaseScreenComponent.tsx
This pull request introduces enhancements to the `PaymentsMethodDetailsBaseScreenComponent` make the header solid on scroll without opacity.
- Apply to `enableDiscreteTransition` to ScrollView component
- Tap on _Pagamenti_
- Open a payment card
- Check the header on scroll to be solid every time
> fix: [IOBP-902] Payment header opacity on scroll

- ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
This pull request includes changes to the `ItwIssuanceEidFailureScreen` component to handle unsupported device errors more effectively. The most important changes involve adding a secondary action to the error screen
* [`ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx`](diffhunk://#diff-6e81827f65b8e2bf66539bd0bc1af3eef64bd8a4bd685f383904160bc44cfb2bR106-R112): Added a secondary action to the unsupported device error screen that opens a URL with more information.
When obtaining the WI simulate an unsupported device error and check the error screen with the new secondary action button + [link](https://io.italia.it/documenti-su-io/faq/#n1_12)
Preview:
https://github.com/user-attachments/assets/4d9818bf-0e5c-4529-ba7c-ffb8b957e441
> chore(IT Wallet): [SIW-1769] Reintroduce integrity check KO message 

- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
- ts/features/itwallet/machine/eid/selectors.ts
This PR addresses an issue where failure screens are rendered with incorrect props on initial load or, in rare cases, are displayed unnecessarily. This update ensures that failure screens render only when appropriate, with the correct failure type.
1. Use a network inspection tool (e.g., Proxyman) to override the response of either the `/eid` or `/credential` endpoints, forcing them to return an error status code.
2. Initiate the eID or credential issuance flow.
3. To verify if the failure screens are rendered twice, insert a `console.log` statement in the `ContentView` component. You should observe:
- An initial render with a `GENERIC` failure type.
- A second render with the actual, specific failure type.
This behavior occurs because the first render processes a `None` failure type, …
> fix(IT Wallet): [SIW-1798] Removes unnecessary rendering of failure screens during issuance flows

- ts/features/payments/checkout/analytics/index.ts
This PR maps the payment outcome 19 in the mixpanel events with the value `PAYMENT_METHOD_AUTHORIZATION_ERROR`.
- Added a case inside the switch of the mixpanel mapping outcome to handle outcome 19 (`WalletPaymentOutcomeEnum.PAYPAL_REMOVED_ERROR`)
> chore: [IOBP-940] Map payment outcome 19 in the mixpanel events

- ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
- ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsDetailsScreen.tsx
This PR adds the payee entity's name to the header with a discrete transition effect.
- Replaced the `IOScrollViewWithLargeHeader` with the `IOScrollView` that uses the `animatedRef` to the custom hook `useHeaderSecondLevel` to show the discrete transition in the header while scrolling
- Open the Payments screen tab;
- Choose any transaction from the list navigating to the transaction details screen;
- While scrolling, you should be able to see the discrete transition of the header with the payee entity's name;
https://github.com/user-attachments/assets/7a65c078-a558-4c54-a0ca-59bc97bb2560
> chore: [IOBP-837] Add payee name as header title into transaction details

- ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
This PR removes the title inside the transaction details screen.
- Removed the `H2` title inside the heading of the transaction details screen
Open a transaction details from the Payment screen.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/6d15145f-44df-4d34-9935-00fdd941d328" />|<video src="https://github.com/user-attachments/assets/4f2122e0-3294-42c3-b72c-27c32519d9ce" />|
> chore: [IOBP-948] Remove transaction details screen title

- ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsCartItemDetailsScreen.tsx
- ts/features/payments/transaction/screens/PaymentsTransactionOperationDetails.tsx
This pull request is adding clipboard functionality to certain items in transaction details screen.
- Replace `ListItemInfo` component with `ListItemInfoCopy`
- Navigate to the _Pagamenti_ section
- Select any receipt
- Tap on its details
- Verify that the **Tax Code**, **Codice Avviso**,  **IUV** and **Oggetto del pagamento** fields are copyable
- Confirm that the copied values match the original information accurately
|             |   |
> chore: [IOBP-757] Apply info copy component into transaction details screen

- ts/features/payments/bizEventsTransaction/components/PaymentBizEventsSectionListHeader.tsx
- ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsFilterTabs.tsx
- ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
This PR fixes a strange behavior on the filter tabs in the notices list screen. When the user taps on a tab and it become selected, it seems that doesn't stay in "active" mode. This PR fixes it preventing unnecessary rerendering.
- Memoized the `SectionListHeaderTitle` component to avoid unnecessary re-renders that causes an issue with the component animation of the TabItem that loses the focus state.
- Open the `Pagamenti` section.
- Tap on the CTA `Vedi tutte`.
- Tap on any of the three available tabs in the list and check that the color is the one that marks the active state.
> fix: [IOBP-950] Filter tabs behavior into biz events notices list

- ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
- ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
- ts/features/payments/bizEventsTransaction/utils/index.ts
This pull request includes importing and utilizing a new utility function for text capitalization, and updating the test cases to cover new scenarios.
- Apply `capitalizeTextName` to `getPayerInfoLabel` function
- Update test suite of `getPayerInfoLabel` to handle uppercase string
- Go in `Pagamenti`
- Tap on a transaction
- Check _Eseguita da_ and _Metodo intestato a_ field to be capitalize (Edit `PaymentsBizEventsTransactionInfoSection` file with custom string and check results)
> fix: [IOBP-953] Capitalize transaction fields

- ts/features/payments/checkout/navigation/navigator.tsx
This pull request disables gesture navigation for the `WalletPaymentOutcomeScreen` component.
- Set `gestureEnabled` to false for PAYMENT_CHECKOUT_OUTCOME screen
https://github.com/user-attachments/assets/1025f4aa-0d1f-473a-941a-edea906c52c8
> chore: [IOBP-522] Disable back gesture for outcome screens

- ts/features/payments/bizEventsTransaction/saga/handleDisableBizEventsTransactionReceipt.ts
This PR adds missing success toast notification when a receipt is successfully hidden
-  Added a success toast notification when a receipt is successfully hidden.
- Try to hide a receipt
- Verify that a toast notification is displayed
https://github.com/user-attachments/assets/ad40631d-48f9-4911-a257-2790d4ca0a3a
> fix: [IOBP-997] Missing success toast on hide receipt

- ts/features/itwallet/common/utils/itwCredentialUtils.ts
- ts/features/itwallet/presentation/components/ItwCredentialTrustmark.tsx
This PR fixes the issue of the trustmark being displayed even when a credential is invalid.
- Modified render condition of `ItwCredentialTrustmark` component
Mock an invalid status for a credential, access the detail screen and ensure the trustmark button is not shown.
> fix(IT Wallet): [SIW-1845] Hide trustmark when a credential is invalid

- ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
This PR removes the error Toast that was shown if the InApp Browser somehow failed
This has been done since the login-utils library is not up to date with the error handling and does not allow to check for errors on both systems with the same syntax.
- Empty error handling
Using the io-dev-api-server, check that the FIMS flow works correctly
> fix: [IOCOM-1927] Remove error Toast on InApp Browser opening on FIMS

- ts/features/messages/components/Home/DS/MessageListItem.tsx
- ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
This PR fixes the wrong alignment of the dot separator in the `MessageListItem`. Previously it was rendered with a smaller font size, resulting in an off-centre separator. This visual problem was more noticeable when the user set a larger text size.
- Uniform size of the bottom section of the `MessageListItem`
| ![Simulator Screenshot - iPhone 16 Pro - 2024-11-18 at 13 33 45](https://github.com/user-attachments/assets/df6ca247-6e08-4ae1-a9b8-831040fd05d2) | ![Simulator Screenshot - iPhone 16 Pro - 2024-11-18 at 13 33 07](https://github.com/user-attachments/assets/d194a941-aeb6-4c8e-98d5-a27215a23e0f) |
N/A
> fix(Cross): [IOAPPX-431] Fix alignment of the dot separator in the `MessageListItem`

- locales/en/index.yml
- locales/it/index.yml
- ts/features/payments/checkout/analytics/index.ts
- ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
- ts/features/payments/checkout/screens/___tests___/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
- ts/features/payments/checkout/types/PaymentOutcomeEnum.ts
This PR adds outcome 99 inside the payment screen when receiving it from the backend.
- Created a custom `BE_NODE_KO` that's equals to outcome `99`;
- Mapped the new outcome inside the labels and the screen to show into the `WalletPaymentOutcomeScreen.tsx` file;
- Added missing outcomes to keep track on mixpanel inside the `getPaymentAnalyticsEventFromFailureOutcome` function
- Checkout and run the dev-server with this PR: https://github.com/pagopa/io-dev-api-server/pull/438;
- Complete the payment flow and choose from the dropdown the BE_NODE_KO;
https://github.com/user-attachments/assets/a062456d-44a1-4f9f-ae3e-a9fb45644d98
> chore: [IOBP-982] Add outcome 99 screen into payment flow

- publiccode.yml
Thisd PR fixes an error on publicode_validation action due to the recent app logo changes
Check publicode validation run
> fix: missing app logo file on publicode.yml

- ts/features/fims/history/saga/handleExportFimsHistorySaga.ts
- ts/features/fims/history/saga/handleGetFimsHistorySaga.ts
This PR fixes the format for the value of the Authorization headers on FIMS history
- Header's value computed as `Bearer ${token}`
Using the production environment, check that the FIMS history section works as expected
> fix: [IOCOM-1948] Proper Authorization header's value for FIMS history

- ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
- ts/features/payments/bizEventsTransaction/utils/index.ts
This pull request add a new utility function and its integration into the `PaymentsBizEventsTransactionInfoSection` component to handle the removal of asterisks from payment information
- Add `removeAsterisks` function that replaces asterisks in a given string with an empty string
- Apply the new `removeAsterisks` utility function to the wallet information to remove asterisks from the blurred number display
- Mock a `blurredNumber` with some `*` and the card number at the end
- Verify that `*` are not render
> fix: [IOBP-1037] Remove asterisks from card transaction info

- ts/features/newWallet/components/WalletCardsContainer.tsx
- ts/features/newWallet/saga/__tests__/handleWalletLoadingPlaceholdersTimeout.test.ts
- ts/features/newWallet/saga/handleWalletLoadingPlaceholdersTimeout.ts
- ts/features/newWallet/screens/__tests__/WalletHomeScreen.test.tsx
This PR fixes the behavior of the homepage banner in the "wallet" by ensuring the retry banner is displayed even when all API calls of the B&P domain fail. Previously, the retry banner was not shown if the number of onboarded cards was zero. Now, the logic has been updated so that if the number of cards is zero and at least one API call fails, the retry banner will be displayed.
- Added a logic inside the `WalletCardsContainer.tsx` to handle this edge-case when no card is available
- Test the app on your physical device and check that when you open the app, before opening the "Wallet" tab, disable your internet connection and then tap on the "Wallet tab";
- After that, check that there is visible the backoff-retry banner.
> fix: [IOBP-1021] Show retry banner when all the other cards fetch fails

- ios/Podfile.lock
- package.json
- ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
- yarn.lock
This PR adds support for `iossoapi` protocol when using the InApp Browser on FIMS
- latest react-native-login-utils library 
- `iossoapi` protocol added to the InApp Browser callback
Using the related io-dev-api-server, check that the InApp Browser from FIMS is closeable using the related web page button.
> chore: [IOCOM-1949] FIMS `iossoapi` protocol

- ts/features/zendesk/saga/index.ts
- ts/sagas/startup/__tests__/watchCheckSessionSaga.test.ts
- ts/sagas/startup/watchCheckSessionSaga.ts
In the as-is when polling, the data in the redux store was overwritten and the zendeskToken was no longer available. This led to an error when sending messages to support, within the chat with support. (only for logged in users)
| .env.local | .env.production |
| - | - |
| <video src="https://github.com/user-attachments/assets/4580715e-08f7-488d-9146-27b424efaa97"/> | <video src="https://github.com/user-attachments/assets/6d1b63d3-5c3f-4aa1-baeb-4029dfa2e6e4"/> | 
> [!Warning]
> In order to test this PR using .env.local, you need to use this branch on the dev-server https://github.com/pagopa/io-dev-api-server/pull/445
Run the application using or .env.local or .env.production or both
Activate the fast-login settings 
follow the video demo
> fix: [IOPID-2543] Add logic to merge data during zendesk polling

- ts/features/wallet/components/WalletCategoryFilterTabs.tsx
This PR adjusts paddings in the filter chips within the wallet home screen
- Adjusted paddings in `WalletCategoryFilterTabs` component
Run the app, check that everything is ok and paddings are [aligned with the Figma design](https://www.figma.com/design/4Pbt3wd9WoPnAXVMkAA6UT/App-IO-2.0---Design-System?node-id=11659-113426&t=lUQmAFWv9kFH888E-4).
https://github.com/user-attachments/assets/e34c66c1-90bd-4ac9-8163-1a67eb8a43f2
> fix(IT Wallet): [SIW-1899] Fix filter tabs padding within wallet home screen

- locales/de/index.yml
- locales/it/index.yml
This pull request includes changes to locales files to update the text for remove button when CGN card is expired.
- Changed the expired card cta message from "Elimina Carta Giovani Nazionale" to "Rimuovi dal Portafoglio".
- From dev-server mock an expired `cgn` response
- Add `cgn` to your wallet
- Tap on it
- Check the remove cta text, press on it  
- Ensure alert is also aligned with design
> chore: [PE-868] CGN Update cta when card is expired

- ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimLabel.tsx
- ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
This PR fixes a regression on font weight within skeumorphic cards
- Added `fontWeight` to `ClaimLabel` style
Check that the skeumorphic cards correctly renders their labels with proper styles
| --- | --- |
| <img src="https://github.com/user-attachments/assets/778d8e49-9f47-455c-a78e-dd31962d97cf" width="200" /> | <img src="https://github.com/user-attachments/assets/35380503-f995-487a-a612-413fa5e8020c" width="200" /> |
> fix(IT Wallet): [SIW-1913] Fix regression on font weight in skeumorphic cards

- ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
- ts/features/itwallet/common/store/reducers/__tests__/index.test.ts
- ts/features/itwallet/common/store/reducers/index.ts
This PR fixes a crash in the credentials onboarding screen by adding a store migration needed after a store update made in https://github.com/pagopa/io-app/pull/6516 
- Added ITW store migration 1
- Updated snapshot test with warning about this problem happening again
1. Uninstall the app from your device 
2. Install it again building from https://github.com/pagopa/io-app/commit/a3799e35feefabdcadaa2ee1d32bc287ad5fb58c
3. Activate the Wallet
4. Navigate to the Credentials onboarding screen, check that everything works as expected
5. Update the app building from this branch
6. Navigate to the Credentials onboarding screen again, check that everything works as expected
> fix(IT Wallet): [SIW-1917] Fix crash in credentials onboarding screen

- ts/api/content.ts
- ts/features/payments/checkout/hooks/usePaymentFailureSupportModal.tsx
> [!NOTE]
> To test this PR [check this](https://github.com/pagopa/io-dev-api-server/pull/450) 
This pull request update the URL path and improve the handling of Zendesk payment categories. The most important changes include modifying the URL for the Zendesk payment configuration and refactoring the code for checking and adding subcategories in the payment failure support modal.
- Changed the URL path in the `getZendeskPaymentConfig` object from `/assistanceTools/payment/zendeskOutcomeMapping.json` to `/assistanceTools/payments/zendeskOutcomeMapping.json`
- Refactored the `zendeskAssistanceLogAndStart` function to improve the handling of the `zendeskPaymentCategory` check and the addition of subcategories to the ticket. The new code ensures that the subcategory is only processed if …
> fix: [IOBP-1082] Typo in Zendesk assistance json remote path  

- locales/en/index.yml
- locales/it/index.yml
- ts/features/payments/checkout/screens/___tests___/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
This pull request includes updates to the subtitle text in the payment verification messages. The changes ensure that users are instructed to wait at least 15 minutes before retrying a payment.
- Update text as defined in design
- Update related snapshot
- Try to pay something
- Cancel the transaction before select an outcome
- Ensure that outcome message is align with design 
https://github.com/user-attachments/assets/12c32c91-c289-4192-9b1f-39580a544c14
> chore: [IOBP-1083] Update `IN_APP_BROWSER_CLOSED_BY_USER` outcome text

- ts/features/payments/checkout/hooks/useWalletPaymentAuthorizationModal.tsx
This PR removes the delete transaction API request when the user closes the in-app browser during the payment flow.
- Removed the API request trigger when closing the payment flow form the in-app browser.
- Start a payment flow with the dev-server started;
- Reach the final step when the in-app browser appears;
- Tap on "Cancel" button and check that the API request to delete the transaction isn't fired;
> chore: [IOBP-1085] Removed delete transaction API request when closing in-app browser

- .github/workflows/distribute-beta.yml
- .github/workflows/release-canary.yml
- .github/workflows/release-new-cycle.yml
- .github/workflows/release-nightly.yml
- .github/workflows/test-e2e.yml
This PR bumps the version of setup-ruby on CI workflows.
ref. https://github.com/ruby/setup-ruby/issues/595
> fix: setup-ruby on CI failure

- Gemfile
- Gemfile.lock
This PR fixes an issue on android release workflow
see https://github.com/ffi/ffi/issues/1103#issuecomment-2186974923
> fix: ffi version mismatch on linux environment

- locales/en/index.yml
- locales/it/index.yml
- ts/features/payments/receipts/screens/ReceiptListScreen.tsx
This pull request includes updates to localization files and enhancements to the `ReceiptListScreen` component. The most important changes is refactoring the empty state logic in the receipt list screen.
- Refactored the empty state logic to use a new `emptyProps` object based on the `noticeCategory`.
- Added `emptyPayer` locale for displaying payment receipts made in the app.
- In `Pagamenti` tap on `Vedi tutte`
- Ensure that the `Pagate in app` tab is display correct empty state
https://github.com/user-attachments/assets/8501fe55-1370-4613-9543-b929aa9907d6
> refactor: [IOBP-1091] Paid in app empty state screen

- ts/components/screens/OperationResultScreenContent.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
This PR changes the line break strategy in the issuance failure screens to display email addresses in the same line. The issue seems to affect Android devices only.
- Added `textBreakStrategy: "simple"` in `ItwIssuanceEidFailureScreen` and `ItwIssuanceCredentialFailureScreen`
The easiest way to test it is to mock an error during credential issuance with a message that contains an email address.
|Before|After|
|------|-----|
|<img src="https://github.com/user-attachments/assets/fe546b8e-249a-4955-921f-39106dfa1242" width="240"/>|<img src="https://github.com/user-attachments/assets/ad478750-93a5-4b5c-8024-2d166c4be92d" width="240"/>|
> chore(IT Wallet): [SIW-1949] Display email address in the same line in issuance failure screen

- ts/sagas/installation.ts
Fix behavior where the app navigated to the LandingScreen before obtaining the remoteConfig data
- Replaced `put(sessionInvalid())` with `call(AsyncStorage.removeItem, "persist:authentication")` in the `installation` saga. This fixes a wrong startup behavior where in response to the `sessionInvalid` action, the `status` attribute in the startup reducer is set to `notAuthenticated`, causing the app to navigate to the LandingScreen.
<details><summary>iOS</summary>
|With `sessionInvalid` action (current implementation)|With `AsyncStorage.removeItem` (proposed scenario)|
|-----------------------------------------------------|----------------------------------|
|<video src="https://github.com/user-attachments/assets/f9aa90e5-5fba-4403-9316-2dd66ae4268d"></video>|<video …
> [IOPID-2592] Fix wrong navigation on first app install

- scripts/generate-api-models.sh
- ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
Replaced badge label of "novità" with actual new discounts count. 
- change label
- to test with dev-api-server you need https://github.com/pagopa/io-dev-api-server/pull/455
- login into the app
- go to carta giovani nazionale trough portafoglio (add the card if necessary)
- go to discount list by pressing "scopri opportunià"
- press "by partner" tab
- check that the badges contain numbers instead of a fixed label
- press "by category" tab
- press on any category
- check that the badges contain numbers instead of a fixed label
> feat: [PE-882] CGN new discounts count

- locales/en/index.yml
- locales/it/index.yml
- ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
- ts/features/payments/checkout/screens/__tests__/WalletPaymentPickPspScreen.test.tsx
- ts/features/payments/checkout/store/reducers/index.ts
- ts/features/payments/common/utils/__tests__/index.test.ts
- ts/features/payments/common/utils/index.ts
This PR removes the logic to preselect a PSP if there is the `onUs` field;
- Removed the `onUs` check to preselect the PSP when in the PSP list choosing screen;
- Edited the featured label;
- Added the onUs as first element in the sorting algorithm;
- Added unit tests;
- Update the dev-server;
- Run the dev-server and start a new payment;
- After choosing a payment method, check that when the PSP list presents, there is any element preselected but there must be the featured text `Sei già cliente`
https://github.com/user-attachments/assets/34c69c71-2287-4db5-bc27-fc816fe8de30
> chore: [IOBP-1122] Remove PSP preselection logic based on the onUs field

- ts/features/services/home/hooks/useInstitutionsFetcher.tsx
- ts/features/services/home/screens/ServicesHomeScreen.tsx
- ts/features/services/home/store/reducers/__tests__/store.test.ts
- ts/features/services/home/store/reducers/index.ts
This PR removes the control introduced in #5849 because when the user scrolls quickly down, the _distanceFromEnd_ value returned by the _onEndReached_ function becomes zero, preventing the next page from loading.
Additionally, if there was an error in the call to retrieve the institutions, we block the call and wait for a short period before allowing the request to be sent again.
- updated reducer
- removed `isLoadingPaginatedInstitutionsSelector`, `isUpdatingPaginatedInstitutionsSelector` and `isErrorPaginatedInstitutionsSelector`
- refactored `useInstitutionsFetcher` hook
- updated tests
Navigate to the services home screen and scroll down quickly. Check that the next pages load correctly.
> fix: [IOPAE-1688] Fix infinite scroll on the services home page

- ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
- ts/features/payments/receipts/components/ReceiptInfoSection.tsx
- ts/features/payments/receipts/components/___tests___/ReceiptInfoSection.test.tsx
- ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
- ts/features/payments/receipts/screens/ReceiptListScreen.tsx
This PR hides the "Download receipt" button inside a receipt detail page if the transaction is a cart type. By definition a `cart type` transaction is a receipt with more than one item in the list.
- Hide the download button and show the unavailable receipt banner if `isCart`;
- Start the dev-server;
- Open the `Payments` section;
- Open a detail of transaction marked as `Pagamento multiplo` and check that there isn't visible the download button and there is a banner explaining it.
https://github.com/user-attachments/assets/8c22aeac-4e2d-48e3-9b2a-1737220ca877
> chore: [IOBP-1149] Hide download receipt button if the transaction is of cart type

- ts/features/barcode/screens/BarcodeScanScreen.tsx
- ts/features/payments/history/store/reducers/index.ts
This PR fixes some mixpanel properties in the payments flow mapping the right values.
- Added the `trackPaymentStartDataEntry` if the user starts the flow from the "Scan" tab;
- Fixed the `organization_fiscal_code` property mapping;
> fix(Payments): [IOBP-1153,IOBP-1154] Payments mixpanel properties mapping

- ts/utils/hooks/__tests__/usePreventScreenCapture.test.tsx
- ts/utils/hooks/usePreventScreenCapture.ts
This PR enables the screen capture in dev mode even when `usePreventScreenCapture` is used. This is useful for recording the screen during development.
- Check the value of `isDevEnv` in `usePreventScreenCapture`
Take a screenshot in the credential detail screen while in dev mode: screenshots should be allowed.
> chore(IT Wallet): [SIW-1996] Bypass the screen capture block in dev mode

- ts/features/itwallet/common/components/ItwCredentialCard.tsx
- ts/features/itwallet/common/components/ItwSkeumorphicCard/index.tsx
- ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
- ts/features/itwallet/common/utils/itwCredentialUtils.ts
- ts/features/payments/common/components/PaymentCard.tsx
- ts/features/payments/common/components/__tests__/__snapshots__/PaymentCard.test.tsx.snap
This PR adds a proper dark mode support to the `ItwCredentialCard` component.
- To get the correct theme color values, convert the `borderColorByStatus` function to the `useBorderColorByStatus` hook
- **[extra]** Add smooth corners to the wallet cards (iOS only)
| ![Simulator Screenshot - iPhone 16 Pro - 2025-01-28 at 10 16 12](https://github.com/user-attachments/assets/efce5f5e-c1ce-4e2e-904e-17b588f78522) | ![Simulator Screenshot - iPhone 16 Pro - 2025-01-28 at 10 14 59](https://github.com/user-attachments/assets/015e561d-fb6d-4c27-8405-3e39b18b30f0) | 
Launch the app in your local environment, switch to the dark mode and go to the **Wallet** section of the Design System
> style: [IOAPPX-473] Add dark mode support to the `ItwCredentialCard` component

- scripts/generate-api-models.sh
- ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
> [!WARNING]
> To test it you need this https://github.com/pagopa/io-dev-api-server/pull/460
This pull request includes updates to a script and a navigation route in the codebase
- Updated `IO_BACKEND_VERSION` from `v16.7.3-RELEASE` to `v16.7.4-RELEASE`
- Changed the navigation route in the `onPress` function from a string literal to a constant defined in `CGN_ROUTES`
Ensure that CGN works without regression
> chore: [PE-786] CGN update support fields optional

- ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
This pull request introduces the `HSpacer` component to improve the layout spacing between elements for CGN merchant list.
- Added `HSpacer` component to provide spacing between the merchant name and the badge in the `CgnMerchantListViewRenderItem` component
Check that CGN list items are rendering correctly
| Old | New |
| <img width="350" src="https://github.com/user-attachments/assets/15e5e472-63a5-4b22-a1f4-f6c28ce396cc"/> | <img width="350" src="https://github.com/user-attachments/assets/f24198c2-4ef8-4e2c-876d-087067e501bf"/> |
> refactor: [PE-923] CGN adjust list item element spacing

- ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
This PR replaces the `GradientScrollView` with `IOScrollView` component in order to hide the gradient at the bottom and allowing to see the entire PSP list.
- Replaced the `GradientScrollView` with `IOScrollView`;
Start a payment flow and reach the PSP selection step;
|Before|After|
|-|-|
|<img src="https://github.com/user-attachments/assets/d09c89a0-1658-4824-a8ce-09cd91807241" width="350px" />|<img src="https://github.com/user-attachments/assets/7d7e4a17-7ff4-44bb-ad15-2361392d81da" width="350px" />|
> refactor: [IOBP-1168] Replaced `GradientScrollView` with `IOScrollView` into PSP selection screen

- ts/features/idpay/details/components/InitiativeRulesInfoBox.tsx
- ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
- ts/features/idpay/payment/navigation/navigator.tsx
- ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
- ts/features/idpay/payment/screens/IDPayPaymentCodeInputScreen.tsx
- ts/features/idpay/unsubscription/navigation/navigator.tsx
- ts/features/idpay/unsubscription/screens/UnsubscriptionConfirmationScreen.tsx
- ts/features/idpay/unsubscription/screens/UnsubscriptionResultScreen.tsx
This pull request is refactoring and improving the consistency of the UI components across various screens in the `idpay` feature replacing custom layout components with standardized ones from the design system and adjusting the navigation options
- Replaced custom `ContentWrapper` and `ButtonSolid` components with `FooterActions`
- Replaced `ContentWrapper`, `FooterActionsInline`, and custom header with `IOScrollViewWithLargeHeader` and `ListItemHeader` for a more standardized header and footer layout 
Check refactored screen and ensure everything work properly
| `IDPAY_UNSUBSCRIPTION_CONFIRMATION` | `IDPAY_UNSUBSCRIPTION_CONFIRMATION` modal | `IDPAY_DETAILS_BENEFICIARY` modal |`IDPAY_PAYMENT_CODE_INPUT`|`IDPAY_PAYMENT_AUTHORIZATION`|
|--------|--------|--------|--------|--------|
| <img …
> refactor: [IOBP-1170] Align IDPay screen to design requirements

- ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
This pull request includes accessibility improvements to the `PAYMENT_NOTICE_SUMMARY` screen.
- Removed `accessibilityLabel` properties from the `ListItemInfo` components for recipient, object, amount, dueDate, payment notice code, and entity code.
- Using a real device 📱, go to the `PAYMENT_NOTICE_SUMMARY` screen
- Tap in each row and check if all are read correctly
> fix: [IOBP-1157] Correct `a11y` label in `PAYMENT_NOTICE_SUMMARY`

- ts/features/payments/details/components/PaymentsMethodDetailsBaseScreenComponent.tsx
This pull request enhances the accessibility of the header in the `PAYMENT_METHOD_DETAILS_SCREEN` screen. The implementation follows a similar approach to PR https://github.com/pagopa/io-app/pull/6418 to ensure consistency and improve the user experience.
- Removed the `transparent` property from the component's configuration
- Modified the `blueHeader` style by changing the `paddingTop` and `marginTop` properties to use fixed values instead of percentages
- Using a real device 📱, go to the `PAYMENT_METHOD_DETAILS_SCREEN` screen
- Tap on each header action and verify that all elements are correctly read by screen readers
@thisisjp this change will also adjust the Android card position relative to the top header. Could this be a design issue?
| Old …
> chore: [IOBP-1165] Remove transparent header in `PAYMENT_METHOD_DETAILS_SCREEN`

- ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
- ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
This pull request includes accessibility improvements to the `PAYMENTS_HOME` screen.
- Added missing `accessibilityLabel` to `endElement` prop
- Using a real device 📱, go to the `PAYMENTS_HOME` screen
- Tap `Aggiungi` and check if it is read correctly.
- Tap `Vedi tutte` and check if it is read correctly.
> fix: [IOBP-1162] Add missing `a11y` label in `PAYMENTS_HOME`

- locales/de/index.yml
- locales/en/index.yml
- locales/it/index.yml
This pull request includes updates to the localization files for German, English, and Italian
- Updated the `amountInfo` title and message to clarify that changes in the amount are automatically updated by the creditor institution, and to include additional details on potential reasons for the changes
- Try to pay something
- In `PAYMENT_NOTICE_SUMMARY` screen tap on ℹ️
- Ensure the bottom sheet text is align with design requirements
| `De` | `En` | `It` |
|--------|--------|--------|
| <img width="464" alt="Screenshot 2025-02-04 at 11 45 35" src="https://github.com/user-attachments/assets/8bd32768-f14c-49a0-8a66-618c97cc7cf7" /> | <img width="448" alt="Screenshot 2025-02-04 at 11 46 08" src="https://github.com/user-attachments/assets/3441cc68-e57a-4e01-b911-022b5f99ce9d" /> | <img …
> chore: [IOBP-1174] Align bottom sheet text with design requirements

- ts/App.tsx
This PR aims to filter error events to track on Sentry, in order to ignore error generated by the OS Http client when opening a in-app browser instance
- Changes on sentry init callback
Nothing should be changed in terms of app functionalities, just sentry ignoring related events
> chore: [IOPLT-949] Filters HttpClientErrors events from Sentry

- README.md
This PR removes `main/profile` deep link route from `README.md` file.
> chore: [IOAPPX-000] remove main/profile deep link route

- ts/sagas/startup.ts
- ts/store/reducers/backendStatus/remoteConfig.ts
This PR prioritizes the remote feature flag instead of the local feature flag to enable/disable the IDPay feature. Within this implementation, is possible to have both the remote FF and local FF giving high priority to the remote settings. The local feature flag is still needed because the IDPay feature will be disabled in a second interaction when the "Guidonia" bonus ends.
- Edited the startup saga to see if the IDPay feature is enabled from the remote configuration
- Edited the `isIdPayEnabledSelector` logic that is true if the local FF is true or the remote FF is true
- Edit the `dev-server` -> `backend.ts` file and set the `min_app_version` to the `idPay` attribute to a value lower or equal than the current app version and check that the bonuses cards are visible from the wallet …
> chore: [IOBP-1180] Add priority to remote feature flag for the IDPay feature

- .github/workflows/pr-title-conventional-commit-linter.yml
- .github/workflows/pr-title-linter-and-linker.yml
This pull request includes changes to two GitHub Actions workflow files to handle cases where multiple comments with the same title are found. The changes ensure that the workflows exit with a [specific error message](https://github.com/pagopa/io-app/actions/runs/13245583583/job/36971175921) if such a situation is detected  avoiding [this error](https://github.com/pagopa/io-app/actions/runs/13245489050/job/36970864682).
* [`.github/workflows/pr-title-conventional-commit-linter.yml`](diffhunk://#diff-de57f78a94808c565c7223c76a3f918609a1e89cc3284597286690c944e9e2cbR50-R56): Added logic to count existing comments with the same title and exit with an error message if more than one is found.
* [`.github/workflows/pr-title-linter-and-linker.yml`](diffhunk://#diff-36369bf33364c44d17cf895448fcaf59 …
> fix(Cross): [IOAPPX-000] Check for more than one message in linter workflows

- .github/actions/setup-composite/action.yml
- .github/workflows/distribute-beta.yml
- .github/workflows/release-canary.yml
- .github/workflows/release-new-cycle.yml
- .github/workflows/release-nightly.yml
- .github/workflows/staticcheck.yaml
- .github/workflows/test-e2e.yml
- .github/workflows/weekly-jobs.yml
This pull updates the actions/cache action from version v3.3.1(deprecated) to v4.2.0
> ci: [IOAPPX-483] updates actions/cache due to github deprecation

- ts/features/barcode/screens/BarcodeScanScreen.tsx
- ts/screens/profile/DeveloperModeSection.tsx
- ts/screens/profile/SecurityScreen.tsx
- ts/store/reducers/backendStatus/remoteConfig.ts
- ts/store/reducers/persistedPreferences.ts
This PR moves certain IDPay features under a local feature flag, as they are not yet needed in production. These features will be controlled by a local feature flag instead of a remote one, while all required functionalities remain under a remote feature flag.
- Renamed the local feature flag selector in `isIdPayLocallyEnabledSelector`
1. Keep the app’s local feature flag disabled and the remote feature flag enabled (via dev-server).
2. Verify that IDPay cards are displayed in the Wallet section.
3. Check that in Security & Access, the "IDPay Code" option is not visible.
4. In the Scan section, when tapping on "Digita", no bottom sheet appears asking what to insert.
5. Then, enable the local feature flag and ensure all these features are displayed as expected.
> fix(IDPay): [IOBP-1203] Show some IDPay features not needed under local feature flag

- ts/components/screens/OperationResultScreenContent.tsx
- ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
This pull request includes updates to the `OperationResultScreenContent` and `WalletPaymentFailureDetail` components to enhance the user interface by adding icons to actions
- Added the `icon` property to the `action` and `secondaryAction` props to allow the inclusion of icons in buttons
- Added an `icon` property with the value `"categLearning"` for better visual indication
At payment verify phase, try to recreate a `PAYMENT_CANCELED` error and ensure the outcome is aligned with [design requirements](https://www.figma.com/design/KY9BpP4LaSSd18fuYMwxYK/branch/AGn2SCNf81WNpAt8eCm7GG/Paga-un-avviso-pagoPA?node-id=2750-12850&t=ker70SekwtX08w91-0)
> refactor: [IOBP-1202] Icon for `PAYMENT_CANCELED` cta

- locales/de/index.yml
- locales/en/index.yml
- locales/it/index.yml
- ts/features/payments/receipts/screens/ReceiptCartItemDetailsScreen.tsx
This pull request updates the localization for noticeCode to include the IUV text
- Updated the `noticeCode` translation to _Codice avviso/IUV_ and added a new entry for `noticeCodeAccessible` with the value _Codice avviso/Identificativo Univoco Versamento_
- Apply `noticeCodeAccessible` text for the `accessibilityLabel`
Ensure that label text in `PAYMENT_RECEIPT_CART_ITEM_DETAILS` now includes `/IUV`
> refactor: [IOBP-1204] Add `IUV` to label

- ts/features/idpay/details/components/MissingConfigurationAlert.tsx
- ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
- ts/features/idpay/details/screens/__tests__/IdPayInitiativeDetailsScreen.test.tsx
This PR removes the missing configuration alert for initiatives of type `EXPENSE`
- Added tests to check if the alert should be shown or not;
- Removed the component `MissingConfigurationAlert` from the content render of IDPay details screen;
- Open an IDPay expense initiative that has the `status` of value `NOT_REFUNDABLE_ONLY_INSTRUMENT`;
- Check that there isn't any alert showing a message;
- Double-check that the other initiatives of type `REFUND`, if `status` is `NOT_REFUNDABLE_ONLY_INSTRUMENT`, should show the correct alert.
|Before|After|
|-|-|
|<img src="https://github.com/user-attachments/assets/1665c8dc-61bc-454b-b0d8-3008c2b4dbe3" width="350px" />|<img src="https://github.com/user-attachments/assets/0488398b-3f3a-4293-9fa0-47efbf6558d5" width="350px" />|
> chore(IDPay): [IOBP-1205] Removed the missing configuration alert for `EXPENSE` initiatives

- locales/en/index.yml
- locales/it/index.yml
- ts/components/ui/Markdown/handlers/__test__/link.test.ts
- ts/components/ui/Markdown/handlers/link.ts
- ts/features/common/components/IOMarkdown/__test__/customRules.test.tsx
- ts/features/common/components/IOMarkdown/customRules.tsx
This PR removes (broken) support for non https links on IOMarkdown, on messages and services
<video src="https://github.com/user-attachments/assets/217bc4db-86de-4c36-be06-14894a4b7e97" />
- Link filtering to only work for ioit and https links
Using the io-dev-api-server, check that:
- ioit links work
- https links work
- any other type of link does not work
> fix: [IOCOM-2097] Special link support removed from IOMarkdown on messages and services

- package.json
- ts/features/design-system/core/DSSelection.tsx
- ts/features/itwallet/common/components/__tests__/__snapshots__/ItwFeedbackBanner.test.tsx.snap
- ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
- ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerOnboarding.test.tsx.snap
- ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
- ts/features/messages/components/MessageDetail/__tests__/__snapshots__/RemoteContentBanner.test.tsx.snap
- ts/features/pushNotifications/components/__tests__/__snapshots__/PushNotificationsBanner.test.tsx.snap
- ts/screens/authentication/__tests__/__snapshots__/LandingScreen.test.tsx.snap
- ts/screens/profile/__test__/__snapshots__/ProfileMainScreenTopBanner.test.tsx.snap
- ts/screens/profile/components/__test__/__snapshots__/SettingsDiscoveryBanner.test.tsx.snap
- yarn.lock
This pull request updates the @pagopa/io-app-design-system to solve the accessibility focus order of the `Banner` component
- Updated the `@pagopa/io-app-design-system` package from version `4.5.5` to `4.5.6`
- Removed the unused `SwitchLabel`
- Removed the unnecessary fragment tags around the `AnimatedMessageCheckboxShowroom` component
- Using a real device 📱, check the Banner in the `Pagamenti` section
- Ensure that when navigating with the `Tab` and `Shift + Tab` keys, the switch logic for the `Banner` component correctly moves focus (Text -> CTA -> Close Icon)
https://github.com/user-attachments/assets/de385151-cd7f-4b31-9a4f-b36e7b84c929
> fix: [IOBP-1179] `a11y` banner focus order

- ts/features/bonus/cgn/components/CgnCard.tsx
This PR fixes the a11y text on the expiry date of the CgnCard component, replacing it with more accessible text that contains the full month and full year.
- Formatted the accessibilityLabel with the full month and full year in order to be more accessible.
Inside the wallet home screen, open the SR on your device and check that the CGN validity is more accessible with full month and full year as values.
> fix: [PE-937] a11y on `CgnCard` expiry date

- ts/features/cieLogin/components/CieIdLoginWebView.tsx
- ts/features/messages/components/Home/__tests__/__snapshots__/TabNavigationContainer.test.tsx.snap
- ts/navigation/AuthenticationNavigator.tsx
- ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
- ts/utils/__tests__/hooks/useOnbardingAbortAlert.test.ts
- ts/utils/hooks/useOnboardingAbortAlert.ts
This PR adds the possibility to go back from `CieIdLoginWebView` and `CieConsentDataUsageScreen`
<details><summary>Details</summary>
<p>
| Cie | CieID |
| - | - |
| <video src="https://github.com/user-attachments/assets/554a8c5a-0dfa-4c64-aaa8-4dcba98e0229" /> | <video src="https://github.com/user-attachments/assets/6d0a43ce-7c64-4e9f-9957-aeeaa7bf7928" />
| Cie | CieID |
| - | - |
| <video src="https://github.com/user-attachments/assets/d656f050-f6af-4c51-8159-72810288b9e2" /> | <video src="https://github.com/user-attachments/assets/ce052883-3f9d-44ee-9584-97d159ce264d" />
</p>
</details> 
* [`ts/features/cieLogin/components/CieIdLoginWebView.tsx`](diffhunk://#diff-8525a47a8c535183fa25dcb03b4edd382aaed38fc026f3ff0e12d9cf206d02c8R40): Added the `useOnboardingAbortAlert` hook and updated …
> chore: [IOPID-2690] Support back navigation from `CieIdLoginScreen` and `CieConsentDataUsageScreen`

- locales/en/index.yml
- locales/it/index.yml
- ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
This PR adds a view wrapper with an accessibility label that describes that there is displayed a pdf receipt in that screen.
- Added a11y description label to a view that wraps the Pdf preview.
With a real device (particularly Android), open a receipt detail and go inside the receipt preview screen.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/ace3349f-6ca4-45c8-9b65-37031f6204cc" width="300" />|<video src="https://github.com/user-attachments/assets/4c30ddf0-311b-4acf-830f-ad06a3db2641" width="300" />|
> chore: [IOBP-1164] Add a11y description to the receipt PDF preview page

- ts/features/itwallet/common/utils/__tests__/itwCredentialStatusUtils.test.ts
- ts/features/itwallet/common/utils/itwCredentialStatusUtils.ts
- ts/features/itwallet/credentials/store/selectors/index.ts
This PR increases the notification period of expiring credentials to 30 days.
- Increased default value to 30 in `getCredentialStatus`
Use credentials that are about to expire or mock the `expiry_date` claim.
> chore(IT Wallet): [SIW-2012] Notify the user 30 days before credential expiration

- ts/features/itwallet/common/store/actions/preferences.ts
- ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
- ts/features/itwallet/common/store/reducers/preferences.ts
- ts/features/itwallet/common/store/selectors/preferences.ts
- ts/features/itwallet/common/utils/itwTypesUtils.ts
- ts/features/itwallet/presentation/details/components/ItwPresentationClaimsSection.tsx
This PR allows users to save and persist their preference for displaying claim values in credential details
- Add a new action (`itwSetClaimValuesHidden`) and selector (`itwIsClaimValueHiddenSelector`) to manage the hidden state of claim values in credentials detail screen.
- Updated the `ItwPresentationClaimsSection` component to dispatch the action and retrieve the state from the store
Hide the claim values, exit from the credential details or close the app, and verify that the selected display preference is retained
https://github.com/user-attachments/assets/f47c6a7e-bf9d-4638-8a13-f22d919fd2b2
> chore(IT Wallet): [SIW-1990] Persist user preference for hiding claim values in credential details

- package.json
- ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
- yarn.lock
This PR fixes and improves the accessibility focus issue when opening the Barcode scan screen. Now it announces and focuses on the "Scan" tab when opening the screen and focusing it back.
- Updated the `io-app-design-system` library with the version `5.0.2` which supports the TabItem `ref` prop;
- Disabled the automatic accessibility focus on the `BaseHeader` component;
- Set the accessibility focus to the "Scan" tab item at every screen focus with a 200ms delay which is necessary due iOS behaviors.
- Run `yarn install` and check that the `io-app-design-system` library has the version `5.0.2`
- With the SR enabled, open the barcode scan screen both from "Scan" tab and "Payments" tab;
- Check that the "Scan" tab item is announced and focuesed at the first render and when navigating back …
> chore: [IOBP-1194,IOBP-1196] a11y focus improvements on Barcode scan screen

- ts/features/bonus/cgn/screens/activation/CgnActivationLoadingScreen.tsx
- ts/features/bonus/cgn/screens/activation/__tests__/CgnActivationLoadingScreen.test.tsx
This pull request is improving accessibility for `CgnActivationLoadingScreen` to its loading state
- Added a `useRef` hook and `useOnFirstRender` to set accessibility focus on the `SafeAreaView` component when the `LoadingComponent` is first rendered
- Using a real device 📱, start the `CGN` card onboarding
- Press on `Attiva Carta Giovani Nazionale`
- Ensure that, when the loading state is appearing, the screen reader is now reading the loading state
> chore: [PE-996] Accessibility for CGN loading component

- ts/features/itwallet/presentation/details/components/ItwPresentationCredentialStatusAlert.tsx
Replaced the `Body` component with `IOMarkdown` to support markdown formatted errors descriptions when using EC error messages
- Replaced the `Body` component with `IOMarkdown` inside `IssuerDynamicErrorAlert`
Simulate a remote dynamic error checking that the error description is displayed correctly
> feat(IT Wallet): [SIW-2042] Use IOMarkdown when displaying a remote message inside credential presentation 

- scripts/generate-api-models.sh
- ts/features/idpay/wallet/components/IdPayCard.tsx
- ts/features/idpay/wallet/components/__tests__/IdPayCard.test.tsx
- ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap
This PR removes the total amount label from the IdPayCard shown in the wallet home screen if the IdPay initiative is of the `EXPENSE` type.
- Updated the IDPay openAPI version;
- Added a conditional render inside the `IdPayCard` to show the total amount;
With the dev-server started, onboard a new IDPay EXPENSE type and check that you don't see the total amount inside the wallet home page.
> chore: [IOBP-1231] Removed total amount from IdPayCard if reward type is `EXPENSE`

- ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
This PR removes the `referer` unused custom header from CGN's webview. The correct referrer header is `X-PagoPa-CGN-Referer`
> fix: [IOBP-1361] CGN webview referer unused header

- package.json
- ts/features/bonus/cgn/screens/merchants/__tests__/__snapshots__/CgnMerchantsCategoriesSelectionScreen.test.tsx.snap
- ts/features/messages/components/Home/__tests__/__snapshots__/TabNavigationContainer.test.tsx.snap
- yarn.lock
This pull request updates the design system version to resolve the accessibility issue with the price label for the `RadioGroup` items
- Update`@pagopa/io-app-design-system` package from `5.0.6` to `5.0.7`
- Start a payment workflow using a real device📱
- Turn on TalkBack accessibility tool when you reach the second step of `PAYMENT_CHECKOUT_MAKE` screen
- Ensure that all radio items are correctly spelled
> chore: [IOBP-1236] Adjust `a11y` RadioGroup item price label

- ts/components/ui/BannerErrorState.tsx
This PR fixes the banner error state text alignment to the center.
- Added text align center style
With the dev-server, simulate an error inside the wallet home screen by throwing an error to one of the API available in that page (CGN, IDPay or Payments)
|Before|After|
|-|-|
|<img src="https://github.com/user-attachments/assets/4e879464-dcb2-4e14-98fb-3b91b3f709e5" width="300" />|<img src="https://github.com/user-attachments/assets/3a49a847-b471-49df-81f3-354166f7f5f9" width="300" />|
> fix: [IOBP-1360] Banner error state text align

- locales/en/index.json
- locales/it/index.json
- ts/features/idpay/onboarding/screens/BoolValuePrerequisitesScreen.tsx
- ts/features/idpay/onboarding/screens/InputFormVerificationScreen.tsx
- ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
- ts/urls.ts
This PR removes the self-declaration DPR text and link from the prerequisites screen in IDPay onboarding.
- Removed the description from `BoolValuePrerequisitesScreen`, `InputFormVerificationScreen` and `MultiValuePrerequisitesScreen`
- Removed from the codebase the unused URL link `dpr28Dec2000Url`
- Removed unused locales
With the dev-server server started, start an IDPay onboarding from the developer section selecting the `Iniziativa GUIDONIA` from the list and checks that the DPR text link isn't shown anymore.
|Before|After|
|-|-|
|<img src="https://github.com/user-attachments/assets/940eb99a-75d6-46b8-9f44-3cdfe98b5f1a" width="300" />|<img src="https://github.com/user-attachments/assets/d0420fec-ed3d-4d79-bffe-8b9ec32e32de" width="300" />|
> refactor: [IOBP-1362] Removed self declaration DPR link text into IDPay prerequisites screen

- ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
This PR fixes a blocking bug in the IDPay multi-value prerequisites screen that, previously, the value mapped was wrong since the value to map isn't the index of the array but the value provided from the API response.
- Edited the `selectedValue` with the `selectedValueIndex` as it indicates the index of the selected value;
- Mapped the correct value when the user continues to the next page.
> fix: [IOBP-1363] IDPay multi value prerequisites value mapping

- ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
- ts/features/payments/common/types/PaymentAnalytics.ts
- ts/features/payments/history/store/__tests__/store.test.ts
- ts/features/payments/history/store/reducers/index.ts
- ts/features/payments/receipts/analytics/index.ts
- ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
This pull request focuses on tracking when a user lands on the PDF receipt screen with the event `DOWNLOAD_RECEIPT_SUCCESS`
- Updated the `PaymentsHistoryState` type to include a new `PDFsOpened` set and modified the reducer to handle the new `getPaymentsReceiptDownloadAction` action, tracking the first-time opening of PDFs based on its receiptID 
- `trackPaymentsDownloadReceiptSuccess` to track successful receipt downloads in `mixpanel`
- Go to Payment section and open a receipt
- Press on `Ottieni ricevuta`
- Ensure that `mixpanel` properties are dispatched correctly (if first time you will see `first_time_opening: true`)
- Go back and open again the same receipt
- Ensure that `first_time_opening` is set to `false`
> chore: [IOBP-1218] `mixpanel` success download receipt event

- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
- ts/features/itwallet/machine/credential/__tests__/machine.test.ts
- ts/features/itwallet/machine/credential/events.ts
- ts/features/itwallet/machine/credential/machine.ts
- ts/features/itwallet/machine/eid/events.ts
- ts/features/itwallet/presentation/remote/machine/events.ts
This PR fixes a bug which causes a double navigation within the async issuance flow.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/85abaf8b-6f69-43f6-a497-d730fbe8b83a" /> |  <video src="https://github.com/user-attachments/assets/d2007033-296a-4c12-930a-ae5917bad043" /> |
- Simplified `ItwIssuanceCredentialAsyncContinuationScreen`
- Fixed `DisplayingTrustIssuer` state actions within the credential's issuance machine
- Removed unused `reset` event from machines
- Added `Loading` tag to `Idle` and `CheckingWalletInstanceAttestation`
- Added `Completed` state
Check if there aren't regressions in the credential issuance flow.
Check if there isn't a double navigation when using the async issuance flow.
> fix(IT Wallet): [SIW-2083] Fix async issuance double navigation within issuer trust screen

- ts/components/BonusCard/BonusCard.tsx
- ts/components/BonusCard/BonusCardScreenComponent.tsx
This PR fixes a critical bug that occurs when a user has a screen reader enabled while opening the CGN details screen. Previously, the focus was blocked, preventing navigation through gestures within the page.
- The only feasible solution for now is to disable header transparency when the screen reader is enabled;
- Added accessibility focus to the bonus card title on the details page.
1. Use a real iOS device and enable VoiceOver.
2. Navigate through the CGN details card page.
3. Verify that when VoiceOver is enabled:
- The header transparency is disabled.
- You can navigate within the screen using swipe gestures.
4. Double-check that when VoiceOver is disabled, the header transparency remains enabled as expected.
|Before|After|
|-|-|
|<video …
> fix: [IOBP-1379,IOBP-IOBP-1380] Disable CGN header transparency when screen reader is enabled

- locales/en/index.json
- locales/it/index.json
- ts/features/pn/navigation/navigator.tsx
- ts/features/pn/screens/PnReminderBannerFlow.tsx
- ts/features/pn/screens/__test__/__snapshots__/PnReminderBannerFlow.test.tsx.snap
addition of success, failure and loading screens UI for the SEND engagement banner flow
- said components
-  required i18n keys
- back navigate header for the `WAITING_USER_INPUT` state
- regeneration of snapshots
tests should solve correctly, also make sure that all screens render correctly, and that the "activate send" screen's header tap navigates to MESSAGES_HOME as expected.
> feat: [IOCOM-2184] addition of loading and result UI for SEND banner flow

- ts/features/bonus/cgn/components/merchants/discount/CgnDiscountContent.tsx
This pull request includes an improvement to the accessibility of the `CgnDiscountContent` component by adding an `accessibilityLabel` to the discount validity information
- Added an `accessibilityLabel` to provide a clear and descriptive label for the discount validity dates. This label includes the start and end dates formatted according to the locale's short date format
- With Talkback enabled go in `CGN_MERCHANTS_DISCOUNT_SCREEN`
- Tap on `Validità` label
- Verify that the screen reader correctly announces the date, including the `validity_interval` phrase
> chore: [IOBP-1414] Adjust a11y discount validity dates label

- ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
- ts/features/landingScreenMultiBanner/components/LandingScreenBannerPicker.tsx
- ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
- ts/features/pn/components/PNActivationReminderBanner.tsx
- ts/features/pn/screens/PnReminderBannerFlow.tsx
- ts/features/pn/store/actions/index.ts
- ts/features/pn/store/reducers/bannerDismiss.ts
- ts/features/pn/store/reducers/index.ts
- ts/store/reducers/index.ts
addition of a persisted state entry for dismiss for the SEND engagement banner
- required persisted reducer
- required action
- required selector, and update to the bannerMap
- small refactor the the landingScreenBannerPicker 
complete tests to come 
- existing tests should pass
- on banner dismiss or success flow end, the banner should be dismissed
- the dismissal should persist until the asyncStorage is cleared
- the landingScreenBannerPicker should work as usual and intended
- the landing_banners reducer's data should not be impacted other than the standard dismiss.
> feat:[IOCOM-2223] persisted dismiss logic for SEND banner

- README.md
- ios/ItaliaApp.xcodeproj/project.pbxproj
This PR updates the node binary detection script on iOS according to the one provided directly from React Native for the current version of the app.
- Update the `project.pbxproj` with the new script which automatically detects and create a `.xcode.env.local` file which contains the result of `which node`;
- Update `README.md` instructions to build the app accordingly.
Try to run a iOS build from Xcode without manually changing the `node` path.
> chore: [IOAPPX-494] Update node binary script detection on iOS

- ts/features/payments/receipts/saga/handleDisableReceipt.ts
- ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
- ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
This pull request enhances Mixpanel analytics for receipt-related actions by including the missing `organization_fiscal_code` field. These updates ensure compliance with tracking requirements.
- Added missing mixpanel property for `HIDE_RECEIPT_SUCCESS`, `DOWNLOAD_RECEIPT_FAILURE` and `SAVE_AND_SHARE_RECEIPT` events
Verify that all relevant properties are correctly tracked in the analytics events
> chore: [IOBP-1487] Enhance Mixpanel analytics for payment events

- ts/features/pn/reminderBanner/reducer/__test__/bannerDismiss.test.ts
- ts/features/pn/reminderBanner/reducer/bannerDismiss.ts
- ts/store/reducers/index.ts
proposed fix for said misbehaviour
- updated reducer
- updated root reducer behaviour for SEND's part
- required tests
using the dev-server, and using physical devices and emulators, make sure that after the following sequence:
- login
- banner dismissal
- quit+reopen app (banner should still not be shown)
- logout, login again without quitting the app (banner should now be shown)
- quit and reopen app
the banner correctly gets shown
> fix: [IOCOM-2279] logout misbehaviour for SEND banner dismissal

- ts/components/WebviewComponent.tsx
- ts/screens/profile/CgnLandingPlayground.tsx
This PR adds the error debug logger when the debug mode is enabled when showing the `WebviewComponent` that is used for the CGN merchants landing page discount;
- Dispatched the debug data log when there is any error inside the webview render;
- Enable the debug mode;
- Open the `CGN Landing Page` playground screen;
- Type any invalid URL and a not-empty Referer;
- Check that the debug icon at the top of the screen is shown with a log;
https://github.com/user-attachments/assets/53935a68-8144-4d34-b7f2-111d04bcc0e1
> chore: [IOBP-1516] Add CGN webview landing page debug error logger

- ts/features/services/search/screens/SearchScreen.tsx
This PR reverts the recent change to the keyExtractor in the services search to prevent blank spaces when potential duplicate results are returned by AI Search.
- updated keyExtractor
Using `io-dev-api-server`, navigate to the services tab. Check that the search works as expected
> chore: [IOPAE-1950]: Revert keyExtractor in the services search

- ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
This pull request includes changes to the `CgnMerchantDetailScreen` file in order to replace the `GradientScrollView` component with the `IOScrollView` component
- Replaced the `GradientScrollView` component with the `IOScrollView` component in the `CgnMerchantDetailScreenSkeleton` function
Ensure that displayed skeleton has no white gradient shadow when `CGN_MERCHANTS_DETAIL` screen is loading
| Old | Now |
| <video src="https://github.com/user-attachments/assets/9fd47663-1648-42da-b6a2-db114e5b2d0d"/> | <video src="https://github.com/user-attachments/assets/1595747a-8cd4-437d-a3a6-c6c391c62796"/> |
> chore: [IOBP-1551] Replace `GradientScrollView` with `IOScrollView`

- ts/features/payments/history/store/reducers/index.ts
- ts/features/payments/receipts/components/HideReceiptButton.tsx
- ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
- ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
This pull request focus on removing the `payment_status` that is set to `paid` from various analytics tracking calls across B&P stream
-  Removed the `payment_status` field from the B&P mixpanel tracking
Ensure that property `payment_status: "paid"` is no more tracked
> chore: [IOBP-1559] `payment_status` always set to `paid` – removed from analytics

- ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
This pull request includes changes to the `PaymentsHomeUserMethodsList` component to enhance the tracking of selected payment methods. The modifications involve updating the `handleOnMethodPress` function to accept an additional parameter for the selected payment method and adjusting the corresponding calls to this function
- Updated the `handleOnMethodPress` function to accept an optional `payment_method_selected` parameter for improved analytics tracking
- Modified `handleOnMethodPress` to pass the `method.details?.type` as the `payment_method_selected` parameter
Ensure that the `payment_method_selected` now is defined when pressing a card from carousel in `Pagamenti` screen
> chore: [IOBP-1561] Adjust `payment_method_selected` mixpanel property

- locales/en/index.json
- locales/it/index.json
This PR updates the copy for the screen indicating that the user's eID has expired in the remote presentation flow.
- Update copy in `ItwRemoteFailureScreen`, `EID_EXPIRED` case
Verify that the error screen is the same as the one on Figma
https://github.com/user-attachments/assets/fee391f8-cdef-446b-8709-148c1d53f977
> feat(IT Wallet): [SIW-2208] Remote presentation, update copy eID expired screen

- locales/en/index.json
- locales/it/index.json
- ts/features/itwallet/common/hooks/useItwDismissalDialog.tsx
- ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
- ts/features/itwallet/identification/screens/cieId/ItwCieIdLoginScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
- ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
- ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
This PR modifies the copy for the `ItwRemoteFailureScreen` in the case of an inactive wallet. 
Show an alert using `useItwDismissalDialog`, in case you want to exit from the remote presentation flow
- Updated the copy for the `ItwRemoteFailureScreen` in the wallet inactive case
- Modified `useItwDismissalDialog` to accept a custom body message.
Without IT-Wallet scan a valid QR code for remote presentation, check that the screen displayed is correct and clicking get “IT-Wallet” takes you to the activation flow. Clicking “Not now” should display the alert asking for confirmation to close the process or not.
https://github.com/user-attachments/assets/7fbe24b0-7e7d-499f-bf48-58a2feb0ea3e
> feat(IT Wallet): [SIW-2207] Remote presentation, inactive IT-Wallet failure screen

- ts/store/reducers/index.ts
This PR fixes a regression where logging in after a logout would freeze until the `connectivityStatus` was updated.
Bonus Fix: It also ensures the `cie` status is preserved. Without this, citizens were not given the option to choose between EIC+PIN and CieID login methods.
<details><summary>Details</summary>
<p>
| ❌ | ✅ |
| - | - |
| <video src="https://github.com/user-attachments/assets/c62a5894-2076-4043-9d81-803704d60caa" /> | <video src="https://github.com/user-attachments/assets/1660169d-f57a-4ec8-ba85-7f921088a019" />
</p>
</details> 
- Keep `cie` and `connectivityStatus` after a logout.
1. Launch the app and perform a successful login.
2. Logout from the app.
3. Attempt to log in again.
✅ You should be able to access the app immediately without encountering any blocking or frozen …
> fix: [IOPID-2949] keep `cie` and `connectivityStatus` after logout

- ts/features/payments/receipts/components/HideReceiptButton.tsx
This pull request includes a minor change to the `HideReceiptButton` modifying the `variant` property that has been updated from `"primary"` to `"danger"` to better reflect its purpose of hiding receipts
- Update `variant` property
Ensure that the hide receipt button color now is red
> style: [IOBP-1623] Update hide receipt button color

- ts/hooks/useStatusAlertProps.tsx
This PR addresses a bug which causes the status alerts to be displayed within the offline mini app,  causing a double alert to appear
- Added `offlineAccessReason` check within `useStatusAlertProps` hook
Ensure that status alerts works as expected across all app features and no regression were introduced.
With the device offline, open the wallet screen and check that appears a single alert which informs of the offline status.
> fix(IT Wallet): [SIW-2339] Disable status alert for offline mini-app

- android/app/src/main/AndroidManifest.xml
This PR disables Android ANRs error from native config to sentry
> fix: [IOPLT-0000] Disables ANR errors to Sentry from native layer config

- .github/workflows/release-canary.yml
This PR changes the canary workflow to trigger only on manual dispatch.
> ci: [IOPLT-0000] Canary release trigger only on manual dispatch

- ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
This pull request makes updates to the `CgnMerchantsListByCategory` file adding a new constant for consistent spacing
- Removed unused variables `screenHeight` and `translationY` from the component to clean up the code
-  Updated the `contentContainerStyle` of the `FlatList` to include `paddingBottom` using `IOVisualCostants.appMarginDefault`, ensuring consistent spacing across the app
Ensure that in iOS the screen `CGN_MERCHANTS_LIST_BY_CATEGORY` has enough room for last element
> refactor: [IOBP-1624] Add extra bottom padding to CGN merchants list

- ts/features/payments/receipts/analytics/index.ts
- ts/features/payments/receipts/analytics/utils.ts
- ts/features/payments/receipts/components/HideReceiptButton.tsx
- ts/features/payments/receipts/components/ReceiptListItemTransaction.tsx
- ts/features/payments/receipts/components/___tests___/ReceiptListItemTransaction.test.tsx
- ts/features/payments/receipts/saga/handleDisableReceipt.ts
- ts/features/payments/receipts/store/actions/index.ts
This pull request refactors the analytics tracking logic. It introduces support for tracking user interaction trigger types by updating the relevant functions to include a `trigger` type parameter. Common tracking logic has been extracted into utility functions to reduce duplication and enhance maintainability. 
- Updated the hide payments receipt Mixpanel actions payload to include the `trigger` property 
- Removed the `void` keyword from `mixpanelTrack` calls as unnecessary
- Move common function in `utils` 
Ensure that the same data sent to Mixpanel when the "Nascondi dalla lista" button is clicked is also sent when a receipt is hidden via swipe
> chore: [IOBP-1634] Mixpanel events for hide receipt swipe action

- ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
- ts/features/itwallet/common/store/reducers/preferences.ts
- ts/features/itwallet/lifecycle/saga/__tests__/checkCurrentWalletInstanceStateSaga.test.ts
- ts/features/itwallet/lifecycle/saga/checkCurrentWalletInstanceStateSaga.ts
This PR fixed some issues with the IT Wallet Discovery banner
- Fixed an issue with `isWalletInstanceRemotelyActive` that was undefined when interrupting the eID issuance flow
- Replaced the selector to understand if the user has a local active wallet, now it is `itwLifecycleIsValidSelector` that checks if there is a valid `integrityKeyTag` and a valid `eid`. This was causing issues since we were checking only for the `integrityKeyTag` and not for the `eid`.
1) Activate ITW from a clean installation and check if everything works as expected
2) Try to activate ITW and interrupt the flow before the identification screen; the previous banner should be displayed without issues.
3) Activate ITW, uninstall the app, or change device and re-activate ITW; the reactivation banner should be …
> fix(IT Wallet): [SIW-2317] Discovery banner not displayed when leaving eID issuance flow

- ts/features/settings/userData/shared/screens/EmailInsertScreen.tsx
This PR sets a `maxFontSizeMultiplier` on all `Text` components within the `EmailInsertScreen` to prevent layout issues that may lead to unresponsiveness (React Navigation freeze) or screen elements becoming hidden (e.g., the input field and button).
<details><summary>Details</summary>
<p>
| ❌ | ✅ | 
| - | - |
| <img src="https://github.com/user-attachments/assets/33573bb2-db2b-4d30-a637-435e6f097d59" widht="200" /> | <img src="https://github.com/user-attachments/assets/47b2ed36-c778-44ed-9e34-de5e28763d23" widht="200" /> | 
| ❌ | ✅ | 
| - | - |
| <img src="https://github.com/user-attachments/assets/9daf1a82-2a8c-4d11-b5a2-7457fa1155e9" widht="200" /> | <img src="https://github.com/user-attachments/assets/2d64b40a-193f-46af-a7b8-c0ee66c33271" widht="200" /> |
</p>
</details> 
We’ve …
> fix: [IOPID-2806] Add `maxFontSizeMultiplier` to `EmailInsertScreen`

- ts/features/itwallet/common/components/ItwOfflineWalletBanner.tsx
This PR adds the link to the offline FAQ on click of the offline banner.
- Updated the `handlePress` of  `ItwOfflineWalletBanner` 
1. Navigate to the offline wallet banner in app.
2. Click on the offline banner.
3. Verify that the offline FAQ link opens in a new tab.
> feat(IT Wallet): [SIW-2309] Add link to offline FAQ on click of offline banner

- ts/features/pn/analytics/index.ts
- ts/features/pn/store/sagas/__tests__/watchPnSaga.test.ts
- ts/features/pn/store/sagas/watchPnSaga.ts
This PR adds the `reason` property to the mixpanel event `PN_SERVICE_STATUS_CHANGE_ERROR`
- `reason` property to the mixpanel event `PN_SERVICE_STATUS_CHANGE_ERROR`
Using io-dev-api-server, simulate a left either, a 500 failure status code and a generic throw inside the pn activation saga and check that is properly reported.
> chore: [IOCOM-2364] add `reason` to `PN_SERVICE_STATUS_CHANGE_ERROR`

- ts/features/pn/store/sagas/__tests__/watchPnSaga.test.ts
- ts/features/pn/store/sagas/watchPnSaga.ts
- ts/features/services/details/saga/__tests__/handleGetServicePreference.test.ts
- ts/features/services/details/saga/handleGetServicePreference.ts
- ts/sagas/startup.ts
addition of said request during the app's startup cycle
- addition of a generator function specifically to fetch necessary service preferences on startup
- placement of said function in startup saga
- refactor of `loadPreferenceIfValidId` in `watchPnSaga.ts`, in order to use it in the main service preferences fetching function.
- required tests
using reactotron, check that the SEND data (`state.features.services.details.preferencesById`) gets requested on startup, before the user lands in the home screen.
Also, make sure that the requesting function (`fetchServicePreferencesForStartup`) is actually only called once during startup.
> feat: [IOCOM-2335] addition of SEND preferences request to startupSaga

- locales/en/index.json
- locales/it/index.json
- ts/features/pn/reminderBanner/components/__test__/__snapshots__/PNActivationReminderBanner.test.tsx.snap
updated i18n keys for said banner's CTA
- updated i18n keys
- updated snapshots where necessary
tests should pass, also the SEND banner's CTA in the landing screen should match the new design.
> feat: [IOCOM-2343] SEND banner i18n update

- ts/features/payments/checkout/analytics/index.ts
- ts/features/payments/checkout/components/WalletPaymentPspBanner.tsx
This PR tracks on mixpanel the mybank psp banner inside the PSP selection screen.
- Added two tracking events `trackPaymentMyBankPspBanner` and `trackPaymentMyBankPspBannerClose`
- Start a new payment;
- Select "MyBank" as payment method;
- When you reach the PSP selection screen and a PSP banner is displayed, verify that the events are correctly tracked in Mixpanel
> chore: [IOBP-1646] Track MyBank PSP banner on mixpanel

- ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
This PR shows the dismissal dialog when leaving the presentation flow in the missing credentials screen.
- Show dismissal dialog
- Use `i18nNs` in the relevant translation keys
Remove the MDL from the wallet and request it in the presentation. In the missing credential screen, tap on "Not now": you should see the dismissal dialog.
> fix(IT Wallet): [SIW-2408] Show dismissal dialog in missing credentials failure screen

- ios/Podfile.lock
- package.json
- yarn.lock
This PR adds a TEE fallback when the attestation generation with StrongBox enabled fails.
- Updated `io-react-native-integrity` to v0.3.2 to implement this feature
With an Android device, try to activate ITW and check that no regressions are present. The preferred test would be to have a device that supports Strongbox but has issues with it, so although there is support for Strongbox, a fallback to TEE would be made. This case occurred on some Motorola and Xiaomi devices.
> [!NOTE]
> Testable from QA; however, as previously written, this test will be effective on devices with a Strongbox issue.
> feat(IT Wallet): [SIW-2347] Enable attestation generation with fallback over TEE

- ts/features/itwallet/discovery/components/ItwNfcNotSupportedComponent.tsx
This PR adds a link to the FAQ for devices that do not support NFC
- updated the primary action in `ItwNfcNotSupportedComponent` to open the FAQ link
- ensure the wallet is active and the device does not support NFC
- go to Settings > Playground > Documenti su IO > enable L3
- go to the wallet screen > upgrade to IT-wallet > tap on the _Scopri di più_ button
- check that the FAQ link is opened in the browser
> feat(IT Wallet): [SIW-2376] Add FAQ link for devices that do not support NFC

- ts/features/payments/checkout/components/WalletPaymentWebView.tsx
- ts/features/payments/checkout/components/__tests__/WalletPaymentWebView.test.tsx
This PR includes a change to the `WalletPaymentWebView` component in the `WalletPaymentWebView.tsx` file. The change ensures that the "about:blank" URL check also verifies that the event is from the top frame before triggering the `onCancel` callback.
-Updated the condition to include `event.isTopFrame` when checking for the "about:blank" URL, ensuring more accurate handling of user cancellations in the in-app browser.
- Start the app IO in UAT env on iOS;
- Start a payment flow and choose `PayPal (anche in 3 rate)` as payment method and reach the webview page;
- Check that the alert to close the flow doesn't trigger;
> fix: [IOBP-1700] Payment webview alert flow closed

- ts/components/BonusCard/BonusCardScreenComponent.tsx
- ts/features/authentication/login/optIn/screens/OptInScreen.tsx
- ts/features/settings/security/shared/components/PinCreation.tsx
- ts/hooks/useDetectSmallScreen.ts
This PR normalises the threshold used to hide elements on smaller screens. This change is intended to prevent the proliferation of seemingly arbitrary _magic numbers_ (what devices were taken into account, and why these and not others, etc.). Only one threshold is left, under which some elements can be hidden to prevent content overflow on certain screens.
- Use the `useDetectSmallScreen` hook in all the files where a custom `MIN_HEIGHT_TO_SHOW_FULL_RENDER` constant was previously used
Check the screens impacted by the change and test if everything is working as expected.
> chore: [IOPLT-1149] Normalise threshold used to hide elements on smaller screens

- ts/features/itwallet/presentation/remote/screens/ItwRemoteRequestValidationScreen.tsx
- ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteRequestValidation.test.tsx
This PR fixes an issue that arises when the user completes a full authentication and immediately starts a remote presentation. The selector used to "pause" the machine was not correct, as identification is not triggered after the full authentication flow.
- Checked the startup status instead of the identification progress
- Added a test case
Log out from app IO. Log in again and **without closing the app or putting it in the background** start a remote presentation: after the loading screen you should navigate to the claims disclosure screen.
> [!Important]
> Please check for regressions in the following scenarios:
> - Kill the app, start the same device flow
> - Put the app in the background, wait for some time, start the same device flow
> fix(IT Wallet): [SIW-2445] Infinite loading screen when starting presentation after full authentication

- ts/features/onboarding/screens/__tests__/OnboardingShareDataScreen.test.tsx
- ts/features/onboarding/screens/biometric&securityChecks/__test__/FingerprintScreen.test.tsx
- ts/features/onboarding/screens/biometric&securityChecks/__test__/MissingDeviceBiometricScreen.test.tsx
- ts/features/onboarding/screens/biometric&securityChecks/__test__/MissingDevicePinScreen.test.tsx
- ts/hooks/useStatusAlertProps.tsx
> [!IMPORTANT]  
> I was unable to reproduce this bug on my Android device, so I cannot confirm whether the issue is fully resolved. The fix is based on assumptions and should be thoroughly tested across a variety of devices.
This PR is another attemp to address a visual glitch that causes a duplicate header to appear on the home screen of the offline mini-app, only on production build
- Moved `offlineAccessReason` check to `useEffect`
The issue was reported on certain Android devices.  
To verify the fix:
1. Launch the app on an affected Android device (if available).
2. Navigate to the offline mini-app.
3. Confirm that the double header glitch no longer appears.
> fix(IT Wallet): [SIW-2349] Fix double header glitch in offline wallet screen

- ts/features/bonus/cgn/screens/discount/CgnDiscountCodeScreen.tsx
This PR fixes the appearance of the CGN barcode by adding a new `width` property for better visual customization that scales the barcode with the right fit for barcodes that are too long.
- Enhanced the `Barcode` component in `CgnDiscountCodeScreen` to include a `width` property set to `1.15`, improving the barcode's visual scaling.
- Open the CGN card flow;
- Select a merchant that has a discount code with a barcode and check that if the barcode is too long (max length is 20 chars), the barcode doesn't go outside the screen
|Before|After|
|-|-|
|<img src="https://github.com/user-attachments/assets/791ce531-2477-4e89-953f-d731cf539311" width="350px" />|<img src="https://github.com/user-attachments/assets/b8839cce-074d-469c-9fac-3e642b77a889" width="350px" />
> fix: [IOBP-1722] CGN Barcode width scale

- locales/en/index.json
- locales/it/index.json
- ts/features/settings/common/navigation/__test__/__snapshots__/SettingsNavigator.test.tsx.snap
- ts/features/settings/devMode/components/DeveloperModeSection.tsx
This PR introduces changes to improve the handling of the pagoPA test environment in the developer mode section of the settings. It supports detecting local app builds and disabling the pagoPA test environment in such cases, along with corresponding updates to localization files and UI components.
- Modified the `DeveloperTestEnvironmentSection` to use `isLocalEnv` to conditionally set the description and disable the toggle for the pagoPA test environment.
Open the developer settings page with an app built with the .env.local variables and check that the `pagoPA` switch is disabled.
The following preview shows both the case when the app is built with a local .env and another with the production .env
https://github.com/user-attachments/assets/64574470-2abc-4c72-9a63-5a975199d426
> chore: [IOBP-1723] Disable pagoPA UAT toggle if app is in local env

- ios/ItaliaApp.xcodeproj/project.pbxproj
This PR fixes an issue introduced with react-native upgrade PR that prevents app from showing Splash Screen and its own icon on ios platform
> fix: [IOPLT-000] Restore icon and splash screen visualization

- ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
- ts/features/itwallet/presentation/remote/machine/events.ts
- ts/features/itwallet/presentation/remote/machine/machine.ts
- ts/features/itwallet/presentation/remote/screens/ItwRemoteRequestValidationScreen.tsx
- ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteRequestValidation.test.tsx
This PR fixes an issue that occurs when a new presentation is started while another one is pending. The wallet shows an infinite loading screen instead of restarting with the new presentation.
- Added a reset action to reset the presentation machine
- Updated tests
1. Start a remote presentation and stop at the claims disclosure screen
2. Put the app in the background and start a new presentation with different claims (same-device)
3. Ensure the new presentation overrides the previous one and the new claims are displayed in the claims disclosure screen 
|Before (infinite loading)|After|
|------|------|
|<video width="320" src="https://github.com/user-attachments/assets/a0dd99bf-4dff-483d-bb43-768ece563753" />|<video width="320" src="https://github.com/user-attachments/assets/91a592bf-c900- …
> fix(IT Wallet): [SIW-2492] Infinite loading when starting a presentation while another one is pending

- ios/ItaliaApp/Info.plist
This PR removes Roboto font references from Info.plist.
- Roboto was removed back in 2024 [here](https://github.com/pagopa/io-app/pull/6299)
Check that the iOS project runs without warnings related to Roboto.
> chore: [IOCOM-2412] Remove Roboto

- ts/features/bonus/cdc/activation/screens/CdcBonusRequestInformationTos.tsx
- ts/features/bonus/cdc/analytics/index.ts
- ts/features/bonus/cdc/hooks/useSpecialCtaCdc.tsx
This PR adds analytics tracking for user interactions on mixpanel. It adds new tracking events and integrates these events into existing components.
* Added `trackCdcRequestStart`, `trackCdcRequestIntro`, and `trackCdcRequestIntroContinue` functions to track user actions and screen views during the CDC activation flow. 
* Added `trackCdcRequestStart` into the `subscribeHandler` callback in the `useSpecialCtaCdc` hook to track the start of the CDC activation process.
* Added `trackCdcRequestIntro` and `trackCdcRequestIntroContinue` calls in the `CdcBonusRequestInformationTos` component to track screen views and user actions.
- Start a new CdC onboarding request with the dev-server started trough the service "Carta della Cultura"
- Check that the mixpanel event are dispatched when are …
> chore: [IOBP-1734] Add CdC mixpanel tracking events

- ts/features/barcode/hooks/useIOBarcodeFileReader.tsx
This PR fixes an issue that prevents the document picker from opening.
- Directly import the `pick` method.
Start the app and try to upload a file from the "Scan" navigation tab on both Android and iOS. You should be able to load a file.
> fix: [IOAPPX-498] Document picker not opening

- locales/de/index.json
- locales/en/index.json
- locales/it/index.json
- ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
- ts/features/payments/onboarding/screens/__tests__/PaymentsOnboardingFeedbackScreen.test.tsx
This pull request is replacing the bottom sheet with a web link for card onboarding auth error
- Removed the `usePaymentOnboardingAuthErrorBottomSheet` hook and replaced the bottom sheet with a web link that opens the assistance URL when the secondary action button is pressed
- Onboard a payment method
- Select `AUTH_ERROR` as outcome
- Ensure that second CTA is opening the browser instead a modal
## Preview
https://github.com/user-attachments/assets/ac798387-1b84-4281-b17c-d80cbd23ed5c
> refactor: [IOBP-1740] Update CAC for card onboarding auth error

- locales/de/index.json
- locales/en/index.json
- locales/it/index.json
- ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
This PR includes updates to localization files for multiple languages and enhancements to the `WalletPaymentFailureDetail` component. The most significant changes involve updating translations for the "PAYMENT_CANCELED" action and improving the user interface for that error showing an animated pictogram.
- Added support for animated pictograms for the `PAYMENT_CANCELED` error.
- Checkout locally the dev-server to [this branch](https://github.com/pagopa/io-dev-api-server/tree/mock-verify-payment-canceled-error) to simulate a `PAYMENT_CANCELED` error during the verification request
- Check that there is a valid text and UI following [this design](https://www.figma.com/design/KY9BpP4LaSSd18fuYMwxYK/Paga-un-avviso-pagoPA?node-id=2750-12850&t=ogJEOirb8yDdzkoq-4) …
> refactor: [IOBP-1743] Change text of help center CTA from PAYMENT_CANCELED error

- ts/features/payments/home/screens/PaymentsHomeScreen.tsx
This PR fixes the `PaymentsHomeScreen`, ensuring analytics tracking is triggered correctly when the screen gains focus and not every time that the paymentAnalyticsData changes.
* Replaced `useEffect` with `useFocusEffect` in `PaymentsHomeScreen` to ensure the analytics tracking logic runs whenever the screen gains focus, aligning with navigation lifecycle events.
* Updated the dependency array of the callback in `useFocusEffect` to include `paymentAnalyticsData?.paymentsHomeStatus` and `paymentAnalyticsData?.savedPaymentMethods?.length`, ensuring the effect re-runs when these values change. 
Ensure that the `PAYMENT_HOME` mixpanel event is tracked only when the payment home gains focus, and it doesn't dispatch the event during the payment flow.
> fix: [IOBP-1695] PAYMENT_HOME mixpanel event dispatched too many times

- ts/api/backend.ts
- ts/features/messages/analytics/__test__/index.test.ts
- ts/features/messages/analytics/index.ts
- ts/features/messages/saga/__test__/handlePaymentUpdateRequests.test.ts
- ts/features/messages/saga/handlePaymentUpdateRequests.ts
- ts/features/messages/store/actions/index.ts
This pull request fixes the Authorization header being malformed on the new eCommerce API (for messages' payments)
- Proper Authorization header composition
- Tracking of generic errors on payment's failures
Using the io-dev-api server, check that the new eCommerce API works properly
> fix: [IOCOM-2439] Message's eCommerce API

- ts/features/messages/hooks/useMessageReminder.ts
this PR targets an issue where, especially on Android, when using a screenReader, the a11y focus would fall on an empty title when opening the alert that requests calendar permissions in a payment message with reminder.
- swapped title and body in the affected Alert
on both Android and iOS, using physical devices, make sure that the following case happens:
1) using a screen reader, and with calendar permissions disabled for the app, open a reminder message 
2) when receiving a system prompt for calendar access, dismiss it without enabling the permissions
3) when tapping on the "alert"(component) that prompts the addition of a reminder, a system alert should open and the screen reader focus should fall on the first paragraph -- **not on an empty invisible paragraph**.
> fix: [IOCOM-2451] payment reminder alert empty focus

- ts/features/pn/reminderBanner/components/PNActivationReminderBanner.tsx
- ts/features/pn/reminderBanner/components/__test__/PNActivationReminderBanner.test.tsx
- ts/features/pn/reminderBanner/reducer/__test__/bannerDismiss.test.ts
- ts/features/pn/reminderBanner/reducer/bannerDismiss.ts
This PR fixes a bug that made the SEND banner render and dispatch mixpanel events when the app was not certain about SEND's activation status
- rendering logic fix
- updated the BANNER_SHOWN event dispatching logic
- updated tests
using the dev-server, add an `Alert` in  the banner's mixpanel dispatching logic (`maybeDispatchBannerShown`) , and make sure that
- it only runs if the banner is visible
- it does not rerun when switching screens
- it runs again when activating and deactivating the SEND preferences
- it does not run if you are in a screen different than MESSAGES_HOME
> fix: [IOCOM-2450] SEND banner optimistic render fix

- jestSetup.js
- ts/features/messages/components/Home/__tests__/Toast.test.tsx
- ts/features/messages/components/Home/__tests__/WrappedListItemMessage.test.tsx
- ts/features/messages/components/MessageDetail/__tests__/MessageDetailsBody.test.tsx
- ts/features/pn/components/__test__/MessageBottomMenu.test.tsx
- ts/features/pn/components/__test__/MessageDetails.test.tsx
- ts/features/pn/components/__test__/MessagePaymentBottomSheet.test.tsx
- ts/features/pn/components/__test__/MessagePayments.test.tsx
- ts/features/pn/components/__test__/Timeline.test.tsx
- ts/features/pn/components/__test__/TimelineListItem.test.tsx
- ts/features/pn/screens/__test__/MessageDetailsScreen.test.tsx
This pr adds global mock for `react-native-screenshot-prevent` in order not to have warning messages during tests.
- Global mock for `react-native-screenshot-prevent`
- Removed unneccessary mocks
CI should succeed.
> feat: [IOCOM-2465] Global mocks for `react-native-screenshot-prevent`

- ts/features/wallet/types/index.ts
This PR is updating wallet card categories order to display IDPay bonus at top
- Update `walletCardCategories` dependency array
Ensure that wallet card follow this order:
- IDPay
- CGN
- Payment cards
> chore: [IOBP-1800] Update wallet card categories order

- ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
- ts/features/itwallet/lifecycle/saga/handleWalletInstanceResetSaga.ts
- ts/features/wallet/store/selectors/index.ts
This PR resolves the TypeError caused by the `selectWalletPlaceholderCards`, as seen on the Sentry dashboard.
- Added nullish coalescing
- Fixed state inconsistencies while updating Mixpanel properties, which was a possible cause of the error
Check that no regressions were introduced by this change.
> fix(IT Wallet): [SIW-2663] TypeError: Cannot convert undefined value to object

- scripts/generate-api-models.sh
- ts/features/idpay/code/components/IdPayCodeCieBanner.tsx
- ts/features/idpay/details/components/IdPayInitiativeDiscountSettingsComponent.tsx
- ts/features/idpay/details/screens/__tests__/IdPayInitiativeDetailsScreen.test.tsx
- ts/features/settings/security/screens/SecurityScreen.tsx
- ts/features/settings/security/screens/__tests__/SecurityScreen.test.tsx
- ts/store/reducers/backendStatus/remoteConfig.ts
This PR introduces changes to enable and integrate a new remote feature flag for IDPay CIE payment codes. The updates include modifying selectors, conditional logic, and component behavior to support the new feature flag.
* Updated `IO_SERVICES_METADATA_VERSION` to reference the new feature flag version.
* Added a new selector `isIdPayCiePaymentCodeEnabledSelector` to check if the CIE payment code feature is enabled based on remote configuration.
* Updated the `showBanner` logic to include the new `isIdPayCiePaymentCodeEnabledSelector` for determining whether to display the banner.
* Added conditional rendering based on `isIdPayCiePaymentCodeEnabledSelector` to ensure the component is only displayed when the feature is enabled.
- Checkout the dev-server from this PR: …
> chore: [IOBP-1822] Add IdPay CIE code remote feature flag

- locales/en/index.json
- locales/it/index.json
- ts/features/idpay/details/components/IdPayBeneficiaryDetailsContent.tsx
- ts/features/idpay/details/components/IdPayInitiativeRulesInfoBox.tsx
- ts/features/idpay/details/components/IdPayInitiativeStatusItem.tsx
- ts/features/idpay/details/components/__tests__/IdPayBeneficiaryDetailsContent.test.tsx
- ts/features/idpay/details/screens/IdPayBeneficiaryDetailsScreen.tsx
- ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
This PR removes the IDPay unsubscribe CTA button as product requirement isn't needed anymore. This PR is used also to simplify beneficiary components, improving user interface elements with [the designed UI](https://www.figma.com/design/oo4ehPaT3ONNI8FAs9aZH2/PARI---Bonus-Elettrodomestici?node-id=2384-27360&t=2Gun57lciaoZgZQu-4).
* Added a new `IdPayinitiativeStatusItem` component to display initiative status with a badge for better visual distinction.
* Replaced `Body` and `BodySmall` components with `ListItemAction` and `IOButton` for better alignment with the design system.
* Replaced the `ScrollView` with the `IOScrollView` in `IdPayBeneficiaryDetailsScreen`.
* Refactored `IdPayInitiativeRulesInfoBox` to remove the footer as designed in the figma.
* Removed the …
> refactor: [IOBP-1866] Remove the IDPay unsubscribe CTA  and adapted the beneficiary details content screen

- locales/en/index.json
- locales/it/index.json
- ts/features/idpay/onboarding/screens/IdPayFailureScreen.tsx
This pull request includes updates to localization files and a minor UI adjustment in the `IdPayFailureScreen` component
- Updated the subtitle for the generic error message to clarify the suggested action for users.
- Changed the `pictogram` value for the `INITIATIVE_ENDED` failure state from `"ended"` to `"time"`
Ensure that all screen are now aligned with design
> refactor: [IOBP-1867,IOBP-1868] Update pictogram and outcome body text

- ts/features/itwallet/presentation/details/components/ItwPresentationPidScaffoldScreen.tsx
- ts/features/itwallet/wallet/components/ItwWalletCardsContainer.tsx
- ts/features/wallet/components/WalletCardsContainer.tsx
This PR adds a default space value to all `VStack` components when no spacing is set.
- Apply default space value to `VStack` components without an explicit space prop
Go to the affected screens and check that there are no visual regressions.
> fix(IT Wallet): [SIW-2757] Add default space value to `VStack` components if not set

- ts/features/payments/checkout/utils/__tests__/index.test.ts
- ts/features/payments/checkout/utils/index.ts
This PR updates the `getPspFlagType` function in `ts/features/payments/checkout/utils/index.ts` to improve the handling of PSP fee comparison logic. This change ensures that when a user selects a PSP with the lowest fee, it is correctly tracked as "cheaper."
Previously, if multiple PSPs had the same (lowest) fee, only the first one in the list was marked as "cheaper."
Refactored the fee comparison logic in `getPspFlagType` to use `Math.min` on filtered numeric fees.
- Start a payment flow and select a credit card as payment method;
- Select the cheaper PSP in the list and verify that if multiple PSPs have the same fee, selecting any of them (e.g., the second in the list) still correctly marks it as "cheaper."
> fix: [IOBP-1897] Cheaper PSP selected check improved

- ts/features/payments/home/screens/PaymentsHomeScreen.tsx
This pull request fix the `PaymentsHomeScreen` card carousel by removing unnecessary `ContentWrapper` component that is adding extra horizontal spacing
-Removed `ContentWrapper` wrapper from `PaymentsHomeUserMethodsList` streamlining the layout
- On dev-server change [that line simulating no remote transactions](https://github.com/pagopa/io-dev-api-server/blob/0ec7f23a4fa4b1d0d53714280e6323e870b9f3fd/src/config.ts#L191)
- Ensure that now with no transactions, carousel has no more horizontal padding 
https://github.com/user-attachments/assets/b544d3be-0b73-4f63-b2db-097028fc8401
> fix: [IOBP-1905] Adjust carousel spacing on empty transactions list

- ts/features/itwallet/common/utils/itwAttestationUtils.ts
- ts/features/itwallet/common/utils/itwAttestationUtils.v1.ts
- ts/features/itwallet/common/utils/itwAttestationUtils.v2.ts
- ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
- ts/features/itwallet/lifecycle/saga/checkCurrentWalletInstanceStateSaga.ts
- ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
- ts/features/itwallet/machine/eid/__tests__/machine.test.ts
- ts/features/itwallet/machine/eid/actors.ts
- ts/features/itwallet/machine/eid/machine.ts
This PR splits `itwAttestationUtils.ts` into two files to avoid mixed imports of `io-react-native-wallet` v1 and v2.
Without this clear separation, `createCryptoContextFor` was imported only from v1, so the Wallet Attestation's `cnf.jwk` could be affected by the 33 bytes issue; later, when using the Wallet Attestation to request a IT-Wallet credential, the `createCryptoContextFor` from v2 was used and the two JWKs did not match.
> [!NOTE]
> The separation will be removed alongside the two versions `io-react-native-wallet`.
- Split `itwAttestationUtils.ts` into `itwAttestationUtils.v1.ts` and `itwAttestationUtils.v2.ts`
- Used the whitelisted status to choose between v1 and v2
The problem is not easy to reproduce, as it only happens when a JWK with a coordinate of 33 bytes is generated. …
> fix(IT Wallet): [SIW-2813] Split attestation utils between v1 and v2

- locales/en/index.json
- locales/it/index.json
- ts/features/idpay/timeline/components/IdPayTimelineDetailsBottomSheet.tsx
This pull request refactor the `IdPayTimelineDetailsBottomSheet` to align the operation details modal to design
- Removed the `modalFooter` constant, which included a footer with a close button, and its associated styles. The `useIOBottomSheetModal` function no longer includes a `footer` property
- Navigate into a discount bonus
- Tap on an list element
- Ensure displayed modal information are aligned with design 
https://github.com/user-attachments/assets/a8bf24b1-4e2a-4f18-982e-4e99c481633b
> refactor: [IOBP-1931] Update IDPay operation details modal

- ts/features/payments/home/screens/PaymentsHomeScreen.tsx
This pull request fix a regression introduced in [this development](https://github.com/pagopa/io-app/pull/7228) (thanks @dmnplb )
- Restored the `ContentWrapper` component to wrap the `PaymentsHomeUserMethodsList`
- Updated the `IOScrollView` component to set `includeContentMargins` to `false`, allowing more control over content margins when list is empty
**Test all cases with and without payment methods & transactions**
Ensure that spacing is now correct, carousel has no extra padding and text is aligned correctly
> fix: [IOBP-1940] Wrong banner and text layout alignment

- ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimLabel.tsx
- ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
This PR resolves a rendering issue on Android where ClaimLabel text on skeumorphic cards would inherit the system's theme color. This resulted in low-contrast, illegible text when dark mode was enabled.
- Explicitly set high-contract color for `Text` within `ClaimLabel` component
1. Run the application on an Android device.
2. Navigate to the screen displaying the MDL details.
3. Toggle the system theme between light and dark modes.
4. Confirm that the text labels on the skeumorphic card are legible and maintain sufficient contrast in both themes. 
| --- | --- |
|<img width="250" height="2280" alt="Screenshot_20250812_095651" src="https://github.com/user-attachments/assets/45c321d2-6e3e-478e-8d05-836d25edd72d" /> | <img width="250" height="2280" …
> fix(IT Wallet): [SIW-2865] Claim labels not visible with dark theme on Android

- ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
- ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteFailureScreen.test.tsx
This PR fixes the IT-Wallet activation button visualization.
- Show the button conditionally in the Wallet Inactive Screen.
Ensure it is not possible to activate the Wallet when the L3 flag is disabled.
> fix(IT-Wallet): [SIW-2891] IT-Wallet activation button

- ts/features/payments/checkout/components/WalletPaymentWebView.tsx
This PR makes a small change to the `WalletPaymentWebView.tsx` file by adding support for the `intent://*` schema to the `originSchemasWhiteList` array. This update allows the webview to handle URLs with the `intent://*` schema, which is commonly used for deep linking in mobile applications on Android.
- Added `intent://*` schema to the whitelisted origin schemas;
On the dev server, mock any page (e.g., the payment authorization page), add an Android intent link to an external app, and verify that tapping it launches the app successfully
> chore: [IOBP-1948] Add `intent://` schema inside the payments origin webview whitelist schemas

- ts/features/messages/components/MessageDetail/MessageDetailsAttachmentItem.tsx
- ts/features/messages/components/MessageDetail/MessageDetailsAttachments.tsx
- ts/features/messages/components/MessageDetail/__tests__/MessageDetailsAttachmentItem.test.tsx
- ts/features/messages/components/MessageDetail/__tests__/MessageDetailsAttachments.test.tsx
- ts/features/messages/hooks/useAttachmentDownload.tsx
- ts/features/messages/saga/__test__/handleDownloadAttachment.test.ts
- ts/features/messages/saga/handleDownloadAttachment.ts
- ts/features/messages/screens/MessageDetailsScreen.tsx
- ts/features/messages/store/actions/__tests__/index.test.ts
- ts/features/messages/store/actions/index.ts
- ts/features/messages/store/reducers/__tests__/downloads.test.ts
- ts/features/messages/store/reducers/paginatedById.ts
- ts/features/pn/components/F24ListBottomSheetLink.tsx
- ts/features/pn/components/F24Section.tsx
- ts/features/pn/components/MessageDetails.tsx
- ts/features/pn/components/__test__/F24ListBottomSheetLink.test.tsx
This pull request refactors downloadAttachmentWorker and downloadAttachment.request to improve structure and to allow downloadAttachment.request to accept a serviceId parameter instead of relying on the getServiceByMessageId selector.
- Modify downloadAttachment.request to accept serviceId as an input parameter
- Remove getServiceByMessageId selector usage
Automated tests should pass
> refactor: [IOCOM-2541] DownloadAttachmentWorker and request

- ts/components/BonusCard/BonusCardCounter.tsx
- ts/features/bonus/common/components/ProgressBar.tsx
- ts/features/bonus/common/components/__tests__/ProgressBar.test.tsx
- ts/features/idpay/wallet/components/IdPayCard.tsx
This pull request updates the color scheme for progress bars and value displays to better support dark mode 
- Apply `blueIO-300`(replacing the previous `blueIO-200`) in dark mode for `blueItalia-500` light mode color
Ensure that IDPay progress bar colors are aligned with design
> refactor: [IOBP-1961] Adjust IDPay progress bar dark mode colors

- README.md
- ts/features/payments/common/components/PaymentCard.tsx
This PR updates the `PaymentCard` expired state, by using the established pattern for IT Wallet cards.
- Remove extra thick border from the expired state
- **[extra]** Remove the dark mode reference from README before the beta launch
| <img width="1206" height="1022" alt="Simulator Screenshot - iPhone 16 Pro - 2025-09-10 at 15 36 15" src="https://github.com/user-attachments/assets/ea2f9393-abd7-4877-945b-7b32bf36e6e2" /> | <img width="1206" height="1030" alt="Simulator Screenshot - iPhone 16 Pro - 2025-09-10 at 15 34 54" src="https://github.com/user-attachments/assets/5aea238c-6e46-4319-bc16-556849eb4ccd" /> | 
Go to the **Design System** → **Cards** (Components) → scroll horizontally to view other states
> fix: [IOPLT-1331] Remove extra thick border from `PaymentCard` expired state

- ts/features/zendesk/analytics/index.ts
- ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
This pull request adds analytics tracking for the display and interaction of the Contextual Help CaC banner in the Zendesk Help Center feature
- Added `trackZendeskCaCBannerShow` and `trackZendeskCaCBannerTap` functions to send Mixpanel events for banner display and tap actions, including detailed event properties
Ensure that new events are tracked while showing and tapping on CaC banner
> chore: [IOBP-1969] Add Mixpanel events for help center CaC banner

- ts/hooks/__tests__/useStatusAlertProps.test.tsx
- ts/hooks/useStatusAlertProps.tsx
This PR fixes a glitch with the offline/no session alert in the offline mini app.
- Refactored `useStatusAlertProps` hook
- Added `useDerivedConnectivityState` helper hook
- Added tests
- 
With a valid wallet with at least one credential, test the different scenarios as described below. 
Verify the alerts, bottom sheets and CTAs works as expected.
<details>
<summary>Full app, remove connection</summary>
<p>
https://github.com/user-attachments/assets/e5d66c59-6d0f-471f-bb86-b5f1b3650633
</p>
</details> 
<details>
<summary>Full app, restablish connection</summary>
<p>
https://github.com/user-attachments/assets/4ac7c723-7341-4aaa-8fec-176ef655b15e
</p>
</details> 
<details>
<summary>Mini app, start with no connection</summary>
<p>
https://github.com/user-attachments/assets/dc0fd218-da89-46b0- …
> fix(IT Wallet): [SIW-3005] Fix offline wallet header for `session_expired` access reason

- locales/it/index.json
- ts/features/itwallet/identification/common/screens/ItwL2IdentificationModeSelectionScreen.tsx
- ts/features/itwallet/machine/eid/actions.ts
This PR removes the "Recommended" badge on the CIE+PIN identification method for the `Documenti su IO` issuance
- Removed `badge` from `ModuleNavigationAlt` component
- Added correct parameter to `navigateToL2IdentificationScreen` eid issuance action
- Verify there isn't regression in the _Documenti su IO_ identification page
- Verify that the badge is displayed in the `Documenti su IO` identification page only for reissuing
> fix(IT Wallet): [SIW-3989] Remove "Recommended" badge from CIE+PIN identification method

- locales/it/index.json
- ts/features/itwallet/common/components/ItwCredentialCard/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
This PR renames "Residenza" to "Attestato di residenza".
- Renamed residency credential
- Updated snapshots
Ensure the residency credential is always displayed as "Attestato di residenza".
| Wallet | Detail |
|-|-|
|<img height="460" src="https://github.com/user-attachments/assets/e9071c1c-775a-4b56-8716-a9bd906acc1e" />|<img height="460" src="https://github.com/user-attachments/assets/9bbbca48-e9cc-49c2-90f6-e6d5986b9b92" />|
> chore(IT Wallet): [SIW-3083] Rename "Residenza" to "Attestato di residenza"

- ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
This pull request makes a small UI improvement to the `PaymentsHomeTransactionsList` component by wrapping the error state banner in a `ContentWrapper`.
* Wrapped the `BannerErrorState` component in a `ContentWrapper` to ensure consistent layout when displaying errors in `PaymentsHomeTransactionsList.tsx`.
- Check that whenever there is an error inside the payments home screen, check that there is an horizontal padding to the error banner
|Before|After|
|-|-|
|<img src="https://github.com/user-attachments/assets/1c0fd9bc-af2f-437f-8e7c-b2d2cfa9d4ef" width="300px" />|<img src="https://github.com/user-attachments/assets/9a683c68-2e2a-4bd7-b4bc-1f5001fb4ff2" width="300px" />
> fix: [IOBP-2035] Receipts banner error padding

- ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
- ts/features/itwallet/presentation/remote/components/ItwRemotePresentationDetails.tsx
This PR replaces "Identità Digitale" with "IT-Wallet ID" where appropriate.
- Correctly pass the `isItwCredential` parameter to `getCredentialNameFromType`
Check the following screens.
| Remote presentation | Credential Trust Issuer PID L3 | Credential Trust Issuer PID L2 |
|---|---|---|
|<img height="480" alt="it_wallet_id_2" src="https://github.com/user-attachments/assets/fc8ff8a0-f890-4f2f-bfc8-9e44d0a89f47" />|<img height="480" alt="it_wallet_id_1" src="https://github.com/user-attachments/assets/18be18ec-3c78-4cd4-81af-e9aaa51cbcd2" />|<img height="480" alt="it_wallet_id_3" src="https://github.com/user-attachments/assets/83533c07-7c61-475a-8e20-2377f99f87af" />|
> fix(IT Wallet): [SIW-3084] Update copy related to IT-Wallet ID

- ts/features/idpay/details/components/IdPayInitiativeTimelineComponent.tsx
- ts/features/idpay/onboarding/screens/IdPayFailureScreen.tsx
This pull request makes a minor update to the `IdPayFailureScreen` component. The pictogram displayed for the `ONBOARDING_INITIATIVE_NOT_STARTED` failure case has been changed from `"eventClose"` to `"ended"` to better represent the failure state.
Fix IDPay dark mode empty list
- Try to onboard a not started initiative
- Ensure that pictogram is aligned with design
| Before | Now |
| <img width="440" height="934" alt="Screenshot 2025-10-03 at 09 34 29" src="https://github.com/user-attachments/assets/70dd3443-c38a-4fb9-9130-07a1f7783af7" /> | <img width="438" height="932" alt="Screenshot 2025-10-03 at 09 33 57" src="https://github.com/user-attachments/assets/3384d356-5541-4483-a88c-71f73c825635" /> |
> refactor: [IOBP-000] Update initiative not started pictogram, fix empty list dark mode

- ts/features/pn/aar/components/SendQRScanFlowHandlerComponent.tsx
- ts/features/pn/aar/components/__tests__/SendQRScanFlowHandlerComponent.test.tsx
- ts/features/pn/aar/utils/__tests__/generic.test.ts
- ts/features/pn/aar/utils/generic.ts
This PR removed the temporary isSendAARPhase2Enabled flag and replaced it with the isAAREnabled selector from the store to manage the AAR flow feature toggle.
- Removed the temporary isSendAARPhase2Enabled flag.
- Updated SendQRScanFlowHandlerComponent to use the isAAREnabled selector via useIOSelector for feature flag control.
- Use the toggle available in the dev section to set AAR to true or false.
- All automated tests should pass.
> refactor: [IOCOM-2627] remove temporary isSendAARPhase2Enabled flag

- ts/features/idpay/barcode/components/IdPayBarcodeExpireProgressBar.tsx
- ts/features/idpay/barcode/screens/IdPayBarcodeResultScreen.tsx
This pull request fixes the expiration logic of the IDPay barcode progress bar to ensure that, on Android devices, the countdown does not freeze when the app is sent to the background. 
* The `IdPayBarcodeExpireProgressBar` component now receives the full `barcode` object instead of a precomputed `secondsToExpiration` value, and internally calculates the seconds to expiration using the `calculateIdPayBarcodeSecondsToExpire` utility. This ensures the progress bar always displays the correct remaining time. 
- On an android device or emulator, generate a barcode from the IDPay details screen.
- Verify that if you put the app in the background and resume it after a few seconds, the countdown correctly decrements according to the barcode’s validity and does not freeze.
|Before|After|
|-|-| …
> fix: [IOBP-2054] Countdown progressbar barcode IDPay on Android devices
