pagopa/io-app

package.json, yarn.lock
=> [#152926756] Update some outdated libraries

README.md, js/utils/configureErrorHandler.js, locales/en.json, locales/it.json
Changes to add internazionalization and documentation for the custom error handler.
=> [#149819781] Custom error handler internazionalization and documentation

.eslintrc.json, .gitignore, js/actions/user.js, js/reducers/__tests__/appState.test.js, js/reducers/__tests__/user.test.js, js/reducers/appState.js, js/reducers/user.js
Just a note: i have changed receiveUserProfile action from ThunkAction to Action because it doesn't perform async operations.
=> [#154952305] Unit tests for reducers

.flowconfig, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/it/teamdigitale/app/italiaapp/MainApplication.java, ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/Contents.json, ios/Podfile, ios/Podfile.lock, package.json, yarn.lock
Update react-native to v0.54, this allow us to use the latest version of flow/flow-bin.
=> [#155777750] Update react-native to v0.54

android/app/src/main/AndroidManifest.xml, ios/ItaliaApp/Info.plist
Fix orientation to portrait for both Android and iOS
=> [#155734996] Fix orientation to portrait for both Android and iOS

flow-typed/npm/react-navigation_v1.x.x.js, js/actions/index.js, js/actions/types.js, js/actions/user.js, js/components/ConnectionBar.js, js/components/ProfileComponent.js, js/navigation/index.js, js/reducers/appState.js, js/reducers/navigation.js, js/reducers/types.js, js/reducers/user.js, js/screens/IngressScreen.js, js/screens/LoginScreen.js, js/screens/MessagesScreen.js, js/screens/ProfileScreen.js, js/utils/api.js
This PR add flow typing for the redux store and all related functions (ex. connect/mapStateToProps).
=> [#155873674] Add flow typing for all redux store stuff

.circleci/config.yml
Improve the CircleCI Android build adding jars to the cache
=> [#156160076] Add jars to the CircleCI cache

.env.example, .env.production, js/screens/authentication/IdpSelectionScreen.js
Use the App Backend deployed on K8S
=> Fix the .env files

package.json, yarn.lock
color-3.0.0
danger-3.6.0
jest-22.4.3
react-native-i18n-2.0.12
=> Monday upgrades

ts/App.tsx, ts/RootContainer.tsx, ts/actions/types.ts, ts/api/index.ts, ts/boot/configureErrorHandler.ts, ts/boot/configureStoreAndPersistor.ts, ts/components/ConnectionBar.tsx, ts/components/IdpsGrid.tsx, ts/components/forms/SpidInformationForm.tsx, ts/components/forms/utils.tsx, ts/components/ui/Modal.tsx, ts/config.ts, ts/i18n.ts, ts/react-native-source-maps/index.ts, tslint.json
Temporarily disables some rules, we're going to do a first iteration of fixes and then enable more stricter rules
=> Fixes TSlint and Prettier warnings

ts/@types/native-base-types.d.ts, ts/@types/react-native-offline.d.ts, ts/boot/configureStoreAndPersistor.ts, ts/components/forms/utils.tsx, ts/reducers/appState.ts, ts/reducers/index.ts, tsconfig.json
Enabling the `strict` flag currently breaks the build, help welcome for fixing the types (just a couple of places).
=> [#157113003] Enables "strict" flag in TypeScript compiler

ts/api/index.ts, ts/screens/authentication/IdpLoginScreen.tsx, ts/utils/login.ts
Login helpers are not related to API calls
=> Extracts login related functions from the API module.

ts/sagas/profile.ts
Fixes linting errors exposed by #185
=> Use correct return types in profile saga

ts/__mocks__/react-native-keychain.ts, ts/boot/configureStoreAndPersistor.ts, ts/store/reducers/index.ts, ts/store/reducers/session.ts, ts/store/reducers/types.ts, ts/store/storages/__tests__/keychain.test.ts, ts/store/storages/keychain.ts
This PR:
- Add a new redux-persist storage that use the Keychain
- Move the session to the new storage
=> [#158408564] Move the session to a redux-persist keychain storage

ts/RootContainer.tsx
=> [#158769336] Add the App version in overlay

ts/RootContainer.tsx
Use getVersion method instead of getReadableVersion to show the exact version.
=> Use getVersion method to show the version

android/app/build.gradle
Some commented code was left there in a previous PR -- this one takes care of it
=> removing commented code

package.json
Adds payment metadata to messages, following this: https://www.pivotaltracker.com/n/projects/2116794/stories/157930299
=> [#157930340] Updates backend specs to v0.0.26

ts/components/IdpsGrid.tsx, ts/screens/authentication/IdpSelectionScreen.tsx
Example for a Device with very small screen.
=> [#158787997] Make the entire content scroll in the IdpSelectionScreen

ts/boot/configureStoreAndPersistor.ts, ts/screens/authentication/IdpLoginScreen.tsx, ts/store/reducers/index.ts
The App doesn't store the authentication info after logging out and trying to logging in again. This PR fixes the problem.
=> [#159064438] Fix the authentication after the logout

ts/screens/PreferencesScreen.tsx
=> [#159196194] Shows only primary language in prefs

ts/components/ui/Markdown/__tests__/__snapshots__/index.test.tsx.snap, ts/components/ui/Markdown/rules/list.ts, ts/components/ui/Markdown/rules/text.ts
=> [#159434085] Fix Markdown component

ts/components/ui/H4.tsx, ts/components/ui/H5.tsx, ts/components/ui/H6.tsx, ts/components/ui/Markdown/__tests__/__snapshots__/index.test.tsx.snap, ts/components/ui/Markdown/rules/heading.ts, ts/components/ui/Markdown/rules/text.ts, ts/screens/authentication/MarkdownScreen.tsx, ts/theme/components/H4.ts, ts/theme/components/H5.ts, ts/theme/components/H6.ts, ts/theme/index.ts, ts/theme/variables.ts
Fix H1-3 rendering and adds H4-6 (non in native-base by default)
=> [#159399206] Improve headers Markdown rendering

ts/components/wallet/WalletLayout.tsx
Bug fix based on the feedback received for story [#159229087](https://www.pivotaltracker.com/n/projects/2048617/stories/159229087)
=> [#159229087] Fixes "back" behavior in Wallet screens

.env.production
=> adding pagoPA REST endpoint to .env.production

ts/components/messages/MessageDetailsComponent.tsx
=> [#159195645] Adds sender to message details

ts/components/TopScreenComponent.tsx, ts/screens/messages/MessagesScreen.tsx, ts/screens/preferences/PreferencesScreen.tsx, ts/screens/profile/ProfileMainScreen.tsx, ts/theme/components/ScreenHeader.ts, ts/theme/components/TopScreenComponent.ts, ts/theme/index.ts
This also enables the pull to refresh behavior in the messages screen
=> [#159553934] Creates a component for top screens

ts/components/wallet/card/Logo.tsx, ts/types/__tests__/pagopa.test.ts, ts/types/pagopa.ts
- Specifying required fields of additional pagoPA types
- Adding some tests for the various types used (using data returned by pagoPA REST)
- Fixing some types according to the introduced tests
=> adding pagoPA required types + tests

ts/screens/PinLoginScreen.tsx
Ok for now..
TODO: 
- find a generic way to catch the screen background color and adjust the status bar backgorund and color
=> [#160165192] Pin screen status bar color and background

ts/screens/wallet/AddCardScreen.tsx
=> [#160176473] Fix card expiration date handler.

ts/screens/PinLoginScreen.tsx
=> [#160167290] Set pin error message colour to white.

ts/components/messages/MessageComponent.tsx, ts/screens/messages/MessagesScreen.tsx, ts/theme/components/MessageComponent.ts
The scrollbar that was overlapping the message was bothering me :)
=> [#159586459] Makes message list a little mode dense and avoids overlapping scrollbar

locales/en/index.yml, locales/en/preferences_services_help.md, locales/it/index.yml, locales/it/preferences_services_help.md, ts/screens/preferences/ServicesScreen.tsx
=> [#159957627] Fixes layout of services screen

package.json, ts/api/backend.ts, ts/components/messages/MessageComponent.tsx, ts/components/messages/MessageDetailsComponent.tsx, ts/sagas/profile.ts, ts/sagas/startup/__tests__/checkProfileEnabledSaga.test.ts, ts/sagas/startup/__tests__/watchLoadMessages.test.ts, ts/sagas/startup/checkProfileEnabledSaga.ts, ts/screens/IngressScreen.tsx, ts/screens/preferences/PreferencesScreen.tsx, ts/screens/preferences/ServiceDetailsScreen.tsx, ts/screens/preferences/common.ts, ts/store/actions/profile.ts, ts/store/reducers/profile.ts, ts/types/utils.ts, ts/utils/payment.ts
A few things broke after we updated the backend specs
=> Updates backend specs to 0.0.54

ts/sagas/watchNavigateToDeepLinkSaga.ts, ts/store/actions/navigation.ts
`master` was currently failing the build due to typings error
=> Fixes broken build on master

package.json, ts/components/Pinpad.tsx, ts/components/Pinpad/Pinpad.style.ts, ts/components/Pinpad/Placeholders.tsx, ts/components/Pinpad/index.tsx, ts/screens/PinLoginScreen.tsx, ts/screens/onboarding/PinScreen.tsx, yarn.lock
=> [#159491535] Refactor pin input

ts/store/reducers/wallet/payment.ts
Makes sure we do not access the top of an empty stack
=> Use NonEmptyArray for wallet stack.

ts/sagas/notifications.ts, ts/screens/profile/ProfileMainScreen.tsx, ts/store/reducers/notifications/installation.ts
Apparently APM doesn't like IDs that contain dashes
=> [#160655715] Strip dashes from notification installation ID

ts/screens/wallet/Checkout3DsScreen.tsx
This PR adds a spinner when loading the webview for the 3ds url.
=> [#160648742] show spinner in pagopa webview

ts/screens/preferences/ServicesScreen.tsx
This PR fixes https://github.com/teamdigitale/italia-app/issues/530.
=> Fix cropped text with italic style.

ts/screens/wallet/payment/ManualDataInsertionScreen.tsx
This PR fixes https://github.com/teamdigitale/italia-app/issues/529.
=> Fix scrolling issue of <ManualDataInsertionScreen>.

ios/ItaliaApp.xcodeproj/project.pbxproj, package.json, yarn.lock
With this changes, now I am able to use Instabug on iOS simulator.
=> [#147991535] Fix Instabug on iOS

ts/components/IdpSuccessfulAuthentication.tsx, ts/screens/authentication/IdpLoginScreen.tsx
=> [#160751445] Show tick when user has been successfully logged in

ts/screens/wallet/payment/ScanQrCodeScreen.tsx
This PR fixes https://github.com/teamdigitale/italia-app/issues/531.
=> Fix button style of QR screen.

ts/components/PreferenceItem.tsx, ts/screens/preferences/PreferencesScreen.tsx
This PR fixes https://github.com/teamdigitale/italia-app/issues/512.
=> Fix preference list scroll issue

ts/components/messages/MessageCTABar.tsx
=> Fix MessageCTABar component

ts/screens/IngressScreen.tsx, ts/theme/components/List.ts, ts/theme/index.ts
This PR fixes https://github.com/teamdigitale/italia-app/issues/528.
=> Fix list styles.

ts/components/screens/TopScreenComponent.tsx, ts/screens/authentication/IdpSelectionScreen.tsx
=> [#158788201] Move expired session banner to top.

ts/components/ui/SectionList.ts, ts/screens/preferences/ServicesScreen.tsx, ts/theme/components/ListItem.ts, ts/theme/index.ts
=> [#160991215] Fix service list style

ts/screens/onboarding/TosScreen.tsx
=> [#160916379] Fix TOS scrolling issue.

ts/components/Pinpad/index.tsx
=> [#160986866] Blur pin input when keyboard is being hidden

ts/components/wallet/WalletLayout.tsx, ts/components/wallet/card/CardBody.tsx, ts/components/wallet/card/CardComponent.tsx, ts/components/wallet/card/CardFull.tsx, ts/components/wallet/card/CardHeader.tsx, ts/components/wallet/card/CardsFan.tsx, ts/components/wallet/card/FooterRow.tsx, ts/screens/wallet/TransactionDetailsScreen.tsx, ts/screens/wallet/TransactionsScreen.tsx, ts/screens/wallet/WalletHomeScreen.tsx, ts/screens/wallet/WalletsScreen.tsx
Gets rid of the convoluted enum logic for displaying cards, in favor of simpler cards components that gets passed to the wallet layout.
=> Refactors wallet layout to make it less complex

locales/en/index.yml, locales/it/index.yml, ts/screens/wallet/payment/ManualDataInsertionScreen.tsx
Incidentally also adds feedback on form validation
=> [#161279607] Fixes amount in manual payment form

ts/components/ui/Markdown/rules/list.ts
=> [#161142830] Fix markdown list item bullet style

ts/IdentificationOverlay.tsx
=> [#161314174] Fix the background color of the status bar

ts/components/ui/Markdown/__tests__/__snapshots__/index.test.tsx.snap, ts/components/ui/Markdown/rules/paragraph.ts
=> Fix markdown line break

ts/components/messages/MessageDetailComponent.tsx, ts/components/messages/MessageListItemComponent.tsx
=> Fix message list and detail theme

ts/screens/messages/MessageDetailScreen.tsx, ts/screens/preferences/ServiceDetailsScreen.tsx, ts/screens/preferences/ServicesScreen.tsx
Dispatch contentServiceLoad before the navigation.
=> [#161290183] Fix navigation from message to related service

ts/sagas/startup/watchLoadMessagesSaga.ts
Add a try...catch to handle max-retries
=> [#161346137] Handle max-retries on message and services sagas

ts/components/ui/Markdown/MarkdownDemo.tsx, ts/theme/components/markdown/MarkdownDemo.ts
Add rounded corner and line height
=> Improve MarkdownDemo component theme

ts/components/screens/BaseScreenComponent.tsx
=> [#161376443] Trucate header title when necessary

ts/components/messages/MessageListComponent.tsx, ts/components/messages/MessageListItemComponent.tsx, ts/screens/messages/MessageDetailScreen.tsx, ts/screens/messages/MessageListScreen.tsx, ts/store/actions/messages.ts, ts/store/reducers/entities/messages/index.ts, ts/store/reducers/entities/messages/messagesUIStatesById.ts
=> [#161368623] Store and show messages read state

locales/en/index.yml, locales/it/index.yml, ts/components/NoticeBox.tsx, ts/screens/wallet/ConfirmCardDetailsScreen.tsx
=> [#161257393] Add a notice box to the ConfirmCardDetailsScreen

ts/components/messages/MessageListItemComponent.tsx
=> Change the MessageListItemComponent layout

ts/navigation/MainNavigator.tsx
=> [#161410671] Always show the first screen on tab press

locales/en/index.yml, locales/it/index.yml, ts/screens/preferences/PreferencesScreen.tsx
=> [#160248464] Show alert when an unavailable setting preference is pressed.

locales/en/index.yml, ts/screens/profile/PrivacyMainScreen.tsx
This PR fixes https://github.com/teamdigitale/italia-app/issues/709.
=> Fix style of the privacy screen.

ts/components/wallet/AddPaymentMethodButton.tsx, ts/screens/wallet/WalletHomeScreen.tsx, ts/screens/wallet/WalletsScreen.tsx
=> [#161375266] Fix style of the add payment button

ts/components/messages/MessageDetailRawInfoComponent.tsx, ts/store/reducers/entities/messages/messagesAllIds.ts
Note: requires cleaning up the cache
=> [#161510861] Fixes duplicate messages in message list

ts/screens/wallet/ConfirmCardDetailsScreen.tsx
=> [#161607910] Increase width of button of <PickPaymentMethodScreen>.

ts/sagas/startup.ts
=> [#161607939] Restore reset pin watcher

ts/components/wallet/PaymentSummaryComponent.tsx
=> [#161596555] Minor fixes to <PaymentSummaryComponent>

ts/screens/wallet/AddCardScreen.tsx
=> [#161607946] Fix style of cancel button of add card screen.

ts/screens/wallet/payment/TransactionSummaryScreen.tsx
also removes flickering when doing the "attiva" step
=> [#161678775] Show spinner while loading psps

ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
(Don't mind the "?"s and the "NaN"s, I used mocked data to show this screen)
=> [#161448002] Move the card under total amount

ts/components/wallet/PaymentBannerComponent.tsx
=> [#161698193] Fix style of cancel button of confirm payment screen

ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
=> [#161607918] Improve style of <PickPaymentMethodScreen>.

ts/IdentificationModal.tsx
=> [#161710594] Fix pin contextual help content

ts/components/helpers/withErrorModal.tsx, ts/components/helpers/withLoadingSpinner.tsx, ts/components/ui/Overlay.tsx, ts/screens/wallet/payment/TransactionSummaryScreen.tsx
also makes withErrorModal to use a simple overlay screen
instead of a real modal
=> [#162167584] Fixes activation of verifica when resetting payment state

ts/RootContainer.tsx, ts/boot/configureStoreAndPersistor.ts, ts/components/InstabugButtons.tsx, ts/screens/profile/ProfileMainScreen.tsx, ts/store/actions/debug.ts, ts/store/actions/types.ts, ts/store/reducers/debug.ts, ts/store/reducers/index.ts, ts/store/reducers/types.ts
=> [#162540750] Adds debug mode switch

locales/en/index.yml, locales/it/index.yml, ts/@types/react-native-calendar-events.d.ts, ts/components/messages/MessageCTABar.tsx, ts/store/actions/calendarEvents.ts, ts/store/actions/types.ts, ts/store/reducers/entities/calendarEvents/calendarEventsByMessageId.ts, ts/store/reducers/entities/calendarEvents/index.ts, ts/store/reducers/entities/index.ts
=> [#163389254,#163389233] Add calendar events in redux store

locales/en/index.yml, locales/it/index.yml, ts/components/messages/MessagesSearch.tsx, ts/components/screens/BaseHeader.tsx, ts/components/screens/BaseScreenComponent.tsx, ts/components/screens/TopScreenComponent.tsx, ts/screens/messages/MessagesHomeScreen.tsx, ts/utils/messages.ts, ts/utils/services.ts, ts/utils/strings.ts
=> [#163591981] Allow users to search messages that contain a text

locales/en/index.yml, locales/it/index.yml, ts/components/InfoBanner.tsx, ts/screens/authentication/IdpSelectionScreen.tsx, ts/screens/profile/ProfileMainScreen.tsx, ts/store/actions/authentication.ts, ts/store/reducers/authentication.ts, ts/store/reducers/index.ts
I have also added a button in the ProfileMainScreen to Simulate session expired.
=> [#161915009] Handle back button on session expired

locales/en/index.yml, locales/it/index.yml, ts/screens/preferences/ServiceDetailsScreen.tsx
=> [#161875912] Show toast on update enabled channels failure

locales/en/index.yml, locales/it/index.yml, ts/components/messages/MessageCTABar.tsx
=> [#162126937] Reminder button small version

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/TransactionsList.tsx, ts/screens/wallet/TransactionsScreen.tsx, ts/screens/wallet/WalletHomeScreen.tsx
=> [#161734960] Wallet specific no-transactions message

ts/components/SelectCalendarModal.tsx, ts/components/messages/MessageCTABar.tsx
=> [#164418709] Update SelectCalendarModal layout

ts/components/messages/MessageCTABar.tsx, ts/theme/components/Button.ts, ts/theme/variables.ts
This PR aims to downsize call-to-action elements in the message pane to 32px high
=> [#164418326] resized call-to-action in the messages as 32 high

ts/IdentificationModal.tsx
This PR aims to fix biometric recognition window pop up in iOS
=> [#164576383] Fix biometric recognition modal pop up in iOS

ts/theme/components/Button.ts
=> [#164595359] Remove iOS buttons shadow

ts/components/ContextualHelp.tsx, ts/components/GoBackButton.tsx, ts/components/InstabugButtons.tsx, ts/components/screens/BaseHeader.tsx, ts/components/screens/BaseScreenComponent.tsx, ts/components/wallet/WalletLayout.tsx, ts/screens/authentication/IdpLoginScreen.tsx, ts/screens/authentication/SpidInformationScreen.tsx, ts/screens/messages/MessagesHomeScreen.tsx, ts/screens/onboarding/PinScreen.tsx, ts/screens/wallet/AddCardScreen.tsx, ts/screens/wallet/AddPaymentMethodScreen.tsx, ts/screens/wallet/ConfirmCardDetailsScreen.tsx, ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx, ts/screens/wallet/payment/ManualDataInsertionScreen.tsx, ts/screens/wallet/payment/PickPaymentMethodScreen.tsx, ts/screens/wallet/payment/PickPspScreen.tsx, ts/screens/wallet/payment/ScanQrCodeScreen.tsx, ts/screens/wallet/payment/TransactionSummaryScreen.tsx, ts/theme/components/Header.ts, ts/theme/components/ScreenHeader.ts, ts/theme/variables.ts
This PR aims to set header buttons size of 40x40 minimum.
Message screen:
============================================================
Android
=> [#164595630] set header buttons min 40x40

ts/components/wallet/card/style.ts
=> [#164595852] Fix card component style

ts/theme/components/Header.ts, ts/theme/variables.ts
This PR aims to align app screens headers' height
=> [#164595614] Align headers

ts/components/ui/Markdown/handlers/internalLink.ts, ts/components/ui/Markdown/handlers/link.ts, ts/components/ui/Markdown/index.tsx, ts/components/ui/Markdown/script.ts
=> [#164727060] Handle both internal and external markdown links

ts/components/messages/MessagesInbox.tsx
Change requested here https://www.pivotaltracker.com/story/show/164418438/comments/200429979
=> [#164418438] Change archive buttonbar background color

ts/components/screens/MarkdownScreenComponent.tsx
=> [#164771279] Add padding to MarkdownScreen

ts/components/ui/Markdown/index.tsx
=> [#164632262] Add Markdown activity indicator

android/app/src/main/AndroidManifest.xml
[Android] removed duplicate **Vibrate** permission from _AndroidManifest.xml_
=> [Android] removed duplicated Vibrate permission

android/app/build.gradle, android/app/src/main/java/it/teamdigitale/app/italiaapp/MainApplication.java, android/settings.gradle, package.json, ts/@types/react-native-flag-secure-android.d.ts, ts/RootContainer.tsx, ts/components/FlagSecure.tsx, yarn.lock
=> [#164630993] Enable FLAG_SECURE when debugmode is disabled

locales/en/index.yml, locales/it/index.yml
This PR aims to change unavailable-property alert copywright in properties screen
=> [#160248464] change unavailableAlert copywright in properties screen

locales/en/index.yml, locales/it/index.yml, ts/components/messages/MessageCTABar.tsx
This PR aims to add an alert in the flow of removing a reminder from messageCTA pane
=> [#163389254] Add confirmation alert to remove reminder action

ts/components/messages/MessageCTABar.tsx, ts/components/messages/MessageDetailRawInfoComponent.tsx, ts/utils/dates.ts
This PR aims to localize date in calendar SVG of MessageCTA and in Message raw details
=> [#164769718] adapt dates to the current locale

patches/react-native+0.57.8.patch
Try to fix the bug reported in the story and also here https://github.com/facebook/react-native/issues/22938 applying the patch suggested here https://github.com/facebook/react-native/issues/22925#issuecomment-471995610.
=> [#164968781] Fix scroll on Android patching ReactScrollView

package.json, ts/types/utils.ts, yarn.lock
There's quite a lot to fix it seems :)
=> Upgrades Typescript to 3.4.1

ts/components/CalendarIconComponent.tsx, ts/components/messages/MessageCTABar.tsx
Change CalendarIconComponent width and  height to number.
=> [#164603501] - Change CalendarIconComponent width and  height to number

locales/en/index.yml, locales/it/index.yml, ts/screens/profile/ProfileMainScreen.tsx
[#160287423] added confirmation alert before pin reset in the profile section
=> [#160287423] added confirmation alert before pin reset in profile section

ts/components/ContextualHelp.tsx
=> [#165245284] Fix ContextualHelp padding

ts/IdentificationModal.tsx, ts/components/Pinpad/KeyPad.tsx, ts/components/Pinpad/index.tsx, ts/components/animations/ShakeAnimation.tsx, ts/screens/onboarding/PinScreen.tsx
[#160835617] adding animation and waiting for one second when the pin is wrong
=> [#160835617] wait after wrong pin

ts/screens/wallet/payment/PickPspScreen.tsx
@matteodesanti please test if this works.
=> [#165245247] Fix PickPspScreen padding

ts/screens/profile/ProfileMainScreen.tsx, tslint.json
Set style properties to Wallet and Session Token buttons to not allow text going over multiple lines
=> [#160613323] set one line token buttons in profile section

ts/screens/authentication/IdpLoginScreen.tsx
review some debts from PR #952
=> [#165356866] review-mixpanel-spid-login-trace

ts/screens/preferences/ServiceDetailsScreen.tsx
it seems the UI allows user to create multiple parallel update requests.
This should cause an error and an inconsistent user state
=> [#161950703] errors on update user's preferences

package.json, ts/components/wallet/card/CardsFan.tsx, ts/components/wallet/card/RotatedCards.tsx, ts/screens/profile/ProfileMainScreen.tsx, ts/screens/wallet/AddCardScreen.tsx, ts/theme/variables.ts, ts/utils/__tests__/stringBuilder.test.ts, tslint.json, yarn.lock
Migrating all our tslint rules to `italia-tslint-rules` with the objective to share the same rules across all projects.
=> TSLint shared rules

.circleci/config.yml
Parallelizes typescript compilation, tests and checks reducing runtime by 1 minute (from 2:30 to 1:30)
=> Parallelize tests and checks

ts/screens/wallet/AddCardScreen.tsx
removed the dismiss of keyboard
=> [#165283342] fix-keyboard-in-payment-section

ios/Podfile.lock, package.json, yarn.lock
The latest version of react-native-webview include this [PR](https://github.com/react-native-community/react-native-webview/pull/472) that fix the overflow issue.
=> [#165465552] Fix webview overflow issue

locales/en/index.yml, locales/it/index.yml, ts/screens/preferences/ServiceDetailsScreen.tsx, ts/screens/preferences/ServicesScreen.tsx, ts/store/actions/persistedPreferences.ts, ts/store/reducers/persistedPreferences.ts, ts/store/reducers/preferences.ts
This pr introduces an alert displayed the first time the user tries to disable a service. The message is displayed until the user proceeds with disabling a service for the first time.
=> [#159010582] display alert about enabilng/disabling single service

publiccode.yml
This PR adds a `publiccode.yml` file to the repo root in order to index the project in the Developers Italia software reuse catalogue (see [this](https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/index.html) for reference).
I tried to fill it with info taken from this repo. Please feel free to change the values or add a comment and I will upload it consequently.
The `screenshots` field is empty at the moment since after a brief chat with @matteodesanti we decided to fill it at a later stage.
Thanks a lot! 
@cloudify
=> Adds publiccode.yml file for reuse catalogue

ios/ItaliaApp/Info.plist, ios/ItaliaApp/it.lproj/InfoPlist.strings, ios/Podfile, ios/Podfile.lock
NSLocationAlwaysUsageDescription permission not used and removed module RCTGeolocation from the podfile
=> [#165661178] removed unused permission

ts/screens/profile/ProfileMainScreen.tsx
=> [#165860729] Print App version with build number on iOS

ts/components/wallet/WalletLayout.tsx, ts/screens/wallet/WalletsScreen.tsx
This pr makes the background color of the WalltesScreen equal to darkGray instead of white.
=> [#161442382] Unify the background color of WalletsScreen

locales/it/index.yml
This PR aims to change "Disarchivia" with "Ripristina" in message unarchive CTA
=> [#165631329] change "Disarchivia" with "Ripristina"

ts/components/IdpsGrid.tsx, ts/components/InstabugButtons.tsx, ts/components/screens/BaseHeader.tsx, ts/screens/messages/MessagesHomeScreen.tsx, ts/screens/preferences/ServicesScreen.tsx
=> [#165425115] Fix voice over

ts/screens/messages/MessagesHomeScreen.tsx, ts/theme/variables.ts
This PR aims to update and uniform Tab Components' style
=> [#165715960] Update and uniform Tab Components' style

locales/en/index.yml, locales/it/index.yml, ts/components/ui/AlertModal.tsx, ts/components/ui/Overlay.tsx, ts/screens/profile/ProfileMainScreen.tsx
=> [#165966077] Added custom alert when the PagoPA environment is changed

ts/theme/components/Input.ts, ts/theme/index.ts, ts/theme/variables.ts
This PR aims to align the style of search bar with the app style.
=> [#165864924] Fix font family in search input

package.json, yarn.lock
Avoid problems installing a specific and updated version of fsevents.
=> Set fsevents version resolution

package.json, yarn.lock
This reverts commit 903ff8df93f2c3262ef509a1fb6aca2e77a8acca.
=> Revert "Set fsevents version resolution (#1073)"

ts/components/messages/MessageAgenda.tsx, ts/components/messages/MessagesDeadlines.tsx, ts/screens/messages/MessagesHomeScreen.tsx
=> [#166232598] Archive messages from Deadlines tab

ts/screens/profile/ProfileMainScreen.tsx
This PR aims to fix width of list items when their text is too long for screen width
iPhone 5s
=> [#166281158] fix Profile Item list width

locales/it/index.yml
this pr aims to fix typo QR code text
=> [#165913473] fix typo QR code

ts/screens/IngressScreen.tsx, ts/theme/variables.ts
Created and used a new contentPaddingTop for 'initialization' label
=> [#166163662] Fix for 'initialization' label position

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/PaymentMethodsList.tsx
=> [#166329582] Not implemented payment methods style

locales/en/index.yml
=> [#160648832] Fix alert label

ts/screens/wallet/payment/ScanQrCodeScreen.tsx
Increased timeout qrcode alert
=> [#166439526] Increased timeout qrcode alert

ts/screens/wallet/WalletHomeScreen.tsx
Hidden add payment method button when error occurring in wallet
=> [#166695115] Hidden add payment method button when error occurring in wallet

locales/en/index.yml, locales/it/index.yml, ts/components/Pinpad/index.tsx
=> [#166787075] Added alert and locales

locales/en/index.yml, locales/en/wallet_help.md, locales/it/index.yml, locales/it/wallet_help.md, ts/components/wallet/WalletLayout.tsx
Added the help modal for the wallet tab
=> [#166761503] Added modal view wallet info

locales/en/wallet_help.md, locales/it/wallet_help.md
Fix format text in wallet contextualHelp
=> [#166761503] Fix format text in wallet contextualHelp

ts/sagas/wallet.ts
Fix back to wallet home during transaction
=> [#167131233] Fix back to wallet home during transaction

android/app/build.gradle, ios/Podfile.lock, package.json, yarn.lock
Updated react native camera to 2.11.1
=> [#167563485] Update react native camera to 2.11.1

ts/screens/profile/PreferencesScreen.tsx
Inverted language and mobile phone
=> [#167575686] Inverted values in Profile/Preferences section

ios/ItaliaApp/it.lproj/InfoPlist.strings
=> [#167588824] Missing translation in microphone alert

ts/components/ProfileTabIcon.tsx
=> [#167596435] Removed custom color for experimental features profile icon

ts/components/screens/ListItemComponent.tsx, ts/screens/profile/PreferencesScreen.tsx
Fixed the email icon misalignment in the Preferences screen.
**BEFORE:** 
**NOW:**
**Android:**
=> [#167575736] Fix misalignment in Preferences

ts/components/screens/SectionHeaderComponent.tsx, ts/components/services/ServiceSectionListComponent.tsx
Added the sticky header to the sections in the new services list.
**BEFORE:**
**NOW:**
=> [#165716236] Added sticky header in services list

README.md
=> [#167461154] Fix build warning ios

locales/en/index.yml, locales/it/index.yml, ts/screens/preferences/OldServiceDetailsScreen.tsx
Changed the email notifications label to "email forwarding".
**BEFORE:**
**AFTER:**
=> [#168169513] Changed email notifications label

locales/en/index.yml, locales/it/index.yml
This PR update the messages shown to user from SPID.
=> [#167164297] Update SPID messages

ts/components/screens/ListItemComponent.tsx, ts/components/ui/Switch.tsx, ts/screens/profile/BiometricRecognitionScreen.tsx, ts/screens/profile/ProfileMainScreen.tsx, ts/screens/wallet/ConfirmCardDetailsScreen.tsx
- Now the switch color in all the app is IO's blue
- Fixed a problem that causes the service item to be resized
=> [#168504115] Change switch color

.env.example
Changed default value for flag NEW_HOME_SERVICES
=> [#168635224] Changed default value for flag NEW_HOME_SERVICES

ts/screens/preferences/OldServiceDetailsScreen.tsx
=> [#168660223] Fix layout

ts/screens/services/ServicesHomeScreen.tsx
this PR allows you to continue the massive selection when you click on the same tab:
BEFORE
AFTER
=> [#168661808] fix tap tabs services

ts/sagas/startup/watchLogoutSaga.ts
This pr adds the try-catch to the logout request. Even if offline, the user is taken back to the LandingScreen and, if the user selects the hard logout, the store is cleaned.
=> [#168930387] Add try-catch to watchLogoutSaga

ts/components/wallet/card/Logo.tsx
Logo for Maestro credit card when this card is present in payment methods list
=> [#169062363] Logo for Maestro credit card when this card is present in payment methods list

ts/components/SelectLogoutOption.tsx, ts/screens/profile/ProfileMainScreen.tsx
This PR introduces the loading while the logout operation is running.
=> [#168935085] Add loading to logout

ts/components/InstabugButtons.tsx
=> [#169038279] Add Instabug option always active 

.env.example
=> [#169401814] Added two missing keys

ts/components/InstabugButtons.tsx, ts/sagas/instabug.ts, ts/sagas/startup.ts, ts/store/actions/instabug.ts, ts/store/reducers/instabug/instabugUnreadMessages.ts
This pr insert inserts the immediate IB badge update when an IB messages is read:
=> [#169288080] Update IB badge

locales/en/cie/noNfcConnection.md, locales/en/index.yml, locales/it/cie/noNfcConnection.md, locales/it/index.yml, ts/navigation/AuthenticationNavigator.ts, ts/screens/authentication/InvalidNfcConnectionScreen.tsx
This pr insert the Invalid NFC connection screen:
=> [#169167649] Add screen CIE hold card reminder

locales/it/index.yml
=> [#169566004] Fix typo choose payment method

ts/screens/onboarding/EmailInsertScreen.tsx
This pr updates the link to the story that will be focussed on introduce the "REmember to validate your email" modal into the preference flux
=> [#168247670] Update link to story

.circleci/config.yml
This PR updates circeci node-cache from  1.7 to 1.8
=> Update circeci node-cache

ts/theme/variables.ts
This PR solves the following problems:
* Uppercase text button in all CTA
* Black Checkbox
=> [#169642240] Fixed Native Base upgrade

ts/screens/services/ServicesHomeScreen.tsx
This PR fixes a bug on when services are successfully loaded
=> [#169642081] Fix services load

ts/screens/onboarding/PinScreen.tsx
=> [#169486366] Removed unnecessary debounce

ts/screens/profile/PrivacyMainScreen.tsx
=> [#169731875] Change privacy screen title

locales/en/index.yml, locales/it/index.yml, ts/screens/wallet/ConfirmCardDetailsScreen.tsx
Fixed the button width in ConfirmCardDetailsScreen.
**BEFORE:**
**AFTER**
=> [#169601567] Fix button width in ConfirmCardDetailsScreen

README.md
=> [#169751457] Fix typo

ts/components/services/ServicesSectionsList.tsx
=> [#168659762] Fixed padding

ts/components/LoadingSpinnerOverlay.tsx, ts/components/helpers/withErrorModal.tsx, ts/components/ui/AlertModal.tsx, ts/components/ui/Overlay.tsx
This PR sets the default opacity to 1 in the Overlay component and the LoadingSpinnerOverlay.tsx component has been adjusted to handle the opacity in the backgroundColor.
=> [#169427269] removed opacity from Overlay.tsx

ts/components/LabelledItem.tsx, ts/theme/variables.ts
This PR changes the bottom border color on input field when it has focus and it is empty
=> [#169872472] Change item bottom border color on focus 

ts/screens/services/ServicesHomeScreen.tsx
Fixed the scroll event on services's list when the keyboard is shown
=> [#168803731] Fixed the scroll event on services's list when the keyboard is shown

ts/components/FiscalCodeLandscapeOverlay.tsx, ts/components/ui/LightModal.tsx
This PR adds the slide animation, similar to the Modal component, to the light modal when it is shown.
=> [#167511240] added slide animation to light modal

package.json, ts/components/FiscalCodeLandscapeOverlay.tsx, yarn.lock
=> [#169948016] Removed unused package

ts/components/ui/LightModal.tsx, ts/screens/profile/FiscalCodeScreen.tsx
This PR adds the showAnimatedModal function in LightModal in order to open it with the slide animation.
=> [#170026531] added showAnimatedModal in LightModal

ts/components/CiePinpad/index.tsx
This PR fixes an index out of range bug
=> [#170074090] Fix bug on CIE Pin screen

ts/navigation/OnboardingNavigator.ts, ts/navigation/routes.ts, ts/sagas/startup.ts, ts/store/actions/navigation.ts
This PR remove _LoadingScreen_ because it causes side effects (this PR introduced the bug https://github.com/teamdigitale/io-app/pull/1457)
=> [#170156080] Removed LoadingScreen

.github/PULL_REQUEST_TEMPLATE.md
The aim of this PR is to add a _basic_ `pull_request_template.md` file to facilitate the review process.
- Added `pull_request_template.md` in `.github` folder.
_No tests added_
=> Add: pull request template

ts/components/ui/LightModal.tsx, ts/screens/profile/FiscalCodeScreen.tsx
This PR adds the ability to configure five animations in the LightModal:
* slide right to left (default)
* slide left to right
* slide bottom to top
* slide top to bottom
* fade
=> [#170026531] added AnimationLightModal in showAnimatedModal

Gemfile
Update fastlane version
from 2.126.0 to 2.137.0
=> Update fastlane from 2.126.0 to 2.137.0

locales/it/index.yml
=> [#170044192] Changed label amount to pay

ios/Podfile.lock, yarn.lock
Clean yarn.lock with yarn-deduplicate command
=> Clean yarn.lock with yarn-deduplicate command

ts/sagas/instabug.ts
This PR replaces the scheduled check of new Intabug replies with the usage of Instabug sdk callback
When a new Instabug replay arrives the counter badge is updated immediately
=> [#169895937] Replace Instabug on new reply pooling with sdk callback

ts/sagas/startup/__tests__/watchLoadMessages.test.ts, ts/sagas/startup/watchLoadMessagesSaga.ts, ts/store/middlewares/analytics.ts
This PR solves the problem of removing messages from the app store that are no longer present in the back-end.
=> [#170204165,#170334519] fix remove messages from cache

.circleci/config.yml, patches/react-native-touch-id+4.4.1.patch
Fixed fragment fingerprint
Added control to avoid double creation of the fragment for fingerprint verification
To replicate the bug (fixed in this PR) just click twice at the same time on the pinpad fingerprint button
=> [#170333681] Fixed fragment fingerprint

.circleci/config.yml
This PR upgrade node version in circleci config
=> Upgrade circleci node version

.circleci/config.yml, ts/components/SelectLogoutOption.tsx, ts/store/reducers/authentication.ts
The authentication status is updated on the logout
=> [#169425266] Update authentication state on logout

patches/react-native+0.59.9.patch
=> [#169262311] Fix loader home services

.env.production, README.md, bin/add-ios-source-maps.sh, ios/fastlane/Matchfile, package.json, publiccode.yml, ts/api/content.ts, ts/components/ui/TextWithIcon.tsx, ts/config.ts, ts/navigation/MainNavigator.tsx, ts/sagas/startup/checkProfileEnabledSaga.ts, ts/utils/fetch.ts, yarn.lock
This PR updates all refs from teamdigitale to pagopa
Due to the company migration, several assets must be updated
=> [#170670746] Update refs from teamdigitale to pagopa

ts/types/pagopa.ts
=> [#171101485] Fix pagopa api spec

.env.example, .env.production
This PR updates the Mixpanel token with a new one
=> [#171151674] Update Mixpanel token

ts/components/wallet/card/CardComponent.tsx
=> [#171303862] Removed an unnecessary event

ts/sagas/startup/checkAcceptedTosSaga.ts, ts/screens/onboarding/TosScreen.tsx
This PRs updates some code align profile with the new shape **_InizializedProfile_**
=> [#169702282]Refactor profile with InizializedProfile

ts/components/screens/BaseHeader.tsx
Set the goback function also on the screen title label
=> [#170818734] Add go back navigation on screen title

locales/en/index.yml, locales/en/profile/profile_preferences_spid_email.md, locales/it/index.yml, locales/it/profile/profile_preferences_spid_email.md, ts/screens/profile/PreferencesScreen.tsx
Added contextual help for spid email
In the preferences screen the contextual help will be shown on click the spid-email item
=> [#171385299] Added contextual help for spid email

yarn.lock
=> Upgrade handlebars to v4.3.0

ios/Podfile.lock, package.json, yarn.lock
Upgrade react-native-device-info v.5.5.3
=> Upgrade react-native-device-info v.5.5.3

ts/components/messages/CalendarEventButton.tsx
**Added check on the reminder label for small displays, to risolve this bug**
=> [#171647062] Added check on the reminder label for small displays

ts/boot/configureStoreAndPersistor.ts, ts/store/reducers/entities/index.ts, ts/store/reducers/index.ts, ts/store/reducers/types.ts
This PR adds a specific configuration to avoid to persist _messages_ section
_messages_ is a section of _entities_. Other sections of _entities_ different from _messages_ will be persisted
=> [#171570702] Avoid to persist messages section

ts/sagas/startup/watchLoadMessagesSaga.ts
This PR updates the condition for which the service detail load action is dispatched
```
// we need to load a service if (one of these is true)
// - service is not cached
// - service is not loading AND (service is none OR service is error)
```
=> [#171855460] Fix service load condition on message detail load complete

locales/en/index.yml, locales/it/index.yml, ts/components/Pinpad/Placeholders.tsx, ts/components/Pinpad/index.tsx, ts/types/PinString.ts, ts/utils/constants.ts
2 Features:
- Set the pin length from 5 to 6 digits
- Render the numbers present on the pinpad randomly
=> [#171608911] Set pin lenght to six digits

ts/boot/configureStoreAndPersistor.ts
This PR increases redux persist store version to 10
=> [#171881648] Increase redux persist store version

ts/boot/configureInstabug.ts, ts/sagas/startup.ts
This PR removes cf and email from instabug tracked attrs
=> [#171905053] Remove CF from Instabug attrs

package.json, yarn.lock
upgrade italia-pagopa-commons to v1.2.0
=> [#171915730] upgrade italia-pagopa-commons to v1.2.0

locales/en/index.yml, locales/it/index.yml
Changed the messages shown for pin reset
=> [#171191238] Changed the messages shown for pin reset

ts/sagas/index.ts
This PR removes double instabug saga invocation
=> [#172002706] Remove instabug saga duplications

locales/en/index.yml, locales/it/index.yml, ts/screens/wallet/payment/PickPspScreen.tsx
This pr updates the UI of the PickPspScreen:
UPDATED UI:
DESIGN:
=> [#171997936] update PickPspScreen UI

ts/screens/profile/PrivacyMainScreen.tsx, ts/store/middlewares/analytics.ts
This PR forwards user request on download/delete his data on Mixapel.
Furthermore it fixes a bug on display badge in privacy main screen
=> [#172019334] Add tracking user download/delete requests on mixpanel

ts/theme/components/Content.ts, ts/utils/constants.ts
This pr is a UI fix. It fixes the white bottom space displayed on iPhones X.
pink: content space
yellow: uncovered bottom space
**BEFORE  & AFTER**
=> [#172085594] fix bottom space iphone x

locales/en/spid.md, locales/it/spid.md
Changed the external link on Spid/CIE Information page
- locales/en/spid.md
- locales/it/spid.md
- Click on "Don't have SPID or CIE?" link on login footer
- Click on "Learn more" link on SPID tab
=> [#172122395] Fixed the external link on SPID Learn more info description

.circleci/config.yml, ts/screens/authentication/LandingScreen.tsx
This PR restore the Android alpha lane stopped due to allow review on Play Store
=> [#172075548] Restore Android alpha lane

.circleci/config.yml
This PR temporarily blocks Android alpha lane
=> [#172075548] Block Android alpha lane

ts/boot/configureRectotron.ts
This PRs add **ignoreUrls** key in the _Reactotron_ config to allow developers to specify a regex to avoid specific urls.
This is to ensure that the timeline if _Reactotron_ is always clean
=> [#172205784] add ignored urls in Reactotron config

.env.example, .env.local, .env.production, .gitignore, ts/components/VersionInfoOverlay.tsx, ts/config.ts, ts/screens/authentication/LandingScreen.tsx
This PR updates existing env files by adding description and exposing all config fields used in the app.
.env.local files has been added to allow a fast config to use with [io-dev-api-server](https://github.com/pagopa/io-dev-api-server)
=> Update env config files

ts/boot/configureInstabug.ts
Avoid Instabug to trace network requests
=> [#172313592] Configure Instabug to don't trace network requests

ts/api/backendPublic.ts
This PR adds current time milliseconds to certain request to ensure no response will be cached
requests involved:
- backend status
- backend info
=> [#172349278] Add a timestamp to avoid caching in certain requests

ts/screens/profile/ProfileMainScreen.tsx
Remove the Switch to toggle the debug mode in develop environment.
Switch removed.
=> [#172224951] Remove debug switch in dev mode from profile screen

.circleci/config.yml
=> [#172075548] Stop Android alpha lane

ts/screens/authentication/cie/CieCardReaderScreen.tsx
This PR adds the handling of NOT CIE card reading event
=> [#172396903] Handle not CIE card event

ts/components/FAQComponent.tsx, ts/components/InstabugButtons.tsx, ts/components/wallet/PaymentMethodsList.tsx, ts/store/reducers/entities/services/index.ts
This PR adds few adjustments
- payment methods ordered alphabetically
- remove bottom line from faq when it is expanded
- instabug email now is optional
- services grouped by organization name
=> [#172457330] UI adjustments / fix organization duplication

ts/navigation/AppNavigator.ts, ts/navigation/AuthenticationNavigator.ts, ts/navigation/MessagesNavigator.ts, ts/navigation/OnboardingNavigator.ts, ts/navigation/ProfileNavigator.ts, ts/navigation/ServicesNavigator.ts, ts/navigation/WalletNavigator.ts
This PR removes the swipe back gesture on iOS devices.
- ts/navigation/AppNavigator.ts
- ts/navigation/AuthenticationNavigator.ts
- ts/navigation/MessagesNavigator.ts
- ts/navigation/OnboardingNavigator.ts
- ts/navigation/ProfileNavigator.ts
- ts/navigation/ServicesNavigator.ts
- ts/navigation/WalletNavigator.ts
=> [#172409009] Disables iOS swipe back gesture on navigators

ts/theme/components/Button.ts
This pr removes an undesired style applied to icons wrapped in a button
=> [#172533403] Fix wrong color assigned to button icons

scripts/make-locales.ts
This pr introduce a try-catch logic to print the error when the generation of locales fails
=> [#172532568] print error if  locale generation fails

ts/sagas/services/refreshStoredServices.ts
This PR fix the infinite loading for services or other entites that are serialiazed in the store in the `loading` state.
- Remove the check `isLoading`
Close the application while loading service data, re-open the application.
=> [#172431153] Fix infinite loading services

ts/sagas/startup.ts, ts/sagas/startup/__tests__/watchCheckSessionSaga.test.ts, ts/sagas/startup/watchCheckSessionSaga.ts, ts/store/actions/authentication.ts
This PR adds a new saga to the authentication to check the current session validity.
- ts/sagas/startup.ts
- ts/sagas/startup/watchCheckSessionSaga.ts
- ts/store/actions/authentication.ts
=> [#172556308] Added a new saga to check the current session status

ts/components/cie/CieRequestAuthenticationOverlay.tsx
This PR fixes a bad UI disposition when an error occurred while CIE authentication
=> [#172648858] Fix CIE error mask rendering

locales/en/faq/faq57.md, locales/it/faq/faq57.md
Changed the text in the payments faq
=> [#172655832] Changed the text in the payments faq

ts/store/middlewares/analytics.ts
This PR adds the userMetadataLoad actions to mixpanel 
- ts/store/middlewares/analytics.ts
=> [#172355081] Adds userMetadataLoad to mixpanel

locales/en/index.yml, locales/it/index.yml, locales/it/profile/profile_privacy_main.md, ts/components/messages/MessageDetailComponent.tsx
This PR updates some texts and remove edge component from message detail screen
=> [#172713219] Update texts

ts/screens/messages/MessageDetailScreen.tsx
This PR fixes **message read state** when message is opened from notification
Furthermore it fixes a bug on load services metadata
=> [#172734338] Fix message read state 

ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
This pr add the edge component to the list of payment methods displayed if the user decided to change the payment method during a payment
=> [#172815260] add edge component to payment method list

ts/components/cie/CieRequestAuthenticationOverlay.tsx, ts/screens/onboarding/TosScreen.tsx
Minor fixes on the injected JS to webview.
- ts/components/cie/CieRequestAuthenticationOverlay.tsx
- ts/screens/onboarding/TosScreen.tsx
Using dev server, force to accept the TOS, that was the webview raising the exception.
=> [#172576356] Fixes a minor warning on the injected JS from the webview

ts/screens/wallet/payment/ManualDataInsertionScreen.tsx
Dismiss keyboard on show modal
=> [#172762181] Dismiss keyboard on show modal

.gitignore, ts/components/messages/MessageDetailComponent.tsx, ts/components/messages/MessageDetailData.tsx
This PR fixes how message sent date is displayed inside Message Detail screen.
It also introduces a little refactoring on conditional rendering
=> [#172897716] Fix display message sent date

ts/screens/wallet/payment/TransactionSummaryScreen.tsx
This pr introduces the euro symbol on the total amount displayed in the transaction summary
**How to duplicate**
The screen is displayed:
- when press the pay button in the message CTA
- when check a payment by qr code or by manual instertion of payment credentials
=> [#173031294] add euro symbol on total amount

ts/features/bonusVacanze/api/backendBonusVacanze.ts, ts/features/bonusVacanze/store/actions/bonusVacanze.ts, ts/features/bonusVacanze/store/reducers/bonusVacanze.ts, ts/features/bonusVacanze/store/sagas/bonusSaga.ts, ts/features/bonusVacanze/types/eligibility.ts
PR number 3 about bonus vacanza API integration
This syncs the status code and payload with last changes defined in backend side
=> [#172989345] Sync eligibility API POST/GET

ts/features/bonusVacanze/store/reducers/bonusVacanze.ts
PR number 6 about bonus vacanze API integration
rename store section `bonusVacanze` -> `bonusVacanzeActivation`
=> [#172989345] Rename store section bonusVacanze -> bonusVacanzeActivation

ts/features/bonusVacanze/mock/mockData.ts, ts/features/bonusVacanze/store/reducers/__tests__/bonusVacanzeActivation.test.ts, ts/features/bonusVacanze/store/sagas/bonusActivation/handleStartBonusActivationSaga.ts, ts/features/bonusVacanze/store/sagas/handleBonusEligibilitySaga.ts
update status codes with last specs
=> [#172989345] update status codes with last specs

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/PaymentSummaryComponent.tsx, ts/features/bonusVacanze/components/AvailableBonusItem.tsx, ts/features/bonusVacanze/components/TosBonusComponent.tsx, ts/features/bonusVacanze/data/availableBonuses.ts, ts/features/bonusVacanze/screens/BonusInformationScreen.tsx, ts/screens/onboarding/TosScreen.tsx, ts/utils/__tests__/string.test.ts, ts/utils/strings.ts, ts/utils/webview.ts
This PR updates the usage of bonus available since its shape is changed:
- remove data placeholders with the remote ones
- update bonus detail screen
- now ToS are loaded from remote url
| list  | detail |
=> [#173361687] Update Bonus Available 

ios/ItaliaApp.xcodeproj/project.pbxproj, ios/ItaliaApp/Info.plist, ios/ItaliaAppTests/Info.plist
- Increase iOS deploy target from 9 to 13
- Remove multiple upload source (Instabug)
=> [#173464503] Increase iOS deploy target to 13

ts/features/bonusVacanze/components/AvailableBonusItem.tsx, ts/features/bonusVacanze/data/availableBonuses.ts, ts/features/bonusVacanze/screens/BonusInformationScreen.tsx, ts/features/bonusVacanze/store/reducers/availableBonusesTypes.ts
According to available bonus type definition now some content are localized (it/en)
=> [#173435275] Update available bonus type with new spec

locales/en/index.yml, locales/it/index.yml, ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx
This PR corrects the status description on Bonus detail screen
**Redeemed**
**Active**
=> [#173443307] Show different texts base on bonus status

ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx
=> [#173475769] Fix QrCode display

ios/ItaliaApp.xcodeproj/project.pbxproj
=> [#173486320] Restore iOS 9

ts/screens/wallet/TransactionsScreen.tsx
This PR fixes the crash when mounting the TransactionsScreen
=> [#173515056] Fixes crash on transactions list

ts/features/bonusVacanze/utils/bonus.ts, ts/store/middlewares/analytics.ts
Updated the events dispatched to mixpanel
Removed:
- BONUS_VACANZE_ACTIVATION_REQUEST
- BONUS_VACANZE_ACTIVATION_COMPLETE
- BONUS_VACANZE_LOAD_FROM_ID_REQUEST
- BONUS_VACANZE_LOAD_FROM_ID_SUCCESS
Updated:
- BONUS_VACANZE_CHECK_ELIGIBILITY_SUCCESS
- BONUS_VACANZE_CHECK_ELIGIBILITY_STORE_REQUEST_ID
- BONUS_VACANZE_ACTIVATION_SUCCESS
=> [#173517663] Change the bonus vacanze events dispatched to mixpanel for troubleshooting

locales/en/index.yml, locales/it/index.yml, ts/features/bonusVacanze/screens/activation/EligibilityExpired.tsx
Update the screen for eligibility expired.
=> [#173521040] Update eligibility expired screen

ts/store/reducers/content.ts, ts/utils/locale.ts
This PR fixes a bug that causes a crash if the device has a language not supported (it/en)
**how to reproduce**
- change your device to a language that is not italian or english (i.e. german)
- run the app
- :boom:
=> [#173530583] Fix crash on language 

ts/utils/locale.ts
This PR fixes the CTA title: english title is shown even if the app is set to italian
=> [#173538229] Fix CTA text localization

locales/en/faq/faq42.md
=> [#172149906] traduzione faq

locales/en/faq/faq43.md
=> [#172149906] Traduzione faq (2)

ts/screens/wallet/WalletHomeScreen.tsx
This PR forces bonus vacanze reload each time _payments_ section has focus
=> [#173602010] Reload bonus vacanze on payment section focus

locales/it/index.yml
Timeout messages copy updated according to stakeholders request.
=> Copy updates

ts/features/bonusVacanze/components/BonusCardComponent.tsx, ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx
This PR corrects the bad display of bonus card component on tablet devices
=> [#173640918] Fixes Bonus card alignment on Tablet devices

ts/store/reducers/allowedSnapshotScreens.ts
Add Wallet Home and Transaction Details to allowed snapshottable screens
=> [#173651699] add Wallet Home and Transaction Details to allowed snapshottable screens

locales/en/index.yml, locales/it/index.yml, ts/screens/profile/ProfileMainScreen.tsx
This PR remove the double option to logout: soft or hard.
Now an alert is shown and if user wants to logout, the hard logout is always performed
This change solves 2 bugs:
- Another user can see the transactions list of the previous logged used
- Another user can see the place of birth of the previous logged used
|  | |
=> [#173651298,#173651447] Add hard-logout as default option to logout

locales/en/index.yml, locales/it/index.yml, ts/components/helpers/withLightModalContext.tsx, ts/screens/authentication/LandingScreen.tsx, ts/screens/modal/RootedDeviceModal.tsx
Display an alert that inform the user that the interface is optimized for smartphone only.
=> [#173640797] Display alert for tablet

ts/components/screens/BaseHeader.tsx, ts/components/ui/AppHeader.tsx
This PR restores the accessibility of app header
=> [#173686901] Restore accessibility for app header

locales/en/bonus/faq/faq63.md, locales/it/bonus/faq/faq63.md
This PR fixes the bad url on FAQ to the pdf guide for bonus.
=> [#173744863] Fixes bad url to bonus guide

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/PaymentSummaryComponent.tsx, ts/components/wallet/PaymentsHistoryList.tsx, ts/screens/wallet/PaymentHistoryDetailsScreen.tsx, ts/store/reducers/payments/history.ts, ts/utils/payment.ts
Added to log:
- notice code
- description of the error
In the payment history detail the notice code is shown in place of IUV
=> [#173712388] Add Codice Avviso in place of IUV

ts/screens/wallet/WalletHomeScreen.tsx, ts/store/actions/wallet/transactions.ts, ts/store/reducers/wallet/transactions.ts
This PR includes a fix on transactions refresh:
since the newer transactions are at the start of the list, the fix clears all stored transactions and loads transactions from the beginning
=> [#173752636] Fix wallet transactions refresh

locales/en/index.yml, locales/it/index.yml
This PR changes the text of the button to enter payment data manually
***Before***
***Now***
=> [#173790471] Fixes too long text on CTA to enter payment data manually

locales/en/index.yml, locales/it/index.yml, ts/components/FiscalCodeComponent.tsx, ts/components/FiscalCodeLandscapeOverlay.tsx, ts/screens/profile/FiscalCodeScreen.tsx, ts/screens/profile/ProfileMainScreen.tsx, ts/utils/accessibility.ts, ts/utils/convertDateToWordDistance.ts, ts/utils/profile.ts
This PR implements the accessibility on the fiscal code component and screen
=> [#173703056] Fix accessibility on Fiscal code

ts/screens/authentication/IdpLoginScreen.tsx, ts/screens/authentication/IdpSelectionScreen.tsx, ts/utils/SpidErrorCode.ts, ts/utils/spidErrorCode.ts
This pr allows to log on instabug the reason of the SPID login failure.
- When the user choose an IDP, log the action: Idp selected
- When the user fail to login using SPID, log the error code + error code textual description and add the tag `spid-login-failure`
- When the user successfully logs in, log the action and remove the tags
=> [#173827829] Log login failure on instabug

scripts/check_urls/check_urls.py
- add contextual help data source
- more explicit error logs
=> [#173887151] Check urls - add contextual help data source

ts/mixpanel.ts
Since it is useless for any analysis, it should be disabled
=> [#173898167] Disable Mixpanel geo-ip localization

locales/en/cie.md, locales/en/index.yml, locales/it/cie.md, locales/it/index.yml, ts/screens/authentication/cie/CieExpiredOrInvalidScreen.tsx
=> [#173936682] Remove links from code

scripts/check_urls/check_urls.py
On check urls ignore some exceptions that are not relevant for url reachability
=> [#173936506] Check urls - ignore some exceptions

ts/components/CalendarsListContainer.tsx, ts/screens/profile/CalendarsPreferencesScreen.tsx, ts/store/actions/persistedPreferences.ts, ts/store/reducers/persistedPreferences.ts
This PR adds the remove favourite calendar feature on preferences screen.
- ts/components/CalendarsListContainer.tsx
- ts/screens/profile/CalendarsPreferencesScreen.tsx
- ts/store/reducers/persistedPreferences.ts
- ts/store/actions/persistedPreferences.ts
=> [#173938203] Remove the selected favourite calendar

locales/en/index.yml, locales/it/index.yml, ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx, ts/features/bonusVacanze/screens/BonusInformationScreen.tsx, ts/features/bonusVacanze/store/reducers/__tests__/allActive.test.ts, ts/features/bonusVacanze/store/reducers/allActive.ts
This PR adds the check to bonus on status `Redeemed` to show the alert and advice box for multiple bonuses requested
Minor fix on alert label.
=> [#173965657] Adds the status redeemed for multiple bonus alert selector

ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx
This PR fixes the hidden screen title under the BonusCardComponent
This was the bug:
=> [#173977842] fixes the title under bonus card

.circleci/config.yml
=> Disable android ci

ios/fastlane/Fastfile
This pr disable the fastlane tag creation (not needed anymore due to (#2089 )
- Changed `Fastfile`
=> [#173984568] fastlane creates another version tag

ts/components/CalendarsListContainer.tsx, ts/components/screens/SectionHeaderComponent.tsx
This PR organize the list of calendars based on related account
=> [#172455914] Organize available calendars by account

android/app/src/main/AndroidManifest.xml
This PR should fix a error loading that could happen in certain devices of Android family
rel https://github.com/react-native-community/react-native-webview/issues/1050
=> [#174115403] Error loading webview url [Android]

ts/components/InstabugChatsComponent.tsx, ts/features/bonusVacanze/screens/BonusInformationScreen.tsx, ts/utils/accessibility.ts
If there is a screen reader enabled the CTAs will be rendered on top
| screen reader OFF  | screen reader ON |
=> [#174089908] Improve accessibility bonus description screen

scripts/changelog/ts/__mocks__/storyMock.ts, scripts/changelog/ts/changelog.ts, scripts/changelog/ts/types.d.ts
[Add MyPortal](https://www.pivotaltracker.com/n/projects/2463683) as changelog project scope
=> feat: [#174574704] Add My Portal project as changelog-scope

ts/components/wallet/PaymentMethodsList.tsx
Remove max fee from credit card payment method
=> feat(Payments): [#174689572] Remove max fee from credit card payment method

ts/config.ts
=> chore: [#174731503] Upgrade tos version to 2.1

ts/types/ServicesWebviewParams.ts, ts/types/__tests__/ServicesWebviewParams.test.ts
This PR adds a codec to decode params available when navigating to ServicesWebviewScreen
=> feat(MyPortal): [#174801117] Adds ServicesWebviewParams codec

ts/components/core/typography/BaseTypography.tsx
This pr fixes the wrong style application to the typography components.
=> fix: [#174932033] Apply style to typography remove inner style

ts/screens/profile/PrivacyMainScreen.tsx
This PR remove the block that doesn't allow user with a not validated email from request the download of his data.
- ts/screens/profile/PrivacyMainScreen.tsx
=> feat: [#174864406] Remove the not validated email block to request the download of data

ts/screens/authentication/cie/CieCardReaderScreen.tsx
This PR sends some logs to Instabug while the app reads the user CIE card.
**No personal information will be forwarded**
=> feat: [#174878537] Log CIE events 

ts/components/RegionServiceWebView.tsx, ts/screens/profile/WebPlayground.tsx, ts/screens/services/ServicesWebviewScreen.tsx
This PR Fixes some behaviors on RegionWebview component when handling a message from the webview
Use the latest version of myportal_playground.html commited on the dev server
=> feat(MyPortal): [#175076372] Fixes Region Webview behaviour on message received

ts/screens/modal/IdentificationModal.tsx, ts/screens/profile/BiometricRecognitionScreen.tsx
Changed Touch ID label from `reason` to `title`
=> fix: [#175090750] Wrong label shown in Touch-ID identification

package.json, ts/api/pagopa.ts, ts/features/bonus/bpd/api/patchedTypes.ts, ts/features/wallet/onboarding/bancomat/store/actions/index.ts
The last API spec about bancomat is available here 
- [origin](https://acardste.vaservices.eu/pp-restapi-CD/v2/api-docs)
- [bancomat api extracted](https://raw.githubusercontent.com/pagopa/io-services-metadata/master/bonus/specs/bpd/pm/swagger_bancomat.json)
- app side: `yarn generate:all`
- io-dev-server: get the last commit and execute `yarn generate:all`
=> chore(Bonus Pagamenti Digitali): [#175186882] Sync code last PM API spec 

locales/en/index.yml, locales/it/index.yml, ts/screens/profile/ProfileMainScreen.tsx
This PR add the subtitle in the change code item in the profile section.
- ts/screens/profile/ProfileMainScreen.tsx
- locales/it/index.yml
- locales/en/index.yml
=> feat: [#175165123] add subtitle in change code item

locales/en/index.yml, locales/it/index.yml
This PR change the label Showroom in UI Showroom in order to ensure higher clarity
=> feat: [#175594236] change Showroom label

ts/components/messages/PaymentButton.tsx
This PR fixes a bug on pay CTA when a message has payment info, the payment due date is exceeded but the payment is still valid to pay.
=> fix: [#175620603] Pay CTA produces no action

package.json, ts/api/pagopa.ts
This PR updated the API code to align it with the new generated types/codec
=> chore: [#175657969] Sync pago/API with last specs

locales/en/index.yml, scripts/make-locales.ts, ts/features/bonus/bpd/api/backendBpdClient.ts, ts/features/bonus/bpd/saga/index.ts, ts/features/bonus/bpd/saga/networking/patchCitizenIban.ts
This PR implements patch citizen API (upsert IBAN) by sending a payload as described in the last specs.
Test token has been removed (obsolete login)
=> chore(Bonus Pagamenti Digitali): [#175659272,#175412288] Sync IBAN API to last specs

ts/features/wallet/onboarding/bancomat/saga/networking/index.ts, ts/features/wallet/onboarding/bancomat/screens/add-pans/PanCardComponent.tsx
This PR fixes few bugs discovered during today testing session
- bancomat date has a bad format
- add bancomat payload misses a nested field
=> fix(Bonus Pagamenti Digitali): [#175705143] Add bancomat payload generates 400

ts/features/bonus/bpd/screens/iban/insertion/IbanInsertionComponent.tsx, ts/screens/onboarding/EmailInsertScreen.tsx, ts/utils/keyboard.tsx
This PR fixes a wrong behaviour about CTA while IBAN insertion
Now the CTA is always over the virtual keyboard
=> feat(Bonus Pagamenti Digitali): [#175686157] CTA under keyboard while IBAN insertion

package.json, yarn.lock
This upgrade should support the authentication within multi-vendors card
=> feat: [#175729293] Upgrade react-native-cie v0.3.3

CODEOWNERS
Remove francescopersico from CODEOWNERS
=> Remove francescopersico from CODEOWNERS

ts/features/bonus/bpd/store/reducers/details/amounts.ts, ts/features/bonus/bpd/store/reducers/details/paymentMethods.ts, ts/features/bonus/bpd/store/reducers/details/transactions.ts
This pr clean the store after an unsubscription.
=> fix(Bonus Pagamenti Digitali): [#175745708] Clean store after unsubscription

ts/features/bonus/bpd/components/paymentMethodActivationToggle/base/PaymentMethodBpdToggle.tsx
This pr reverts a lost content during the merge of https://github.com/pagopa/io-app/pull/2373/commits/0ee6a3f0199543d61565d3ce56600135a491effc
=> chore(Bonus Pagamenti Digitali): [#175785820] Restore missing content

ts/screens/modal/Checkout3DsModal.tsx
This PR stores the entire url string when the Webview load the result URL containing the `AuthorizationCode`
=> feat: [#175784510] Log the AuthorizationCode

ts/screens/wallet/AddPaymentMethodScreen.tsx
This PR removes the PagoBancomat option when during payment user adds a new payment method
=> fix(Bonus Pagamenti Digitali): [#175797704] Fixes in payment pagobancomat method option

scripts/changelog/ts/changelog.ts
Add Changelog scope for new pivotal project.
=> feat: [#175850928] Add changelog scope for bpd

ts/features/wallet/onboarding/bancomat/screens/search/SearchBankScreen.tsx
Update bancomat privacy policy url -> https://io.italia.it/app-content/privacy_bancomat.html
=> feat(Bonus Pagamenti Digitali): [#175204653] Update bancomat privacy policy link

ts/features/bonus/bpd/analytics/index.ts
Add the field `abi` to the tracked action `searchUserPans.request`
=> fix(Bonus Pagamenti Digitali): [#175897659] Track the chosen abi

ts/api/pagopa.ts, ts/features/wallet/onboarding/bancomat/saga/networking/index.ts, ts/features/wallet/onboarding/bancomat/store/actions/index.ts, ts/features/wallet/onboarding/bancomat/store/reducers/pans.ts, ts/features/wallet/onboarding/satispay/saga/networking/index.ts, ts/features/wallet/onboarding/satispay/store/actions/index.ts, ts/sagas/wallet.ts, ts/screens/wallet/WalletHomeScreen.tsx, ts/store/actions/types.ts, ts/utils/errors.ts
This PR adds the scaffold (actions and network, handler&api) to search about user's Satispay
- make sure to have the last commit of io-dev-server
=> feat: [#175883641] Support search Satispay API

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/bpd/screens/details/components/paymentMethod/WalletPaymentMethodBpdList.tsx
This PR adds an alert when users adds payment method inside bpd detail screen
=> feat: [#175876595] Adds alert when adding new method in bpd

locales/en/index.yml, locales/it/index.yml, ts/api/content.ts, ts/features/bonus/bonusVacanze/components/AvailableBonusItem.tsx, ts/features/bonus/bonusVacanze/screens/AvailableBonusScreen.tsx, ts/features/wallet/component/FeaturedCard.tsx, ts/features/wallet/component/FeaturedCardCarousel.tsx, ts/screens/wallet/AddCardScreen.tsx, ts/screens/wallet/WalletHomeScreen.tsx
=> fix(Bonus Pagamenti Digitali): [#175938380] restore bonus is incoming

ts/components/CopyButtonComponent.tsx, ts/features/bonus/bonusVacanze/components/QrModalBox.tsx, ts/features/bonus/bpd/screens/details/transaction/detail/BpdTransactionDetailComponent.tsx
This PR Fixes the copy button not working in a bottom sheet on android plaform
| Before  | After |
| ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/3959405/100726935-e3e5e380-33c5-11eb-9e32-8f87b88de857.gif) | ![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/3959405/100727042-04ae3900-33c6-11eb-84fa-3842830b4d32.gif) |
=> fix(Bonus Pagamenti Digitali): [#175923455] Fixes copy button press on android

.env.example, .env.local, .env.production
This PR enables BPD in production
=> feat(Bonus Pagamenti Digitali): [#175989320] enable BPD

locales/en/index.yml, locales/it/index.yml
- updated customer care working hours
- copy update to better explain support also to credit cards with multi circuit
=> chore(Bonus Pagamenti Digitali): [#175991108] Copy updates

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/bpd/components/BpdTransactionSummaryComponent.tsx, ts/features/bonus/bpd/screens/details/transaction/BpdEmptyTransactionsList.tsx
-  markdown support
-  updated markup text
=> Valid transactions text update

locales/en/index.yml
=> fix(Bonus Pagamenti Digitali): [#176007673] Update index.yml

locales/it/index.yml
Typo in self-declaration screen
=> Typo in self-declaration screen

codecov.yml
This pr changes the codecov settings in order to allows the merge in master without errors if the codecov patch and project are not respected.
=> feat: [#176032092] Change codecov settings

locales/en/bonus/bpd/faq/faqBpd2.md, locales/en/bonus/bpd/faq/faqBpd3.md, locales/en/index.yml, locales/it/bonus/bpd/faq/faqBpd2.md, locales/it/bonus/bpd/faq/faqBpd3.md, locales/it/faq/faq37.md, locales/it/index.yml, ts/screens/wallet/AddCardScreen.tsx, ts/utils/faq.ts
This PR adds new FAQs to the AddCardScreen and AddMethodScreen
=> feat: [#176015857] Adds FAQ on AddCardScreen and AddMethodScreen

ts/features/wallet/component/FeaturedCardCarousel.tsx, ts/screens/wallet/WalletHomeScreen.tsx
This PR displays BPD Cards in wallet if Cards and transactions load has errors
=> feat(Bonus Pagamenti Digitali): [#176033170] Show BPDCard if wallets has error

locales/en/index.yml, locales/it/index.yml
- Bancomat is now "PagoBANCOMAT"
=> fix(Bonus Pagamenti Digitali): [#176027176] Corrected bancomat string fallback

locales/en/index.yml, locales/it/index.yml
- More explicit error message when unable to retrieve active methods on BPD
- Fixed references to ladybug icon
=> Copy changes

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/WalletHomeHeader.tsx, ts/screens/wallet/WalletHomeScreen.tsx
This PR moves the add button on screen title of WalletHomeScreen
=> feat(Bonus Pagamenti Digitali): [#176053058] Implements new Add button on wallet home screen

ts/boot/configureStoreAndPersistor.ts, ts/store/reducers/index.ts, ts/store/reducers/wallet/index.ts, ts/store/reducers/wallet/wallets.ts, ts/store/transforms/dateISO8601Tranform.ts
Payment Methods are now stored in persisted storage and will be cleaned when the user will logout manually or with a session expired event
=> feat(Bonus Pagamenti Digitali): [#176052891] Adds logic to persist loaded wallets

locales/en/index.yml, locales/it/index.yml
I propose a new copy in case the card has more than one logo.
=> Copy proposal

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/bpd/screens/onboarding/ErrorPaymentMethodsScreen.tsx
This pr updates the ErrorPaymentMethodsScreen.
=> feat(Bonus Pagamenti Digitali): [#176058971] Update ErrorPaymentMethodsScreen

ts/features/bonus/bpd/screens/details/components/paymentMethod/WalletPaymentMethodBpdList.tsx, ts/sagas/wallet.ts, ts/screens/wallet/WalletHomeScreen.tsx, ts/store/actions/wallet/transactions.ts, ts/store/actions/wallet/wallets.ts, ts/store/reducers/wallet/index.ts, ts/store/reducers/wallet/lastRequestError.ts, ts/store/reducers/wallet/transactions.ts, ts/store/reducers/wallet/wallets.ts
This PR support backoff retry on get wallets/transactions
=> feat(Bonus Pagamenti Digitali): [#176058079] support backoff retry

locales/en/index.yml, locales/it/index.yml, ts/components/screens/BetaBannerComponent.tsx
This PR removes beta references from text and images
=> fix(Bonus Pagamenti Digitali): [#176068210] Remove beta references

ts/sagas/wallet.ts, ts/screens/wallet/WalletHomeScreen.tsx, ts/store/reducers/wallet/lastRequestError.ts
This pr changes the saga logic (dispatch action instead of direct calling)
=> feat(Bonus Pagamenti Digitali): [#176071266] Dispatch action instead of calling saga for fetchTransactions and fetchWallets

ts/components/wallet/WalletHomeHeader.tsx
This PR fixes the cut texts on bottomsheet list items
=> fix(Bonus Pagamenti Digitali): [#176076602] Fixes cut text on add method bs

ts/boot/configureInstabug.ts, ts/components/screens/BaseScreenComponent.tsx, ts/screens/wallet/AddCardScreen.tsx
This PR makes report attachments configurable.
Default config includes them all
=> feat: [#176071893] Make report attachments configurable

ts/api/backendPublic.ts, ts/components/SectionStatusComponent.tsx, ts/components/wallet/PaymentMethodsList.tsx, ts/features/wallet/onboarding/bancomat/screens/search/SearchBankComponent.tsx, ts/screens/wallet/AddPaymentMethodScreen.tsx, ts/store/reducers/backendStatus.ts
This PR adds badge on payment method to indicate how the service is running.
=> feat(Bonus Pagamenti Digitali): [#176074721] Add payment method status badge

ts/components/HorizontalScroll.tsx, ts/utils/__tests__/number.test.ts, ts/utils/number.ts
This PR fixes a bug on multiple periods carousel visualization
=> fix(Bonus Pagamenti Digitali): [#175896616] Fixes scrollview snap on android

ts/screens/wallet/AddCardScreen.tsx
This PR includes the SectionStatusComponent inside AddCreditCardScreen
=> feat(Bonus Pagamenti Digitali): [#176091565] Add section status component in add credit card screen

ts/components/bottomSheet/BottomSheetHeader.tsx, ts/components/wallet/WalletHomeHeader.tsx
This PR fixes the overflow on bottom sheet titles when the text is too long
=> fix(Bonus Pagamenti Digitali): [#175991400] Fixes overflow text on bottomsheet title

ts/features/wallet/onboarding/bancomat/screens/search/BancomatSearchStartScreen.tsx, ts/features/wallet/onboarding/bancomat/screens/search/SearchBankScreen.tsx
This PR restore the service banner on Bancomat screens.
- Restored the service banner on SearchBankScreen
- Restored the service banner on BancomatSearchStartScreen
=> fix(Bonus Pagamenti Digitali): [#176117520] Restore service banner on Bancomat screens

ts/components/core/typography/H4.tsx, ts/features/bonus/bpd/components/transactionItem/BaseBpdTransactionItem.tsx
Go to wallet -> cashback -> transaction detail, cashback amount should be blue.
=> chore(Bonus Pagamenti Digitali): [#176095635] Changed color to the amount of cashback received

ts/features/bonus/bpd/screens/iban/insertion/IbanInsertionComponent.tsx
=> feat(Bonus Pagamenti Digitali): [#175898796] Fixed IBAN insertion field font

locales/en/index.yml, locales/it/index.yml
During Checkout, copy about PSP is now more user friendly
=> feat: [#176225664] PSP copy change

ts/features/bonus/bpd/screens/details/components/bottomsheet/WhyOtherCards.tsx
=> [#176258786] Update WhyOtherCards.tsx

locales/en/index.yml, locales/it/index.yml, ts/features/wallet/component/NewMethodAddedNotifier.tsx
1. Fixed title in "Does your card have one of these logos?
2. Fixed label variable
@CrisTofani please check if I got right fix no.2, and if so, I'd like a new "geek" badge 🥇 🤣
=> chore(Bonus Pagamenti Digitali): [#176185198] Co-badge banner title update

ts/features/bonus/bpd/components/paymentMethodActivationToggle/bottomsheet/BpdNotActivableInformation.tsx
This pr fixes graphical glitches on `BpdNotActivableInformation`.
=> fix(Bonus Pagamenti Digitali): [#176291435] Glitch on BpdNotActivableInformation

ts/features/bonus/bpd/components/BpdLastUpdateComponent.tsx
This pr temporary disables the bpd data refresh from the `BpdDetailsScreen`
- Temporary remove `UpdateLabel` from `BpdLastUpdateComponent`
=> feat(Bonus Pagamenti Digitali): [#176307536] Disable update from BpdDetails

ts/utils/paymentMethod.ts
This pr changes the `description` and `numberObfuscated` for `BPayPaymentMethod`.
Description: 
1) Try to find the description in the `Abi` list
2) Use the `bankName`
3) Use `BANCOMAT Pay`
numberObfuscated:
Replace * with ●
=> feat(Bonus Pagamenti Digitali): [#176401375] Update BPay description and numberObfuscated

ts/features/wallet/onboarding/bancomatPay/screens/add-account/AddBPayScreen.tsx
This pr adds BPay raw information for test purpose
=> feat(Bonus Pagamenti Digitali): [#176413063] Display raw information when adding BPay account

locales/en/index.yml, locales/it/index.yml
Now the text encourages you to keep collecting transactions for the SuperCashback leaderboard
=> chore(Bonus Pagamenti Digitali): [#175797909] 150€ Milestone copy update

locales/en/index.yml, locales/it/index.yml, ts/components/messages/MedicalPrescriptionDueDateBar.tsx
Changed "pagamento scaduto" to "avviso scaduto" in overdue payments banners shown in messages
=> Copy update

.env.example, .env.local, .env.production, scripts/changelog/ts/changelog.ts, ts/config.ts
The purpose of this PR is to add the beginning configuration of CGN feature flag and pivotal stories track to `changelog.ts`
=> feat(Carta Giovani Nazionale): [#176442968] Adds CGN Feature Flag

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/bpd/components/BaseDailyTransactionHeader.tsx, ts/features/bonus/bpd/components/BpdTransactionSummaryComponent.tsx, ts/features/bonus/bpd/components/superCashbackRanking/RankPositionItem.tsx, ts/features/bonus/bpd/components/superCashbackRanking/SuperCashbackRanking.tsx, ts/features/bonus/bpd/screens/details/components/summary/TransactionsGraphicalSummary.tsx, ts/features/bonus/bpd/screens/details/components/summary/textualSummary/ClosedTextualSummary.tsx, ts/i18n.ts, ts/screens/profile/LanguagesPreferencesScreen.tsx
This pr adds the integer formatting for the transactions number and ranking.
=> fix(Bonus Pagamenti Digitali): [#176516558] Missing integer formatting for transactions number & ranking

locales/en/index.yml, locales/it/index.yml
Copy has been fixed because the message should not specifically refer to payments.
=> fix: [#176680694] Notice banner fix

package.json
This PR updates the CGN specs url to the master branch of IO Backend
=> fix(Carta Giovani Nazionale): [#176905852] Updated CGN spec url to master branch of IO Backend repository

ts/features/bonus/cgn/saga/networking/activation/getBonusActivationSaga.ts, ts/features/bonus/cgn/store/actions/activation.ts, ts/features/bonus/cgn/store/reducers/activation.ts
This PR fixes the API Specifications for CGN after the renaming of some types and attributes
=> fix(Carta Giovani Nazionale): [#176963464] Fixes the API specifications for CGN after type and attributes renaming

locales/en/index.yml, locales/it/index.yml, ts/features/wallet/onboarding/cobadge/screens/add-account/AddCobadgeComponent.tsx
This pr updates the copy for `AddCobadgeComponent`
- Changes the `warning` rendering in `AddCobadgeComponent`
- Add a cobadge card.
=> chore(Bonus Pagamenti Digitali): [#177015049] Update copy for add cobadge screen disclaimer

locales/en/index.yml, locales/it/index.yml, ts/screens/wallet/payment/PickPspScreen.tsx
- removed pickPsp info label
- small fixes
=> chore: [#177044503] No PSP assigned page - copy fix

.env.example, .env.local, .env.production, ts/config.ts
This pr adds the privative feature flag
=> chore(Bonus Pagamenti Digitali): [#177140858] Add privative feature flag

ts/components/wallet/card/Logo.tsx
This PR fixes a bad import that was not-aligned with the used specs for code generation
ref https://github.com/pagopa/io-services-metadata/pull/260/files
=> Fix bad import 

.env.production
This reverts commit a735ac869d10edc34d915d89c94ed09b2e050927.
=> feat(Bonus Pagamenti Digitali): [#177339683] Revert change test config

.env.example, .env.local, .env.production, ts/config.ts, ts/navigation/WalletNavigator.ts, ts/sagas/wallet.ts, ts/screens/wallet/AddPaymentMethodScreen.tsx
This pr removes the privative feature flag from the codebase.
=> chore(Bonus Pagamenti Digitali): [#177140866] Remove privative feature flag

ts/features/wallet/onboarding/privative/screens/choosePrivativeIssuer/ko/PrivativeIssuerKoDisabled.tsx
This pr changes the style of the `close` button in the `PrivativeIssuerKoDisabledScreen`
=> feat(Bonus Pagamenti Digitali): [#177338693] Changed style for close button in PrivativeIssuerKoDisabled

.env.production
This PR enables the 2 FF about CGN for the beta release of the app
=> feat(Carta Giovani Nazionale): [#177479621] Enables CGN Feature Flags

.env.production
=> feat(Carta Giovani Nazionale): [#177479621] Disables CGN Feature Flags

locales/en/index.yml, locales/it/index.yml
This PR slightly improves the instructional text when users add their supermarket card
=> feat(Bonus Pagamenti Digitali): [#177510097] Copy fix

scripts/check_urls/check_urls.py, ts/store/reducers/entities/organizations/index.ts
- add `PayWebViewModal.tsx` in the blacklist (it'll never be analyzed)
- remove broken link to pivotal (404)
=> chore: [#177506546] Remove false positive from urls check

ts/components/screens/SectionHeaderComponent.tsx, ts/components/services/ServiceList.tsx, ts/components/services/ServicesSectionsList.tsx
This PR moves the organization logo from left to right side of list item
| before  | before - long press |
| after  | after - long press |
=> chore: [#177288211] Move organization logo to the right side

package.json, yarn.lock
This reverts commit 78597708d61a76ccdbc3dbe9fc8daaa1d6193818 and pr #2948
=> chore: [#177560562] Revert Close NFC dialog when card is successfully read 

ts/screens/wallet/WalletHomeScreen.tsx
Removal of the dynamic header that appears when you scroll down in the wallet section.
**BEFORE:** 
**AFTER:**
=> feat: [#177386218] Remove transaction dynamic header on wallet screen

locales/en/index.yml, locales/it/index.yml
This PR updates the text showing the support working hours
=> fix: [#177775588] Customer care working hours update

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/cgn/components/detail/eyca/EycaInformationComponent.tsx, ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx, ts/features/bonus/cgn/components/otp/OtpCodeComponent.tsx, ts/features/bonus/cgn/components/otp/OtpNotWorking.tsx, ts/features/bonus/cgn/screens/CgnOtpScreen.tsx
This PR fixes some minor component visualization errors on CGN screens and bottomsheets.
=> fix(Carta Giovani Nazionale): [#177777595] Accessibility improvements on CGN screens and bottomsheets

ts/sagas/index.ts
This PR  removes obsolete link and comment
=> chore: Remove obsolete link and comment

.env.production
This PR loads the staging url for local services. It is intended only for test purposes
=> chore: Activate local services - staging url

.env.production
=> chore: Revert #3022

scripts/ts/danger/utils/changelog.ts
This pr adds the project ID `IAC` https://pagopa.atlassian.net/secure/RapidBoard.jspa?rapidView=82&projectKey=IAC to the `Bonus Pagamenti Digitali` scope.
=> chore(Bonus Pagamenti Digitali): [IAC-62] Add changelog scope for cashback jira project

scripts/ts/danger/utils/changelog.ts
This PR add the SiciliaVola id to the function that update the PR titles.
=> chore(Sicilia Vola): [IASV-1] Add Sicilia Vola Id for title generation and changelog

locales/en/index.yml, locales/it/index.yml
This PR improves the text of the disclaimer shown in case of a write-off (storno)
=> chore(Bonus Pagamenti Digitali): [IAC-70] Write-off copy update

ts/features/wallet/onboarding/satispay/screens/StartSatispaySearchScreen.tsx, ts/sagas/wallet.ts
This PR removes broken static urls from the alert message
=> chore: [#178297319] Fixes broken urls

scripts/ts/danger/utils/changelog.ts
This pr adds the "Green Pass" as changelog scope.
=> chore(Green Pass): [IAGP-1] Add "Green Pass" to changelog scope

locales/en/index.yml, locales/it/index.yml
This PR fixes copy of write-off disclaimer
=> chore(Bonus Pagamenti Digitali): [IAC-70] Copy fix

package.json, ts/features/euCovidCert/saga/networking/__tests__/handleGetEuCovidCertificate.test.ts, ts/features/euCovidCert/saga/networking/handleGetEuCovidCertificate.ts, ts/features/euCovidCert/types/EUCovidCertificate.ts
This pr updates the APi specs and adds the "expired" EU certificate state.
=> chore(EU Covid Certificate): [IAGP-44] Update api specs and add the "expired" state

package.json
This pr updates the `io_eu_covid_cert`specs.
=> Update EU covid api specification

.env.local, .env.production
This pr enables the euCovidCert feature flag, activating the functionality in the app.
=> chore(EU Covid Certificate): [IAGP-50] Enable EuCovidCert feature flag

ts/store/middlewares/analytics.ts
This pr adds the tracking for the eu covid certificate message.
=> chore(EU Covid Certificate): [IAGP-51] Track eucovidcert message

locales/en/index.yml, locales/it/index.yml
This PR improves UX copy of DGC
=> chore(EU Covid Certificate): [IAGP-52] Copy check

locales/en/index.yml, locales/it/index.yml, ts/features/euCovidCert/screens/valid/EuCovidCertMarkdownDetailsScreen.tsx, ts/features/euCovidCert/screens/valid/EuCovidCertValidScreen.tsx
This pr adds some minor graphical refinements.
=> chore(EU Covid Certificate): [IAGP-53] Graphical refinements

.env.local, .env.production, ts/config.ts
This PR adds the SiciliaVolta certificate feature flag.
- Add `svEnabled`
=> chore(Sicilia Vola): [IASV-3] Add SiciliaVola feature flag

README.md
An update of the README based on my recent experience with the onboarding process.
**How far did I go?** I stopped short of _Internationalization_ because I want to keep this update small and moreover I do have some opinions on how to split the docs into separate files. More on that later ⌛ 
- The largest update affects the _Pre-requisites_ section, where I removed the instructions for _nodenv_ and _rbenv_ in favour of a more concise reference to the tools' official website.
- Smaller updates across the file are related to missing/extra spaces, misstyped official names, missing links, extra markup.
- I'm afraid I also added a few line breaks to fit the text in my editor before turning line-wrap on. Please let me know if this is something I should revert.
n/a
=> chore: [IA-18] Update README

ts/features/bonus/bpd/analytics/index.ts
This PR reviews the flow of two events: BPD_TRANSACTIONS_SUCCESS and BPD_PAYMENT_METHOD_ACTIVATION_SUCCESS
=> Review events for Cashback

android/app/build.gradle
This PR removes an useless Android implementation since it is never used in any part of the code
=> Remove useless implementation

ts/features/euCovidCert/screens/BaseEuCovidCertificateLayout.tsx, ts/features/euCovidCert/screens/valid/EuCovidCertMarkdownDetailsScreen.tsx, ts/features/euCovidCert/screens/valid/EuCovidCertQrCodeFullScreen.tsx
This pr adds shouldAskForScreenshotWithInitialValue for missing screens.
=> chore(EU Covid Certificate): [IAGP-61] Add shouldAskForScreenshotWithInitialValue

locales/en/index.yml, locales/it/index.yml
This PR updates copy for Profile > Privacy as requested by @CaraDune
=> chore: [IA-34] New copy

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/bpd/components/superCashbackRanking/SuperCashbackRanking.tsx
This PR updates the text within the Supercashback bottom sheet.
=> chore(Bonus Pagamenti Digitali): [IAC-80] Supercashback copy update

ts/mixpanel.ts
This PR calls mixpanel SDK API opt-in on setup and opt-out on terminate
=> [IA-45] Add opt-in / opt-out on setup and terminate

locales/en/index.yml, locales/it/index.yml
This PR updates locales with new copy
=> chore: [IA-36] Copy update

scripts/ts/danger/utils/changelog.ts
This PR introduces the Redesign Servizi label to changelog scopes
=> chore(Redesign Servizi): [IARS-3] Adds Redesign Servizi to Changelog scopes

locales/en/index.yml, locales/it/index.yml
=> chore: [IA-39] Copy update

locales/en/index.yml, locales/it/index.yml, ts/components/wallet/PayWebViewModal.tsx, ts/components/wallet/__test__/PayWebViewModal.test.tsx, ts/screens/wallet/ConfirmCardDetailsScreen.tsx, ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
Remove the title and update the description.
- Move the title from the screen content to the header
- Replace the description with an infobox
- to be able to observe the message, please set [the timeout in the dev server](https://github.com/pagopa/io-dev-api-server/blob/master/src/routers/payment.ts#L154) to something longer than 1s
- navigate under _Wallet_
- add a new card
- click on _save_
- see the new message in the webview
=> chore: [IA-69] Remove title, update description and tests

ts/sagas/startup/__tests__/checkAcceptedTosSaga.test.ts, ts/sagas/startup/checkAcceptedTosSaga.ts
This PR fixes a bug regarding the profile update while the user is accepting the Term of Service
=> fix: [IA-106] Profile is not updated

locales/en/index.yml, locales/it/index.yml
This PR fixes some typos + minor changes
=> chore: [IRS-66] Locales update

ts/components/messages/MessagesInbox.tsx
This PR fixes a bug reported here https://github.com/pagopa/io-app/issues/3209
=> fix: [IA-120] Info message is not right localized

ts/sagas/profile.ts, ts/sagas/startup/__tests__/checkProfileEnabledSaga.test.ts, ts/sagas/wallet.ts, ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx, ts/screens/profile/EmailForwardingScreen.tsx, ts/screens/profile/ServicesPreferenceScreen.tsx, ts/store/actions/profile.ts, ts/store/reducers/profile.ts
This PR introduces the saga to handle all the events of the profile upsert completed successfully
=> chore(Redesign Servizi): [IARS-34] Implements saga to handle profile preference upsert success action

ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx, ts/components/services/ContactPreferencesToggles/index.tsx, ts/screens/messages/MessageDetailScreen.tsx, ts/screens/services/ServiceDetailsScreen.tsx, ts/screens/services/ServicesHomeScreen.tsx
This PR fixes the not updated selected service ID when navigating from message detail to service detail
=> fix(Redesign Servizi): [IARS-39] Fix services not selected from message detail screen

locales/de/index.yml, locales/en/index.yml, locales/it/index.yml, scripts/make-locales.ts, ts/boot/configureInstabug.ts, ts/components/RegionServiceWebView.tsx, ts/features/bonus/bonusVacanze/components/AvailableBonusItem.tsx, ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx, ts/features/bonus/common/components/BonusInformationComponent.tsx, ts/features/wallet/component/card/FeaturedCardCarousel.tsx, ts/i18n.ts, ts/store/reducers/content.ts, ts/types/MessageCTA.ts, ts/utils/__tests__/content.test.ts, ts/utils/__tests__/locale.test.ts, ts/utils/__tests__/messages.test.ts, ts/utils/dates.ts, ts/utils/locale.ts, ts/utils/messages.ts
=> Revert "feat: [#174730105,IA-96] Add support to german language"

locales/en/index.yml, locales/it/index.yml
This PR changes the notification content when users never performed their first login. It's a more explicit text conveying the idea login is required to start using the app properly.
=> chore: [IA-141] Change notification text

ts/screens/authentication/IdpLoginScreen.tsx
This PR logs the SPID login webview errors by sending these informations
- idp
- code
- description
- domain
=> chore: [IA-150] Trace SPID login errors

locales/de/index.yml
This PR add the translation of the Green Pass strings for the German language
- Added the strings provided by Alto Adige Riscossioni (💙)
Generate the locales with `yarn generate:locales` and change the language in the Profile section.
The green pass messages sended by the dev-server has the added strings
=> chore: [IA-121] Green Pass de translation

ts/sagas/startup/watchLoadMessagesSaga.ts, ts/screens/wallet/AddCardScreen.tsx, ts/store/actions/analytics.ts, ts/store/actions/messages.ts, ts/store/actions/wallet/payment.ts, ts/store/actions/wallet/wallets.ts, ts/store/middlewares/analytics.ts
This PR removes obsolete events and updates other ones
=> chore: [IA-153] Events cleanup

locales/de/index.yml
This PR adds new strings in German language, as provided by friends from Südtiroler Einzugsdienste
=> chore: [IA-155] Update index.yml

locales/de/index.yml, locales/it/index.yml
- New German translations by Alto Adige
- fix cta in italian
=> chore: [IA-169] Copy update

locales/it/index.yml
Use gender neutral questions in Italian locale
=> chore: gender neutral questions in Italian locale

locales/de/index.yml
Improved the German translation file and standardized some expressions.
=> improve German translation

ts/store/middlewares/analytics.ts
This PR add to analytics the event fired when the user press on message search feature
=> chore: [IA-179] Track message search enabling

locales/de/index.yml
This PR adds a new string as suggested by a user
=> chore: [IA-184] New German string

ts/screens/authentication/IdpLoginScreen.tsx
This PR adds the tracking of the intent if it is processed by the webview that hosts the login
=> chore: [IA-188] Track SPID IDP Intent

ts/store/middlewares/analytics.ts
This PR adds the profileLoadRequest action type to analytics
=> fix: [IA-163] Add profileLoadRequest for analytics

package.json
=> Fix cgn specs

locales/en/index.yml, locales/it/index.yml, ts/components/ScreenHeader.tsx, ts/screens/services/ServicesHomeScreen.tsx
This PR fixes the accessibility on services home header. Now button and title are read by each element.
=> fix: [IABT-1233] Fixes accessibility on services home screen

ios/Podfile.lock, locales/en/index.yml, locales/it/index.yml, ts/components/wallet/card/SectionCardComponent.tsx, ts/features/bonus/bonusVacanze/components/RequestBonus.tsx, ts/screens/wallet/WalletHomeScreen.tsx
This PR introduces an accessibility improvement on the SectionCardComponent to handle properly payment method refresh and bonuses refresh
=> chore: [IA-51] Fixes accessibility for sectionCardComponent

locales/de/index.yml, locales/en/index.yml, locales/it/index.yml
This PR slightly improves an error message when the scanned QR code is not valid (e.g.: wrong printout, wrong setup by Payee).
=> chore: [IA-194] Copy update

locales/en/profile/profile_appinfo_main.md, locales/it/profile/profile_appinfo_main.md, publiccode.yml
Substitution of old website with the new one www.pagopa.it
- changed url in profile info
- changed url in publicode yml
=> chore: [IA-196] PagoPA corporate new website url

locales/de/index.yml, locales/en/index.yml, locales/it/index.yml
This pr updates the copy for the deletion of a method.
https://user-images.githubusercontent.com/26501317/131304197-6e47604a-e026-4f93-a6d6-9ac29741b138.mov
=> chore: [IA-189] Update delete methods copy

.circleci/config.yml
This pr updates the circleCI images, replacing the legacy ones.
https://circleci.com/developer/images/image/cimg/node
=> chore: [IAI-45] Update circleci images

.github/workflows/stale.yml
This pr fixes a typo in the stale workflow message.
=> fix: Wrong days in stale workflow message

android/app/build.gradle
This pr fixes a crash that can occurs on some devices due to different okttp3 versions.
- force to version `3.12.12`
=> fix: [IA-221] Java.lang.NoSuchMethodError for okhttp3

.circleci/config.yml
This pr fixes the CircleCI job `io_check_uris` in order to avoid the continuous fail on execution.
=> fix: [IAI-50] Check url fails on CircleCI

ts/sagas/contentLoaders.ts, ts/store/reducers/entities/payments.ts
- Removed the not working url
- Replace the pivotal story with the JIRA equivalent
=> fix: pivotal url is not longer available

ts/screens/wallet/PaymentHistoryDetailsScreen.tsx, ts/screens/wallet/creditCardOnboardingAttempts/CreditCardOnboardingAttemptDetailScreen.tsx, ts/utils/payment.ts, ts/utils/profile.ts
This PR removes some code from payment and cc onboarding flow
=> chore: [IA-230] Review payment and cc onboarding flow

ts/components/ContextualHelp/index.tsx, ts/mixpanel.ts, ts/screens/profile/ProfileMainScreen.tsx, ts/utils/device.ts
This PR removes the inclusion of device ID in the assistance request.
Note that it is included only when **the user accepts** to share his/her personal CF
=> chore: [IA-232] Remove deviceId within the assistance request

locales/en/index.yml, locales/it/index.yml
=> chore: [IA-231] Copy update 

README.md
This PR updates the definitions' table for android permissions on repo's readme file
=> chore: [IA-236] Update permissions specification on Readme file

publiccode.yml
This pr fixes a typo in publiccode.yml
=> fix: typo in publiccode.yml

.env.local, .env.production, ts/config.ts, ts/features/wallet/component/features/PagoPaPaymentCapability.tsx, ts/features/wallet/creditCard/screen/__tests__/CreditCardDetailScreen.test.tsx
This pr removes the `pmActivatePaymentEnabled` feature flag and `PM_ACTIVATE_PAYMENT_ENABLED` .env config since the development is finished.
=> chore: [IA-239] Remove payment toggle feature flag

locales/en/index.yml, locales/it/index.yml, ts/screens/modal/IdentificationModal.tsx
This PR handles the lock by device on Biometric authentication in case users exceeds the number of attempts allowed by device OS
Manage to fail Biometric Authentication too many time.
https://user-images.githubusercontent.com/3959405/133292689-f2d28a39-c368-4ddd-b402-c11ee8bffabb.mov
=> chore: [IA-220] Hides the biometric button if device biometry response is currently blocked

ts/sagas/profile.ts
This PR replaces the usage of `readableReport` with the more safe `readablePrivacyReport`
=> chore: Add readablePrivacyReport in profile API requests

ts/sagas/testLoginSaga.ts, ts/screens/authentication/IdpLoginScreen.tsx, ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx, ts/store/actions/authentication.ts, ts/store/middlewares/analytics.ts
This PR adds the `idp` field to the `LOGIN_FAILURE` event
=> feat: [IA-248] Enhance LOGIN_FAILURE event

.circleci/config.yml
This pr fixes the e2e execution.
=> fix: [IAI-56] Fix: E2E tests fail to run

.env.local, .env.production
This PR updates the new BPD API endpoints
=> chore(Bonus Pagamenti Digitali): [IAC-114] Update BPD API endpoints

scripts/ts/notifyNewAppVersion/notifyNewAppVersion.ts
This pr changes the new released app version format for the release message, in order to be in the same format displayed in app.
This pr also adds the team tag @devioapp in order to be notified for reply in the message topic.
=> chore: [IAI-72] Change app version format for release message

assets/paymentManager/README.MD, assets/paymentManager/spec.json, package.json
This PR is one of three and it aims to move the Payment Manager API spec file from `io-services-metadata` to `io-app` repository
If you review and approve this PR, after that you should review also these two (with no specific order)
- ➖  https://github.com/pagopa/io-services-metadata/pull/511
- ✏️  https://github.com/pagopa/io-dev-api-server/pull/86 (re-run the CI to remove the error)
=> chore: [IA-411] Add PaymentManager API spec file

scripts/ts/danger/utils/changelog.ts
This PR add the Zendesk id (ASZ) to the function that update the PR titles.
=> chore(Zendesk): [ASZ-115] Add Zendesk Id for title generation and changelog 

android/build.gradle, ios/ItaliaApp.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, yarn.lock
This PR add the [io-react-native-zendesk](https://github.com/pagopa/io-react-native-zendesk) package. 
- Added `io-react-native-zendesk` using as a reference the tag 0.3.0 of the forked library.
=> chore(Zendesk): [ASZ-104] Add zendesk package

ts/features/wallet/onboarding/paypal/screen/__mocks__/psp.ts, ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalPpsSelectionScreen.test.tsx
Move mocks where Jest expects them.
Tests are now passing.
=> Fix misplaced mocks

locales/en/index.yml, locales/it/index.yml
This PR updates some copy to reflect how the feature works
=> chore: [IA-464] Copy improvement

ts/screens/profile/ProfileMainScreen.tsx
This PR restores the device ID item in the dev section
=> chore: [IA-313] Restore DeviceID item in the dev section

ts/components/screens/SectionHeaderComponent.tsx, ts/components/services/NewServiceListItem.tsx, ts/components/services/ServiceList.tsx
- Added the AccessibilityRole "header" to the service owner
- Added the AccessibilityRole "link" to the services
To test these changes you should enable a screen reader on your device (Voice Over on IOS and TalkBack on Android) and navigate on the national services list.
=> feat: [IA-341] & [IA-342] Improved the accessibility of national services list

locales/it/index.yml
This Pull Request fixes a small typo in a string related with BANCOMAT Pay.
=> chore: [IA-413] Typo fix

ts/boot/configureInstabug.ts
This PR disables the crash reporting
=> fix: [IA-485] Disable crash reporting

scripts/ts/danger/utils/changelog.ts
This pr adds the new scope "Messaggi a valore legale".
=> chore(Messaggi a valore legale): [IAMVL-15] Add new scope "Messaggi a valore legale" to changelog and GitHub tag

.circleci/config.yml, .env.production
This PR enable the zendeskEnabled ff and comment temporarily the CircleCi Android release workflow
=> chore: [IA-539] Enable FF for testing purpose

ts/store/reducers/__mock__/backendStatus.ts
This PR align the mock to the new [definition](https://github.com/pagopa/io-services-metadata/pull/525) of the zendesk FF.
run `yarn tsc --noemit`
=> chore: [IA-549] Align mock backendStatus

locales/de/index.yml, locales/en/index.yml, locales/it/index.yml, scripts/check_urls/check_urls.py, ts/screens/authentication/cie/CiePinScreen.tsx
This PR update the `check_url` script setup and remove some not working urls
[see here](https://pagopaspa.slack.com/archives/C029VR4LMNK/p1638846193000800) for more details
=> chore: Update check_url script config

.circleci/config.yml, .env.production
This PR turn on the feature flag of Paypal
=> chore: set Paypal feature flag ON 

.circleci/config.yml, .env.production
This PR turns off the feature flag of Paypal
=> chore: set Paypal feature flag OFF 

ts/screens/wallet/TransactionDetailsScreen.tsx
This PR improves the accessibility on Transaction full reason link, to include the state of accordion and consider the link as a button and not a real link
=> feat: [IA-404] Improves accessibility on transaction full reason link

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/values/styles.xml
This PR updates the Android Zendesk SDK colors align them to the IOS version.
- Added `ZendeskTheme` style section in `android/app/src/main/res/values/styles.xml`
- Added activities in `android/app/src/main/AndroidManifest.xml`
Open a request and the list of the already opened tickets in Android.
=> feat: [IA-514,IA-519] Update android color

.env.local, .env.production
This PR enable the local FF both in the local and in the prod env config.
=> chore: [IA-590] Enable Zendesk local feature flag

.circleci/config.yml
This PR disable temporary the Android release.
=> disable android release

locales/it/index.yml
=> chore: [IA-591] Copy changes CGN

.circleci/config.yml
This PR reverts commit a2609dfb9edb1769d58d2b0f4fa00eb9730e9d52.
=> Revert "chore: Disable android release (#3606)"

package.json
This PR fixes the mislinked api specification for discounts and operators
=> chore(Carta Giovani Nazionale): [IOACGN-11] Fixes API specs

ts/utils/__tests__/fetch.test.ts
Disable a flaky test
Strictly related to https://github.com/pagopa/io-app/pull/3592
=> Disable flaky test

.circleci/config.yml
This pr adds the explicit code generation for the dev-server in the e2e job.
=> chore: [IAI-103] Explicit code generation for dev-server on e2e job

ts/navigation/NavigationService.ts, ts/utils/navigation.ts
This pr fixes a bug that causes a crash when the tos version is increased
- https://github.com/pagopa/io-app/blob/2cf419a089e3f931fb47b7ab330142811019ab07/ts/config.ts#L92 -> increase the tos version
- Execute the app
=> fix: [IA-609] Increasing the tos version causes an app crash 

.circleci/config.yml
This pr restores the iOS build & notify new app on CI.
=> chore: Restore iOS release & notify new app on CI

ts/features/bonus/cgn/saga/index.ts, ts/features/bonus/cgn/saga/networking/bucket/index.ts, ts/features/bonus/cgn/store/actions/bucket.ts, ts/features/bonus/cgn/store/actions/index.ts, ts/features/bonus/cgn/store/reducers/bucket.ts, ts/features/bonus/cgn/store/reducers/index.ts
This PR introduces the first implementation of action and reducer for the consuption of a discount code from a Bucket for CGN Merchants.
No UI Component or API definition is still available, to test the correct behaviour just dispatch from anywhere `cgnCodeFromBucket.request` action.
=> chore(Carta Giovani Nazionale): [IOACGN-13] Implements action/reducer/saga for code from bucket consuption

ts/boot/configurePushNotification.ts
This PR will report the `NOTIFICATION_PARSING_FAILURE` event via Mixpanel when a push notification with an invalid `message_id` field is received.
- Add a new event as discussed and approved in [IA-573](https://pagopa.atlassian.net/browse/IA-573)
- Sanitize the payload using `readablePrivacyReport()`
- We only check against the decoder: a `message_id` for a non-existing message is not considered an error as of today
1. comment the [early return](https://github.com/pagopa/io-app/blob/master/ts/boot/configurePushNotification.ts#L70)
2. install and run the app
3. give push notifications permissions
4. get the UUID of your emulator
5. send an invalid notification via 
```bash
$ printf '{
"aps": {
"alert": "message_id is -1",
"sound": "default",
"badge": 1
},
"message_id": -1
}' | xcrun simctl …
```
=> chore: [IA-574] Track error with `message_id` in push notification

ts/features/bonus/cgn/components/merchants/__test__/CgnDiscountDetail.test.tsx, ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap, ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx, ts/features/bonus/cgn/components/merchants/discount/CgnDiscountCodeComponent.tsx
This PR implements the component to display a code from the bucket list of codes on a CGN discount.
https://user-images.githubusercontent.com/3959405/148924523-c2f0b85f-a632-4a0e-9e03-4f58e6e92902.mp4
=> chore(Carta Giovani Nazionale): [IOACGN-14] Implements component to display a code from a bucket for 

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx, ts/features/bonus/cgn/saga/networking/bucket/index.ts, ts/features/bonus/cgn/store/actions/bucket.ts, ts/features/bonus/cgn/store/reducers/bucket.ts, ts/features/bonus/cgn/types/DiscountBucketCodeResponse.ts
This PR implements a proper error handling for CGN bucket code visualization
=> chore(Carta Giovani Nazionale): [IOACGN-21] Implements error handling on bucket code visualization

locales/en/index.yml, locales/it/index.yml
This PR updates revoked body text
- use the dev server and put on the config flag `withEUCovidCert`
=> feat(EU Covid Certificate): [IAGP-69] Update revoked body text

ts/features/bonus/cgn/api/backendCgnMerchants.ts, ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
This PR updates CGN merchants API's base path
A minor fix on merchants list has been added in case one of the lists returns an error
=> chore(Carta Giovani Nazionale): [IOACGN-26] Updates CGN merchants API path

locales/en/index.yml, locales/it/index.yml
Deleted a sentence referring to the Cashback programme in the "add debit/credit card process"
=> fix: [IA-621] Bottom sheet copy changes

ts/features/bonus/cgn/analytics/index.ts
Adds missing CNG Actions to app analytics.
=> chore(Carta Giovani Nazionale): [IOACGN-18] Integrate tracking for missing CGN Actions

locales/en/index.yml, locales/it/index.yml, ts/screens/profile/components/ShareDataComponent.tsx
This PR changes a copy text and the link behavior in `profile/privacy/share your data` screen
https://user-images.githubusercontent.com/822471/149532424-0693f464-be8d-4426-b42b-f850fddec6d9.mov
https://user-images.githubusercontent.com/822471/149532477-ca3d332e-b0ab-458a-b6a8-6a1ee8de4f16.mov
=> chore: [IA-493] Update privacy/share data copy and link

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap, ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
This PR fixes UI Components and behaviour on CGN error cases for bucket code retrieve
https://user-images.githubusercontent.com/3959405/149755831-719ac932-2b5b-4371-be1e-cbfcf7c99d53.mp4
=> chore(Carta Giovani Nazionale): [IOACGN-24] Implements UI component for CGN Buckets errors

TESTING_E2E.md
This pr updates the TESTING_E2E.md
=> docs: Update TESTING_E2E.md

ts/store/reducers/backendStatus.ts
This PR restores previous remote CGN FF
=> chore(Carta Giovani Nazionale): [IOACGN-31] Re-enables CGN remote FF

scripts/check_urls/check_urls.py
This PR adds a false positive url to the black list
=> chore: Update check-urls

ts/store/reducers/backendStatus.ts
This PR disables the remote CGN Feature flag for the next production app release
=> chore(Carta Giovani Nazionale): [IOACGN-36] Temporary ignore CGN FF for production release

ts/screens/modal/UpdateAppModal.tsx
This pr adds the missing accessibilityRole `button` in `UpdateAppModal`
=> fix: [IA-660] Missing button accessibility role in UpdateAppModal

ts/store/reducers/backendStatus.ts
This PR restores remote CGN Feature Flag selector
=> [IOACGN-36] Reverts Temporary ignore CGN FF for production release

ts/mixpanel.ts, ts/utils/device.ts
This PR adds a mixpanel super property to know if the running device has at least one screen lock set
=> chore: [IA-657] Track screen lock availability

.circleci/config.yml, .env.production
A per [today's announcement](https://pagopaspa.slack.com/archives/C013V764P9U/p1645606561665109)
- Disable Android release
- Enable MVL and pagination
> We test in production
That guy you like.
=> Enable MVL, disable Android

.circleci/config.yml, .env.production
=> Revert "Enable MVL, disable Android"

locales/en/bonus/bpd/optInPaymentMethods.md, locales/it/bonus/bpd/optInPaymentMethods.md
- added a sentence that was missing 
- amended a sentence in agreement with the legal dept (after July 31st the data is kept by Consap and not by PagoPA
=> chore: [IA-677] Copy changes after a final check with the legal dept 

ios/Podfile.lock
This pr update the Podfile.lock
=> chore: Sync Podfile.lock

ts/features/uaDonations/components/__test__/UaDonationsBanner.test.tsx
This pr improves the readability of the `UaDonationsBanner.test.tsx`
=> chore: [IA-710] UaDonationsBanner test refactoring

.circleci/config.yml
This PR upgrades the xcode version from `12.5.1` to `13.3.0` in order to address this issue
=> chore: [IAI-177] Upgrade xcode version in circleCI config

.env.production
Enable pagination to test internally via beta.
=> chore: [IA-766] Enable pagination

locales/en/index.yml, locales/it/index.yml
Editing texts for migration messages.
=> chore: [IA-765] Migration messages: copy update

ts/api/backend.ts, ts/sagas/messages/__tests__/watchLoadNextPageMessages.test.ts, ts/sagas/messages/__tests__/watchLoadPreviousPageMessages.test.ts, ts/sagas/messages/__tests__/watchReloadAllMessages.test.ts, ts/sagas/messages/watchLoadNextPageMessages.ts, ts/sagas/messages/watchLoadPreviousPageMessages.ts, ts/sagas/messages/watchReloadAllMessages.ts
Rename `get_archived` to `archived` in the API call.
=> chore: [IA-774] Rename query parameter

ts/store/middlewares/analytics.ts
Track the migration events (start, success, failure).
An example of the events is reported [here](https://eu.mixpanel.com/project/2460815/view/3003771/app/insights#report/28984148/migration-errors).
=> chore: [IA-754] Track migration events

.env.local, .env.production
Enable FF for release candidate.
=> chore: [IA-799] Enable pagination

.env.local, .env.production, scripts/ts/danger/utils/changelog.ts, ts/config.ts
This PR adds the `carta della cultura` local feature flag
- Mapped the `carta della cultura` in the changelog
- Added the local feature flag `cdcEnabled`
-
=> chore(Carta della cultura): [AP-2] Add CDC local feature flag

locales/en/index.yml, locales/it/index.yml, ts/screens/onboarding/TosScreen.tsx
This PR removes the sticky header from the terms of service screen, following a design request.
| Old | New |
| - | - |
| ![157696163-45a6c0e7-6167-4d53-81f5-e1061f0987d5](https://user-images.githubusercontent.com/467098/162151706-85c9e712-a193-464c-a2c3-11a9a12ade23.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-04-07 at 10 04 46](https://user-images.githubusercontent.com/467098/162151726-9498afc0-16c1-42f3-b1d8-544a6de959e6.png) |
=> chore: [IA-740] Remove header from terms of service

locales/en/bonus/bpd/optInPaymentMethods.md, locales/it/bonus/bpd/optInPaymentMethods.md
Copy changes to update the text to the current context
=> chore: [IA-809] Copy changes

locales/it/jailbroken_body.md, locales/it/rooted_body.md, ts/screens/modal/RootedDeviceModal.tsx
A better wording for those two files.
However translations are needed for "de" and "en".
=> chore: [LB-348] Change italian root/jailbreak message

locales/en/index.yml
Optimized copy for the bonus "Carta della Cultura"
=> chore: Updated EN copy for Carta della Cultura

.circleci/config.yml, ios/ItaliaApp.xcodeproj/project.pbxproj
This PR is going to fix the E2E build with `react-native-vision-camera`.
- Updated the `project.pbxproj` file
The E2E tests ran on the CI in this commit: https://github.com/pagopa/io-app/pull/3950/commits/f272d086cb0f8ba30bd21e4deb94c12092654360
=> chore: [IAI-197] Fix E2E test build with `react-native-vision-camera`

ios/Podfile.lock
This PR syncs the podfile.lock to remove useless dependencies
=> chore: Sync podfile.lock to remove dependencies

.circleci/config.yml, patches/@gorhom+bottom-sheet+4.1.5.patch
This PR patches the bottomsheet library to solve the animation glitch when opening on iOS
=> fix: [IA-847] Fixes bottomsheet randomly glitching on present

locales/en/index.yml, locales/it/index.yml, ts/features/bonus/cdc/components/CdcRequestPartiallySuccess.tsx, ts/features/bonus/cdc/components/__test__/CdcRequestPartiallySuccess.test.ts
@debiff possiamo togliere anche la parte di contatta l'assistenza?
=> English copy for CDC reviewed

scripts/ts/danger/utils/changelog.ts
With this PR I wanna change the label that the danger bot automatically applies to PRs open from the IAMVL board.
=> chore(Piattaforma Notifiche): [IAMVL-80] Fix scope of IAMVL project in danger bot

.env.local, .env.production, ts/config.ts
This PR adds a new feature flag for the integration with PN.
=> feat(Piattaforma Notifiche): [IAMVL-76] Add the local feature flag for PN

ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx, ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
This PR fixes a major bug that won't show discount code component on CGN discounts detail
=> fix(Carta Giovani Nazionale): [IOACGN-75] Fixes discount code not showing on discount detail

.env.local, .env.production
This PR enables the feature flag for the new transaction summary screen.
=> chore: [IA-876] Enable the feature flag for the new transaction summary screen

publiccode.yml
=> chore: add awards to publiccode.yml

ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
This PR hides the CTA if the CGN status is not active
=> fix(Carta Giovani Nazionale): [IOACGN-82] Shows merchants CTA only for card Activated

ts/features/pn/store/types/types.ts
This PR adds a [missing value](https://raw.githubusercontent.com/pagopa/pn-delivery-push/19f21d11419bf7ed29b15cfd37e2533b1a833910/docs/openapi/schemas-pn-status-v1.yaml#/components/schemas/NotificationStatusHistory) to the `NotificationStatusEnum`.
=> chore(Piattaforma Notifiche): [IAMVL-93] Update type for parse third party data from PN

.env.production
This PR disables the PN feature flag for the next release. It will be rolled back for the next internal build.
=> chore(Piattaforma Notifiche): [IAMVL-96] Disable PN feature flag

ts/theme/variables.ts
This PR fixes a visual regression introduced with latest developments related to the new Design System.
- Restore `native-base` theme variable that disable uppercase buttons
=> fix: [IA-924] Disable uppercase buttons on Android

.env.production
This PR enables the PN local feature flag in production.
=> chore(Piattaforma Notifiche): [IAMVL-87] Enable PN in production

ts/features/messages/components/MessageAttachmentPreview.tsx, ts/features/mvl/screens/details/components/attachment/MvlAttachmentDownload.tsx, ts/features/pn/components/PnMessageDetails.tsx, ts/features/pn/components/PnMessageTimelineCTA.tsx, ts/features/pn/components/PnOpenConfirmationBottomSheet.tsx, ts/features/pn/components/PnServiceCTA.tsx, ts/features/pn/screens/PnAttachmentPreview.tsx, ts/sagas/messages/watchThirdPartyMessageSaga.ts, ts/screens/messages/paginated/MessageRouterScreen.tsx
This PR adds analytics for PN.
=> feat(Piattaforma Notifiche): [IAMVL-97] Track PN events to Mixpanel

.circleci/config.yml
This PR updates the Xcode 13 version used by CircleCI to the latest public release.
=> chore: [IAI-240] Update Xcode 13 to CircleCI

ts/components/BarcodeCamera.tsx
This PR adds the prominent disclosure for camera permission request on android
=> chore: [IA-944] Show prominent disclosure alert on camera permission request

ios/ItaliaApp.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, yarn.lock
This PR aims to upgrade react-native-vision-camera to the latest release in order to fix the build [issue](https://github.com/mrousavy/react-native-vision-camera/issues/1125)
=> chore: [IOAPPFD0-8] Upgrade `react-native-vision-camera` to fix the build time error in Android

package.json, ts/features/idpay/onboarding/api/client.ts, yarn.lock
Use the codegen to generate the types and the client from the IDPay Onboarding OpenAPI spec
Add a new generate script for the IDPay Onboarding api.
This PR depends on #4148.
=> chore(IDPay): [IDPAY-31] Generate IDPay onboarding types and client

scripts/ts/danger/utils/changelog.ts
Add IDPay changelog project scope
Add IDPay changelog project scope
=> Add IDPay changelog project scope

ts/features/idpay/onboarding/screens/InitiativeDetailScreen.tsx, ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts, ts/features/idpay/onboarding/xstate/machine.ts, ts/features/idpay/onboarding/xstate/services.ts
Add machine step to accept ToS
Add steps to the machine
Unit tests added
https://user-images.githubusercontent.com/15610456/200166690-0a8b0619-d356-4838-85ec-257ffa1c2eaa.mp4
=> feat(IDPay): [IODPAY-36] State machine accept ToS steps

ts/features/idpay/onboarding/screens/InitiativeDetailScreen.tsx, ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts, ts/features/idpay/onboarding/xstate/machine.ts, ts/features/idpay/onboarding/xstate/services.ts, ts/screens/profile/playgrounds/IDPayOnboardingPlayground.tsx
Add XState machine step to retrieve required criteria
Add machine stuff to manage required criteria fetching
Tests included for the new steps
https://user-images.githubusercontent.com/15610456/200291373-7d0b563e-dba9-4017-ab95-3630a6bd28a2.mp4
=> feat(IDPay): [IODPAY-38] Retrieve required criteria machine steps

ts/features/idpay/onboarding/screens/InitiativeDetailScreen.tsx, ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts, ts/features/idpay/onboarding/xstate/machine.ts, ts/features/idpay/onboarding/xstate/services.ts, ts/screens/profile/playgrounds/IDPayOnboardingPlayground.tsx
Add machine steps to give PDND and Self consent.
Add machine steps to conclude the onboarding.
=> feat(IDPay): [IODPAY-40] Add consent steps to machine

locales/en/bonus/bpd/optInPaymentMethods.md, locales/en/index.yml, locales/it/bonus/bpd/optInPaymentMethods.md, locales/it/index.yml, ts/features/bonus/bpd/components/optInStatus/BottomSheetMethodsToDelete.tsx, ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/__tests__/optInShouldShowChoiceHandler.test.ts, ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/optInShouldShowChoiceHandler.ts, ts/store/reducers/wallet/wallets.ts
This PR fixes some minor issues raised during the internal test of the flow.
- Filters the card by functionality and store visualization
- Changes in copy
=> feat: [IOAPPPEB-6] Filter mehods not in BPD or added by EXT channel

ts/features/idpay/onboarding/navigation/navigator.tsx, ts/features/idpay/onboarding/screens/CompletionScreen.tsx, ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts, ts/features/idpay/onboarding/xstate/actions.ts, ts/features/idpay/onboarding/xstate/machine.ts
Add machine steps and screen to complete onboarding
- Machine stuff to complete onboarding
- Tests for the new machine steps
- Completion screen to show last steps of the onboarding flow
https://user-images.githubusercontent.com/15610456/201307491-7b507895-b157-4a3c-af64-d4da9d7b46f6.mp4
=> feat(IDPay): [IODPAY-4] Onboarding completion steps

ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/__tests__/optInShouldShowChoiceHandler.test.ts, ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/optInShouldShowChoiceHandler.ts
This PR fixes the possibility to double request the API on status for BPD
=> feat: [IOAPPPEB-7] Fixes double API request

.env.production, ts/config.ts
This PR upgrades the TOS mionr version and enables opt-in for reminders and descriptive push notifications
=> chore: [IOAPPCOM-12] Enables the FF and updates required tos version

locales/en/index.yml, locales/it/index.yml
copy changes to the push notification examples
=> [IOAPPCOM-15] Modifiche copy agli esempi dinamici di push 

.env.production
=> chore: [IOAPPFD0-17] Change backend domain

ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
added spacing between items in PDNDPrerequisites page
-  spacer between PDNDPrerequisites items
=> feat(IDPay): [IODPAY-66] Added padding between items in PDNDPrerequisites page

package.json
This pr fixes the FCI specs.
- Updated `package.json`
=> fix(Firma con IO): Fix FCI specs

.env.production, ts/store/reducers/backendStatus.ts
This PR enabled `FCI` feature flag
=> chore(Firma con IO): Activate FCI feature flag

package.json, ts/features/idpay/initiative/configuration/api/client.ts
This PR adds the client and API definitions generation for IDPay IBAN endpoints
- Added API definitions generator script in `package.json`
- Added `createIDPayIbanClient` function in `ts/features/idpay/initiative/configuration/api/client.ts`
=> feat(IDPay): [IODPAY-71] Add client and API definition for IDPay IBAN endpoints

.env.production, ts/store/reducers/backendStatus.ts
This PR disable `Firma con IO` feature flag
=> chore(Firma con IO): [SFEQS-1255] Disable local feature flag

ts/utils/__tests__/convertDateToWordDistance.test.ts
Fix tests that do not take year change in consideration
- Use a mocked date for the test
Tests now are fixed
=> fix: [IOAPPFD0-19] Fix date format test on year change

ts/screens/profile/DownloadProfileDataScreen.tsx
This PR fixes the glitch caused by [HOC inside render method](https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method) moreover converts Class Component to Functional Component.
Specifically, adds a safe area and prevents unnecessary refresh of markdown.
| Before  | After  | 
| ------------- | ------------- | 
| <video src="https://user-images.githubusercontent.com/29163287/211524926-82708110-53c2-4393-a5af-9a1c962da1c7.mp4" />  | <video src="https://user-images.githubusercontent.com/29163287/211525171-ccd528fe-4917-4cdd-96df-9c4bc8922676.mp4" />  | 
- Updated `DownloadProfileDataScreen.tsx`
- Start dev server
- Perform a login
- Browse to the screen
=> fix: [IOAPPCIT-23] Fix the glitch in the Download Profile screen

ts/components/LabelledItem/index.tsx
This PR fixes the wrong rendering of `SearchButton`
| ✅ iOS | ❌ iOS|
| - | - | 
| <img src="https://user-images.githubusercontent.com/16268789/212661009-846669d4-c093-4dd0-97c7-c57fd0ef8fba.jpg" width="150" />  | <img src="https://user-images.githubusercontent.com/16268789/212661054-6897877e-c7fd-49fb-aabe-24533e40e9f1.PNG" width="150" /> |
| ✅ Android | ❌ Android |
| - | - | 
| <img src="https://user-images.githubusercontent.com/16268789/212662149-29373e14-13cf-4767-8009-bf667910456c.png" width="150" /> | <img src="https://user-images.githubusercontent.com/16268789/212662202-3d7f5dc2-7a08-4668-ab41-9bf90b6c78b8.png" width="150" /> |
- ts/components/LabelledItem/index.tsx: removes `flex: 1` style that makes `SearchButton` render incorrectly
On Android and iOS try searching inside the …
=> fix: [IOAPPCOM-48] SearchButton renders incorrectly

locales/en/index.yml, locales/it/index.yml, ts/features/idpay/common/labels.ts
Added i18n keys for IDPAY card activation status labels
=> chore(IDPay): [IODPAY-88] Add I18n for card activation status

package.json
small pr to update the IDPAY IBAN api yaml for the codegen
- update of the referenced api specs' tag to `1.101.0`
navigate to an initiative's details and start the iban onboarding workflow: there was a bug affecting older yaml versions which sent the app in an error state upon requesting the user's iban list, this PR adresses that.
=> fix(IDPay): [IODPAY-89] Updated iban yaml version

.env.production
This PR enable local FF for FCI
=> chore(Firma con IO): Enable FCI feature flag

ts/components/wallet/PaymentMethodsList.tsx
This PR fixes the UI regression introduced in the last PRs related to the Design System.
| - | - |
| <img src="https://user-images.githubusercontent.com/1255491/217789100-75ced38c-b8b6-41a9-839a-2bf20a2f7ff6.png" width="350" /> | <img src="https://user-images.githubusercontent.com/1255491/217789164-8de73e16-7a26-47af-9f1d-b51a36450e82.png" width="350" />
Go to the `Wallet → Add → Payment Method`
=> fix: [IABT-1432] Fix UI regression in the `Add Payment Method` screen

ts/features/idpay/onboarding/xstate/services.ts
fixed serialization bug in multivaluePrerequisites
=> fix(IDPay): [IODPAY-148] Serialization bug in multivaluePrerequisites

locales/en/index.yml, locales/it/index.yml, ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx, ts/features/idpay/onboarding/xstate/selectors.ts
added initiative name to idpay's onboarding pdnd prerequisite screen, also added fallback for possible errors loading an initiative's name
- added initiative name in pdnd screen
- added fallback initiative name
- refactored the page to use selectors instead of actors
start an initiative's onboarding flow and check if the PDNDprerequisites stage correctly renders an intiative's name
=> fix(IDPay): [IODPAY-132] Added initiative name in PDNDprerequisites screen

package.json
This PR fixes the onboarding flow for whitelist initiatives.
- Updated `idpay_onboarding` definitions url
Start the onboarding for an initiative with a whitelisted CF.
=> fix(IDPay): [IODPAY-150] Fix onboarding flow for whitelist initiative

package.json, yarn.lock
Upgrade the version of the react-native-cie library to fix read of the new CIE type
- Upgrade react-native-cie library to latest version
You need a CIE released in 2023.
=> fix: [IABT-1426] Fix new CIE read on Android

locales/en/index.yml, locales/it/index.yml, ts/features/idpay/initiative/configuration/iban/screens/IbanEnrollmentScreen.tsx, ts/features/idpay/initiative/configuration/iban/screens/__test__/IbanEnrollmentScreen.test.tsx, ts/features/idpay/initiative/configuration/xstate/__mocks__/actions.ts, ts/features/idpay/initiative/configuration/xstate/__tests__/machineIban.test.ts, ts/features/idpay/initiative/configuration/xstate/actions.ts, ts/features/idpay/initiative/configuration/xstate/machine.ts
This PR fixes an issue that was preventing the modification of the IBAN associated with an initiative.
Also adds a toast to let users know the change went through successfully.
- Resolved an issue with `useEffect` that was preventing the change of the IBAN
- Added missing locales
- Added feedback toast on IBAN change success
Go to the initiative details screen and try to change the associated IBAN.
=> chore(IDPay): [IODPAY-151] Fix IBAN change issue

ts/config.ts
This PR upgrades the minor TOS version to make the user accept it.
=> feat: [LLK-34] Bump minor TOS version

ts/components/FiscalCodeLandscapeOverlay.tsx, ts/components/core/variables/IOSpacing.ts, ts/components/messages/MessageDetail/index.tsx, ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx, ts/features/bonus/bpd/components/paymentMethodActivationToggle/bottomsheet/OtherChannelInformation.tsx, ts/features/bonus/bpd/screens/iban/insertion/IbanInsertionComponent.tsx, ts/features/bonus/bpd/screens/onboarding/ErrorPaymentMethodsScreen.tsx, ts/features/bonus/cgn/screens/CgnDetailScreen.tsx, ts/features/design-system/core/DSSpacing.tsx, ts/features/euCovidCert/screens/valid/EuCovidCertValidScreen.tsx, ts/screens/wallet/TransactionDetailsScreen.tsx
This PR updates the spacing scale used by the `VSpacer` and `HSpacer` components, according to the design guidelines.
- Add the new accepted values to the `IOSpacer` array
- Delete subsequent `VSpacer` components, thanks to the new spacing values
| - | - |
| <img src="https://user-images.githubusercontent.com/1255491/220158381-f86bd8d5-59a7-449a-be95-ae7bc1e8932d.png" width="350" /> | <img src="https://user-images.githubusercontent.com/1255491/220158440-1a117570-f2a4-4ca9-82eb-a2d8194ec900.png" width="350" />
Go to the _Profile → Design System → Spacing (Foundation)_
=> chore: [IOAPPFD0-37] Update spacing scale

locales/en/index.yml, locales/it/index.yml
- Changed feedback microcopy when updating IBAN
- Changed instruction on thank you page
=> chore(IDPay): [IODPAY-163] Copy changes

ts/features/fci/saga/networking/handleCreateSignature.ts
This PR fix request body format during createSignature request
- Update `handleCreateSignature` saga
Using `io-dev-server-api` try to start a signing flow
=> fix(Firma con IO): [SFEQS-1511] Fix body on create signature request

ts/components/services/LocalServicesWebView.tsx
This PR adds the web view style inside the already defined `styles` property.
See change list.
Navigate to Services -> Local Services and all should look fine.
=> fix: [IOAPPFD0-54] Refactor WebView style on `LocalServicesWebView`

README.md
This PR updates the Readme file with the instructions for proper ruby and bundler versions
- `Readme.md` changed with proper versions for ruby and bundler
Check that the file content is properly displayed on the repo's main page
=> chore: [IOAPPFD0-69] Update Readme with latest ruby and bundler versions

ios/Podfile.lock
This PR adds the updated `Podfile.lock` that was not added with #4485 .
=> chore: [IOAPPFD0-73] Add updated Podfile.lock

package.json, ts/features/fci/components/SuccessComponent.tsx, ts/features/fci/components/__tests__/SuccessComponent.test.tsx, ts/features/fci/saga/networking/__tests__/handleGetQtspMetadata.test.ts, ts/features/fci/saga/networking/handleGetQtspMetadata.ts, ts/features/fci/screens/__tests__/FciRouterScreen.test.tsx, ts/features/fci/store/reducers/fciSignatureRequest.ts, ts/features/fci/types/__mocks__/SignatureRequestDetailView.mock.ts
This PR adds new FCI definitions.
- Update `package.json`
- Update mocked value
The test for FCI should be resolved with success. It should be also possible to start a signing flow using `io-dev-api-server`.
=> chore(Firma con IO): [SFEQS-1578] Update FCI definitions

locales/en/index.yml, locales/it/index.yml, ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx, ts/features/fci/utils/__tests__/signatureFields.test.ts, ts/features/fci/utils/signatureFields.ts
This PR updates the locales string related to clauses type.
- Update signatureFields util
- Update test
Test should solve correctly. Using io-dev-server on the FciSginatureFieldsScreen the section header should render correctly.
=> chore(Firma con IO): [SFEQS-1608] Update locales for clauses type

.circleci/config.yml, scripts/check_cie_button_exists/check_cie_button_exists_ios.py
This PR restores the CIE ios button check by fixing the underlying issue which made it fail every time due to a new session check in the CIE login page.
- .circleci/config.yml: Enables the check again;
- scripts/check_cie_button_exists/check_cie_button_exists_ios.py: Adds a request session to pass the login page check which returns an error if cookies are disabled.
- Install python dependencies;
- Run the python script locally and it should finish with exit code 0.
=> fix: [IOAPPFD0-87] CIE iOS button check in CircleCI

ts/features/idpay/initiative/details/components/InitiativeSettingsComponent.tsx
This PR fixes the visualization of settings skeleton in initiative details screen
- Fixed skeleton render logic in `SettingsButtonComponent`
With `io-dev-server`, navigate to the initiative details screen and check the correct visualization of the skeleton in the settings section (at the bottom of the screen). Also check that the skeleton is not rendered if the screen is not in loading state
=> fix(IDPay): [IODPAY-217] Fix IDPay initiative settings component skeleton

ts/features/fci/components/ErrorComponent.tsx, ts/features/fci/screens/valid/FciSignatureRequestsScreen.tsx, ts/utils/supportAssistance.ts
This PR adds zendesk custom field id for FCI feature.
- Update ts/features/fci/components/ErrorComponent.tsx
- Update ts/features/fci/components/FciSignatureRequestsScreen.tsx
- Update ts/utils/supportAssistance.ts
=> chore(Firma con IO): [SFEQS-1629] Add zendesk fci custom field id

locales/en/index.yml, locales/it/index.yml, package.json, ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts, ts/features/idpay/onboarding/xstate/__tests__/services.test.ts
This PR updates the definitions for IDPay API
- Updated `idpay_api` url in `package.json`
Tests should solve correctly
=> chore(IDPay): [IODPAY-221] Update IDPay API definition to v2.52.1

ts/features/fci/analytics/index.ts
This PR updates trackFciAction replacing `fciPollFilledDocument.cancel` with `fciPollFilledDocument.success`
- Update analitycs
=> fix(Firma con IO): [SFEQS-1635] Fix mixpanel events action

ts/features/idpay/initiative/details/components/InitiativeCardComponent.tsx, ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
This PR refactors the styling in the initiative details screen to simplify components centering.
Open the details screen of an IDPay initiative. Check that scrolling works smoothly and without glitches.
=> chore(IDPay): [IODPAY-223] Initiative details screen refactoring

.circleci/config.yml, .github/workflows/nightly-jobs.yml
Nightly jobs migration from CircleCI to Github Actions.
Here's the list of the jobs migrated:
- Check API specs alignment
- Check URIs validity on static texts
- Check CIE button exists on IOS
=> feat: [IOPLT-8] Migrate nightly jobs from Circle CI to GitHub Actions

README.md
This PR updates the README.md of the repository. I recently reinstalled MacOS so I had to follow the guide from scratch and I noticed a few issues.
- Adds a missing step in the build section;
- Updates the troubleshooting section;
- Fixes a wrong RN CLI link.
You can check the markdown preview [here](https://github.com/pagopa/io-app/blob/IOAPPFD0-97-update-readme/README.md).
=> chore: [IOAPPFD0-97] Update README.md

locales/en/index.yml, locales/it/index.yml
This PR updates the timeline label of PN.
- updated locales
Open PN message using `io-dev-api-server` and view the timeline label for the `VIEWED` status.
=> fix: [IOCOM-326] PN copy changes

scripts/ts/danger/utils/changelog.ts
Add IT Wallet project scope
- Update changelog.ts
=> feat(IT Wallet): [SIW-239] Add danger it wallet project scope

ts/features/it-wallet/navigation/ItwStackNavigator.tsx, ts/features/it-wallet/navigation/params.ts, ts/features/it-wallet/navigation/routes.ts, ts/navigation/AuthenticatedStackNavigator.tsx, ts/navigation/params/AppParamsList.ts
This PR initialize main stack navigator for ITW feature.
- Add ItwStackNavigator
- Update AuthenticatedStackNavigator
Note: for this use case the user is already authenticated. The unauthenticated case should be discovered in the future.
=> feat(IT Wallet): [SIW-222] ITW stack navigator initialization

ts/screens/profile/components/ShareDataComponent.tsx
This PR updates the share data security information URL.
Go to Profile -> Privacy Screen and navigate to the "Learn more" link.
=> fix: [IOPID-388] Shared data security info URL is broken

ts/components/cie/CieRequestAuthenticationOverlay.tsx
This PR clear all session cookies at CIE login start on Android
Test a CIE login on both Android and iOS.
=> fix: [IOPID-389] Clear session cookies at CIE login start on Android

.env.production
This PR reverts pagopa/io-app#4785, disabling FL production local FF.
=> chore: [IOPID-417] Enable FL production FF"

ts/components/IdpsGrid.tsx, ts/screens/authentication/IdpSelectionScreen.tsx
This PR fixes a nested `ScrollView` error in the `IdpSelectionScreen`. Now the entire screen, including title and description, is managed by the `IdpsGrid` component.
- Slightly refactor the `IdpSelectionScreen` to delete `ScrollView`
Go to the `IdpSelectionScreen` with the console open. You should not see any errors related to the page.
=> fix: [IOPID-485] Fix nested `ScrollView` error in the `IdpSelectionScreen`

locales/en/index.yml, locales/it/index.yml
This PR changes text inside the CGN section about the discounts which renames them in some screens from "agevolazioni" to "opportunità" according to the [desired design](https://www.figma.com/file/yOoBGDr1MJpa0LY5lDUFSd/IOapp_CartaGiovaniNazionale_20220211?type=design&node-id=2765-71614&mode=design&t=DOpApS7omFiCdsqs-0)
- Changed texts into locale file
In order to test, go into CGN section detail and CGN Merchant list and check that there is "opportunità" label that follows the desired design attached;
=> chore: [PE-442] Change CGN details text labels

ts/features/idpay/initiative/details/components/InitiativeSettingsComponent.tsx, ts/features/idpay/initiative/details/components/__tests__/InitiativeSettingsComponent.test.tsx, ts/features/idpay/initiative/details/components/__tests__/__snapshots__/InitiativeSettingsComponent.test.tsx.snap
This PR fixes a bug where every initiative was labeled with missing IBAN
Tests should resolve correctly.
=> fix: [IOBP-156] Fix bug in initiative details screen

ios/Podfile.lock, package.json, yarn.lock
This PR adds io-react-native-cie-pid package to bundle/it-wallet.
- Update package.json
- Update yarn.lock
- Update podfile.lock
Tests should be solved correctly
=> chore(IT Wallet): [SIW-342] add `io-react-native-cie-pid` package

ts/screens/authentication/idpAuthSessionHandler.tsx
=> Fix: Remove native login comment

README.md
This PR updates the `README.md` of the repository.
Added the `POST_NOTIFICATIONS` permission to the permissions mapping.
Check the markdown preview.
=> feat: [IOCOM-396] Update `README.md`

locales/de/index.yml
This PR adds/corrects strings of the german language file from PR #4832, #4688 and #4573
=> Update 🇩🇪 file

ts/features/barcode/hooks/useIOBarcodeFileReader.tsx
This PR fixes a crash in QRCode scan screen during an image upload
- [ts/features/barcode/hooks/useIOBarcodeFileReader.tsx](https://github.com/pagopa/io-app/compare/IOBP-171-fix-crash-during-image-selection-in-qrcode-scan?expand=1#diff-36bd07843535011c4a091fd48fba32d133ba39986aa714dbe03a54332c1803a1): replaced `uri` with `base64` for image decoding task
With the `io-dev-server`, try to authorize an IDPay transaction uploading the image of a QR Code. There shouldn't be any crashes..
=> [IOBP-172] Fix app crash in QRCode scan screen during image upload

ts/features/it-wallet/screens/issuing/cie/CieConsentDataUsageScreen.tsx
This PR updates the injected JS code to customize the webview content during IT-Wallet activation.
- Update CieConsentDataUsageScreen.tsx
Start IT-Wallet activation. The Data usage screen should show the CieID page with the list of data shared to get the PID.
=> fix(IT Wallet): [SIW-358] Update injected JS code in data usage screen

ts/features/it-wallet/hooks/useItwAbortFlow.tsx, ts/features/it-wallet/saga/authenticationSaga.ts, ts/features/it-wallet/saga/cie.ts, ts/features/it-wallet/saga/index.ts, ts/features/it-wallet/screens/discovery/ItwActivationDetailsScreen.tsx, ts/features/it-wallet/screens/issuing/ItwPidActivationScreen.tsx, ts/features/it-wallet/screens/issuing/cie/CieInfoUsageScreen.tsx, ts/features/it-wallet/store/actions/index.ts
This PR updates it-wallet authentication saga and fix an issue when user try to authenticate again with CIE in io-app.
- Update it-wallet saga
- Add new action (Start, Stop, Completed) for itwAuthentication
- Update screens to dispatch the right action
Start it-wallet and login with cie. Start the it-wallet authentication flow. Try to stop the authetication flow. Logout from profile section. Try to login with cie again. The authentication should solves correctly.
=> fix(IT Wallet): [SIW-360] Update saga to handle authentication stop

package.json, ts/components/ui/ButtonExtendedOutline.tsx, ts/components/ui/ButtonLink.tsx, ts/components/ui/ButtonOutline.tsx, ts/components/ui/ButtonSolid.tsx, ts/components/ui/IconButton.tsx, ts/components/ui/IconButtonContained.tsx, ts/components/ui/IconButtonSolid.tsx, yarn.lock
Migrating Buttons components from @pagopa/io-app-design-system.
- ButtonSolid
- ButtonExtendedOutline
- ButtonLink
- ButtonOutline
- IconButtonSolid
- IconButton
- IconButtonContained
=> feat: [IOPLT-117] Migrating buttons components from design system

ts/App.tsx, ts/components/core/Divider/index.tsx, ts/features/design-system/components/DSIconViewerBox.tsx, ts/features/design-system/components/DSSpacerViewerBox.tsx, ts/features/design-system/components/DesignSystemScreen.tsx, ts/features/design-system/core/DSBottomSheet.tsx, ts/features/design-system/core/DSHapticFeedback.tsx, ts/features/design-system/core/DSIcons.tsx, ts/features/design-system/core/DSLayout.tsx, ts/features/design-system/core/DSListItems.tsx
This PR fixes a problem on DS components using the dark mode
Copied from #4908
=> fix(IT Wallet): [SIW-445] Fix components not showing text with dark mode

package.json, yarn.lock
This PR updates `io-react-native-wallet` dependency to the `0.4.1` version.
Test both the PID issuing and presentation flow.
=> chore(IT Wallet): [SIW-487] Update io-react-native-wallet to 0.4.1

ts/features/it-wallet/screens/discovery/ItwDiscoveryInfoScreen.tsx, ts/features/it-wallet/screens/issuing/ItwPidAuthInfoScreen.tsx
This PR fix a scroll issue on some screens adding an additional VSpacer.
Start an activation flow. It should be possible to scroll all screen to show entire content.
=> fix(IT Wallet): [SIW-419] Fix scroll issue on some info screen

ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap, ts/components/ui/cards/payment/__test__/__snapshots__/PaymentCards.test.tsx.snap, ts/features/idpay/initiative/details/components/__tests__/__snapshots__/InitiativeSettingsComponent.test.tsx.snap, ts/store/reducers/persistedPreferences.ts
This PR enables the expertimental design system by default.
- Sets the initial state of the experimental design system flag to `true`;
- Updates snaphots for testing.
Start the app and the experimental design system should be enabled by default.
=> chore(IT Wallet): [SIW-500] Enable experimental design system by default

patches/react-native-vision-camera+2.15.4.patch
This PR adds [this proposed patch](https://github.com/mrousavy/react-native-vision-camera/issues/1840#issuecomment-1732360337) to fix a crash on iPhone 15.
Build the app and start the QR code screen. Try to scan a QR Code and everything should work as expected.
=> fix(IT Wallet): [SIW-558] Fix camera crash on iPhone 15

ts/features/it-wallet/screens/presentation/crossdevice/ItwRpInitScreen.tsx
This PR updates "Tutte le condizioni" action to navigate at 404 error page
- Update `ItwRpInitScreen.tsx`
Start a presentation flow on the entity data scroll to bottom and tap on "Tutte le condizioni" link to open a 404 error page.
=> chore(IT Wallet): [SIW-538] Update all conditions link to 404 page

CODEOWNERS
This PR adds @dmnplb (me) as the code owner of the DS section. This means that I'll be notified when a PR changes something in the `/ts/features/design-system` folder.
- Add my username to the `CODEOWNERS` file with relative folder path
=> chore: [IOAPPFD0-169] Add `@dmnplb` as code owner of the DS section

ts/features/idpay/details/components/__tests__/__snapshots__/InitiativeSettingsComponent.test.tsx.snap, ts/features/it-wallet/components/__tests__/__snapshots__/ItwActionCompleted.test.tsx.snap
This PR updates tests snapshots, outdated due to the latest rebase.
Run `yarn test:dev` and tests should pass.
=> chore(IT Wallet): [SIW-581] Update tests snapshots

ts/features/fci/screens/valid/FciDataSharingScreen.tsx
This pr fix a problem with displaying the date of birth in data sharing screnn
Start signing flow. On data sharing screen the date of birth must be correct
=> fix(Firma con IO): [FCIA-77] Update birthdate format in data sharing screen

package.json, ts/features/it-wallet/saga/itwRpInitializationSaga.ts, ts/features/it-wallet/saga/itwWiaSaga.ts, ts/features/it-wallet/store/actions/itwRpActions.ts, ts/features/it-wallet/store/reducers/itwRpInitializationReducer.ts, ts/features/it-wallet/utils/pid.ts, ts/features/it-wallet/utils/wia.ts, yarn.lock
Upgrade package `@pagopa/io-react-native-wallet` to latest version. Change usage accordingly.
See also: https://github.com/pagopa/io-react-native-wallet/pull/43
=> chore(IT Wallet): [SIW-547] Update `io-react-native-wallet` to `v0.7.0`

package.json, ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap, yarn.lock
This PR updates `io-app-design-system` package to the `1.13.0` version.
Static checks should be enough.
=> feat(IT Wallet): [SIW-595] Update `io-app-design-system` package to `1.13.0`

ts/features/design-system/navigation/navigator.tsx, ts/navigation/AppStackNavigator.tsx, ts/theme/navigations.ts
Moves the theme definition on a utility file removing the require loop warning
nothing should be chenged, just code reorg.
=> fix: removes the require loop on navigators definition

.env.production, CHANGELOG.md, android/app/build.gradle, ios/ItaliaApp.xcodeproj/project.pbxproj, ios/ItaliaApp/Info.plist, ios/ItaliaAppTests/Info.plist, package.json, publiccode.yml
This PR enables FL FF in production.
This we'll be used in the next RC (possibly `2.44.0.1`) and then disabled.
=> chore: [IOPID-999] Enable FL in production

CHANGELOG.md, android/app/build.gradle, ios/ItaliaApp.xcodeproj/project.pbxproj, ios/ItaliaApp/Info.plist, ios/ItaliaAppTests/Info.plist, package.json, publiccode.yml, ts/screens/wallet/payment/TransactionSummaryScreen.tsx
This PR aims to fix the crash on android devices on `2.44.0.3` and aligns the app version.
- Crash fix
- Align app version
=> fix: [IABT-1498] Fix crash on android build and align app version

package.json, ts/features/barcode/types/decoders.ts, ts/features/it-wallet/saga/itwRpInitializationSaga.ts, ts/features/it-wallet/saga/itwRpPresentationSaga.ts, ts/features/it-wallet/saga/itwWiaSaga.ts, ts/features/it-wallet/store/actions/itwCredentialsActions.ts, ts/features/it-wallet/store/actions/itwRpActions.ts, ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts, ts/features/it-wallet/store/reducers/itwPidReducer.ts, ts/features/it-wallet/store/reducers/itwRpInitializationReducer.ts, ts/features/it-wallet/store/reducers/itwRpPresentationReducer.ts, ts/features/it-wallet/utils/pid.ts, ts/features/it-wallet/utils/types.ts, ts/features/it-wallet/utils/wia.ts, yarn.lock
Co-edit by @LazyAfternoons 
Update package and review interfaces according to the changes introduced in https://github.com/pagopa/io-react-native-wallet/compare/v.0.7.4...v0.9.2.
Changes have no effect on functionalities but serve as a mere rename of the actions.
- Adopt new API from `@pagopa/io-react-native-wallet`
=> chore(IT Wallet): [SIW-632] Update package `io-react-native-wallet` from `v0.7.4` to `v0.9.2`

ts/features/it-wallet/components/ItwTextInfo.tsx
This PR adds support to **H2** and **H6** header support in `ItwTextInfo` component.
- Update `ItwTextInfo`
Try to import this component. Try to use as content prop a markdown string with H2 and H6 header. For example:
```typescript
const markdownString =
"## H2 header\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ornare odio non libero tempus accumsan. Cras vel tincidunt nibh. Etiam augue lorem,\n\n###### H6 header\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ornare odio non libero tempus accumsan. Cras vel tincidunt nibh. Etiam augue lorem";
//...
<ItwTextInfo content={markdownString} />
//...
```
=> chore(IT Wallet): [SIW-642] Add h2 and h6 header support to `ItwTextInfo` component

ios/ItaliaApp.xcodeproj/project.pbxproj
This PR bumps the minimum version of supported iOS devices to version 12
- Changed the target/minimum version on xcode projects
Nothing should be changed 
Further details [here](https://github.com/pagopa/io-platform/discussions/4)
=> feat: [IOPLT-43] Increase iOS target version to deprecate faulty builds

ts/features/bonus/cgn/screens/activation/CgnActivationCompletedScreen.tsx, ts/features/bonus/common/components/BonusInformationComponent.tsx
This PR fixes some CGN e2e test regression after the massive refactor.
- Added missing testIDs
=> fix: [IOBP-397] CGN e2e tests

.env.production, CHANGELOG.md, android/app/build.gradle, ios/ItaliaApp.xcodeproj/project.pbxproj, ios/ItaliaApp/Info.plist, ios/ItaliaAppTests/Info.plist, package.json, publiccode.yml
This PR enables FL in production to deploy a new beta and then disables the flag again.
=> chore: [IOPID-1103] Enable/Deploy/Disable FL in production

ts/features/it-wallet/screens/credential/issuing/ItwCredentialPreviewScreen.tsx
This PR introduces a force scroll to bottom in the credential preview. 
- Replaces the `ScrollView` with `ForceScrollDownView`. 
- Replaces `FooterWithButtons` with `ItwFooterVerticalButtons`. 
Try to obtain a credential, the preview screen should now have a bottom to force the scroll to the bottom.
=> chore(IT Wallet): [SIW-660] Force scroll to bottom in credential preview

ts/features/it-wallet/components/ItwCredentialClaimsList.tsx, ts/features/it-wallet/saga/new/itwIssuanceSaga.ts, ts/features/it-wallet/screens/credential/ItwCredentialDetailsScreen.tsx, ts/features/it-wallet/screens/credential/issuing/ItwCredentialPreviewScreen.tsx, ts/features/it-wallet/store/actions/new/itwIssuanceActions.ts, ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts, ts/features/it-wallet/store/reducers/new/itwIssuanceReducer.ts
This PR adds the "Released by" claim for a generic credential.
- Edits the issuance reducer state by storing the whole issuer configuration which also contains the organization name used to render the credential;
- Updates the UI accordingly by adding a component which renders the aformentioned claim. 
Try to obtain a credential and check if the "Released by" claim is rendered.
=> chore(IT Wallet): [SIW-676] Add released by claim for credentials

ts/features/messages/components/__test__/MessageAttachmentPreview.test.tsx, ts/features/messages/components/__test__/MessageAttachments.test.tsx, ts/features/pn/components/__test__/MessageDetails.test.tsx, ts/features/pn/components/__test__/MessageF24.test.tsx, ts/features/pn/components/__test__/__snapshots__/MessageF24.test.tsx.snap
This PR adds unit tests for F24 feature
- updated unit tests for `MessageF24`
- added snapshot for `MessageF24`
- added unit tests for `MessageAttachmentPreview`
Run the test suite and check that it is completed successfully
=> feat: [IOCOM-662] Add unit tests for F24 feature

ts/features/it-wallet/saga/itwCieSaga.ts
This PR is the result of a prettier run after the rebase due to updates in the main branch.
Static checks.
=> chore(IT Wallet): [SIW-706] Prettier after rebase

locales/en/index.yml
This PR fixes an error in the "check organization" EN locale.
Static checks.
=> chore(IT Wallet): [SIW-739] Fix error in check organization EN locale

.env.production
This PR enables the Zendesk FF in production.
Static tests should be enough.
=> chore(IT Wallet): [SIW-738] Enable Zendesk FF in production

.env.production
This PR enables all FL related local FF in production.
=> chore: [IOPID-1182] Chore: enable all FL related local FF in production

ts/features/bonus/cgn/utils/__test__/dates.test.ts
This PR fixes a failing CGN test.
- Proper mock of Date.now
Check that all tests succeed
=> Failing CGN test

ts/features/bonus/cgn/utils/__test__/dates.test.ts
This PR fixes a failing CGN test by implementing #5367. It must be merged as soon as possible instead of waiting for a rebase.
Static checks.
=> fix(IT Wallet): [SIW-786] Fix CGN test

ts/config.ts
=> chore: [IOPID-1301] Bump ToS version from 4.7 to 4.8"

locales/en/index.yml, locales/it/index.yml, ts/features/fastLogin/components/SecuritySuggestions.tsx
change fingerprint icon and fix typo as requested in this [Jira task](https://pagopa.atlassian.net/browse/IOPID-1287)
- fix typo in it and en
- change finger print icon name from the library
Run the application with fast login FF active.
=> fix: [IOPID-1287] Change fingerprint icon and fix typo

locales/de/index.yml
This PR removes duplicate spaces
=> 🇩🇪 remove spaces

ios/Podfile.lock
This PR is only to update Podfile.lock reference after PR #5468
=> fix: align podfile.lock io-react-native-zendesk version

ts/__e2e__/payment.e2e.ts
This PR fixes the payment E2E tests.
E2E tests should pass
=> chore: [IOBP-546] Fix payment E2E tests

.github/workflows/test-e2e.yml, jest-e2e.config.js
This PR aims to fix the restore issue on pods cache
- Updates on test-e2e.yml
check e2e run
=> fix: e2e cache restore issue

scripts/ts/danger/updatePrTitle.tsx
This PR adds SIW id in updatePrTitle
Static checks should be enough
=> chore(IT Wallet): [SIW-941] Update Pr title with SIW id

Gemfile, Gemfile.lock
This PR bump cocoapods for alignment on gem dependencies
- Gemfile
- Gemfile.lock
Run
```
bundle install
cd ios; bundle exec pod install; cd ..
```
=> fix: update minor version on cocoapods

package.json, ts/components/cta/__test__/__snapshots__/CTAsBar.test.tsx.snap, ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap, ts/features/fci/components/__tests__/__snapshots__/QtspClauseListItem.test.tsx.snap, ts/features/fci/components/__tests__/__snapshots__/SignatureFieldItem.test.tsx.snap, ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap, ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap, ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsStickyFooter.test.tsx.snap, ts/features/messages/components/MessageDetail/__tests__/__snapshots__/OrganizationHeader.test.tsx.snap, ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap, ts/features/newWallet/components/__tests__/__snapshots__/WalletEmptyScreenContent.test.tsx.snap, ts/features/pn/components/__test__/__snapshots__/MessageFooter.test.tsx.snap, ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap, yarn.lock
This PR updates the `io-app-design-system` to the latest version available.
- Update `io-app-design-system` to `1.31.0`
N/A
=> chore(Cross): [IOAPPX-270] Update `io-app-design-system` to `1.31.0`

locales/en/index.yml
Add english copy 
> [!WARNING]
> this PR integrates the English copy of this PR https://github.com/pagopa/io-app/pull/5647
=> feat: [IOPID-1611] Add en copy on modal cie not supported

ts/features/services/common/api/__mocks__/client.ts, ts/features/services/common/saga/index.ts, ts/features/services/common/store/actions/index.ts, ts/features/services/common/store/reducers/index.ts, ts/features/services/institution/saga/__tests__/handleFindServices.test.ts, ts/features/services/institution/saga/handleFindServices.ts, ts/features/services/institution/saga/index.ts, ts/features/services/institution/store/actions/index.ts, ts/features/services/institution/store/reducers/__tests__/store.test.ts, ts/features/services/institution/store/reducers/index.ts
This PR adds actions, reducer, selectors and saga to handle the institution's services.
- added actions, reducer and selectors to handle the institution's services
- added `handleFindServices` saga
- added tests
Tests should pass correctly
=> chore: [IOPAE-1119] Institution's services: actions, reducer, selectors and saga

ts/screens/profile/TosScreen.tsx
Add title in profile ToS screen
| ToS Profile | ToS Profile Error |
| - | - |
| ![Screenshot_20240503_112500_IO](https://github.com/pagopa/io-app/assets/83651704/f649efc0-f589-42b7-9aea-28d1b624205d) | ![Screenshot_20240503_112451_IO](https://github.com/pagopa/io-app/assets/83651704/7c09c5c9-542d-4101-8aff-94699cb99a04) |
Run the application and after login navigate in Profile > Terms and conditions > Privacy Policy and Terms of Service
=> feat: [IOPID-1505] Add title in profile ToS screen

locales/en/index.yml, locales/it/index.yml
Added missing space in bottom sheet explaining the sorting criteria
=> fix: [PE-590] Added missing space in CGN bottom sheet

ts/features/services/common/api/__mocks__/client.ts, ts/features/services/home/saga/__tests__/handleGetFeaturedInstitutions.test.ts, ts/features/services/home/saga/__tests__/handleGetFeaturedServices.test.ts, ts/features/services/home/saga/handleGetFeaturedInstitutions.ts, ts/features/services/home/saga/handleGetFeaturedServices.ts, ts/features/services/home/saga/index.ts, ts/features/services/home/store/actions/index.ts, ts/features/services/home/store/reducers/__tests__/store.test.ts, ts/features/services/home/store/reducers/index.ts
This PR adds actions, reducer, selectors and saga to handle _**featured institutions**_ and _**featured services**_ _(shown in services main screen tab as "Featured")_.
**Note:** _This PR remove old https://github.com/pagopa/io-app/pull/5736 "FeaturedItems" implementation decoupling it into two concepts, precisely featured institutions and featured services._
- added actions, reducer and selectors to handle FeaturedInstitutions
- added handleGetFeaturedInstitutions saga
- added actions, reducer and selectors to handle FeaturedServices
- added handleGetFeaturedServices saga
- added unit tests
Tests should pass correctly.
=> chore: [IOPAE-1144] Featured Institutions, Featured Services: actions, reducer, selectors and saga

ts/features/services/common/saga/index.ts, ts/features/services/common/store/actions/index.ts, ts/features/services/common/store/reducers/index.ts, ts/features/services/search/saga/__tests__/handleFindInstitutions.test.ts, ts/features/services/search/saga/handleFindInstitutions.ts, ts/features/services/search/saga/index.ts, ts/features/services/search/store/actions/index.ts, ts/features/services/search/store/reducers/__tests__/store.test.ts, ts/features/services/search/store/reducers/index.ts
This PR adds actions, reducer, selectors and saga to search institutions.
- added actions, reducer and selectors to search institutions
- added `handleFindInstitutions` saga
- added tests
Tests should pass correctly
=> chore: [IOPAE-1146] Search institutions: actions, reducer, selectors and saga

publiccode.yml
This PR replaces old maintainer on publicode file declaration
- publicode.yml
N/A
=> chore: fix maintenance team on publicode

ts/features/idpay/details/store/__test__/store.test.ts, ts/features/idpay/timeline/store/__test__/store.test.ts, ts/features/messages/components/__test__/MessageList.test.tsx, ts/features/messages/components/__test__/MessagesInbox.test.tsx, ts/features/messages/store/reducers/__tests__/allPaginated.test.ts, ts/features/messages/store/reducers/__tests__/detailsById.test.ts, ts/features/messages/store/reducers/__tests__/paginatedById.test.ts, ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx, ts/screens/profile/LanguagesPreferencesScreen.tsx, ts/screens/profile/__test__/TosScreen.test.tsx
This PR fixes a wrong `pot` import.
=> fix: `pot` import

.env.local, .env.production, ts/config.ts, ts/features/services/common/navigation/navigator.tsx, ts/features/services/common/saga/index.ts, ts/navigation/TabNavigator.tsx, ts/navigation/components/HeaderFirstLevelHandler.tsx, ts/sagas/__tests__/initializeApplicationSaga.test.ts, ts/sagas/startup.ts
This PR enables new services section by default.
Start the app, tap on services tab, enjoy :)
=> chore: [IOPAE-1221] Enable new services section by default

ts/features/services/common/analytics/index.ts, ts/features/services/details/screens/ServiceDetailsScreen.tsx
Update mixpanel `SERVICES_DETAIL_CTA_TAPPED` event properties.
=> chore: [IOPAE-1231] Update mixpanel trackServiceDetailsCtaTapped event props

ts/features/bonus/cgn/__e2e__/cgn00.e2e.ts, ts/features/bonus/cgn/__e2e__/cgn02.e2e.ts, ts/features/bonus/cgn/__e2e__/utils.ts, ts/features/bonus/cgn/components/detail/CgnUnsubscribe.tsx, ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
This PR fixes CGN E2E tests.
> [!warning]
> This PR depends on https://github.com/pagopa/io-dev-api-server/pull/395
> [!tip]
> [![Run e2e tests](https://github.com/pagopa/io-app/actions/workflows/test-e2e.yml/badge.svg?branch=cross-e2e-cgn)](https://github.com/pagopa/io-app/actions/workflows/test-e2e.yml)
=> chore(cross): fix CGN e2e tests

locales/en/index.yml
As a consequence of an error of distraction, I did not wait for the copy review to be done in this PR. This PR is intended to add the English copy and the texts were communicated by the copy team. The PR are: 
- https://github.com/pagopa/io-app/pull/5925
- https://github.com/pagopa/io-app/pull/5915
[IOPID-1528]: https://pagopa.atlassian.net/browse/IOPID-1528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [IOPID-1552, IOPID-1553, IOPID-1528] remediation english copy 

ios/Podfile.lock, ts/features/itwallet/machine/credential/actors.ts
This PR align dependencies and fixes after the merge of rn update
=> fix: align dependencies after rn upgrade

locales/en/index.yml, locales/it/index.yml
this PR updates some content in the receipts section
=> fix: [IOBP-742] Copy improvement

CHANGELOG.md, android/app/build.gradle, ios/ItaliaApp.xcodeproj/project.pbxproj, ios/ItaliaApp/Info.plist, ios/ItaliaAppTests/Info.plist, package.json, publiccode.yml, ts/components/SectionStatus/__tests__/SectionStatusComponent.test.tsx, ts/components/screens/BaseScreenComponent/__tests__/BaseScreenComponent.test.tsx, ts/features/pn/components/__test__/TimelineListItem.test.tsx, ts/features/wallet/bancomatpay/component/__test__/BPayWalletPreview.test.tsx, ts/features/wallet/cobadge/component/__tests__/CobadgeWalletPreview.test.tsx, ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx, ts/screens/profile/DeveloperModeSection.tsx, ts/screens/profile/__test__/TosScreen.test.tsx, ts/store/reducers/backendStatus.ts, ts/store/reducers/persistedPreferences.ts
=> New wallet FF cherry pick to master

locales/en/index.yml, locales/it/index.yml
This PR updates some labels in the receipt detail page
=> fix: [IOBP-741] Copy fixes

ios/Podfile.lock
This PR resolve problem on wrong hashes on the Podfile.lock
- Podfile.lock
N/A
=> fix: resolve Podfile.lock wrong hashes

scripts/check_cie_button_exists/check_cie_button_exists_ios.py, scripts/check_cie_button_exists/check_cie_button_exists_ios.test.py
This PR updates the SPID level from L2 to L3 to our EIC scripts. 
Run the script and check for a successful result:
```python
python3 'scripts/check_cie_button_exists/check_cie_button_exists_ios.py'
```
=> chore: update EIC button scripts

locales/en/index.yml, locales/it/index.yml
This PR updates ToS of credential preview screen
Try to get a credential, at the bottom of preview tap on informativa privacy link
=> chore(IT Wallet): [SIW-1381] Update `ToS` in preview credential screen

ios/ItaliaApp.xcodeproj/project.pbxproj, locales/en/index.yml, locales/it/index.yml
This PR adds spacing in the mDL banner text.
Static check and optionally check that the banner is properly displayed.
=> fix(IT Wallet): [SIW-1407] Add spacing in mDL banner text

locales/en/index.yml, locales/it/index.yml, ts/features/itwallet/common/components/ItwCredentialClaim.tsx, ts/features/itwallet/common/components/ItwReleaserName.tsx
This PR updates the copy for the issuer claim bottom sheet.
- Remove unused copy and remove its references;
- Update copy according to the [new FIGMA](https://www.figma.com/design/pVD9XCba7crkg5yOIdJCXl/%5BIT-Wallet%5D---%E2%9C%85-Approved-only-%E2%9C%85?node-id=534-17139&t=5aWDgMfvRvBkVPG7-0).
Try to obtain an eID and credential and check the bottom sheet content of the issuer claim.
=> chore(IT Wallet): [SIW-1410] Update copy in issuer claim bottom sheet

ts/App.tsx
This PR adds a check on dev env for Sentry enabling
- Sentry.init on App.tsx
Error events should not be sent to sentry.
=> chore: Disables Sentry when the build is coming from local development

.github/workflows/release.yml
Fix github release creation step
The release creation run should be correctly executed
=> fix: adds the checkout step to release creation

ts/features/fims/singleSignOn/utils/index.ts
This PR adds support for fast login session expiration during service details retrieval, on the FIMS consents' permission screen.
https://github.com/user-attachments/assets/322d1ddf-b0a5-444c-82fd-446db0ac2413
- Detection and restart of FIMS authorisation flow if a fast login error happens during service details retrieval
Using the io-dev-api-server, change the `service/:id` endpoint response so that it returns `401` upon first FIMS service details retrieval's request. You should be able to renovate the IO session and automatically restart the FIMS authorisation flow.
=> chore: [IOCOM-1679] FIMS consents screen: fast Login handling on service retrieval

locales/en/index.yml, locales/it/index.yml
- update translation files
- Login into app
- go to CGN card screen trough wallet
=> chore: [PE-683] CGN detail screen change labels

.env.local, .env.production
This PR changes the trustmark verifier base URL.
- Updated env files
Scan the QR code trustmark.
=> chore(IT Wallet): [SIW-1657] Change trustmark verifier base URL

locales/de/index.yml
=> DE updates

locales/en/index.yml, locales/it/index.yml
Pending comment left from #6224
=> Small copy change

.env.local, .env.production
> [!WARNING]
> Currently these endpoints do not work, that's intended
This PR updates the trustmark env URL. 
- Set IPZS trustmark env URL;
- (Bonus) Update the wallet provider URL in `.env.local` which currently points to production regardless of the environment.
N/A
=> chore(IT Wallet): [SIW-1709] Update trustmark env URL

locales/en/index.yml, locales/it/index.yml, ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
This PR updates the copy in the wallet activation flow.
- Updated copy
- Removed unused action in `IdentityNotMatching` failure screen
Please refer to the **Approved Only** Figma.
=> chore(IT Wallet): [SIW-1728] Wallet instance activation copy review

CHANGELOG.md, android/app/build.gradle, ios/ItaliaApp.xcodeproj/project.pbxproj, ios/ItaliaApp/Info.plist, ios/ItaliaAppTests/Info.plist, package.json, publiccode.yml
This PR aligns the app version after releasing a hotfix from a different branch.
=> chore(release): 2.72.0-rc.0

locales/de/index.yml
This PR changes some copy in german, related to services section
=> german copy fix

locales/en/index.yml, locales/it/index.yml
Update CGN department title in camel case format  
- Update locales strings
- Tap in wallet
- Check the CGN department subtitle
- Tap in CGN card
- Check the CGN department subtitle
Wallet screen             |  CGN Detail screen
=> fix: [PE-726] CGN camelize department title

locales/en/index.yml, locales/it/index.yml
This PR edits the filter notice tab in the notices list from `Pagate da me` to `Pagate in app`
- Edited locales
Open the Payments screen and then tap on the `Vedi tutte` CTA, you should be able to see the new label "Pagate in app"
=> chore: [IOBP-954] Edit filter notice tab label

ts/store/reducers/backendStatus/__tests__/backendInfo.test.ts, ts/store/reducers/backendStatus/__tests__/remoteConfig.test.ts, ts/store/reducers/backendStatus/remoteConfig.ts
This PR adds tests that were removed while refactoring backendStatus
- Existing tests for backendInfo
- Existing tests for remoteConfig
CI should succeed
=> feat: [IOPLT-724] Missing tests for backendInfo and remoteConfig

ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
This PR fixes a test that might fail randomly
Static checks should pass
=> fix: IT Wallet preferences reducer tests

ts/features/itwallet/machine/eid/failure.ts
This PR catches the following errors from `io-react-native-integrity` to display the unsupported device screen instead of the generic error:
- `REQUEST_ATTESTATION_FAILED`
- `UNSUPPORTED_DEVICE`
- `UNSUPPORTED_IOS_VERSION`
- `UNSUPPORTED_SERVICE`
> [!NOTE]
> These errors will be expanded after the analysis in **SIW-1833**.
- Modified the errors mapping in `machine/eid/failure.ts`
1. Test the wallet activation as usual to ensure no regressions were introduced.
2. Test the wallet activation with a device that doesn't support the integrity services. Mocking the error is not straightforward; it can be done throwing the error directly from `getAttestation` in the `io-react-native-integrity` Kotlin module:
```kt
ModuleException.REQUEST_ATTESTATION_FAILED.reject(
promise, …
```
=> chore(IT Wallet): [SIW-1823] Handle local integrity errors

locales/de/index.yml, locales/en/index.yml, locales/it/index.yml, ts/features/payments/details/saga/handleDeleteWalletDetails.ts
This pull request includes changes to the localization files for card removal button and toast.
- Update localization
- Add missing toast on backend failure
- Try to remove a payment method
- Check toast message text
=> chore: [IOBP-1013] New copy for card method removal

package.json, ts/features/zendesk/screens/__tests__/ZendeskAskPermissions.test.tsx, ts/features/zendesk/screens/__tests__/ZendeskChooseCategory.test.tsx, ts/features/zendesk/screens/__tests__/ZendeskChooseSubCategory.test.tsx, ts/features/zendesk/store/reducers/__tests__/index.test.ts, ts/store/reducers/content.ts, ts/utils/__tests__/content.test.ts, ts/utils/supportAssistance.ts
> [!note]
> This PR depends on:
> * https://github.com/pagopa/io-dev-api-server/pull/442
This pull request includes several changes across multiple files to update the locale data and improve the content reducer. The most important changes include updating YAML file references, adding German locale descriptions to Zendesk categories, and modifying the content reducer to use a different locale function.
- Updated the `io_content_specs` reference to a new version.
- Replaced `getRemoteLocale` with `getCurrentLocale`
-  Added German (`de-DE`) descriptions to various Zendesk categories and test
Check FAQ in the application with German language
=> fix: [IOBP-961] Missing German key for FAQ

ios/Podfile.lock, locales/en/index.yml, locales/it/index.yml, package.json, ts/screens/profile/DeveloperModeSection.tsx, ts/utils/storeReview.ts, yarn.lock
This PR implements and integrate an in-app review library to ask for a store review.
- Adds `react-native-store-review`
- Adds the test button into the app developer section
Launch the app and check the test button under developer section
https://github.com/user-attachments/assets/2c90ec34-96c1-4afa-a144-f315ace13c22
=> chore: [IOPLT-780] Adds `react-native-store-review` library to request on demand review

README.md
Adds a badge on nightly build status on repo readme
=> Adds status badge on nightly build

locales/de/index.yml, locales/en/index.yml, locales/it/index.yml
This pull request includes updates to the `wallet` section in localization files.
- Updated the bottom sheet title to match the new content
- Onboard a new payment method
- Simulate outcome 2
- Press on `Scopri di più`
- Ensure that the screen is align with design
| Old | New |
| <video src="https://github.com/user-attachments/assets/5c29ef9b-02f3-4241-8cd1-74f1ac7df201"> | <video src="https://github.com/user-attachments/assets/fbe4eafe-aed4-4eeb-89c1-45643d017945"> |
=> chore: [IOBP-1071] Payment onboarding bottom sheet text

.github/workflows/pr-title-conventional-commit-linter.yml
This PR adds context space handling inside PR Title
Try to change the PR title to see the workflow in action in different scenarios.
=> fix(C r o s s): [IOAPPX-464] Context space handling inside PR Title

ts/features/fims/history/components/FimsHistoryKoScreen.tsx, ts/features/fims/history/components/__tests__/FimsHistoryKoScreen.test.tsx, ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryKoScreen.test.tsx.snap
addition of tests for said screen
- tests 
- snapshot
- small update to main component in order to properly test
automated tests should pass -- also make sure that the `go back` button in the KO screen still works as intended, given it was subject to a change.
=> test: [IOCOM-1827] FimsHistoryKoScreen tests

ts/features/payments/common/utils/index.ts
Hot fix for the psp list sorting
=> fix: [IOBP-1169] Psp order logic

locales/en/index.yml, locales/it/index.yml
This PR adds a more detailed description for the buttons inside the barcode scan screen.
- Edited the a11y description text.
With a real device, enable the screen reader/voice over and open the barcode scan screen from the "Payments" section and check that the described text is more detailed.
=> chore: [IOBP-1191] Add a11y description to button inside the barcode scan screen

ts/features/itwallet/common/store/reducers/index.ts
This PR fixes a redux migration issue, using now a different logic
- Redux migration fix
Try to update from a previous version and verify that any error occurs.
=> fix(IT Wallet): [SIW-2003] Fix redux migration logic

ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx, ts/features/itwallet/presentation/details/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
This pull request is adding contextual help to the `MultiValuePrerequisitesScreen` screen
- Add missing contextual help properties
Ensure `IDPAY_ONBOARDING_MULTI_SELF_DECLARATIONS` screen has `contextualHelp` action
=> fix: [IOBP-1216] Add missing contextual help properties

ts/features/itwallet/common/components/ItwCredentialCard/DigitalVersionBadge.tsx, ts/features/itwallet/common/components/ItwCredentialCard/ItwCredentialCard.tsx, ts/features/itwallet/common/components/ItwCredentialCard/__tests__/DigitalVersionBadge.test.tsx, ts/features/itwallet/common/components/ItwCredentialCard/__tests__/ItwCredentialCard.test.tsx, ts/features/itwallet/common/components/ItwCredentialCard/__tests__/__snapshots__/DigitalVersionBadge.test.tsx.snap, ts/features/itwallet/common/components/ItwCredentialCard/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
This PR enables the new typeface in the `ItwCredentialCard` component
- Add the `typefacePreference` condition to enable/disable the new typeface in the `ItwCredentialCard`
- Update test and relative snapshots
1. Go to the **Design System → Wallet (Components)** and check the cards
2. Change typeface preference in the **Settings → Preferences → Appearance**
3. Repeat step 1
=> fix: [IOAPPX-489] Enable the new typeface in the `ItwCredentialCard`

locales/de/index.json, locales/en/index.json, locales/it/index.json, ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx, ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
This pull request is adding accessibility announcements to enhance the user experience for screen where an header tittle is not provided
- Added accessibility announcements for payment summary and notice summary 
- Start a payment workflow using a real device📱
- Turn on TalkBack accessibility tool
- Ensure that `PAYMENT_NOTICE_SUMMARY` and `PAYMENT_CHECKOUT_MAKE` are announcing `Riepilogo dati avviso` and `Riepilogo del tuo pagamento` after landing
=> chore: [IOBP-1185,IOBP-1188] Announce title for screens with no header title

locales/en/index.json
This PR is updating an outdated translation from https://github.com/pagopa/io-app/pull/6914
=> chore: [IOBP-1600] Adjust payment checkout tos EN text

package.json, ts/features/authentication/login/optIn/screens/OptInScreen.tsx, ts/features/design-system/core/DSAdvice.tsx, yarn.lock
This PR bumps the io-app-design-system package to version `5.6.0`
=> feat(IT Wallet): [SIW-2358] Bump io-app-design-system to version 5.6.0

locales/de/index.json
Add missing DE copy and the privacy policy text for payment summary page
Ensure that text is aligned with [design](https://www.figma.com/design/mo5gsqVuSsH2hENsixu6Zq/ToS-e-PP?node-id=9191-26962&t=EDmvlnGcvjj8KPOg-4) requirements
=> chore: [IOBP-1636] Copy and the privacy policy URL text update for payment summary page

package.json, yarn.lock
This update brings in the latest version of the Design System, which includes a fix for the incorrect button text color. This resolves the issue previously addressed in:
- https://github.com/pagopa/io-app/pull/6888
- https://github.com/pagopa/io-app/pull/6750
With this version, the button text color now correctly follows the Design System specifications.
Ensure that buttons have correct text color
=> fix: [IOAPPX-496] update design system version

ts/features/itwallet/common/components/ItwOfflineWalletBanner.tsx
This PR adds a tracking feature for the wallet offline banner
-  Added tracking feature for the wallet offline banner
- When displaying the offline wallet banner, after clicking the CTA, check Mixpanel and verify if the events are being tracked correctly.
> [!NOTE]
> Not testable from QA without Mixpanel access.
=> feat(IT Wallet): [SIW-2411] Track banner and tap events in offline banner

ts/features/itwallet/credentials/store/reducers/__tests__/migrations.test.ts
This PR adds tests for the ITW `credential` reducer migrations.
- Added migrations tests
Tests should pass
=> chore(IT Wallet): [SIW-2535] Add tests for `credentials` reducer migrations

metro.config.js
=> fix: [IOAPPX-000] metro config

scripts/generate-api-models.sh, ts/components/UpdateAppAlert.tsx, ts/components/__tests__/UpdateAppAlert.test.tsx, ts/components/__tests__/__snapshots__/UpdateAppAlert.test.tsx.snap, ts/components/helpers/withAppRequiredUpdate.tsx, ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx, ts/features/idpay/details/screens/__tests__/IdPayInitiativeDetailsScreen.test.tsx, ts/features/idpay/onboarding/screens/IdPayInitiativeDetailsScreen.tsx, ts/store/reducers/backendStatus/remoteConfig.ts
This PR introduces a new feature for handling app update requirements based on specific functionalities and integrates it into existing components. It includes a custom higher-order component (HOC) implementation that checks whether or not the app should be updated to access that particular feature. Currently, it's implemented on the screens related to the `IdPay` initiative and onboarding. Additionally, it implements new tests for the `UpdateAppAlert` component.
* Added a common HOC `withAppRequiredUpdate` to conditionally display the `UpdateAppAlert` component based on app update requirements for specific features. It uses selectors associated with a specific key to determine if an update is needed.
* Added `idPayOnboardingRequiresAppUpdateSelector` and …
=> feat: [IOBP-1796] Added `withAppRequiredUpdate` HOC to handle feature-related min app version

locales/en/index.json, locales/it/index.json, ts/features/itwallet/discovery/screens/ItwIpzsPrivacyScreen.tsx, ts/features/itwallet/discovery/screens/__tests__/ItwIpzsPrivacyScreen.test.tsx, ts/features/itwallet/discovery/screens/__tests__/__snapshots__/ItwIpzsPrivacyScreen.test.tsx.snap
This PR updates the screen title shown in the `ItwIpzsPrivacyScreen` based on L3
- added conditional logic to display a different title when L3 is enabled
- added tests
Enable L3 and activate the it-wallet. You should see the updated title when accessing the tos acceptance screen
=> feat(IT Wallet): [SIW-2267] Update tos screen title based on L3

ts/features/bonus/cgn/hooks/useCgnUnsubscribe.tsx, ts/features/bonus/cgn/hooks/useSpecialCtaCgn.tsx
This pull request refactors the CTA text of remove alert modal to delete CGN from wallet
- Update CGN alert locale logic
Verify that the CTA button text now is showing only `Rimuovi` text
=> refactor: [IOBP-1812] Update CGN delete alert CTA text

ts/components/ui/IOScrollView.tsx, ts/components/ui/IOScrollViewWithLargeHeader.tsx, ts/features/idpay/onboarding/components/IdPayOnboardingStepper.tsx, ts/features/idpay/onboarding/machine/context.ts, ts/features/idpay/onboarding/machine/machine.ts, ts/features/idpay/onboarding/machine/selectors.ts, ts/features/idpay/onboarding/screens/IdPayBoolValuePrerequisitesScreen.tsx, ts/features/idpay/onboarding/screens/IdPayInputFormVerificationScreen.tsx, ts/features/idpay/onboarding/screens/IdPayMultiValuePrerequisitesScreen.tsx, ts/features/idpay/onboarding/screens/IdPayPDNDPrerequisitesScreen.tsx
This pull request introduces enhancements to the `IOScrollView` and `IdPayOnboarding` features by adding support for a `topElement` prop and implementing a stepper component for onboarding progress tracking.
- Added a new `topElement` prop to the `IOScrollView` component, allowing the injection of custom elements at the top of the scroll view
- Introduced and applied the `IdPayOnboardingStepper` component to display the current step and total steps in the IDPay onboarding process 
- Enhanced the onboarding machine context by adding a `currentStep` property and updating the state transitions to manage step progression and regression
- Try to onboard a IDPay initiative
- Ensure that stepper is visible and works well
https://github.com/user-attachments/assets/0869b289-7fbb-45f6-8753-34bee73a7 …
=> feat: [IOBP-1842] Introduce `Stepper` component into IDPay onboarding flow

ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
This pull request enhances accessibility for the `CgnMerchantDetailScreen` component and introduces a utility hook to improve code readability and functionality.
- Added a `ref` to the `H1` component and used `AccessibilityInfo.setAccessibilityFocus` to set focus on the merchant title when the screen is rendered. 
Ensure that details of CGN opportunity screen is focusing and announcing header title 
## Preview
https://github.com/user-attachments/assets/be2be31f-6719-4290-86ff-a95a299fd9f1
=> refactor: [IOBP-1870] CGN opportunity detail focus on title

ts/features/barcode/screens/BarcodeScanScreen.tsx
This PR enables the AAR phase 1 flow
- Navigation to AAR screen upon detection of an AAR QR Code
Using the io-dev-api-server, check that an AAR QRCode detection brings the user to the "Go to SEND" screen
=> feat: [IOCOM-2504] Enable AAR phase 1

locales/en/index.json, locales/it/index.json, ts/features/itwallet/discovery/screens/__tests__/__snapshots__/ItwDiscoveryInfoScreen.test.tsx.snap, ts/features/itwallet/presentation/proximity/utils/itwProximityPresentationUtils.ts
This PR updates the copy of discovery info component.
- Updated locales
Navigate to the discovery info component and check that it displays the correct copy
=> chore(IT Wallet): [SIW-2869] Update copy for discovery info component

locales/en/index.json, locales/it/index.json, ts/features/services/details/store/reducers/index.ts, ts/features/services/home/components/FeaturedInstitutionList.tsx, ts/features/services/home/components/FeaturedServiceList.tsx, ts/features/services/home/screens/ServicesHomeScreen.tsx, ts/features/services/search/hooks/useInstitutionsFetcher.tsx
This PR introduces an accessibility improvement to the `FeaturedServiceList` component.
- Added the accessibilityLabel prop to the `ListItemHeader` component.
Navigate to the Services Home screen, enable the screen reader and verify that the section title for Featured Services is properly announced.
=> fix: [IOPAE-1735] Improve accessibility of the `FeaturedServiceList` section header

scripts/generate-api-models.sh
This pull request updates the API version for the `biz-events`
- Updated the `biz-events` API model source
Verify that the `biz-events` API endpoints are accessible and returning expected responses
=> chore: [IOBP-1892] Update biz events spec
